# Легкий метод

Ціль цієї книги — це спрямувати вас у нове мислення. У порівнянні зі звичайним методом зупинки — коли ви починаєте з відчуття, що сходите на гору Еверест, і проводите декілька тижнів з відчуттями тяги та позбавлення, тут ви відразу починаєте з відчуття легкості, ніби ви вилікувались від жахливої хвороби. Відтоді, ви будете дивитися на цей період часу і дивуватися як ви могли використовувати будь-яке порно взагалі. Ви будете дивитися на інших порно-користувачів із жалем, а не з заздрістю.

Якщо вважати, що ви не хтось, хто ніколи не ставав залежним (якщо ви читаєте для іншої людини), або хтось, хто кинув (або знаходиться у періоді голодування "порно-дієти"), дуже важливо продовжувати використовувати порно, поки ви повністю не прочитаєте книгу. Це може звучати як протиріччя і ця інструкція спричиняє більше заперечення, ніж будь-яка інша, але з тим, як ви читаєте далі, ваше бажання використовувати порно буде поступово зменшуватись. **Сприйміть цю інструкцію серйозно: спроба кинути раніше не принесе вам користі.**

Багато людей не дочитують цю книгу до кінця, тому що вони вважають, що вони мають відмовитися від чогось, а дехто навіть спеціально читає тільки один рядок у день для того, щоб відтермінувати погану подію. Подивіться на це з іншої сторони: що вам втрачати? Якщо ви не зупинитесь після прочитання книги, ви не будете гіршим ніж ви є зараз. Це Ваги Паскаля: ставка, у якій ви не маєте чого втрачати та маєте великі шанси виграшу.

До речі, якщо ви не дивилися порно декілька днів або тижнів, але не впевнені чи ви порно-користувач, екс-користувач, або не-користувач, тоді не використовуйте порно для мастурбації, поки читаєте. Насправді, ви вже не-користувач, але ми маємо дати вашому мозку наздогнати ваше тіло. Після завершення читання цієї книги ви будете щасливим не-користувачем. EasyPeasy це повна протилежність звичному методу, де хтось перечислює значні недоліки порно і каже:
*"Якщо я зможу прожити достатньо довго без порно, то в кінці кінців бажання піде і я зможу насолоджуватись життям знову, вільним від рабства."*
Це логічний хід думок, тисячі людей зупиняються кожного дня за допомогою цього методу. Але з його допомогою важко досягти успіху з наступних причин:

**Зупинка ПМО це не справжня проблема.**
Кожного разу, коли ви закінчуєте свій сеанс, ви перестаєте використовувати порно. Ви можете мати вагомі причини у перший день своєї раз-у-чотири-дні порно-дієти і сказати: *"Я більше не хочу використовувати порно або мастурбувати."* Всі користувачі мають причини, і вони є більш вагомими, ніж ви можете собі уявити. Справжня проблема це другий день, десятий, або десятитисячний, коли у момент слабкості ви поглянете "лише одним оком", захочете ще одного, і раптом ви знову стаєте залежним.

**Усвідомлення ризику для здоровʼя створює більше страху, через що важче зупинитися.**
Скажіть користувачеві, що це руйнує його мужність і він відразу піде шукати щось, що підніме йому дофамін: цигарки, алкоголь, або навіть відкриє браузер у пошуках порно.

**Всі причини для зупинки насправді зроблять її важчою.**
Так трапляється через дві причини. По-перше, ми постійно змушені відмовлятися від нашого "маленького друга", або опори чи задоволення (в залежності від того, як це бачить користувач). По-друге, вони створюють "завісу". Ми не мастурбуємо з тих причин, з яких ми маємо зупинитися. Але справжнє питання: чому ми хочемо або потребуємо цього?

З EasyPeasy, ми (спочатку) забуваємо причини через які ми хочемо зупинитися, стикаємося з проблемою порно та задаємо собі наступні питання:

1.  Що порно робить для мене?

2.  Чи я справді отримую насолоду від нього?

3.  Чи я справді маю жити, саботуючи своє тіло і розум?

Чудова правда полягає у тому, що *все порно* не робить для вас абсолютно нічого. Дозвольте пояснити: справа не в тому, що недоліки перегляду порно більші за переваги, а в тому, що у перегляді порно немає **ніяких** переваг.

Більшість користувачів вважають за необхідне раціоналізувати їхнє використання порно, але всі причини, які вони придумують, є помилками та ілюзіями.

Спочатку ми видалимо ці помилки та ілюзії. Насправді, ви скоро зрозумієте, що немає від чого відмовлятися. Окрім того, ви отримаєте чудові позитивні результати від відмови від порно, при чому, благополуччя та щастя це тільки двоє з них. Коли ілюзії про те, що життя ніколи не буде таким приємним без порно будуть видалені, коли ви зрозумієте, що життя не тільки так само приємне без нього, але й ще більш чудове, і коли зникне відчуття позбавлення або порожнечі, ми повернемось до питання про збільшення благополуччя і щастя, та десятків інших причин кинути порно. Ці усвідомлення стануть додатковою допомогою у досягненні того, чого ви справді бажаєте: отримання насолоди від життя, вільного від рабства та порно залежності!
