# Чому зупинитися так важко?

Всі користувачі відчувають ніби щось зле вселилося в них. У перші дні це проста обіцянка: *"Я зупинюсь, але не сьогодні"*. Але в решті решт, ми починаємо вірити, що у нас недостатньо сили волі щоб зупинитися, або що порно має щось, що потрібне нам для того, щоб отримувати задоволення від життя. Залежність від порно це як вибиратися зі слизької ями: коли ми знаходимось біля поверхні, ми бачимо сонце, але сповзаємо вниз, коли наш настрій погіршується. Нарешті, ми відкриваємо браузер, і поки ми мастурбуємо, ми почуваємось жахливо.

Запитайте у користувача: *"Якби ти міг повернутися назад у часі, до того як ти став залежним, зі знаннями, які ти маєш зараз, чи почав би ти використовувати порно?"*

Відповідь була б: *"НІ В ЯКОМУ РАЗІ!"*

Запитайте у підтвердженого користувача, який захищає інтернет-порно і не вірить, що воно спричиняє травми мозку або зниження регуляції дофамінових рецепторів: *"Чи ти хотів би, щоб твої діти використовували порно?"*

Відповідь знову ж таки: *"НІ В ЯКОМУ РАЗІ!"*

Порно — це надзвичайна загадка. Як було сказано раніше, проблема не в тому, щоб пояснити чому зупинитися так легко, а в тому, чому зупинитися так важко. Справжня проблема — це пояснити, чому будь-хто продовжує це робити *після* того, як вони дізналися про шкоду, яку порно завдає організму. Одна з причин, чому ми починаємо, це тому що десятки мільйонів людей вже роблять це. Але всі вони хотіли ніколи б не починати взагалі, та говорять нам, що це відчувається так, ніби ти живеш на зменшеній потужності. Ми не дуже віримо в те, що вони не отримують задоволення від цього, тому що ми асоціюємо це зі свободою бути "сексуально освіченим" і важко працюємо над тим, щоб стати залежними. Потім ми проводимо залишок наших життів, кажучи іншим не робити цього, та самі намагаємось кинути звичку, часто з думками що ми такі одні.

Ми також проводимо значну частину нашого часу почуваючись безнадійними та нещасними. "Навчання" себе надприродніми образами змушує нас віддавати перевагу та сумувати за цими холодними зображеннями, навіть коли нам доступні теплі та справжні. Шляхом постійних сплесків та падінь рівня дофаміну, спричинених ПМО, ми прирікаємо себе на життя ізоляції, дратівливості, злості, стресу, втоми, та імпотенції. Використовуючи порно, з відсутністю найкращих частин сексу та відносин, ми почуваємось нещасними та винними.

Насправді, прочитання про залежні та руйнуючі можливості порно на різних сайтах зроблять нас ще більш нещасними! Що це за звичка, що коли ви її робите, ви її не хочете, а коли не робите, ви її бажаєте? Користувачі зневажають себе кожного разу, коли читають про гіперфронтальність та десенситизацію, коли вони використовують порно за спинами своїх партнерів, і кожен раз, коли вони не можуть змусити себе займатися спортом після денного сеансу. У іншому розумна та раціональна людська істота проводить свої дні у презирстві. Але найгірше, що користувачі отримують від того, що вони витримують життя з цими жахливими чорними тінями у себе в голові? **Абсолютно нічого!**

Ви можете думати: *"Це все дуже добре, я це знаю, але коли ти вже підсів на ці речі, зупинитися дуже важко."* Але чому це так важко? Хтось каже, що це через сильний синдром відміни, але як ви скоро дізнаєтесь, синдром відміни насправді дуже непомітний. Доказом цьому існує той факт, що багато користувачів жили і помирали не знаючи, що вони були залежними.

Хтось каже, що інтернет-порно безкоштовне і тому людство має прийняти це біологічне золото, але це неправда — воно викликає залежність та поводить себе як і будь-який інший наркотик. Запитайте у користувача, який насолоджується тільки "еротикою" (наприклад, журналами Playboy), чи вони колись переходили на "небезпечне порно". І якщо вони повністю чесні, вони зізнаються про випадки, коли вони раціоналізували перетин цієї лінії.

Насолода також не має з цим нічого спільного. Я отримую задоволення коли їм крабів, але я ніколи не доходив до того, що я мав їсти їх кожного дня. З іншими речами у житті, ми отримуємо від них задоволення, коли ми їх робимо, але ми не почуваємось позбавленими, коли ми не робимо їх.

Хтось каже:
*“Воно навчає!”* То як воно розвинуло вас як людину?
*“Це сексуальна насолода!”* Тоді чому воно ізолює вас і змушує вас відчувати ненаситну тягу?
*“Це відчуття полегшення!”* Полегшення від стресу у реальному житті? Добре, полегшення на годину, до того, як це все повернеться до вас? І які стреси воно полегшило?
*“Воно допомагає мені спати”* Тоді чому інші можуть спати нормально без нього? Існує [багато](https://www.sleepfoundation.org/insomnia/treatment/meditation) науково доведених [методів](https://www.sleepfoundation.org/insomnia/treatment/cognitive-behavioral-therapy-insomnia) для [покращення](https://www.amazon.com/Uvex-Blocking-Computer-SCT-Orange-S1933X/dp/B000USRG90) сну, та навіть [більше](https://www.menshealth.com.au/what-is-the-military-method-the-technique-that-promises-to-help-you-sleep-in-2-minutes).

Багато хто вірить, що порно полегшує нудьгу, але нудьга — це настрій. Порно швидко привчить вас до пошуку новизни, через що ви будете нудьгувати все більше і більше, допоки ви нарешті не кинетесь у погоню за потрібним роликом, стаючи все більше і більше запрограмованим на пошук всього, що веде за собою новизну, сильні емоції, та, зрештою, шок.

Хтось каже, що вони роблять це через те, що їхні друзі та всі, кого вони знають, також роблять це. Якщо так, тоді моліться, щоб ваші друзі не почали відрізати собі голови, щоб вилікувати головний біль! Багато користувачів, які думають про це, роблять висновок що це лише звичка. Насправді це не пояснення, але якщо відкинути всі звичайні раціональні пояснення, це залишається єдиним виправданням. На жаль, це так само нелогічно, як і відрізання голови. Кожного дня наших життів ми змінюємо звички, і деякі з них дуже приємні. Нам промили мізки що ПМО це звичка, і що звички важко зупинити.

Чи звички справді важко зупинити? Водії у США звикли їздити по правій стороні дороги, але коли подорожують, вони зупиняють цю звичку майже без проблем. І коли ви влаштовуєтеся на нову роботу, ви придумуєте собі інший розпорядок дня, тож ваші звички змінюються. Звикання до цього може потребувати трохи часу, але це ніщо у порівнянні зі спробами зупинити життєву боротьбу з порно залежністю. Ми створюємо та зупиняємо звички кожного дня у нашому житті, тож чому нам так важко зупинити звичку, яка змушує нас почуватися позбавленими коли ми не використовуємо та винними коли використовуємо. Звичку, яку б ми хотіли зупинити, коли все, що нам потрібно — це перестати *робити* це?

Відповідь полягає у тому, що порно це не звичка, це *залежність*! Тому нам здається, що її важко "віддати". Більшість користувачів не розуміють її і вірять що вони отримують справжнє задоволення чи опору від порно. Вони вірять, що вони зроблять справжню жертву, якщо вони кинуть.

Чудова правда у тому, що коли ви зрозумієте справжню природу порно залежності і причини, через які ви її використовуєте, ви зупинитесь — так просто. Після трьох тижнів єдиною таємницею буде те, чому ви колись вирішили, що вам необхідно використовувати порно увесь цей час і чому ви не можете переконати інших *як добре це не бути користувачем!*

## Зловісна пастка

Інтернет-порно це підступна та зловісна пастка, яку обʼєднали людина та природа. Дехто з нас навіть знає про небезпеку, але ми не можемо повірити у те, що ми не отримуємо насолоди від цього. Але, що нас приваблює найперше? Зазвичай це безкоштовні відео від аматорів та професіоналів. Таким чином і спрацьовує пастка. Якби замість цього сайти попереджали нас про небезпеку того, у що ми влазимо перед тим як ми зробимо свій перший перегляд, тоді б ми були стурбовані.

Але ніхто не бʼє тривогу. Можливо, це шокуюча природа багатьох відео переконує наш молодий розум, що ми ніколи не підсядемо. Ми думаємо, що якщо ми не отримуємо насолоди від них, ми можемо зупинитися будь-коли. Або, можливо, удавана невинність мʼякого порно не спричиняє у нас тривоги, так само як вмілий шахрай відводить нашу увагу куди йому потрібно, щоб виконати свій фокус. Якби нас попереджали, ми, як розумні людські істоти, зрозуміли б, чому половина дорослої популяції систематично залежна від чогось, що зменшує їхній власний потенціал виконувати те, що ми дивимось. Цікавість наближає нас ближче до дверей залежності, але ми не наважуємось натискати на відео, мініатюри яких ми розглядаємо, тому що ми боїмося, що вони зроблять нам зло або відправлять нас вниз на небезпечний та аморальний шлях. І якщо ми випадково натиснули на якесь відео, часто нашим єдиним бажанням є якнайшвидше піти з цієї сторінки, у той час як наша цікавість зростає ще більше.

Як тільки цей процес був запущений, ми у пастці. Відтепер ми проводимо залишок наших життів у спробах зрозуміти навіщо ми це робимо, говоримо нашим дітям не починати, і час від часу намагаємось втекти з пастки. Пастка спроектована таким чином, що ми намагаємось зупинитися через якийсь "інцидент", такий як сексуальна невдача, втрата карʼєри або відносин, нестача драйву, або просто відчуття прокаженості. Як тільки ми зупиняємось, ми маємо більше стресу через синдром відміни, і через те, що метод, на який ми покладалися для зняття стресу, тепер недоступний.

Потім наша рішучість кинути стає слабшою. Після декількох днів тортур ми переконуємо себе, що ми обрали поганий час для кидання, і вирішуємо що ми почекаємо періодів без стресу, а коли такі настають, тоді зникає наша причина для зупинки. Звичайно, такий період повністю ніколи не прийде, і ми починаємо думати, що наше життя стає все більш і більш напруженим. Ми покидаємо опіку наших батьків, і стреси, які повʼязані з роботою, домом, іпотекою, покупкою житла та вихованням дітей починають наповнювати наше життя. Але це все ілюзія. Найбільш стресова частина будь-якої істоти це раннє дитинство та молодість.

Ми схильні плутати відповідальність та стрес. Життя користувача, як і звичайного наркомана, автоматично стає більш напруженим, тому що порно не розслабляє нас і не полегшує стрес, як дехто намагається нас переконати. Це все відбувається навпаки: порно робить нас більш напруженими у процесі того, як ми продовжуємо використовувати, а відчуття провини, яке виникає після пізньої ночі, підливає ще більше олії у вогонь. Навіть користувачі, які кидають, як і більшість роблять раз чи більше у своєму житті, можуть жити щасливо, але у якийсь момент підсідають знову. Коли наші мізки заходять у лабіринт порнографії, вони стають лінивими і ми проводимо залишок наших життів, намагаючись втекти. Багато хто досягає успіху в цьому, але потрапляє у пастку знову.

Рішення проблеми залежності від порно це загадка. Вона є складною та важкою. Але коли ви дізнаєтесь відповідь, вона проста і весела, і ви будете гадати чому ви не додумались до цього! EasyPeasy має відповідь на цю загаду, вона виведе вас із лабіринту і ви більше ніколи не будете заходити до нього знову. **Все, що ви маєте робити — це виконувати всі інструкції**. Але, якщо ви вирішите зробити **неправильний крок та будете пропускати розділи**, або **читати книгу зі швидкістю світла**, не роблячи належних зусиль при першому читанні, тоді інші інструкції не мають сенсу.

Будь-хто може легко зупинитися, але спершу ми маємо встановити деякі факти. Ні, не ті факти, які зроблені щоб залякати вас, такої інформації у вас вже достатньо. Якби це вас зупинило, ви б вже не використовували порно. Але чому нам так важко зупинитися? Щоб відповісти на це питання, нам потрібно знати справжню причину, чому ми використовуємо порно. Це зводиться до двох факторів:

-   Природа людини та інтернет-порно.

-   Соціальне промивання мізків.

Порно-користувачі є розумними раціональними людськими істотами. Вони знають, що вони піддають себе великим ризикам у майбутньому, тому вони мають проводити багато часу, щоб раціоналізувати свою "звичку". Але порно-користувачі всередині знають що вони дурні, тому що їм не потрібно було дивитися порно до того, як вони підсіли. Більшість памʼятає, що їхній перший перегляд був сумішшю відрази й цікавості. Потім вони стали спеціалістами у пошуку, фільтруванні та створенні закладок. Вони працювали дуже важко, щоб стати залежними.

Найнеприємнішим є те, що всі не-користувачі — більшість жінок, старших чоловіків, та люди, які живуть у країнах, де недоступне високошвидкісне інтернет-порно, нічого не втрачають та вважають це все смішним. Розібравшись з цими факторами у наступних розділах, ви також зрозумієте цю підступну пастку!
