# Від чого я відмовляюся?

**Абсолютно ні від чого!** Від порно важко позбутися через страх, що ми відмовляємось від нашого задоволення чи опори. Від страху, що якісь приємні ситуації більше ніколи не будуть такими самими. Страху, що ми більше не зможемо справлятися у стресових ситуаціях. Іншими словами, ефекти промивання мізків змушують нас вірити у те, що секс та оргазм необхідні для кожної людини. Навіть більше — це думка, що у інтернет-порно є щось, що нам потрібно, і що коли ми перестаємо його використовувати, ми відмовляємо собі і створюємо порожнечу.

Запамʼятайте: **порно не заповнює порожнечу,** ***воно створює її!***

Наші тіла — це найскладніші обʼєкти на планеті. Неважливо чи вірите ви у розумний замисел, природній відбір або їх комбінацію, наші тіла у тисячі разів ефективніші за людину! Люди не можуть створювати найменші живі клітини, дивовижі ока, репродукувати різні взаємоповʼязані системи у наших тілах та мізках. Якщо цей творець або процес хотів, щоб ми могли витримувати надприродні стимули, тоді б у нас були різні системи винагороди. Наші тіла забезпечені безвідмовними системами захисту, і ми ігноруємо їх на свій страх і ризик.

## Немає від чого відмовлятися

Коли ви очистите свою голову від маленького монстра та промивання мізків (що є великим монстром), ви не захочете часто мастурбувати або використовувати для цього інтернет-порно. Є багато відомого та невідомого про порно залежність, і багато хто у медичному суспільстві не має концепту визначення когось як залежного від порно. Через це, багато симптомів помилково відносять до інших причин. Користувачі не дурні люди, просто вони нещасні без порно. Коли вони спіймані між демоном та глибоким синім морем, вони відмовляють собі і через це стають нещасними, тому що вони не можуть використовувати порно, або тому що вважають себе винними і починають зневажати себе через це. Коли у них зʼявляються такі симптоми, як біль у спині або імпотенція, їхній розум розривається між прийняттям відповідальності та відходом у інший бік.

Ще одна аналогія з курінням: всі з нас бачили курців, які придумують різні виправдання щоб покурити. Тоді ми бачимо справжню залежність в дії. Залежні не роблять це заради насолоди, вони роблять це тому що вони нещасні без цього.

Для багатьох їхній перший сексуальний досвід закінчився оргазмом, тому вони вважають що вони не можуть насолоджуватися сексом без нього. Для чоловіків порно рекламується як допомога для сексу, іноді навіть як тренування впевненості під час сексуального акту. Це нісенітниця, кондиціонування надприроднього стимула лише призводить до його зниження.

Тут не тільки нема від чого відмовлятися, але також можна досягти великих позитивних результатів. Коли користувачі намагаються кинути, вони роблять аспект на здоровʼя та мужність. Це дійсні та важливі причини, але я вірю що найбільші зміни є психологічними:

-   Повернення вашої впевненості та сміливості.

-   Свобода від рабства.

-   Відсутність противних чорних тіней всередині вашої голови та зневаги до себе.

## Порожнеча, порожнеча, чудова порожнеча!

Уявіть, що у вас на обличчі зʼявився висип, тому ви йдете в аптеку і вам дають безкоштовну мазь на пробу. Ви використали її і висип зник відразу. Через тиждень він зʼявляється знову, і ви знову йдете в аптеку та питаєте, чи є в них ще ця мазь. Вам відповідають: *"Звичайно; не викидайте тюбик, він знадобиться вам потім."*

Ви мажете обличчя знову, і висип знову зникає. Але кожного разу він повертається, він стає більшим, болить сильніше, і зникає на все коротші та коротші інтервали. З часом він покриває все ваше обличчя, дуже болить та повертається кожні пів години. Ви знаєте що мазь видалить його тимчасово, але ви дуже переживаєте. Чи розійдеться цей висип по вашому тілу? Чи зникне той інтервал коли його не видно повністю? Ви йдете до лікаря, але він не може це вилікувати. Через це ви пробуєте інші речі, але нічого не допомагає, окрім цієї мазі.

Тепер ви повністю залежні від неї і ніколи не виходите з дому без тюбику в кишені. Якщо ви їдете за кордон, ви берете з собою декілька. Окрім того, що ви переживаєте за своє здоровʼя, в аптеці вам продають цю мазь за дорогою ціною. У вас немає вибору окрім як платити.

Ви випадково помічаєте статтю, яка розповідає, що це трапляється не тільки з вами — багато людей страждають від цієї проблеми. Насправді, медичне суспільство визначило, що ця мазь не лікує висип, а тільки переносить його під шкіру. Вона спричинила розростання, тому все, що вам потрібно зробити аби висип пройшов — це перестати використовувати цю мазь.

Чи продовжите ви її використовувати? Чи буде у вас сила волі не користуватися нею? Якби ви не повірили статті, б ви побоювались декілька днів, але коли б ви зрозуміли що висип почав зникати, потреба та бажання використовувати мазь зникнули б. Чи були б ви нещасними? Звичайно ні! У вас була жахлива проблема і ви думали що вона є невиліковною, але зараз ви знайшли рішення. Навіть якби був потрібен рік на те, щоб висип пішов, кожного дня ситуація ставала б кращою і ви б думали як гарно ви себе почуваєте. Це магія кидання порно.

Висип — це не болі в тілі, відсутність нормальних еротичних бажань, слабке збудження, згасаюча потенція, марно витрачений час на двовимірні зображення, відчуття порушення прав, зневага до людей які вас спіймали, або навіть гірше, зневага до себе. Це все йде на додаток до висипу.

Висип змушує нас закривати очі на всі ці речі. Висип — це те панічне бажання дози. Не-користувачі не страждають від цього відчуття. Найгірша річ це страх, а найбільше досягнення це позбутися цього страху. Він виникає після вашого першого сеансу та далі збільшений і викликаний кожним наступним.

Деякі користувачі "щасливі", вони осліплені своїми маленькими монстрами і проходять через той самий кошмар, вони відкидаються фальшивими аргументами і намагаються виправдати свою дурість.

*Це так гарно бути вільним!*
