# Економія часу

Зазвичай коли користувачі намагаються зупинитися, основними причинами для цього є здоровʼя, релігія, або ультиматум від партнера. Частина промивання мізків цього жахливого наркотику — це чисте рабство від нього; людина важко боролася за те, щоб знищити рабство у багатьох частинах світу, але користувачі живуть у стражданнях від цього самоствореного рабства. Вони не помічають того факту, що коли їм дозволено використовувати порно, вони бажають бути не-користувачами. Порно стає цінним тільки тоді, коли ми намагаємося або змушені утримуватись.

Не можна достатньо повторювати, що саме через промивку мізків складно кинути порно, тому чим більше ми її розвіємо з самого початку, тим простіше буде досягти вашої мети. Користувачі, які не вірять у те, що порно має якісь негативні ефекти на їхнє здоровʼя (імпотенція, гіпофронтальність) і не мають психічного перетягування канату, зазвичай є молодими або самотніми. Тому, у силу їх юного віку, внутрішня петля зворотного звʼязку втрачається, або виникає дуже рідко, через що її важко помітити.

Більш кращим аргументом для молодого користувача є витрачений час. Якщо їм говорять про здоровʼя, вони ще готові сперечатися, але коли говорять про час... Якщо ви скажете: *"Я не можу повірити, що ти не переживаєш за час, який ти витрачаєш."*, то скоріше за все вони дадуть відповідь: *"Я можу собі це дозволити. Це лише Х годин на тиждень і я вважаю, що воно того варте, це тільки для мого задоволення."*

*"Я все ще не можу повірити, що тобі байдуже. Припустімо, що пів години це твій середній показник у день, який включає у себе фізичну втрату дофаміну, тоді ти витрачаєш приблизно повний робочий день кожні два тижні. Я впевнений, що ти погодишся, що півгодини на день — це дуже консервативна оцінка. Чи думав ти про те, скільки часу ти витратиш у своєму житті? Що ти робиш у цей час? Розвиваєш справжні стосунки? Ні, твоя улюблена порнозірка не відчуває до тебе симпатії тільки через те, що ти витратив стільки часу на її відео — ти просто втрачаєш час! Мало того, ти фактично використовуєш цей час, щоб зруйнувати своє фізичне здоровʼя, знищити свої нерви та впевненість, аби все життя страждати від рабства, болю, меланхолії та апатії. Напевно, це повинно тебе хвилювати, чи не так?"*

Це очевидно, особливо у молодших користувачів, що вони ніколи не думали про залежність на все життя. Іноді, вони відпрацьовують час, який вони витрачають у тиждень і це вже тривожно. Дуже рідко, тільки коли вони думають про кидання, вони рахують скільки вони витрачають часу у рік, що жахливо, а протягом життя навіть важко уявити. Але, через те що ми у суперечці, користувач імпульсивно скаже: *"Я можу дозволити це собі, це лише Х годин на тиждень"*.

Чи відмовилися б ви від роботи, яка оплачує вашу поточну річну зарплатню і також дає вам місяць відпустки щороку? Будь-який користувач миттєво полізе в інтернет і буде шукати у якому екзотичному місці вони будуть проводити свою відпустку. Але, було б великою проблемою придумати, як провести цілий місяць без роботи. У кожній дискусії з підтвердженим користувачем (майте на увазі, що це не хтось як ви, хто планує зупинитися) ніхто ніколи не погодився на цю пропозицію. Чому?

Часто у цей момент підтверджений користувач скаже: "*Взагалі, мене не дуже хвилює грошовий аспект*". Якщо ви думаєте так само, запитайте у себе чому ви не хвилюєтесь. Чому в інших аспектах вашого життя ви докладаєте великих зусиль, щоб заощадити декілька гривень, але витрачаєте тисячі, вбиваючи своє щастя та збільшуючи витрати?

Будь-яке рішення, яке ви робите у своєму житті — це результат аналітичного процесу зважування переваг та недоліків, щоб прийти до раціонального рішення. Це може бути погане рішення, але це буде результат раціональної дедукції. Коли якийсь користувач зважує плюси і мінуси інтернет-порно, відповідь зазвичай **"ЗУПИНИСЬ! ТИ ДУРЕНЬ!"** Тому, користувачі використовують його не тому що вони так хочуть або так вирішили, а тому що вони не можуть зупинитися. Вони ***мають*** використовувати порно, і тому промивають собі мізки, зариваючи голови у пісок.

Підтверджені користувачі мають памʼятати, що ситуація буде ставати все гіршою і гіршою, із все більшою кількістю нових досліджень та більшою кількістю людей, які говорять про погані ефекти інтернет-порно. Сьогодні про ефекти розповідають немедичні люди, а завтра це буде у діагностувальному тесті вашого лікаря. Вже пройшли ті часи, коли можна було сховатися за стресом від роботи. Тепер ваш партнер спитає чому ви сидите у своєму компʼютері пізно вночі. Користувач, який вже і так розбитий, тепер хоче провалитися під землю.

Дуже дивна річ, що багато людей платять гроші за абонементи в зал та персональних тренерів для того, щоб нарощувати мʼязи та виглядати гарно, і багато хто з них звертається до таких практик як бустинг тестостерону. І все ж існує багато людей у цій категорії, які б отримали чимало, якби перестали систематично руйнувати свої мізки.

Це через те, що вони досі думають промитими мізками користувача. Витріть пісок зі своїх очей. Інтернет-порно — це ланцюгова реакція і ярмо на життя, і якщо ви не зламаєте цей ланцюг, ви залишитеся користувачем на все життя. Порахуйте, скільки часу ви витратите на порно на залишок свого існування, звичайно кількість буде різна для різних людей, але скажемо що це 1.5 роки робочих годин. Уявіть, якби у вашій пошті лежав чек з лотереї за 1.5 роки вашої зарплатні. Ви б почали танцювати від радості, тож починайте танцювати! Ви вже зараз почнете отримувати ці переваги!

Якщо ви думаєте, що це дивний спосіб сприйняття ситуації, ви досі себе обманюєте. Подумайте, скільки б ви зберегли часу, якби ніколи не вмикали порно з самого початку.

Вже скоро ви будете робити своє рішення використати останній сеанс (але не зараз, памʼятайте інструкції!) і залишитеся не-користувачем, не потрапляючи у цю пастку знову. Все, що ви маєте робити, щоб залишатися не-користувачем — це не використовувати порно та уникати перегляду "лише одним оком". Памʼятайте, якщо ви це зробите, це буде вартувати вам тієї зарплатні, яку ви вирахували.

Якщо ви допомагаєте комусь із їхньою залежністю, скажіть їм що ви знаєте когось, хто відмовився від вакансії на роботу, яка платить їхню поточну річну зарплату і дає їм місяць оплачуваної відпустки. Коли вони спитають хто цей дурень, скажіть їм: ***"Ви!"*** Це грубо, але іноді ви маєте сказати правду не дуже вихованим способом.
