# Здоровʼя

Це та тема, де промивання мізків у користувачів є найбільшим, особливо у тих молодих та одиноких, які думають що вони знають про всі ризики для здоровʼя, але насправді це не так. Багато обманюють самі себе, коли кажуть що вони готові прийняти наслідки. Якби ваш інтернет роутер мав функцію, яка програвала сирену з повідомленням, коли ви натискаєте на порносайт: "*До цього моменту все було добре, але якщо ви залишитесь тут хоча б ще на хвилину, ваша голова розірветься*". Чи продовжили б ви дивитись? Якщо ви сумніваєтеся над відповіддю — спробуйте підійти до краю скелі з закритими очима і уявити що ви маєте вибір: кидати порно, або йти вперед.

Немає сумніву у тому, що ви виберете, але ви нічого не досягнете, якщо ви закопуєте свою голову у пісок і сподіваєтесь, що ви прокинетесь одного ранку та не захочете більше дивитися порно. Користувачі не можуть дозволити собі думати про ризики для здоровʼя, тому що якщо вони це зроблять, тоді зникне уявна насолода від залежності. Це пояснює чому шокова терапія не така ефективна на перших стадіях кидання — тільки не-користувачі можуть змусити себе читати про деструктивні зміни для мозку.

Подивіться на цю поширену розмову з молодими користувачами.

> **Я:** “Чому ви хочете зупинитися?"
>
> **Користувач:** “*Я прочитав у блозі пікапера, що зупинка на чотири дні може допомогти підготуватися до побачення.*"
>
> **Я:** “Ви не переживаєте за ризики здоровʼю?"
>
> **Користувач:** “*Ні, мене завжди може збити автобус.*"
>
> **Я:** “Але ж ви не кинетесь під автобус самі?"
>
> **Користувач:** “*Звичайно ні.*"
>
> **Я:** “Ви не дивитесь по сторонам коли переходите дорогу?"
>
> **Користувач:** “*Звичайно дивлюсь.*"

Вони є обережними щоб не потрапити під автобус, і вірогідність того, що це станеться становить тисячі до одного. Тим не менш, користувач ризикує з майже повною впевненістю бути покаліченим своєю залежністю, і, здається, абсолютно не помічає цього. Така сила промивання мізків; інтернет-порно — це вовк у овечій шкурі. Хіба це не дивно, якби ми побачили, що в літаку є хоч найменша несправність, ми б не полетіли в ньому — незважаючи на те, що ризики складають мільйони до одного — але все ж з порно ми приймаємо ймовірність більшу, ніж один до чотирьох та не помічаємо цього? Що від цього отримує користувач? ***Абсолютно нічого!***

Також розповсюджений міф це депресія або сварливість. Багато молодих людей не переживають за своє здоровʼя, тому що вони не страждають від депресії та меланхолії. Депресія або стрес це не хвороба, це симптоми. Молодь зазвичай не відчуває дратівливість чи депресію через природню здатність їхніх тіл створювати більше дофаміну. Коли вони підростають або переживають серйозні невдачі, їхні вже збіднені ресурси витрачаються ще більше і вони відчувають симптоми по максимуму. Коли старші користувачі відчувають стрес, депресію чи роздратування, це відбувається через те, що природні механізми захищають нервову систему від надлишкового переповнення дофаміном шляхом відрізання рецепторів. Користувач також набуває інших неврологічних змін, які тримають його в колії.

Думайте про це так: якщо у вас є гарна машина і ви дозволяєте їй ржавіти у гаражі, то це дуже безглуздо. Вона швидко стане просто купкою іржі, яка не зможе вас нікуди довезти. Це не кінець світу, тому що це лише питання грошей. Але ваше тіло це машина, яка несе вас через життя. Ми всі кажемо що здоровʼя це головне, спитайте це у будь-якого хворого міліонера. Більшість із нас можуть згадувати як ми молилися щоб нам стало краще, коли у нас була якась хвороба або нещасний випадок. Будучи залежним від порно ви не тільки даєте своєму тілу ржавіти, але й нічого не робите щодо цього. Ви систематично руйнуєте єдину машину, яка використовується, щоб вести вас протягом всього вашого життя.

Будьте мудрішими. Ви не маєте цього робити. Памʼятайте, це не дає вам *абсолютно нічого*. Витягніть свою голову з піску і спитайте себе: якби ви знали з абсолютною точністю, що наступний сеанс почне процес, який змусить вас абсолютно не реагувати на когось, кого ви сильно любите, чи продовжите ви? Ті люди, з якими це трапилось, точно не думали що це станеться з ними, і найгірша річ тут не сама хвороба, а той факт, що вони принесли її самі. Спробуйте уявити, як почуваються люди, які "натиснули на кнопку", коли для них промивання мізків скінчилась. Вони проводять залишок своїх життів з думками: "*Чому я переконував себе увесь цей час, що я маю мастурбувати на інтернет-порно? Якби тільки я мав час повернутись назад!*"

Перестаньте обманювати себе, ви маєте цей шанс. Це ланцюгова реакція: якщо ви почнете порно-сеанс, він поведе вас до наступного. Це вже відбувається з вами. EasyPeasy обіцяє не використовувати шокову терапію, тому якщо ви вже вирішили зупинитися, то наступні слова не будуть для вас шокуючими. Якщо ж ви ще не вирішили, тоді пропустіть *цей розділ* і поверніться сюди тоді, коли дочитаєте книгу.

Вже було проведено багато досліджень про шкоду, яку інтернет-порно завдає нашому сексуальному життю та психічному здоровʼю. Проблема у тому, що поки користувачі не вирішать зупинитися, вони не хочуть цього знати. Форуми і сайти з підтримкою це просто марна трата часу, тому що порно натягує на очі повʼязку, яка не дає вам бачити. Якщо вони ненавмисно прочитають про це, то перше, що вони зроблять — це відкриють порносайт. Порно-користувачі схильні думати про щастя, стрес та сексуальні небезпеки як випадковість, порівнюючи це з наступанням на міну.

Прокиньтесь, це вже трапляється. ***Кожного разу***, коли ви відкриваєте свій порносайт, ви викликаєте переповнення дофаміном і опіоїди йдуть працювати. Нейронні водні гірки змащуються, щоб вам було простіше наступного разу — ваш мозок вже запамʼятав цей сюжет. Нервова система тепер переповнена дофаміном і через те, що це вже не вперше, дофамінові рецептори закриваються. Маленький монстр використовує краплину задоволення у порівнянні з минулим разом і веде вас далі до червоної лінії, до більш шокуючого порно або поведінки, та каже вам продовжувати. Картинки і відео в одному сеансі провокують надприродні стимули, та інжектують більше речовин у мозок та змушують вас продовжувати.

Увесь час ваші рецептори отримують сигнал виключитись у відповідь на переповнення дофаміном. Оргазм тільки збільшує цей ефект і веде до синдрому відміни. Ви у відміні, тому що маленький монстр хоче свою дозу без реального болю та дискомфорту. Погроза мати імпотенцію лякає багатьох, через це вони блокують ці думки зі свого розуму і затьмарюють їх страхом кидання. Справа не у самому страху, а в тому, що кинути потрібно зараз. Навіщо дивитися на негативну сторону? Можливо з вами нічого не станеться, і ви кинете до того моменту.

Ми звикли думати про порно як про перетягування канату, де з однієї сторони страх: "*Це шкідливо, брудно, та поневолює*", а з іншої позитивні речі: "*Це моє задоволення, мій друг, моя підтримка.*" Нам ніколи не спадає на думку, що ця інша сторона це також страх; ми не отримуємо задоволення від порно, ми просто стаємо нещасними без нього. Героїнові наркомани без героїну проходять через нещастя, але уявіть їхню радість коли вони нарешті можуть вколоти собі шприц у вену, щоб зупинити цю жахливу тягу. Спробуйте уявити, як хтось може отримувати задоволення від вколювання гіподермічного шприца у вену. Не-наркомани не відчувають цього панічного відчуття, і героїн не полегшує його, а спричиняє.

Не-користувачі не відчувають себе нещасними якщо їм не дозволено використовувати порно, тільки користувачі відчувають це. Інтернет-порно не полегшує це відчуття, воно спричиняє його. Страх негативних наслідків не дозволяє користувачам кинути, звʼязуючи страх з прогулянкою по мінному полю. Якщо ви змогли пройти, то добре, але якщо ні, то ви підірвались на міні. Якщо ви знали про ризики і були готові їх прийняти, яку справу це має з іншими? Наркомани в цьому стані зазвичай розвивають наступні тактики ухиляння.

"***Ми все одно станемо старими та втратимо свою сексуальну силу...***"

Звичайно так, але сексуальна сила не є головною — ми говоримо про рабство. Навіть якщо це так, це логічна причина для саботажу?

"***Якість життя більш важлива ніж просто життя.***"

Саме так! Ви хочете сказати що якість життя наркомана вища, ніж когось, хто не є залежним? Ви справді вірите, що якість життя користувачів краща ніж не-користувачів?. Нещасне життя, прожите з головою в піску не звучить як щось приємне.

"***Я одинокий і не планую заводити сімʼю у майбутньому, тож чому ні?***"

Навіть якби це було правдою, чи це логічна причина гратися з механізмом нейрологічного контролю імпульсів? Ви можете сказати про когось, хто достатньо дурний, щоб роздягнутися наголо коли вони на самоті, неважливо наскільки вони впевнені що ніхто не прийде? **Це те, що постійно роблять користувачі!**

Прогресивне розстрілювання нашого кола винагороди надмірною стимуляцією робить його неспроможним витримувати природні стреси у житті, та не допомагає користувачам насолоджуватися життям з ентузіазмом та бадьорістю. Порно і мастурбація замінили природний сексуальний апетит, так як шоколадка заміняє справжню їжу. Не дивно, але багато лікарів і психологів тепер повʼязують різні психічні проблеми з психологічними причинами. Основна медична спільнота стверджує, що ніколи не було науково доведено, що порно є прямою причиною проблем, про які повідомляють люди, які зізнаються самі, але публічне визнання своєї сексуальної неспроможності є такою ганьбою, тож навіщо комусь робити це, якщо вони не були справді стурбовані, знайшовши причину та усунувши її з власного життя?

EasyPeasy допоможе вам позбутися порно та стати щасливим екс-користувачем. Ніякого порно, мастурбації за допомогою порно та непотрібних оргазмів. Єдиною допомогою буде дотик, погляд та запах вашого партнера. Як хліб після гарного апетиту, ви більше не захочете солодкого сиропу інтернет-порно. Свідчення такі великі, що не потребують доказів; якщо я вдарю свій палець молотком то мені буде боляче — для цього не треба доказів. Стрес інтернет-порно також має ефекти на інші аспекти життя користувача, що змушує багатьох переходити до наркотиків, таких як цигарки та алкоголь, щоб справлятися. У деяких випадках він навіть змушує користувача думати над самогубством.

Користувачі також страждають від ілюзій що негативні ефекти від порно перебільшені. Але насправді це навпаки — немає сумнівів що інтернет-порно це основна причина для імпотенції та багатьох інших проблем. Скільки було розлучень через порно? Немає точних способів дізнатися про це, але пошуки по онлайн спільнотам підказують, що це число зростає.

Є епізод *Друзів* у якому хлопці, які дивилися безкоштовне порно по телевізору, почали дивуватися чому дівчина, яка доставляє піцу не попросила їх подивитися на їхню "велику спальню". Коли ви залежний, ви починаєте проектувати порно фантазії на справжніх жінок. Уявіть, що може зробити невідповідальний або навіть випадковий перегляд порно в темних кутках інтернету комусь, хто вже знаходиться на переломному моменті свого життя. Боротьба з такими думками, які зʼявляються через порно, стане основним витратником їхнього психічного здоровʼя.

(Ось іще один розумовий експеримент: скажімо хтось приходить до вас додому і вони не обовʼязково хочуть оргазму, а просто хочуть робити любов, навіть проникаючу. Вони хочуть робити це так довго, наскільки ви це можете без оргазму — але якщо він трапиться, то нічого страшного. Я запевняю вас у феноменальному новому сексуальному досвіді, набагато кращому за будь-який інший, якщо ви отримаєте таку пропозицію. Спробуйте це.)

Наслідки промивання мізків змушують нас думати так, як людина, яка падаючи зі 100-поверхового будинку каже: "*Все нормально!*" Ми вважаємо, що поки що нам все сходить з рук, ще один порно-сеанс нічого не змінить. Погляньте на це з іншого боку: "звичка" — це безперервний ланцюжок протягом усього життя, коли кожний сеанс створює потребу в наступному. Коли ви починаєте цю звичку, ви запалюєте запал. Проблема у тому, що ви не знаєте наскільки довго він буде горіти. Кожного разу, коли ви піддаєтеся порно-сеансу, ви на крок ближче до вибуху бомби. **ЗВІДКИ ВИ ЗНАЄТЕ, ЧИ НЕ БУДЕ ВІН НАСТУПНИЙ?**

## Зловісні чорні тіні

Користувачам дуже важко повірити у те, що інтернет-порно спричиняє ці почуття невпевненості, коли ви виходите на вулицю пізно ввечері після дня, проведеного вдома чи на роботі. Не-користувачі не страждають від цих відчуттів, тому що їх створює порно.

Ще одна перевага кидання порно — це звільнення від зловісних чорних тіней у своїй голові. Всі користувачі знають що вони бовдури, коли ховаються від негативних ефектів порно. Більшу частину нашого життя це відбувається автоматично, але чорні тіні завжди ховаються в нашій підсвідомості, під поверхнею. Деякі з дивовижних переваг припинення використання є помітними, такі як зупинка марної трати часу та чистої дурості заняття коханням із двовимірним зображенням.

Попередні розділи розповідали про переваги буття не-користувачем, але для справедливості необхідно дати збалансовану оцінку. Тому наступний розділ перелічить переваги буття користувачем.

# Переваги буття користувачем
