# Метод сили волі

У суспільстві прийнято вважати, що кинути порно дуже складно. Книги та форуми, які радять як кинути залежність, зазвичай починають з того, що кажуть вам, як важко це зробити. Але насправді це дуже легко. Зрозуміло, що можна поставити під сумнів це твердження, але спочатку подумайте про це. Якщо ваша ціль — пробігти милю за чотири хвилини, то це дуже складно і вам доведеться витратити дуже багато часу на важкі тренування, і навіть тоді, можливо, ви будете фізично нездатні на це.

Але все, що вам потрібно зробити, щоб перестати дивитися порно — це більше не дивитись його та/або не мастурбувати. Ніхто не змушує вас мастурбувати (окрім вас самих), і на відміну від їжі або води, це не потрібно для виживання. Тому, якщо ви хочете перестати це робити, чому це має бути складно? Насправді це легко. Лише користувачі ускладнюють собі життя, коли вони використовують силу волі або будь-який метод, який змушує користувача відчувати, що він чимось жертвує. Давайте розглянемо цей підхід.

Ми не вирішуємо стати користувачами, ми просто експериментуємо з порножурналами або веб-сайтами, і оскільки всі вони, за виключенням нашого бажаного кліпу, жахливі (саме так, жахливі), то ми впевнені, що ми можемо зупинитися будь-коли. Спочатку ми дивимось ті перші декілька кліпів коли захочемо і по особливим випадкам. Але до того, як ми це зрозуміємо, ми не тільки регулярно відвідуємо ці сайти та мастурбуємо "коли хочемо", а робимо це щоденно. Порно стало частиною нашого життя, через нього ми маємо необхідність мати доступ до інтернету, де б ми не були. Ми вважаємо, що маємо право на любов, секс, оргазм і ті властивості порно, які знімають стрес. Нам не спадає на думку, що один і той же кліп та актори не забезпечують нам такого ступеню збудження, і ми починаємо боротися з червоною лінією, намагаючись оминути "погане порно". Насправді, мастурбація та інтернет-порно не покращують наше сексуальне життя та не знімають стрес, просто користувачі вважають, що без цього вони не можуть насолоджуватись життям, або справлятися зі стресом.

Зазвичай потрібно багато часу для того, щоб зрозуміти, що ми попалися на гачок, тому що ми помилково вважаємо що користувачі дивляться порно, тому що їм це подобається, а не тому що їм це *потрібно*. Коли ми не отримуємо "задоволення" від порно (що ніколи не відбудеться якщо не додасться новизна, шок або ескалація), у нас виникає уявлення що ми можемо зупинитись у будь-який момент. Це пастка впевненості. *"Я не отримую задоволення від порно, тому я можу зупинитися коли захочу."* Але ви ніколи не "захочете" зупинитись.

Зазвичай ми усвідомлюємо що проблема існує тільки коли намагаємося зупинитися. Перші спроби зазвичай зʼявляються рано — їх провокує знайомство з партнером, коли після перших побачень ми помічаємо що він "недостатньо гарний". Друга поширена причина — неможливість не помічати наслідки для здоровʼя, які зʼявляються у повсякденному житті.

Незалежно від причини, користувач завжди чекає на стресову ситуацію, таку як проблема зі здоровʼям, або невдача у сексі. Як тільки вони перестають використовувати порно, маленький монстр починає відчувати голод. Тоді користувачеві хочеться чогось, що підніме його рівень дофаміну, наприклад цигарки, алкоголь, або його улюблене — інтернет-порно, гарем якого знаходиться всього в одному кліці від нього. Порно-схованка більше не знаходиться у підвалі, вона віртуальна і доступна з будь-якого місця. Якщо партнер користувача поруч, або коли він із друзями, у нього більше немає доступу до свого віртуального гарему, що засмучує його ще сильніше.

Якщо користувач стикався з науковими матеріалами або інтернет-спільнотами, він починає вести перетягування канату у своїй голові, опиратися тягам і відчувати себе позбавленим. Його спосіб звичайного зняття стресу більше не доступний і він отримує потрійний удар. Вірогідним результатом після цих тортур буде компроміс: "*Я зменшу використання*", "*Я обрав непідходящий час*", або, можливо, "*Я почекаю, поки стрес не зникне з мого життя*". Але, як тільки стрес проходить, тоді вже немає причин зупинятися і користувач не збирається кидати, поки знову не прийде складний час у його житті.

Звичайно, ніколи не буває підходящого моменту, тому що життя більшості людей стає більш напруженим. Ми виходимо з-під опіки батьків, вступаємо у світ, облаштовуємо своє життя, іпотеки, народжуємо дітей і отримуємо більш відповідальну і складну роботу. Незалежно ні від чого, життя користувача не може стати менш стресовим, тому що порно насправді викликає стрес. Чим швидше користувач переходить на стадію загострення, тим більше він страждає, і тим більше зростає ілюзія залежності.

Насправді те, що життя стає більш напруженим це ілюзія, а порнографія — або аналогічна милиця — створює цю ілюзію. Більш детально про це буде сказано пізніше, але після перших невдач користувач зазвичай покладається на те, що колись він прокинеться і просто не захоче мастурбувати або використовувати порно. Ця надія зазвичай розпалюється історіями, почутими від інших колишніх користувачів: "*Я не був серйозним, поки у мене не ліг під час сексу і я більше не хотів використовувати порно та перестав мастурбувати*".

Не обманюйте себе, проаналізуйте ці історії і ви побачите, що все не так просто, як здається. Зазвичай користувач вже готувався до кидання, і просто використав цей інцидент як трамплін. Частіше за все люди, які зупиняються "просто так", переживають шок: можливо їх застукав партнер або вони самі помітили, що звертаються до порнографії, яка не збігається з їхньою сексуальною орієнтацією, або реальна імпотенція їх сильно налякала. "*Просто я така людина*". Перестаньте обманювати себе. Цього не трапиться, якщо ви самі цього не зробите.

Давайте розглянемо більш детально чому метод сили волі є настільки неефективним. Більшу частину свого життя ми дотримуємось методу "*я перестану завтра*". У рідкісні моменти щось провокує спробу зупинитись. Це може бути переживання за здоровʼя, мужність, або самоаналіз і розуміння того, що ми не отримуємо від цього задоволення. Яка б не була причина, ми починаємо зважувати всі плюси і мінуси порнографії. Секс буває чуттєвий (дотик, запах, голос) і дітородний (оргазм); розуміння різниці — це один із головних ключів до відкриття нашого розуму, і без цього важливого розділення буде плутанина, яка приведе до невдачі. При раціональній оцінці ми виявляємо істину, яку знали все життя. Одне і те саме повторюється тисячі разів "***ПЕРЕСТАНЬТЕ ДИВИТИСЬ ЙОГО!***"

Якби ви сіли і розписали по пунктам переваги зупинки і порівняли їх з перевагами порнографії, то загальна кількість очок за зупинку значно перевищила б всі "недоліки". Якщо згадати про ваги Паскаля, то кинувши порно ви майже нічого не втрачаєте, і маєте високі шанси на позитивні результати та високі шанси на те, що нічого не втратите. Хоча користувач знає, що йому буде краще якщо він стане не-користувачем, його зупиняє впевненість у тому, що він чимось жертвує. І хоча це ілюзія, вона сильна. Вони не знають чому, але у користувачів є впевненість, що у хороші і погані часи життя порно-сеанси якось їм допомагають. Ще перед тим, як спробувати кинути порно, промивання мізків суспільством, яка підсилюється промивкою мізків від власної залежності, потім ще поєднується з більшою промивкою мізків про те, як важко "відмовитись".

Користувачі чують історії тих, хто перестав використовувати порно багато місяців тому але все ще відчайдушно бажають його, або про тих незадоволених які кинули і проводять залишок свого життя у журбі, з бажаннями ще одного сеансу. Існують історії про те, як користувачі припиняли використання протягом багатьох місяців або років та жили щасливим життям, але варто було їм тільки "заглянути" у порно і вони знову підсідали. Користувачі вірогідно знають декількох людей на пізніх стадіях хвороби, які помітно зруйнували себе і явно не отримують задоволення від життя, але все одно продовжують використовувати порно. Окрім того, вони, вірогідно, самі пережили один або декілька подібних випадків.

Тому замість того, щоб почати з відчуття "*Чудово! Ви чули? Мені більше не потрібно дивитися порно!*", вони починають з відчуття приреченості та журби — ніби намагаються підкорити Еверест, і помилково вважають що як тільки маленький монстр вчепився у них, то вони залишаться залежними на все життя. Багато користувачів починають спроби з вибачень перед своїми коханими: "*Слухай, я намагаюсь кинути порно. Можливо, наступні декілька тижнів я буду роздратованим, так що намагайся потерпіти*". Більшість таких спроб приречені ще до їх початку.

Припустимо, що користувач прожив декілька днів без сеансу. До нього повертається збудження, він починає відновлюватись. Він не відкриває свої улюблені сайти і збуджується від звичайних стимулів, на які раніше не звертав уваги. Але причини, через які він вирішив зупинитись, швидко зникають. Ніби він побачив жахливу аварію за кермом. Цей інцидент сповільнить його на якийсь час, але все одно наступного разу, коли він буде запізнюватись на важливу зустріч, він будете гнати швидше, ніж зазвичай.

З іншої сторони знаходиться маленький монстр, який досі не отримав свого. Фізичного болю тут немає — якби у вас було таке саме відчуття через застуду, ви би не кинули роботу і не впали у депресію, а просто посміялись би над цим. Все, що знає користувач — це те, що він хоче відвідати свій гарем. Маленький монстр знає це і запускає великого монстра промивання мізків, змушуючи ту ж людину, яка декілька годин або днів тому перечислювала всі причини щоб кинути, тепер відчайдушно шукає будь-якого приводу почати знову. Вони починають говорити такі речі, як:

-   "*Життя занадто коротке, десь може вибухнути бомба, завтра мене може збити автобус. Я занадто пізно подумав про це. У наш час кажуть, що будь-що викликає залежність.*"

-   “*Я обрав не той час.*"

-   “*Треба було почекати до Різдва, після моєї відпустки/екзаменів, після цієї стресової події у моєму житті.*"

-   “*Я не можу сконцентруватися, я стаю роздратованим та нетерплячим, я навіть не можу нормально робити свою роботу.*"

-   "*Моя сімʼя і друзі не полюблять мене. Давайте дивитися правді у очі, я маю починати спочатку заради інших. У мене підтверджена сексуальна залежність, і я ніяк не зможу знову стати щасливим без оргазму.*"

-   "*Ніхто не може вижити без сексу.*" (Мізки промиті "благонадійними" людьми, які не розуміють різниці між чуттєвим та дітородним сексом).

-   "*Я знав, що це станеться, мій мозок "сенсибілізований" DeltaFosb через зміни, які були викликані стрибками дофаміну через мого попереднього надмірного споживання порно. Сенсибілізація ніколи не може бути виправленою.*"

На цьому етапі користувач зазвичай здається. Він запускає браузер і посилює свою шизофренію. З однієї сторони користувач відчуває велике полегшення тяги, коли маленький монстр нарешті отримує свою дозу; з іншої сторони оргазм жахливий, а користувач не може зрозуміти навіщо він це робить. Ось чому користувач думає, що йому не вистачає сили волі. Насправді це не відсутність сили волі — все, що йому потрібно зробити — це змінити своє мислення і прийняти раціональне рішення відповідно до отриманої інформації.

"*У чому сенс бути здоровим або багатим, якщо ви нещасливі?*"

Жодного! Набагато краще мати коротке приємне життя, ніж довге нещасливе. На щастя, це неправда для не-користувачів, оскільки життя безмежно приємніше. Страждання, які відчуває користувач, викликані не синдромом відміни — хоча на початку він їх викликає — насправді це боротьба у свідомості, яка була викликана сумнівами і невизначеністю. Оскільки на початку користувач думає, що він чимось жертвує, то він починає відчувати себе обділеним, що є серйозною формою стресу.

У один із таких стресових моментів, через бажання повернутись у сталий стан мозок пропонує "глянути лише одним оком", відразу після того як користувач кинув. Але оскільки він зупинився, він не може цього зробити і це призводить до ще більшої депресії і знову спричиняє пусковий механізм. Ще один фактор, який робить відмову від порно такою складною — це очікування того, що має статись. Якщо ваша ціль — здати екзамен по водінню, то як тільки ви здасте екзамен, ви будете впевнені, що досягли своєї цілі. З використанням методу сили волі внутрішня розмова звучить так: "*Якщо я зможу достатньо довго не дивитися порно, бажання подивитися його нарешті пройде.*" Ми можемо побачити такі приклади на інтернет-форумах, де залежні люди розповідають про свої "рекорди" і кількість днів утримання.

Як вже було сказано раніше, агонія, яку відчуває користувач, є психологічною і викликана невизначеністю. І хоча вона не викликає фізичного болю, вона все одно сильно впливає. Тепер нещасний і невпевнений у собі користувач далекий від забуття, тепер він сповнений сумнівів і страхів.

-   “*Як довго буде тривати тяга до порно?*"

-   “*Чи стану я колись знову щасливим?*"

-   “*Чи захочу я колись вставати вранці?*"

-   “*Як я буду справлятися зі стресами у майбутньому?*"

Користувач чекає на покращення ситуації, і поки він сумує, "гарем" стає все більш бажаним. Насправді, щось дійсно відбувається на підсвідомому рівні, але якщо він проживе декілька тижнів, не відкриваючи порно, тяга до маленького монстра зникає. Однак, як було сказано раніше, синдром відміни від дофаміну та опіоїдів настільки слабкий, що користувач навіть не помічає його. У цей час багато користувачів відчувають, що вони "кинули", і щоб довести це, роблять один перегляд, який знову відправляє їх вниз по водній гірці. Коли вони отримали вкид дофаміну в організм, у глибині своєї свідомості вони чують голос: "*Ти хочеш ще*". Вийшло так, що вони справді вже кинули, але підсіли знову.

У дитинстві ви дивились мультфільми, і відповідно нейронауці, у вас сформувались нейронні звʼязки (deltaFosB) для них. Якби ви хотіли відучити дитину від перегляду мультфільмів, ви б поцікавились, чи існують ще такі звʼязки у вас. Ви б опитали дорослих, чому вони більше не дивляться улюблені дитячі мультфільми. По-перше, є кращі розваги, а по-друге, мультфільми більше не мають тієї магії. При використанні методу сили волі ви просто забороняєте дитині дивитися мультики, а при використанні EeasyPeasy ви показуєте дитині, що у мультиках нема ніякого значення. Який підхід є кращим?

Зазвичай користувач не починає черговий сеанс відразу, він думає: "*Я не хочу знову потрапити на гачок!*", чекає необхідний на свій погляд період у декілька годин, днів, або навіть тижнів. Потім колишній користувач може сказати: "*Ну все, я не залежний, значить я можу спокійно провести ще один сеанс*". Вони вже потрапили в ту саму пастку, що в перший раз, і стали на слизьку дорогу.

Ті користувачі, які досягли успіху за допомогою методу сили волі, зазвичай вважають його довгим та важким, тому що основна проблема полягає у промиванні мізків. Через довгий час після того, як фізична залежність пройшла, користувач все ще сумує та відчуває себе нещасним. Та все ж, після довгих тортур, він розуміє що він не здасться, перестає сумувати і визнає, що життя продовжується і є так само приємним без порно. З використанням такого методу, відсоток невдач значно вищий, ніж відсоток успіху, тому що ті, хто добився успіху, проживають своє життя у вразливому стані та думають, що порно справді дає їм стимул, в якійсь мірі залишаючись з промитими мізками. Це пояснює, чому багато користувачів які надовго перестали використовувати порно з часом починають знову.

Багато колишніх користувачів час від часу проводять сеанси в якості "особливих подарунків", або щоб запевнити себе у тому, наскільки сильним є їхній самоконтроль. Вони роблять це, але як тільки сеанс закінчується, дофамін починає зникати і маленький голос у закутках їхньої свідомості починає підштовхувати їх до нового сеансу. Якщо вони погоджуються і використовують порно знову, то їм все ще здається що все під контролем — вони не відчувають ніякого шоку, ескалацій або потягів до новизни, тому вони кажуть: "*Чудово! Поки мені це не так сильно подобається, я не попадусь на гачок. Після Різдва / цих канікул / цієї травми я зупинюсь*". Вони навіть не підозрюють, що таким чином водні гірки в їхніх мізках змащуються все сильніше.

Надто пізно, вони вже підсіли! Пастка, із якої їм вдалось вирватись, знову схопила їх.

Як було сказано раніше, задоволення у цьому немає. І ніколи не було! Якби ми дивились через задоволення, ніхто б не залишався на сайтах довше, ніж потрібно для завершення справи. У будь-якому разі, найкращий спосіб самозадоволення — це спогади. Ми віримо, що отримуємо задоволення від порно тільки тому, що не можемо припустити, що ми настільки дурні, що потрапили в залежність, яка навіть не приносить задоволення. Більшість користувачів не мають ніякого уявлення про надприродні стимули, новизну або прагнення до шоку, і навіть коли вони прочитають про це, вони не вірять, що їх споживання мотивовано еволюційним механізмом нагороди. Саме тому більша частина порнографії є підсвідомою — якби ви знали про неврологічні зміни у мозку, ви б визнали, що ця залежність буде вартувати вам великих грошей у майбутньому, і у такому разі у вас навіть зникла б ілюзія задоволення.

Коли ми намагаємось відгородитись від поганого, ми відчуваємо себе дурнями. Якби нам прийшлось відкритись цьому, це було б нестерпно! Якщо ви подивитесь за користувачем у дії, ви побачите, що він щасливий тільки тоді, коли не знає, що споживає. Як тільки йому стає це відомо, він починає відчувати дискомфорт і вибачатись. Порно живить маленького монстра, тому коли ви вичистите його зі свого тіла разом з промивкою мізків (великим монстром), у вас не буде ні потреби, ні бажання дивитися порно!
