# Остерігайтеся зменшення використання

Багато користувачів вирішують зменшити використання порно як сходинки до повної зупинки, або як спробу контролю маленького монстра. Багато хто рекомендує зменшення використання або "порно дієту" як засіб для покращення настрою. Зменшувати використання для того, щоб зупинити споживання це ***смертельна небезпека***. Саме ці спроби завʼязати з порнографією тримають нас у пастці до кінця життя. Зазвичай така порно-дієта наступає після невдалих спроб зупинитися. Після декількох годин або днів утримання від порно користувач каже щось схоже на:

"*Я не можу змиритися з думкою, що я піду спати не відвідавши свій онлайн-гарем, тож відтепер я просто буду використовувати порно раз у чотири дні, або очищу свою колекцію від "поганого порно". Якщо я зможу дотримуватись цієї порно-дієти, то я або зупинюсь на цьому, або зменшу використання навіть більше.*"

Потім трапляються такі погані речі:

1. Вони застрягають у найгіршому з двох світів: вони досі залежні від інтернет-порнографії та тримають монстра живим не тільки в своєму тілі, але і у своїй голові.

2. Вони проживають своє життя в очікуванні наступного сеансу.

3. До початку зменшення використання, коли вони хотіли відвідати свій гарем, вони відкривали браузер і хоча б частково знімали симптоми відміни. Тепер, у додачу до звичайних життєвих стресів, вони також змушують себе страждати від синдрому відміни більшу частину своїх життів, що робить їх ще більш нещасними та роздратованими.

4. Потураючи, вони не отримують задоволення від більшості сеансів і не помічають, що вони використовують надприродні стимули. Це відбувалося автоматично — єдине відвідування гарему, яке давало задоволення, було після періоду утримання. Тепер, коли вони чекають візиту гарему, вони "насолоджуються" кожним відвідуванням. Чим довше вони чекають, тим більш "приємним" буде кожний сеанс, тому що "приємним" у ньому є не сам сеанс, а закінчення неспокою який був спричинений тягою — неважливо чи це легка фізична тяга, або розумове бажання. Чим довше триває страждання, тим більш приємним стає кожний сеанс.

Основна складність у зупинці використання полягає не у неврологічній залежності — вона протікає дуже легко. Користувачі перестають використовувати без особливих проблем через різні причини — смерть близької людини, сімейні чи робочі справи. Вони можуть, скажімо, не використовувати порно десять днів, і їх не буде це хвилювати. Але якби вони провели ті ж десять днів коли у них міг бути доступ до порно, вони б виривали на собі волосся.

Багато користувачів спокійно утримуються, якщо у них є шанс подивитися порно у робочий день, або коли відвідують покази мод та басейни без зайвих незручностей. Більшість утримуються, якщо їм доведеться тимчасово спати на дивані, коли до них приїжджають гості, або якщо вони самі знаходяться у гостях. Навіть у барах і на нудистських пляжах немає проблем. Користувачі майже раді, коли хтось або щось говорить, що їм не можна дивитися порно. Насправді, користувачі які хочуть кинути, отримують таємне задоволення від довгої відсутності відвідувань гарему, оскільки це дає їм надію на те, що можливо колись вони більше не захочуть використовувати порно.

Справжня проблема при зупинці — це промивання мізків, ця ілюзія самоцінності, що інтернет-порно — це свого роду підтримка або нагорода, і без нього життя ніколи не буде таким самим. Все, до чого призводить зменшення використання — це до того, що ви відчуваєте себе невпевненим і нещасним, та переконуєте себе у тому, що найцінніше на цій землі це нове відео, яке ви ще не бачили, і що ви ніяк не зможете знову стати щасливим, не якщо не подивитесь його.

Немає нічого більш нещаснішого, ніж користувач, який намагається зменшити перегляд порно та страждає від помилкового уявлення, що чим менше він дивиться порно, тим менше йому захочеться відвідати свій онлайн-гарем. Це працює навпаки — чим менше він дивиться порно, тим довше він страждає від синдрому відміни і тим більше він буде "насолоджуватися" його полегшенням. Скоро він помітить, що його улюблений жанр не приносить йому задоволення як раніше. Але це його не зупинить: якби порносайти були присвячені тільки одній зірці або одному жанру, ні один користувач не зайшов би туди більше одного разу.

Вам складно у це повірити? Який є найгірший момент самоконтролю який хтось може відчувати? Чекати чотири дні і потім отримати кульмінацію. Тоді, який найдорожчий момент для більшості користувачів, які сидять на чотирьохденній порно-дієті? Правильно, той самий кульмінаційний момент після чотирьохденного очікування! Ви справді вірите, що мастурбуєте для того, щоб насолодитись оргазмом? Ось вам більш раціональне пояснення — вам просто потрібно зняти синдром відміни, годуючи ілюзію, що ви маєте на це повне право через те, що ви утримувались.

Видалення промивання мізків необхідне для того, щоб позбутися ілюзій про порно до того, як ви закінчите останній сеанс. Якщо до того, як закрити вікно браузера, ви не позбавитесь від ілюзії, що вам подобається порно, ви ніяк не зможете довести це потім, не потрапивши на гачок знову. Виснучи над закладками і збереженими картинками, спитайте себе що чудового є у цій дії? Можливо, ви вважаєте, що якесь відео гарне. Якщо це так, тоді навіщо дивитися інші відео, або теми? Тому що у вас це ввійшло у звичку? Навіщо комусь звичка, яка засмічує мозок і даремно витрачає людину? Через місяць нічого не зміниться, тож чому порно кліп має бути новим?

Ви можете перевірити це самі. Знайдіть гарячий кліп з минулого місяця щоб довести, що він вже інший. Потім поставте нагадування і подивіться той же кліп після місяця без порно. Він буде (майже) таким самим, як це було минулого місяця. І все ж, те саме відео буде відрізнятися після події, де вам відмовив, або влаштував випробування потенційний партнер. Причина у тому, що користувач ніколи не зможе бути повністю щасливим, якщо маленький монстр залишається незадоволеним.

Де ж у цьому задоволення? Користувачі просто нещасні, якщо не можуть полегшити синдром відміни. Різниця між тим, щоб дивитися порно і не дивитися — це різниця між щастям і нещастям. Через це інтернет-порно і виглядає кращим. Користувачі, які першим ділом вранці заходять на сайт заради порно, є нещасними незалежно від того, дивляться вони його чи ні.

Зменшення використання не тільки не працює, але також є найгіршою формою тортур. Воно не працює, тому що спочатку користувач сподівається, що він зменшить своє бажання дивитися порно, якщо буде все менше й менше занурюватись у звичку. Але це не звичка, це залежність. Природа будь-якої залежності полягає у тому, щоб хотіти все більше і більше, а не навпаки. Тому для того, щоб зменшити перегляд порно, користувач має проявляти силу волі та дисципліну до кінця свого життя. Таким чином, зменшення використання означає тренування сили волі і дисципліни назавжди. Зупинитися набагато легше і не так боляче; є буквально десятки тисяч випадків, коли зменшення використання не допомогло.

Проблема зупинки полягає не у дофаміновій залежності — з нею легко справитись. Спочатку це помилкове уявлення про те, що порно дає вам насолоду, було викликане промиванням мізків, яке ми отримали ще до того, як почали використовувати, і потім було підсилене самою залежністю. Все, що робить зменшення використання порно — це ще більше закріплює це помилкове уявлення, при чому так, що порно повністю домінує у їхньому житті і переконує їх, що найбільш цінна річ на землі це їхня залежність.

Є випадки, коли вдалося досягти успіху завдяки відносно короткому періоду зменшення використання порно, за яким пішла "жорстка відмова". Ці користувачі перестали використовувати порно не зважаючи на зменшення, а не завдяки йому. Зменшення тільки продовжувало агонію, а неуспішні спроби залишали користувачів роздратованими і ще більш впевненими у тому, що вони підсіли на порно на все життя. Цього зазвичай достатньо, щоб вони, у пошуках "задоволення" і "підтримки" повернулись до свого онлайн-гарему принаймні ще на якийсь час до наступної спроби кинути.

Тим не менш, зменшення допомагає проілюструвати марність порно та показати, що візити до гарему не приносять насолоду після періодів утримання. Доводиться знову якийсь час битися головою об стіну (у стражданнях від синдрому відміни), щоб це знову стало приємним. Таким чином, ваш вибір такий:

1.  Зменшувати використання порно все життя і страждати від тортур, які ви все одно не витримаєте.

2.  Все частіше мучити себе протягом всього життя, що не має сенсу.

3.  Бути добрим до себе і кинути використання порнографії повністю.

Інший аспект зменшення використання порнографії полягає у тому, що не існує такого поняття як випадковий або нерегулярний візит гарему. Інтернет-порно — це ланцюгова реакція, яка буде продовжуватись все ваше життя, якщо ви не зробите позитивних рішень, щоб зупинити її.

**Памʼятайте: Зменшення перегляду порно неминуче потягне вас вниз.**
