# Перегляд "лише одним оком"

Перегляд "лише одним оком" — це міф, який ви маєте викинути з голови:

-   Через перегляд *лише одним оком* ми колись почали дивитися порно.

-   Перегляд *лише одним оком* знищує більшість наших спроб зупинитися, коли ми хочемо підтримати себе у складну хвилину, або при особливій нагоді.

-   Саме перегляд *лише одним оком* повертає нас у пастку після того, як нам вдалося позбутися залежності. Іноді ми робимо це, щоб довести собі що ми більше не потребуємо порно, але відвідування гарему доводить інше.

Наслідки перегляду порно будуть жахливими і переконають користувача, що він ніколи більше не потрапить на гачок — але він вже потрапив. Користувач відчуває що щось, що робить його таким нещасним і винним, не мало підштовхувати його займатись цим знову, але все ж воно раз за разом робить саме це.

Саме думка про "один особливий сеанс", який ми маємо після довгої подорожі на конференцію, після важкого робочого дня, сварки з дітьми, або випадку, коли партнер відмовив у сексі, часто заважає користувачам зупинитися. ***Запамʼятайте***, що немає такого поняття як перегляд "лише одним оком". Це ланцюгова реакція, і якщо її не зупинити, вона триватиме до кінця вашого життя. Міф про один особливий сеанс змушує користувачів сумувати після того, як вони припинили використання порно. Створіть звичку ніколи не розглядати сеанс "лише одним оком", тому що це фантазія. Коли ви думаєте про порно, уявляйте брудне життя, проведене за екраном заради привілею знищити себе психічно та фізично — життя рабства та безнадійності. Це не злочин якщо ваші ерекції не є надійними, але це злочин якщо ви могли би бути щасливим у довгій перспективі, але замість цього обрали жертвувати цим заради короткого "задоволення".

Це нормально, що ми не завжди можемо придумати "чим зайнятись", щоб заповнити порожнечу; це неможливо робити постійно протягом нашого життя. Ми можемо робити плани для більшості таких випадків, але іноді це просто трапляється. Також трапляються гарні і погані часи, незалежно від порно. Але зрозумійте, що порно — це не воно. Ви або залишаєтесь страждати на все життя, або не страждаєте взагалі. Ви б не приймали ціанід тільки тому, що вам сподобався смак мигдалю, тому досить карати себе випадковими сеансами "лише одним оком". Спитайте користувача, у якого є проблеми в житті: "*Якби ви мали можливість повернутись у часі, до того як ви підсіли, ви б стали користувачем?*" Відповідь завжди "*Ви мабуть жартуєте!*". Але кожен користувач має цей вибір кожного дня у своєму житті, тож чому вони не зроблять його? Відповідь на це питання — страх. Страх, що вони не зможуть зупинитися, або що життя ніколи не буде таким самим без порно.

Досить обманювати себе! Ви можете зробити це — будь-хто може. Це дуже легко, але щоб це зробити, потрібно розуміти деякі фундаментальні речі.

1.  Немає від чого відмовлятися, вас чекають тільки великі позитивні результати.

2.  Ніколи не переконуйте себе про існування сеансу "просто один раз" або "гляну лише одним оком". Його не існує. Існує тільки життя бруду та рабства.

3.  Ви не є особливими, будь-який користувач може легко зупинитися.

Багато користувачів вважають, що вони підтверджені наркомани, або мають схильні до залежності особистості. Зазвичай це трапляється у результаті надмірного читання шокуючої нейронауки. Такого не буває, ніхто не народжується з потребою мастурбувати на порно, до того як підсядуть на нього. Саме наркотик робить вас залежними, а не природа вашого характеру. Природа надприродніх стимулів, які викликають залежність, змушує вас повірити у це. Необхідно позбутися такого мислення, тому що якщо ви вірите у те, що ви залежні, ви і будете залежними навіть коли маленький монстр у вашому тілі давно помре. Дуже важливо видалити всю цю промивку мізків.
