# Звичайні користувачі

Важкі користувачі зазвичай заздрять звичайним користувачам. Ми всі бачили таких людей: "*Я можу прожити увесь тиждень без сеансу, мене це не хвилює*". Ми б хотіли бути такими. У це важко повірити, але ніякий користувач не насолоджується тим, що він є користувачем. Ніколи не забувайте:


|   *Ніякий користувач ніколи не вирішував стати таким, неважливо звичайним чи будь-яким іншим, **тому,** *

|       *Всі користувачі почуваються дурнями, **тому,** *

|         *Всі користувачі мають брехати собі та іншим у марній спробі виправдати свою тупість.*


Фанатики гольфу хваляться про те, як часто вони грають і хочуть грати, то чому ж користувачі хваляться про те, як мало вони мастурбують? Якщо це справжній критерій, тоді справжня нагорода — це не мастурбувати взагалі, чи не так?

Якби вам хтось сказав: "*Я можу прожити увесь тиждень без моркви, і це взагалі мене не хвилює*", ви б подумали що розмовляєте з божевільним. Якщо мені подобається морква, чому я хотітиму не їсти її цілий тиждень? А якщо вона мені не подобається, навіщо мені казати це? Тому коли користувач робить коментар про те, як він провів тиждень без сеансу, він намагається переконати себе і вас у тому, що він не має проблеми. Але не було б необхідності казати це, якби у нього все було добре. У перекладі цей коментар звучить так: "*Я зміг вижити тиждень без порно.*" Він, як і будь-який користувач, сподівається, що після цього він зможе виживати без порно до кінця свого життя. Якщо у нього вийшло вижити тільки тиждень, чи можете ви уявити, яким дорогоцінним буде наступний сеанс, після того як він відчував себе обділеним увесь тиждень?

Саме тому звичайні користувачі є більш залежними ніж важкі. Вони відчувають не лише сильнішу ілюзію задоволення, але також вони мають менше стимулів кинути, тому що вони витрачають на це менше часу і тому менш схильні до ризиків для здоровʼя. Іноді вони можуть відчувати імпотенцію, але не знають що її викликало, тому звинувачують інші фактори. Памʼятайте, що єдине задоволення, яке отримують користувачі — це дофаміновий цикл, повʼязаний з пошуком та пошуком, і полегшення синдрому відміни, як це було сказано раніше. Задоволення — це ілюзія. Уявіть маленького монстра як непомітний свербіж, про який ми не знаємо більшість часу.

Якщо вам постійно свербить, то нормальною реакцією є почухатись. Оскільки коло нагороди стає більш імунним до дофаміну та опіоїдів, то природною реакцією стає доведення до крайностей, ескалація, переповнення, пошук новизни, пошук шоку, тощо. Є чотири основні фактори, які запобігають ланцюговій реакції користувача.

**Час.**
Більшість не можуть цього дозволити.

**Здоровʼя.**
Для того щоб полегшити свербіж, ми маємо спожити увесь доступний безкоштовний матеріал, а потім ще і ще. Можливість справлятися з таким переїданням різна у кожної людини, і у різні часи та ситуації їхнього життя. Це працює як автоматичне обмеження.

**Дисципліна.**
Дисципліна навʼязується суспільством, роботою, друзями та родичами користувача, а може навіть самими користувачами, як результат природного перетягування канату у їхній голові.

**Уява.**
Нестача уяви зменшує шок, новизну, та інші цінності порно-кліпів на субʼєктивній основі.

Дуже легко вважати "важких" користувачів як слабких, як тих, хто не може зрозуміти чому інші можуть обмежити своє використання. Але важкі користувачі мають памʼятати, що більшість звичайних користувачів просто не можуть переглядати постійно, тому що це вимагає сильної уяви та витривалості. Більшість з цих користувачів, яким заздрять важкі користувачі, фізично не можуть більше, або тому що їм не дозволяє робота, або особиста ненависть до того, що вони потраплять на гачок.

Буде корисно надати декілька визначень.

**Не-користувач**

Хтось, хто ніколи не потрапляв у пастку, але не має цим пишатись. Вони є не-користувачами тільки через щасливу випадковість. Всі користувачі були переконані, що вони ніколи не потраплять на гачок, а деякі не-користувачі продовжують мати випадкові сеанси час від часу.

**Звичайний користувач**

Їх є два типи:

1.  Користувач, який потрапив у пастку, але не знає цього. Не заздріть таким користувачам. Вони їдять нектар мухоловки і скоріше за все, у майбутньому стануть важкими користувачами. Памʼятайте, як всі алкоголіки починають із легких напоїв, так само всі користувачі починають з легкого порно.

2. Користувач, який був важким користувачем раніше і думає, що він не може зупинитися. Такі користувачі є найсумнішими з усіх, і вони поділяються ще на різні категорії.

**Користувач раз-у-день**

Якщо їм подобається своє право на оргазм, тоді навіщо використовувати інтернет-порно тільки раз у день? Якщо вони можуть використовувати, або не використовувати його, навіщо тоді перейматися взагалі? Памʼятайте, що "звичка" — це насправді биття головою об стіну лише заради того, щоб потім розслаблятися, коли зупинишся. Той, хто використовує порно один раз у день, полегшує синдром відміни менше ніж на годину кожного дня. Хоча вони не знають, решта їхнього дня проводиться биттям головою об стіну, і роблять вони це протягом більшої частини своїх життів. Вони використовують порно раз у день, тому що вони ризикують бути спійманими на цьому, або зламати своє здоровʼя. Важкого користувача легко переконати у тому, що вони не отримують від цього задоволення, але важче переконати звичайного користувача. Будь-хто, хто пройшов через спробу зменшення використання знає, що це найгірша тортура з усіх, і майже гарантовано триматиме вас залежним на все життя.

**Користувач, якому відмовили**

Вони вимагають права на оргазм кожного дня, але їхній сексуальний партнер не завжди радий задовольнити їхнє прохання. Спочатку вони використовують інтернет-порно, щоб заповнити цю порожнечу, але після веселого спуску водною гіркою вони потрапляють у цикл новизни, шоку, надприродніх образів, тощо. Насправді, вони є щасливими коли їхній партнер їм відмовляє, бо це дає їм якесь виправдання. Якщо інтернет-порно дає вам так багато, навіщо взагалі мати партнера? Відпустіть їх. Вони навіть не отримують задоволення від сеансів, тому що їм потрібно "тримати" у голові своїх партнерів. Іноді вони шукають свого партнера у реальному житті для того, щоб він дав їм привід відправитись у темні долини інтернету.

**Користувач на порно-дієті**

Також відомий як "*Я можу зупинитись коли захочу. Я робив це вже тисячі разів!*"

Якщо вони думають, що дієта допомагає їм налаштуватися на пошук партнерів, то навіщо вони взагалі на дієті раз у чотири дні? Ніхто не може передбачити майбутнє, і побачення може статися через декілька годин після запланованого сеансу. Також, якщо випадкова "чистка труб" гарно полегшує напругу, чому тоді не робити це кожного дня? Було доведено, що мастурбація не потрібна для того, щоб тримати геніталії здоровими, а інтернет-порно не потрібне взагалі. Навіть якщо це так, ніякий гуру пікапа, який читав про нейрологічну шкоду, ніколи б не рекомендував дивитися порно. Правда у тому, що користувач порно-дієти все одно залишається на гачку. Хоча він позбавився фізичної залежності, але він досі залишився з головною проблемою — промиванням мізків. Кожного разу він сподівається що зупиняється назавжди, але через час знову потрапляє до тієї самої пастки.

Більшість користувачів заздрять таким людям і думають що їм пощастило у їхньому вмінні контролювати своє використання. Але вони не помічають, що користувач не контролює його — коли він використовує, він не хоче цього робити. Вони проходять через складнощі зупинки, потім починають відчувати себе спустошеними і потрапляють у пастку знову, не бажаючи цього. Вони отримують найгірше з двох світів. Якщо задуматись, то це правда і для життя користувачів. Коли їм дозволяють сеанс — вони сприймають це як право, або жаліють що не зробили цього. Тільки коли їх позбавляють, порно стає цінним. Синдром "забороненого фрукту" — це одна з найгірших дилем для користувачів. Вони ніколи не можуть перемогти, тому що вони сумують за міфом, за ілюзією. Є тільки один спосіб перемогти — перестати сумувати, кинувши порно!

**Користувач "Я дивлюся тільки статичне/помірне/домашнє порно"**

Так, спочатку всі це роблять, але чи не дивовижно, як середнє значення кількості шоку цих кліпів поступово зростає, і до того як ми це помітимо, ми почуваємося спустошеними? У статичному порно недостатньо новизни, тому ми спускаємось вниз по водній гірці до відрази та відчуття провини. Найгіршу річ, яку ви можете зробити, це використовувати фотографії свого партнера для мастурбації. Чому? Тому що у процесі ви програмуєте свій мозок до припливів дофаміну, які викликаються пошуком та різноманітністю. Водні гірки у вашій голові це DeltaFosB який зростає, тому потім у вас будуть проблеми, коли ви будете з партнером у реальному житті.

Ще одна пастка в цій категорії це "аматорське" та "домашнє" порно. Більшість із них — це фейки, і ви знаєте про це. До того ж, ви не зупинитесь на першому кліпі, який попадеться — замість цього ви продовжите шукати. Памʼятайте, що мозок шукає не тільки оргазм, але і новизну, яка дає кайф на водній гірці. Порно-контент не є проблемою — неважливо чи це аматорське порно, чи професійне — справа у потоках дофаміну в мозку, які спричиняють вироблення імунітету і насичення. Порно руйнує нормальну роботу мозку, мастурбація збиває з пантелику мʼязово-мозкову реакцію; оргазм переповнює мозок опіоїдами і робить звʼязки міцнішими для наступного разу.

**Користувач "Я зупинився, але іноді переглядаю"**

У якомусь сенсі вони найнещасніші з усіх. Вони або вважають себе спустошеними, або один випадковий перегляд стає двома і більше, вони спускаються по гірці, і раніше чи пізніше знову стають важкими користувачами. Вони знову потрапляють у ту саму пастку, у яку вони потрапили вперше.

Існує ще дві підкатегорії таких користувачів. Перша — це ті, хто мастурбує на картинки або відео нещодавніх знаменитостей у новинах, або на щось, що вони "випадково принесли додому" зі школи чи роботи. Такі люди справді є не-користувачами, але вони відчувають що вони щось втрачають. Вони хочуть бути частиною дії, більшість із нас починають саме так. Наступного разу зверніть увагу, що через якийсь час знаменитість, про яку ви мрієте, перестає вас приваблювати. Чим більш недосяжною є ціль вашої фантазії, тим більше розчаровує відмова від оргазму.

Інша категорія останнім часом привертає все більше уваги, тому краще описати її випадком з інтернету.

Одна жінка багато років читала порно історії в інтернеті і ніколи не використовувала більше ніж раз у ніч. Вона була жінкою із великою силою волі. Більшість користувачів дивувались би, чому вона взагалі хотіла зупинитися, і казали б їй що у неї немає ризику імпотенції. Вона навіть не використовувала статичні картинки, а історії були набагато мʼякші, ніж будь-який матеріал, який вони використовують щодня.

Вони роблять помилку, коли думають що звичайні користувачі щасливіші і мають більше контролю. Вони можуть мати більше контролю, але точно не є щасливішими. У випадку цієї жінки, вона не була задоволена ні своїм партнером, ні реальним сексом, і була дуже роздратованою, реагуючи на щоденні стреси і навантаження. Її близькі не могли зрозуміти що її дратувало. Навіть якщо вона переконувала себе не боятися свого використання за допомогою раціоналізації, вона все одно не могла насолоджуватися своїми відносинами, що приносило сварки. У результаті щоденного дофамінового переповнення центр нагороди у її мозку не міг використовувати природні дестресори, які присутні у житті. Поступове зменшення рецепторів у її голові призвело до того, що у більшості випадків вона ставала меланхолійною. Як і більшість інших, вона відчувала великий страх перед темною стороною порно та ставлення до жінок — до її першого разу. Нарешті, вона стала жертвою соціальному промиванню мізків та зайшла на свій перший сайт. Але, на відміну від більшості, хто здається і стає постійним користувачем, коли вона побачила свій перший кліп з жорстокістю, вона встояла.

Все, чим ви насолоджуєтесь у порно — це припинення тяги, яка виникла до цього, неважливо чи це майже непомітне фізичне бажання, чи душевна тортура від того, що вам не дають полегшення. Інтернет-порно саме по собі є отрутою, тому ви страждаєте від ілюзії насолоди ним після періодів утримання. Подібно до голоду чи спраги, чим довше ви утримуєтесь, тим більше задоволення ви отримуєте коли нарешті наступає полегшення. Помилково вважаючи що порно це лише звичка, вони думають: "*Якщо я зможу знизити його використання до певного рівня або лише в особливих подіях, то мій мозок і тіло приймуть це. Тоді я можу продовжувати використовувати на цьому рівні або зменшити його ще більше, якщо захочу.*"

Зрозумійте, що "звички" не існує. Порно — це наркотична залежність, природною тенденцією якої є полегшення синдрому відміни, а не його подолання. Щоб утриматись на тому рівні, на якому ви зараз знаходитесь, вам знадобиться величезна дисципліна та сила волі до кінця життя. По мірі того, як центр винагороди вашого мозку стає несприйнятливим до дофаміну та опіоїдів, він хоче все більше і більше.

Коли порно починає поступово руйнувати вашу нервову систему, сміливість, впевненість у собі та контроль імпульсів, вам стає важче опиратися і ви зменшуєте інтервали між кожним сеансом. Тому на початковій стадії ми можемо кинути. Якщо ми бачимо ознаки, що щось не так психічно або фізично, ми просто зупиняємось. Не заздріть цій жінці — коли ви дивитесь раз у 24 години, це здається найпрекраснішою річчю на землі, що перетворює порно на "заборонений фрукт". Протягом багатьох років ця жінка була в центрі перетягування канату.

Хоча вона не могла припинити використання, вона боялась перейти до перегляду потокових кліпів. Протягом 23 годин і 10 хвилин кожного дня вона мала боротися з бажаннями та відсутності почуттів до її хлопця. Це все потребувало величезної сили волі, і вона нарешті дійшла до сліз. Такі випадки поодинокі, але подивіться на це логічно: чи є у порно справжнє задоволення? Якщо воно є, навіщо бажати чекати годину, день, або навіть тиждень? Чому ви маєте відмовляти собі у задоволенні? А якщо немає справжнього задоволення, тоді навіщо відвідувати свій онлайн-гарем?

Ось іще випадок у якому чоловік, який використовує один раз у чотири дні, описує своє життя наступним чином:

> "*Мені сорок років, я страждаю від імпотенції з реальними жінками та навіть при використанні порно, що буває у більшості випадків. У мене давно вже не було повної ерекції. До того як я став на порно дієту раз у чотири дні, я міцно спав після сеансу. Тепер я прокидаюсь вночі кожну годину, і це все про що я можу думати. Навіть коли я сплю, мені сняться мої улюблені кліпи. У дні після запланованого сеансу я маю поганий настрій — ця дієта забирає всю мою енергію. Моя дружина залишає мене на самоті, тому що я дуже роздратований, а якщо у неї немає можливості піти, то вона не хоче бачити мене вдома. Я виходжу на пробіжки, але мій розум одержимий цим.*
>
> *У запланований день я починаю готуватися рано вночі, і я дуже дратуюсь якщо щось відбувається не за моїми планами. Я ухиляюсь від розмов і уступаю в суперечках (тільки щоб потім жалкувати) на роботі та вдома. Я не суперечливий чоловік, але я не хочу, щоб тема або розмова стримувала мене. Я памʼятаю випадки, коли я сварився з дурних причин зі своєю жінкою. Я чекаю десятої години, і коли час настає, мої руки неконтрольовано тремтять. Я не починаю відразу, тому що на сайт додались нові відео. Мій розум каже мені, що через те, що я голодував чотири дні, я заслуговую на особливе відео, на яке не шкода витратити часу. Нарешті, я зупинюсь на одному чи двох, але хочу насолодитися цим, щоб я міг "прожити" через наступні чотири дні, тому мені потрібно більше часу на те, щоб закінчити.*"

У додачу до своїх інших проблем, цей бідолага не знає, що він частує себе отрутою. Спочатку він страждає від синдрому "забороненого фрукту" і потім змушує свій мозок качати дофамін. Раніше його дофамінові рецептори не були так сильно зруйновані, але він змащує водні гірки, шукає новизну, шок та тривогу для того, щоб пережити наступні чотири дні. Ви мабуть думаєте про цього чоловіка як про жалюгідного імбецила, але це не так. Коли колишній атлет став колишнім сержантом морських котиків, він не хотів ставати залежним ні від чого. Але після повернення з війни він вчився на IT спеціаліста за програмою реабілітації ветеранів.

Коли він потрапив на цивільну роботу, він був гарно оплачуваним IT професіоналом у банку, і отримав ноутбук додому. Це був той час, коли відомі зірки "зливали" свої порно-відео в інтернет і про це багато говорили. Він підсів, та проводив залишок свого життя, платячи більше ніж потрібно, та руйнуючи себе фізично та психічно. Якби він був твариною, суспільство давно б позбавило його страждань, але ми досі дозволяємо психічно та фізично здоровим підліткам ставати залежними. Ви можете подумати, що цей випадок і цей запис є перебільшеними, але хоч він й екстремальний, але не поодинокий. Є десятки тисяч схожих історій. Чи можете ви бути впевнені, що багато його друзів заздрили, що він дивиться порно раз у чотири дні? Якщо ви думаєте, що це не може статися з вами, то *припиніть обманювати себе*.

**ЦЕ ВЖЕ ТРАПЛЯЄТЬСЯ.**

Як і інші наркомани, користувачі порнографії — відчайдушні брехуни, навіть до самих себе. Їм доводиться бути такими. Більшість звичайних користувачів проводять набагато більше сеансів, ніж вони зізнаються. У багатьох розмовах з так званими "двічі-в-тиждень" користувачами, вони зізнаються, що роблять це більше, ніж три чи чотири рази в тиждень. Почитайте Reddit, NoFap та різні форуми, і ви побачите що вони або рахують дні, або чекають невдачі. Вам не потрібно заздрити звичайним користувачам, ви також не маєте використовувати, життя безмежно солодше без цього. Прочитайте наступний запис:

"*Це почалося з простого випробування — не чіпати свій пеніс один день, і я не зміг. Більше я не думаю про мастурбацію, вона не приходить мені у голову. Це можливо, я обіцяю вам. Багатства, які чекають тих, хто може — вони неймовірні.*"

Підлітків зазвичай важче вилікувати, але не тому що їм складно зупинитися, а тому що вони не вірять у те, що вони залежні, або знаходяться на початкових стадіях пастки та думають, що вони зупиняться перед другою стадією.

Батьки, діти яких ненавидять інтернет-порно не мають почуватися у безпеці. Всі діти ненавидять темні сторони інтернету до того, як підсісти. На якомусь моменті, ви ненавиділи їх також. Не будьте обдурені страшними кампаніями, пастка є такою самою, якою вона була завжди. Діти знають, що інтернет-порно — це надприродній стимул, але вони також знають що один візит або один перегляд нічого не зробить. На якійсь стадії на них можуть вплинути партнер, однокласник, або колега на роботі.

Будь ласка, не будьте спокійним у цьому питанні. Нездатність суспільства запобігти пристрасті підлітків до інтернет-порно та інших наркотиків можливо є найбільш тривожною частиною цієї історії. Мозок підлітка є більш пластичним, тому необхідно навчати та захищати їх. Якщо ви не знаєте з чого почати, гарним ресурсом буде книга YourBrainOnPorn, яка допоможе вам ознайомитись з нейробіологією. Навіть якщо ви підозрюєте, що ваш підліток вже знаходиться на гачку, ця книга дає основне розуміння того, як допомогти комусь кинути. В іншому випадку, рекомендуйте цю книгу!
