# Користувач YouTube / Twitch / Instagram

Цього користувача потрібно віднести до групи звичайних користувачів, але його прояви такі підступні, що це заслуговує на окремий розділ. Використання соціальних мереж призводить до порушення самоконтролю, що майже спричинило розкол для одного користувача NoFap форуму:

> *"Пройшло три тижні після однієї з моїх невдалих спроб кинути. Вона була спричинена переживаннями моєї жінки щодо моєї вʼялості та втрати інтересу. Я сказав їй, що це не через неї, а через стрес на роботі. Вона відповіла: "Я знаю, що ти вже справлявся зі стресом на роботі раніше. Як би ти себе почував, якби ти був мною і тобі б довелось спостерігати як хтось, кого ти любиш, систематично руйнує себе?". Цей аргумент сильно мене сколихнув, тому я спробував зупинитися. Вона знає, що я не зраджую, але це у якомусь сенсі навіть гірше. Спроба закінчилась після трьох тижнів, а її закінченням стала сварка зі старим другом. Тільки лише через багато років я зрозумів, що мій підступний розум навмисно спровокував цю суперечку. У той час я відчував себе виправдано засмученим, але не думаю що це був збіг, оскільки я ніколи не сперечався з цим другом раніше і більше не сперечався з тих пір. Це явно була робота маленького монстра.*
>
> "*Не зважаючи ні на що, я мав своє виправдання. Я відчайдушно потребував полегшення, неважливо якого. Моя жінка не була у настрої, тому я мав відчуття, що я маю "право" на порно, і я переконав себе що все буде добре якщо я "обмежу" себе, буду уникати порносайтів, залишатимусь на цій стороні "червоної лінії" та дивитимусь тільки YouTube відео. Моя жінка все-таки прийшла з бажанням робити любов, але я був втомлений і сказав що у мене болить голова. Мені було нестерпно думати про те, яке розчарування це принесло моїй дружині. Тоді я повернувся до своїх старих звичок і YouTube став моїм новим гаремом. Я памʼятаю, що у той час я був доволі задоволеним та думав, що це хоча б зменшувало моє споживання. Через якийсь час вона звинуватила мене в тому, що я продовжував ігнорувати її в ліжку. Я не помічав цього, але вона описала випадки коли я починав сварки і виходив з дому. Іноді я витрачав дві години на покупку чогось у магазині та симулював різні травми. Я придумував собі виправдання щоб відмовитися від турботи за нею, а коли у мене був надійний онлайн-гарем, це було ще складніше."*

Найгірше за все те, що користувач YouTube підтримує у своїй уяві помилку про те, що він у чомусь обмежений. Одночасно це призводить до серйозних втрат самоповаги, оскільки чесна людина може обманювати своїх коханих. Можливо це вже сталося, або ще досі трапляється з вами у якійсь формі.

Проблеми, які виникають при перегляді таких сайтів як Twitch, Instagram, TikTok, Twitter, тощо, насамперед обумовлені дофаміном. Керовані тягою за новизною, користувачі обманюють себе та вірять, що вони знаходяться на безпечному сайті. Памʼятайте — кайф у пошуку, а не у вбивстві, і маленькому монстру байдуже звідки він отримує свою дозу. Для користувача "мʼякий" контент, який він отримав з різних онлайн каналів, дає йому коротке полегшення синдрому відміни та змушує його залишатися на гачку та чекати наступного сеансу.

Модель на картинці чи у відео справді красива, і якби вона була поруч з вами прямо зараз, вона б могла дати вам задоволення, але ця картинка не може... Вона просто несправжня. Ваш мозок обдурили як бика, що біжить до червоної ганчірки і після цього не розуміє навіщо він це зробив. Тоді можна подумати, що можна просто дивитися на ці картинки та не мастурбувати. Але памʼятайте, що ваш мозок залежний від безмежної новизни, і маленькому монстру байдуже звідки він отримує задоволення. Це одна і та сама пастка.

Можливо, ви бачили серіал Колумбо. Тема кожної серії схожа: лиходій, зазвичай багатий та поважний бізнесмен, вчинив, як він вважає, ідеальний злочин, і його самовпевненість у тому, що його злочин залишається нерозвʼязним збільшується, коли він дізнається що справу веде пошарпаний та невражаючий детектив Колумбо.

У Колумбо є противна практика закривати двері після закінчення допиту з підозрюваним, що дає йому переконання у тому, що він чистий. Але до того як задоволений вигляд на обличчі підозрюваного зникає, Колумбо повертається та каже: "*Лише одна маленька річ, яку, я впевнений, ви зможете пояснити...*". Підозрюваний запинається, і з цієї миті він розуміє, що Колумбо від нього не відстане. Неважливо яким огидним був злочин, з цього моменту більшість людей починали співчувати вбивці.

Ці циклічні запої є схожими: напруга від того, що користувач не дозволяє собі перетнути червону лінію та забороняє собі отримати кайф від порно, який він "заслуговує по праву", а потім дивується від відсутності очікуваного задоволення після закінчення справи. Страх перетнути лінію, втратити контроль та повернутись туди, звідки почав, страх, що ваш партнер захоче сексу. Коли "безпечні" YouTube відео більше не задовольняють вас через десенситизацію, відсутність новизни, та знання, що рано чи пізно ви відвідаєте свій онлайн-гарем. Фінальне приниження та сором наступають тоді, коли це знання стало фактом, який супроводжується поверненням до ланцюгового перегляду.

**ОХ, ЦЕ ЩАСТЯ БУТИ ЗАЛЕЖНИМ!**
