# Соціальна звичка?

Здоровʼя розуму та тіла — це основні причини, через які ми *маємо* хотіти зупинитися — але так було завжди. Нам не потрібні знання у області нейрології щоб сказати, що порно викликає залежність та може потенційно розбити наші життя. Наші тіла — це найбільш складні обʼєкти на планеті і кожен користувач знає з першого сеансу, що стимула може стати дуже багато і він перетвориться на отруту.

Єдина причина, через яку ми звʼязуємось із порно — це перетин циклів ПМО з нашим еволюційним програмуванням. Інтернет-порно дуже доступне, безкоштовне, та транслюється 24/7. Колись порно вважалось нешкідливим, але це було тоді, коли картинки були статичними, а для перегляду відео потрібно було йти до місцевого магазину з касетами.

Сьогодні навіть самими користувачами прийнято вважати, що порно є надприроднім стимулом і створює залежність. У старі часи сильний чоловік не зізнавався про те, що він мастурбує. У кожному пабі, клубі або барі більшість чоловіків з гордістю хотіли забрати жінку додому, щоб зайнятися реальним сексом. Сьогодні позиція повністю повернулась у відношенні порно залежного. Сучасні чоловіки починають відчувати, що жінки їм не потрібні. Вони обʼєднуються у мережі, обговорюють досвід, розробляють стратегії та шукають варіанти. Сучасний сильний чоловік не хоче залежати від наркотиків. Завдяки соціальній революції, всі користувачі серйозно задумуються про те, щоб відмовитись від порно та мастурбації. Сьогоднішні користувачі вважають порно непотрібним та шкідливим заняттям.

Найбільший тренд, який помічається на форумах — це збільшена увага на анти-соціальні аспекти порно. Дні, коли чоловік кожного дня хвалився сексом та оргазмами, поступово замінюються усвідомленням рабства до порно монстра.

Єдина причина, через яку навіть після задоволення первинної цікавості, користувачі продовжують дивитися порно, це тому що вони не змогли зупинитися, або сильно налякані щоб спробувати зупинитись. Існує широкий спектр цікавості до цієї теми. Хтось утримується від порно, мастурбації та оргазму — з партнерами або без них. Зараз масово обговорюються та приймаються практики, які розділяють чутливу та дітородну частини сексу, такі як утримання сперми та Karezza. Багато згаданих невдач це насправді падіння вперед, тому користувачі отримують користь коли практикують їх. Коли ви почнете дорогу не-користувача, ви знайдете найкращий підхід до вашого життя; рекомендується придумати свій особистий план оргазмів після того, як ви зрозумієте та попрактикуєте концепцію розділення сексу. Яким би не був ваш шлях, ви побачите користь у обмеженні кількості разів, коли ви заповнюєте мозок хімічними речовинами шляхом оргазму, і ніколи більше не будете дивитися на порно, секс та оргазм як на задоволення або підтримку для вашого емоційного "я".

Різні популярні онлайн спільноти, засновані не-користувачами, присвячені киданню не тільки порно, але і мастурбації також. Ці сайти цінні для тих, хто кидає, але більшість порад кажуть їм спробувати метод сили волі. Наслідками одержимості смугами (кількості днів без порно підряд) та іншими вимірами є само шкода та відсутність ентузіазму та задоволення. Більша частина промивання мізків також залишається живою. Зрештою, хтось зривається і відбувається ефект доміно: інші користувачі бачать, що вони не самі. Але, їхні спроби не є марними, вони рухаються вперед, хоча і з тортурами, оскільки вони закривають свої браузери, але не за бажанням і потребою. EasyPeasy працює навпаки: спочатку ми відкидаємо потребу та бажання і лише потім закриваємо браузер. Кожного дня все більше і більше користувачів покидають цей корабель що тоне, і тим, хто залишився позаду стає страшно що вони будуть останніми.

**НЕ ДАЙТЕ СОБІ БУТИ ТАКИМ!**
