# Вибір часу

Якщо не зважати на очевидний факт, що порно не приносить вам ніякої користі і що саме зараз час зупинитися, важливо правильно обрати для цього час. Суспільство легковажно ставиться до інтернет-порно та вважає його неприємною звичкою, яка не шкодить здоровʼю. Це неправда. Це наркотична залежність, хвороба та руйнівник відносин. Найстрашніше, що трапляється у житті більшості користувачів — це підсідання на цю жахливу залежність. Якщо вони залишаються на гачку, тоді трапляються жахливі речі. Тому важливо обрати час і дати собі право на правильне лікування.

Насамперед визначте час або випадки, коли порно здається вам важливим. Якщо ви бізнесмен, який використовує порно для ілюзії зменшення стресу — оберіть відносно вільний період або відпустку. Якщо ж ви зазвичай використовуєте порно протягом нудних або розслаблених періодів, тоді оберіть навпаки. Не зважаючи на це все, поставтесь до спроби серйозно і зробіть її найважливішою річчю у вашому житті.

Заплануйте на три тижні вперед і спробуйте передбачити будь-яку можливу подію, яка може спричинити невдачу. Такі випадки як поїздки на конференцію, відʼїзд партнера за місто, тощо, не мають вам заважати, якщо ви передбачите їх завчасно і не будете почуватись обділеними. У той час не намагайтесь зменшити використання, оскільки це лише створить ілюзію того, що це приносить задоволення. Насправді, може допомогти, якщо ви змусите себе дивитися і мати максимальну кількість порно-сеансів. Під час вашого останнього сеансу і останнього разу, памʼятайте про розчарування, невиправдані очікування, тілесний біль, синдром відміни, дратівливість, та меланхолію, які ви отримуєте через насичення. Подумайте про те, як чудово буде коли ви дозволите собі перестати це робити.

**ЩО Б ВИ НЕ РОБИЛИ, НЕ ПОТРАПЛЯЙТЕ У ПАСТКУ, КОЛИ ВИ КАЖЕТЕ: "НЕ ЗАРАЗ, ПІЗНІШЕ", ТА ВИКИНЬТЕ ЦЕ ЗІ СВОЄЇ ГОЛОВИ. СПЛАНУЙТЕ ВАШ ЧАС ЗАРАЗ І З НЕТЕРПІННЯМ ЧЕКАЙТЕ НА ЙОГО ВИКОНАННЯ.**

Памʼятайте, що *ви ні від чого не відмовляєтесь*. Навпаки, ви збираєтесь отримати величезні позитивні результати.

Протягом багатьох років медичні професіонали вважали порно нешкідливим, не знаючи різниці між статичним порно минулих років та новітнім потоковим віртуальним порно. Проблема в тому, що хоч кожен користувач і використовує інтернет-порно тільки аби полегшити спричинену ним тягу до дофаміну, його чіпляє не залежність до хімічної речовини, а промивання мізків, яка викликається залежністю. Розумна людина може повестись на приманку, але тільки дурень продовжить попадатися на неї після того, як побачить у чому обман. На щастя, більшість користувачів не дурні, вони тільки думають що є такими. Кожен окремий користувач має своє особисте промивання мізків. Через це зʼявляється широкий спектр різних типів залежних, що тільки ускладнює таємницю.

Хоча оригінальна книга була на тему кидання нікотину (один з найшвидших наркотиків, знаних людині), було неочікувано побачити що філософія, яка була викладена в оригінальній книзі, все одно працює якщо її адаптувати. Проблема, яку ми з Карром вирішили, полягає у тому, як донести накопичені знання і розуміння до кожного конкретного користувача. Я знаю, що кожен користувач може не тільки легко зупинитися, але й насолоджуватись процесом, але якщо користувач не зрозуміє цього, то все це буде не тільки марно, але і дуже важко. У своїй оригінальній книзі Ален Карр пояснює свою суперечливу пораду:

>"Багато людей казали мені: *"Ви кажете: "Продовжуйте курити, поки ви не дочитаєте цю книгу". Це, як правило, змушує курця затягувати читання книги або просто не дочитувати її". Тому, вам потрібно змінити цю інструкцію."* Це звучить логічно, але я знаю, що якби інструкція була: *"Негайно зупиніться"*, деякі курці навіть не починали б читати книгу. На самому початку мене консультував один курець. Він сказав: *"Мені дуже неприємно звертатися до вас за допомогою, я знаю що у мене сильний дух. В будь-яких інших сферах свого життя я маю повний контроль. Чому всі інші курці кидають, використовуючи силу волі, а мені доводиться звертатися до вас?"* Він продовжував: *"Але я думаю, що я міг би зробити це сам, якби я міг курити, поки кидаю."*"/

Суспільство вважає, що кидати курити дуже важко. А що потрібно курцю, коли йому важко? Наш маленький друг, наша підтримка. Кидати курити — це подвійний удар: мало того, що потрібно виконати складне завдання, що вже важко, але і підтримка, на яку ми зазвичай опираємось в таких ситуаціях не є доступною. Можливо, справжня краса цього методу це те, що вам не потрібно відмовлятися, поки ви у процесі. Замість цього ми спочатку позбуваємось від усіх страхів та сумнівів, тому після закінчення останнього сеансу ви вже насолоджуєтесь свободою.

Через це порада залишається незмінною. Неважливо як багато було сказано про те, що це буде легко та приємно, буде багато людей, яким буде важко це прийняти через промивку мізків щодо того, як важко кидати.

Вибір часу — це єдиний розділ, який змушує мене серйозно сумніватися над початковою порадою Аллена. Понад усе, якщо тригери включають у себе стрес у офісі, тоді користувачі беруть відпустку щоб зробити спробу і навпаки. Також є інший спосіб: обирати той час, який ви вважаєте найбільш складним часом. Чи то стрес, соціальні обовʼязки, концентрація або нудьга, але як тільки ви доведете, що справляєтесь та насолоджуєтесь життям у найважчих ситуаціях, будь-яке інше життя автоматично стане приємним. Але якби це була порада, чи зробили б ви спробу взагалі?

Ось аналогія. Ми з сестрою збираємось плавати разом. Ми приходимо у басейн в один і той самий час, але рідко плаваємо разом. Так трапляється через те, що вона заходить у басейн сантиметр за сантиметром, і тільки через пів години починає плавати. Це повільна тортура. Я завчасно знаю, що якщо я хочу плавати, то на якомусь етапі, неважливо наскільки холодною буде вода, мені доведеться пірнути з головою. Тому я навчився робити це найлегшим шляхом: занурюватись відразу. А тепер уявіть, якби я наполягав, що якщо вона не зануриться відразу, то не буде плавати взагалі. Якби я зробив так, вона б взагалі не стала намагатись зайти у воду. Чи бачите ви проблему?

Судячи з відгуків, багато користувачів використовували початкову пораду про вибір часу щоб відтермінувати те, що за їхньою думкою стане "злим днем". Моя наступна думка буде використовувати техніку, аналогічну розділу "переваги порно", я напишу тут щось схоже на: *"Вибір часу дуже важливий, і в наступному розділі вам порадять найкращий час для здійснення спроби"*, а на наступній сторінці просто великий напис *"ЗАРАЗ!"* Насправді це найкраща порада, але чи дослухаєтесь ви її? Можливо, найбільш тонкий аспект цієї пастки це те, що коли у нашому житті присутній справжній стрес, то це непідходящий час щоб зупинитися, але у час без стресу в нас немає бажання закінчувати свої муки. Спитайте себе наступне:

1.  Коли ви увімкнули порно вперше, чи ви справді вирішили, що ви будете залежати від нього все життя, без можливості зупинитись? ***Звичайно ні!***

2.  Чи збираєтесь ви продовжувати до кінця життя без можливості зупинитись? ***Звичайно ні!***

Тоді коли ви зупинитесь? Завтра? Наступного року? Через рік? Хіба не про це ви себе питали з того часу, коли вперше зрозуміли що підсіли? Чи ви сподіваєтесь, що одного ранку ви просто прокинетеся і не захочете більше дивитися порно? Не обманюйте себе, при будь-якій залежності ви стаєте прогресивно більш залежним, а не навпаки. Чи ви збираєтеся чекати того моменту, коли ви справді почнете відчувати що встати з ліжка складніше, ніж просто мастурбувати? Це вже буде марно.

Справжня пастка — це думки про те, що зараз не той час і що завтра завжди буде простіше. Ми віримо, що ми знаходимось у стресовій ситуації, але насправді це не так. Більшість справжніх стресів відсутні у нашому житті. Коли ви виходите з дому ви не маєте страху що на вас нападуть дикі тварини, а більшість людей не думає про те, де і як вони будуть їсти наступного разу і чи буде у них сьогодні дах над головою. Подумайте про життя диких тварин: кожного разу, коли кролик виходить зі своєї нори, перед ним розкривається Вʼєтнам. Але кролик тримається, тому що він має адреналін та інші гормони, так само як і ми. Правда у тому, що найстресовіші періоди для будь-якої істоти — це раннє дитинство та підлітковий вік. Але три мільярди років природного відбору дали нам засоби справлятися зі стресом, і багато людей, у яких було важке дитинство, живуть нормальним життям.

Фраза: *"Якщо у вас немає здоровʼя, то у вас немає нічого"* є банальною, але це правда. Коли ви відчуваєте себе фізично чи психічно сильними, ви можете насолоджуватись піднесеннями і витримувати падіння. Багато плутають відповідальність зі стресом; відповідальність стає стресом тільки коли ми не почуваємось достатньо сильними, щоб витримати її. Більшість людей руйнує не стрес, робота чи старість, а брехлива підтримка, ця ілюзія що вони опираються на щось реальне.

Погляньте на це з іншого боку — ви вже вирішили, що ви не залишитесь у цій пастці до кінця свого життя. Тому на якомусь моменті, буде він легким чи важким, ви маєте пройти через процес ставання вільним. Порно це не звичка або задоволення, це — наркотична залежність та хвороба. Ми вже визначили, що завтра не стане легше, а лише поступово гірше. Час позбутися цього **зараз**, або так близько до зараз як тільки ви зможете. Просто подумайте як швидко проходить кожен тиждень наших життів, це все що потрібно. Подумайте, як чудово було б насолоджуватися залишком ваших життів без тіней, які літають над вами. Якщо ви виконуєте інструкції, вам навіть не потрібно чекати пʼять днів або три тижні. Ви не тільки побачите що кидати насправді легко, **ви будете насолоджуватися цим!**
