# Чи сумуватиму я за веселощами?

**Ні!** Як тільки маленький монстр помре, ваше тіло перестане бажати дофаміну, а водні гірки та всі залишки промивання мізків у вашій голові швидко зникнуть через відсутність "змащення". Ви не тільки будете відчувати себе фізично та психічно краще підготовленими до стресів і тисків життя, але також будете в повній мірі насолоджуватись гарними подіями.

Існує тільки одна небезпека — це вплив тих, хто досі використовує секс як їхню опору та задоволення. *"У сусіда хліб смачніший"* — це звичне явище у багатьох сферах нашого життя і його легко зрозуміти. Чому ж у випадку порно, недоліки якого настільки великі у порівнянні з неіснуючими "перевагами", екс-користувачі схильні заздрити тим, кому секс та порнографія потрібні як опора?

Цілком зрозуміло що ми попали у пастку, оскільки нам з самого дитинства промивали мізки. Чому ж тоді, після того як ми зрозуміли сутність порно та кинули залежність, ми повертаємось назад у ту саму пастку? Це вплив соціального промивання мізків, у результаті якого порно змішується з сексом та показується як норма. У екс-користувача виникає гостра ломка! Невпевнене відчуття порожнечі від того, що вони самотні (що не є злочином), викликає відчуття тривоги та змушує їх знову кататися на водних гірках. Це справді цікава аномалія, особливо якщо взяти до уваги наступне спостереження: не лише всі не-користувачі у світі є щасливими, але і кожен користувач у світі, навіть з його викривленим, залежним, промитим мозком, що страждає від ілюзії насолоди чи розслаблення, хотіли б ніколи не потрапляти на гачок з самого початку. Тоді чому екс-користувачі заздрять?

1.  Перегляд "лише одним оком". Памʼятайте, його не існує. Досить бачити ізольований випадок та подивіться на це з точки зору порно-користувача. Можливо, ви заздрите їм, але вони не схвалюють свого способу життя і заздрять вам. Якби ви могли якимось чином подивитися за іншим користувачем у його тілі, це могло би бути найсильнішим поштовхом, який би допоміг вам вибратись із цього стану. Чи бачили ви, як швидко вони відкривають багато вкладинок та вікон у браузері? Як вони перемотують до цікавих моментів, як швидко їм набридають кліпи та як вони перебирають жанри, викликають новизну, шок, тривожність, тощо? Особливо зверніть увагу на те, що їх дії виглядають автоматичними та компульсивними. Памʼятайте — вони не отримують від цього задоволення, але вони не можуть насолоджуватись собою без цього. Наступного ранку, коли вони прокидаються з ослабленою волею, втраченою енергією та втомленими очима, їм доведеться продовжувати душити себе при першому прояві стресу. Їм загрожує ціле життя бруду, жахливого психічного здоровʼя та підірваної впевненості у собі. Ціле життя руйнування самих себе з чорними тінями у їхній голові. І заради чого? Ілюзії, що вони отримують те, що "заслужили" та це кляте "задоволення"?

2.  Друга причина, через яку деякі екс-користувачі відчувають страждання, це тому що користувач чимось займається — наприклад, доставляє собі задоволення, а не-користувач ні, тому вони відчувають себе обділеними. Запамʼятайте, що спустошеним є не той, хто не дивиться порно, а той залежний, який позбавляє себе від:

    -   Здоровʼя

    -   Енергії

    -   Впевненості

    -   Спокою

    -   Сміливості

    -   Умиротворення

    -   Свободи

    -   Самоповаги

Киньте звичку заздрити порно-користувачам і почніть бачити їх як нещасних істот, якими вони є насправді. Я знаю це, тому що колись я був одним з найгірших. Через це ви і читаєте цю книгу, а не є тими, хто не може подивитися правді у очі та продовжує обманювати себе.

Ви б не заздрили героїновому наркоману, і як і будь-яка інша залежність, ваша не стане кращою. З кожним разом вона буде погіршуватись у рази — і якщо ви не отримуєте задоволення від того, що ви є користувачем сьогодні, то завтра це буде ще гірше. Не заздріть іншим користувачам, жалійте їх. Повірте мені: ***Їм потрібна ваша жалість!***
