# Чи можу я розділити проблему?

Цей міф головним чином поширюється тими користувачами, які намагаються зупинитися за допомогою методу сили волі, та тими що кажуть: "*Порно — це для мого альтер-его, а романтика у реальному житті — для моєї здорової особистості, яка хоче відносин.*" Ніщо не може бути далі від правди: водні гірки, DeltaFosB та нейрологічні зміни захлеснуть реальну романтику і зроблять її менш бажаною.

Якщо ви використовуєте інтернет-порно, тоді ви тренуєте себе до ролі вуаєриста, вимагаєте можливостей перейти до чогось, що збуджує сильніше при найменших падіннях рівня дофаміну, або вимагаєте постійного пошуку *тієї самої* сцени для досягнення максимального ефекту. Окрім цього, ви можете мастурбувати у згорбленій позі, або дивитися телефон у ліжку вночі, тому згодом ви будете бажати цих сигналів і обставин більше, ніж реальних стосунків. Секс суперечить майже всім аспектам онлайн-гарему, тому у нього немає ніяких шансів у порівнянні з порно. Створені у молодості спогади є сильними та довговічними, тому руйнування цих водних гірок або створення нових займає більше часу. Але, це не означає, що це буде складніше.

Кожного разу, коли ви спускаєтесь по "водній гірці", ви змащуєте її та тримаєте нерви свіжими та готовими до пострілу. Коли ви паркуєтесь поруч з фастфудом і запах їжі залітає у ваш ніс, тоді продаж уже зроблено — ви точно купите собі щось. Так само водні гірки порнографії у вашому мозку готові до того, щоб ви покатались на них, та відкриті 24/7. Кожен натяк або тригер запалює ваше коло нагороди з обіцянкою сексу — але це не секс. Не зважаючи на це, нервові клітини зміцнюють ці асоціації із сексуальним збудженням та створюють нові відростки для зміцнення звʼязків. Чим більше ви використовуєте порно, тим більш міцними стають ці звʼязки. У результаті, вам *потрібно* бути вуаєристом, якому потрібно шукати матеріал, що постійно ескалується та оновлюється. Ви стаєте тим, кому потрібно порно для сну, або кому потрібно шукати ідеальне закінчення для того, щоб завершити справу.

Як і до будь-якої речовини чи поведінкового наркотику організм виробляє толерантність і наркотик більше не полегшує синдром відміни повністю. Як тільки користувач закінчує сеанс, він майже відразу хоче ще — вічний голод залишається незадоволеним. Природнім нахилом є ескалація, щоб отримати потік дофаміну. Але більшість користувачів не можуть цього робити через одну з наступних причин.

**Гроші:** Вони не можуть дозволити собі підписуватись на платні порно-сайти.

**Здоровʼя:** Існує обмеження по тому, скільки наше тіло може витримати дофаміну чи оргазмів. До того ж, оргазми викликають хімічні речовини, щоб зменшити потік дофаміну. Так має бути, оскільки так працює наше тіло.

Як тільки маленький монстр покине ваше тіло, огидне відчуття незахищеності зникне. До вас повернеться впевненість, разом із чудовим відчуттям самоповаги, ви отримаєте контроль над своїм життям та будете використовувати цю впевненість як трамплін, щоб справлятися з іншими проблемами. Це одна із багатьох переваг позбавлення від будь-якої залежності.

Міф розділення — це одна з багатьох ігор, якими маленький монстр грає з вашим мозком. Ці ігри ускладнюють процес зупинки, через неможливість втамувати вічний голод — через що багато користувачів переходять на цигарки, алкоголь, або навіть важчі наркотики для того, щоб заповнити порожнечу.

Люди — це тварини, які оцінюють як себе, так і інших. Перегляд порно з вашим партнером не приносить задоволення, оскільки ви разом оцінюєте одне одного в ліжку в порівнянні з тим, що відбувається у відео. Чи хочете ви бачити Бред Піта у своїй кімнаті, навіть якщо він на постері? Ніяка людина не може бути рівною до гарему, де кожен "досвід" розіграний по сценарію, зрежисований професіоналами і відразу доступний 24/7.
