# Уникайте несправжніх стимулів

Багато користувачів, які використовують метод сили волі, намагаються збільшити свою мотивацію шляхом створення несправжніх стимулів. Є багато таких прикладів, найбільш типовий це нагорода себе подарунками, якщо не переглядав порно місяць. Це виглядає ніби логічний підхід, але насправді це не так, тому що будь-який користувач скоріше буде дивитися порно кожного дня, аніж нагороджуватиме себе подарунком. Це створює сумніви у голові користувачів, тому що їм не тільки доведеться утримуватися *тридцять днів*, але вони навіть не впевнені, чи будуть вони *насолоджуватися* цими днями без порно. У них забрали єдине задоволення чи опору! Все це лише збільшує розмір жертви, яку, як вважає користувач, він робить, і тепер порно стає ще більш цінним у його свідомості.

Інші приклади:

-   Я зупинюсь, щоб це змусило мене зайнятися соціальним життям та отримувати більше реального сексу.

-   Я зупинюсь, щоб якась магічна енергія допомогла мені перегнати суперників та я отримав партнера, якого добиваюсь.

-   Я зупинюсь щоб не витрачати свою енергію та ентузіазм на порно для того, щоб збільшити в собі голод.

Всі ці приклади правильні та можуть бути ефективними, і у результаті ви можете навіть отримати те, що ви хочете, але подумайте трохи про це. Якщо ви справді отримаєте те, що хотіли, то коли новизна піде, ви будете відчувати себе спустошеним; якщо ж ні, то нещасним. У будь-якому разі, рано чи пізно ви потрапите у ту саму пастку.

Коли ви повʼязуєте кидання з несправжніми стимулами, ви тільки збільшуєте сумніви, тому що якщо ви не отримаєте свій стимул (і навіть якщо отримаєте), ви почнете сумніватися: "*Чи кидання справді зробить моє життя кращим? Якщо я кину і не отримаю того, що я хочу, чи використовував я цей метод правильно?*". Такі думки збільшують відчуття жертви і створюють страх.

Іншим типовим прикладом є онлайн форуми або онлайн домовленості. Їх перевага полягає в тому, що вони можуть знищувати тягу на деякі періоди. Але, як правило, вони не працюють через наступні причини:

1.  Цей стимул є несправжнім. Чому ви хочете зупинитися тільки тому що так роблять інші? Все, що це дає — це створює додатковий тиск та збільшує відчуття жертви. Це добре, що всі користувачі справді хочуть зупинитися у якийсь один час — але ви не можете змусити їх зупинитися, якщо всі секретно все ще бажають порно. Допоки вони не готові зробити це, пакт створить додатковий тиск, що тільки збільшує їхнє бажання дивитися. Це перетворює їх у секретних користувачів, що далі збільшує відчуття залежності.

2.  Залежність одне від одного при використанні методу сили волі створює відчуття, що вони переживають період покаяння, під час якого вони чекають поки бажання зникне. Якщо вони здаються бажанню, тоді виникає відчуття невдачі. При використанні методу сили волі як мінімум один з користувачів здасться, що дає іншим користувачам виправдання, на яке вони чекали. Це не їхня провина, вони б тримались, але "Фред" їх підвів. Але правда в тому, що більшість із них вже обманювали інших.

3. Розподіл заслуг — це зворотня сторона такого взаємозвʼязку. Зупинка порнографії це чудове досягнення, і якщо ви робите це самостійно, то заохочення, яке ви отримуєте від своїх друзів та інтернет приятелів, може стати великим стимулом у перші декілька днів. Але, коли всі роблять це в один і той самий час, заслуга має бути розділена і стимул зменшується.

4.  Інший приклад це обіцянка гуру. Зупинка дасть вам щастя, тому що ви більше не перетягуєте канат самі з собою, ваш мозок починає перепрограмовуватись та відновлювати контроль над імпульсами. Але ви маєте памʼятати, що це не зробить вас богом сексу і не дасть виграти лотерею. Ніхто крім вас не переймається чи ви зупинили використання порно. Ви не слабка людина, якщо ви використовуєте порно три рази в день і маєте імпотенцію через неї, і не сильна людина, якщо ви не дивитесь порно і у вас все добре.

Досить себе обманювати. Якщо користувачів не зупинили пропозиції працювати десять місяців у рік за річну зарплату, ризики зменшення можливості вашого мозку справлятися зі стресами щоденного життя, загрози імпотенції, або життя психічних та фізичних тортур та рабства, то декілька несправжніх стимулів зверху не зроблять ніякої різниці, а тільки змусять відчувати що жертва є більшою. Замість цього, сконцентруйтесь на іншому:

\"Що я з цього отримую? Чому мені потрібно дивитися порно?\"

Продовжуйте дивитися на іншу сторону перетягування канату і спитайте у себе, що порно вам дає. *АБСОЛЮТНО НІЧОГО*. Навіщо воно мені потрібне? *НЕ ПОТРІБНЕ! ВИ ТІЛЬКИ НАКАЗУЄТЕ СЕБЕ*. Це ваги Паскаля: вам майже нічого втрачати (зменшене збудження), ви маєте шанси на великі виграші (повне і впевнене збудження, душевне благополуччя та щастя) і нуль шансів сильно програти.

Чому б тоді не розповісти про ваше рішення кинути друзям та родині? Тому що це зробить вас гордим екс-користувачем, а не піднесеним та щасливим не-користувачем. Це може трохи налякати вашого партнера, тому що вони можуть дивитися на це, як на схему щоб мати більше сексу. Вони можуть також боятися, що ви перетворитеся на секс машину, це важко пояснити допоки вони не захочуть слухати.

Будь-яка спроба змусити інших допомогти вам у киданні дає більше сили маленькому монстру. Намагатися виштовхнути його з вашої голови і повністю ігнорувати його означає намагання не думати про нього. Замість цього будьте уважними. Як тільки ви помітите думки, натяки (сам вдома) або випадкові думки, просто скажіть собі *\"Чудово, я більше не раб порно. Я вільний та буду щасливий пізнати звичайний секс!\"* Це допоможе знизити активність думки та зупинить її від переходу у стан тяги та сильного бажання. У цьому аспекті може допомогти практика медитації для деперсоналізації думок.
