# Легкий спосіб зупинитися

У цьому розділі написано про те, як легкого зупинити використання порно. Якщо ви дотримуєтесь інструкцій, то ви побачите, що зупинити використання порнографії — це відносно легко і навіть приємно! Якщо ви будете виконувати наведені нижче інструкції, то зробити це буде дуже легко. Вам потрібно зробити лише дві речі:

1.  Зробіть рішення, що ви більше ніколи не будете дивитися порно.

2.  Не сумуйте за ним. Радійте.

Ви можете запитати: *"Навіщо потрібен залишок книги? Чому ви не могли сказати це з самого спочатку?*". Проблема у тому, що якби ми це зробили, ви б якийсь час сумували через це, і раніше чи пізніше змінили б своє рішення. Скоріше за все, ви вже робили це багато разів раніше.

Як вже було сказано, порно — це підступна, зловісна пастка. Основна проблема у зупинці це не залежність від дофаміну. Вона, звичайно, є проблемою, але не головною. Головна — це промивання мізків. Тому необхідно спочатку зруйнувати всі міфи та помилкові уявлення. Зрозумійте свого ворога, вивчіть його тактику, і ви легко його поборете. Коли я намагався кинути, я провів багато свого часу на депресію, і коли нарешті кинув, я перестав використовувати без єдиного поганого моменту. Це було приємно навіть під час періоду відміни, і відтоді я ніколи не мав ніяких відчуттів болю. Навпаки, це була одна з найкращих речей, яка трапилась у моєму житті.

Моя остання спроба була іншою. Як і всі сучасні користувачі, я серйозно задумався над проблемою. До цього моменту, після невдачі я втішав себе думкою, що наступного разу буде легше. Мені ніколи не спадало на думку, що мені доведеться продовжувати йти цим шляхом до кінця свого життя. Ця думка заповнила мене страхом, і я почав дуже глибоко думати над цим питанням.

Замість того, щоб підсвідомо відкрити браузер, я аналізував свої відчуття і підтвердив те, що вже знав. Я не отримував задоволення від порно і вважав його брудним та огидним. Я почав дивитися на не-користувачів, які жили в інших частинах світу, та старих людей, які ніколи не бачили порносайтів. До цього моменту я завжди вважав не-користувачів невпевненими, несоціальними, вибагливими людьми. Але, після того, як я подивився за їхньою поведінкою, я побачив що вони виглядають більш сильними та більш розслабленими. Вони могли справлятися зі стресами життя і отримували більше задоволення від спілкування, ніж порно-користувачі. Вони точно мали більше блиску ніж у користувачів.

Я почав спілкуватися з екс-користувачами. До цього моменту я завжди вважав, що вони були змушені кинути через проблеми зі здоровʼям або з релігійних причин, і завжди таємно бажали відвідати гарем. Дехто сказав *"Іноді бувають дивні відчуття, але їх так мало і вони такі слабкі, що про них навіть не потрібно думати"*. Більшість казали: *"Сумую за ним? Ви мабуть жартуєте! Життя ніколи не відчувалось кращим!"* Для них невдачі були падінням вперед, вони не засуджували себе і приймали це. Як тренер, хто приймає помилку свого золотого гравця. Після розмов з екс-користувачами було зруйновано ще один міф, який завжди був у мене в голові, що всередині мене була слабкість, допоки я не зрозумів, що всі проходять через цей особистий кошмар.

Я сказав собі: *"Багато людей зупиняються зараз і ведуть нормальні щасливі життя, мені не потрібно було цього робити до того, як я почав, і я памʼятаю, як мені довелось потрудитись, щоб звикнути до цієї бридоти. То чому мені потрібно робити це зараз?"* У будь-якому разі, я не отримував задоволення від порно, ненавидів цей брудний ритуал і не хотів проводити залишок свого життя у рабстві цієї огидної залежності. Потім я сказав собі:

*"Подобається тобі це чи ні, але тільки що ти завершив свій останній сеанс."*

З того моменту я знав, що більше я ніколи не буду використовувати порно. Я не очікував, що це буде легко — навіть навпаки. Я повністю вірив, що я підписався на місяці депресії і проведу залишок свого життя, періодично відчуваючи тягу до порно. Але замість цього, з самого початку це було абсолютне блаженство.

Мені знадобилося багато часу, щоб зрозуміти чому це було так легко і чому я не страждав від цього жахливого синдрому відміни. Причина у тому, що його не існує, його лише викликають сумніви та невпевненість. **Порно легко кинути**, але невизначеність та сум ускладнює це. Навіть поки користувачі ще є залежними, вони можуть проживати відносно довгі періоди часу без порно. Ви страждаєте тільки тоді, коли ви хочете, але не можете отримати його.

Тому для того, щоб це було легко, потрібно зробити зупинку точною та остаточною. Не сподіватися, а *знати*, що ви зупинились, прийнявши рішення. Ніколи не сумнівайтеся і не задавайте питань, навпаки — завжди радійте! Якщо ви будете щасливими з самого початку, це буде легко. Але як ви можете бути впевненим з самого початку? Для цього і потрібен залишок цієї книги. Є деякі важливі моменти, які необхідно зрозуміти для себе до того як почати:

1.  Зрозумійте, що ви можете це зробити. Ви нічим не відрізняєтесь від інших, і єдина людина яка може змусити вас дивитися — це ви самі. Та зірка ніколи у її найшаленіших мріях не думала, що її будуть використовувати для зменшення мужності.

2.  Немає від чого відмовлятися. Навпаки, можна отримати величезні позитивні результати. Ви не тільки станете більш здоровим та багатим, але також будете насолоджуватись гарними часами і будете менше страждати протягом поганих часів.

3.  Не існує такого поняття, як глянути лише одним оком або зайти на один раз. Порнографія — це наркотична залежність і ланцюгова реакція, і якщо ви будете сумувати за одним візитом, ви тільки марно себе покараєте.

4.  Розглядайте порно не як звичку, яка може нашкодити вам, а як наркотичну залежність. Змиріться із тим фактом, що неважливо подобається вам це чи ні, **ви маєте хворобу**. Вона не зникне, якщо ви закриєте на це очі. Памʼятайте, що як і всі смертельні хвороби, вона не тільки триває все життя, але й стає все гіршою і гіршою. Краще вилікуватися від неї зараз.

5.  Розділіть хворобу — неврологічну залежність, від роздумів бути користувачем чи ні. Всі користувачі, якщо дати їм можливість повернутися у часі до того, як вони підсіли, відразу би схопились за цю можливість. Ви маєте таку можливість сьогодні! Навіть не думайте про це як про "відмову".

Коли ви приймете остаточне рішення про те, що у вас був останній візит, ви вже станете не-користувачем. Користувач — це один із тих нещасних, який живе, руйнуючи себе порнографією. Не-користувач — це той, хто цього не робить. Коли ви прийняли остаточне рішення, ви вже досягли своєї цілі. Радійте цьому факту, не сидіть в очікуваннях, поки пройде хімічна залежність. Виходьте і насолоджуйтесь життям відразу. Життя прекрасне, навіть коли ви залежний, а коли ви позбавитесь залежності, з кожним днем воно ставатиме набагато кращим.

Ключ до того, щоб легко кинути порно — це бути впевненим у тому, що вам вдасться повністю утриматись від перегляду протягом періоду відміни, який триває максимум три тижні. Якщо ви маєте правильний настрій, вам буде до сміхоти легко.

До цього моменту, якщо ви відкрили свій розум, як вас просили на початку, то ви вже вирішили, що ви кинете. Тепер ви маєте з нетерпінням чекати того моменту, коли зруйнуєте водні порно-гірки DeltaFosB, як пес, що натягується на ланцюгу. Якщо у вас виникає відчуття приреченості, це може бути через одну з наступних причин:

1.  Щось не зрослось у вашій голові. Перечитайте пʼять вказівок зверху і спитайте себе, чи ви вірите у них. Якщо ви сумніваєтесь на якійсь вказівці, перечитайте відповідний розділ книги.

2.  Ви боїтесь самої невдачі. Не переживайте, просто читайте далі і у вас усе вийде. Увесь бізнес інтернет-порно — це шахрайство великого масштабу. Розумні люди потрапляють на такі хитрощі, але тільки дурень продовжує себе обманювати, після того як дізнався у чому річ.

3.  Ви погоджуєтесь з усім, але все одно є нещасним. Не треба так! Відкрийте свої очі, зараз трапляється щось чудове. Ви збираєтесь втекти з вʼязниці, необхідно починати з правильного настрою: *"Це чудово що я не-користувач!"*

Все, що потрібно зробити зараз — це тримати себе у цьому настрої протягом періоду відміни. У наступних декількох розділах розглядаються конкретні моменти, які дозволять вам це зробити. Після періоду відміни вам не потрібно буде продовжувати думати таким чином, ви будете робити це автоматично. Єдиною загадкою у вашому житті буде те, чому ви не бачили цього раніше. Але, спочатку два важливих застереження:

-   Відкладіть свій план останнього візиту, допоки ви не дочитаєте цю книгу до кінця.

-   Вже багато разів згадувався період виходу із залежності, який триває до трьох тижнів, що може викликати непорозуміння. По-перше, ви можете підсвідомо вирішити, що вам доведеться страждати протягом трьох тижнів. Це не так. По-друге, уникайте мислення по типу: *"Якимось чином я маю утримуватися три тижні, і тоді все буде добре."* Нічого магічного після трьох тижнів не станеться, ви не відчуєте себе не-користувачем. Якщо ви сумуєте з приводу зупинки використання протягом трьох тижнів, то, скоріше за все, ви все ще будете сумувати за цим після трьох тижнів. Підсумовуючи, можна сказати, що якщо ви прямо зараз почнете казати: *"Я більше ніколи не буду використовувати, хіба це не чудово?"*, то через три тижні всі бажання підуть. Але, якщо ви казатимете: *"Якщо я зможу вижити ці три тижні без порно..."*, то через три тижні ви будете помирати від бажання відвідати гарем.

Думайте про це так: ваш мозок хоче зберегти теперішній стан, тож якщо ви переконані, що коли ви кидаєте ви втрачаєте щось хороше, ви відчуватимете себе жахливо. Неможливо змусити відчувати себе якимось чином, якщо ваш мозок у це не вірить. Тому, важливо пройти через складнощі руйнування ілюзії про те, що порнографія узагалі вам щось дає. Так ви зрозумієте, що ви нічим жертвуєте.

Імпотенція багато чим звʼязана з вашим мозком та настроєм. Інтернет-порно перепрограмовує схему нагороди у вашому мозку і дає вашому мозку сумніви. Ці сумніви спричиняють імпотенцію. Мати бажання у верхній частині тіла, але не відчувати збудження у нижній — це найгірше що може статися з вашим мисленням. Лібідо, яке йде рука в руку з романтикою — це еліксир молодості, який ви можете пити до самої смерті. Ви залишите собі високі шанси якщо кинете, але це не єдина і не головна перевага. Головне — це ваша свобода від рабства!
