# Період синдрому відміни

Протягом трьох тижнів після вашого останнього сеансу ви можете відчувати синдром відміни. Він складається з двох окремих факторів:

1.  Синдром відміни від дофаміну. Це пусте, схоже на голод невпевнене відчуття, яке можна ідентифікувати як тяга, або відчуття що "я маю щось робити".

2.  Психологічні тригери конкретних зовнішніх стимулів, такі як реклами, онлайн-інформація, телефонні розмови, тощо.

Через невміння зрозуміти та розпізнати ці два фактори, стає важче досягти успіху за допомогою методу сили волі, і через це багато хто потрапляє у пастку знову. Хоча дофамін не створює фізичного болю, не варто недооцінювати його силу. Якщо ми живемо без їжі один день, то ми відчуваємо "біль у животі" — він може кавчати, але фізичного болю немає. Тим не менш, голод це потужна сила, і ми, скоріше за все, станемо дуже роздратованими без їжі. Це схоже на те, коли наше тіло бажає припливу дофаміну, але різниця полягає у тому, що наше тіло потребує їжі, а не отрути. З правильним підходом, синдром відміни легко долається і дуже швидко зникає.

Після утримання протягом декількох днів за допомогою методу сили волі тяга до дофаміну зникає. А ось другий фактор — промивання мізків — викликає складнощі. Користувач звик полегшувати свій синдром відміни у визначений час та випадки, що спричиняє асоціацію ідей (*"Я збуджений, тому я маю дивитися порно"*, або *"Я в ліжку зі своїм ноутбуком, і я маю провести сеанс, щоб почуватися щасливим"*). Цей ефект найкраще ілюструється прикладом: у вас була машина у якій поворотні сигнали знаходились зліва від керма, але у вашій новій машині вони знаходяться праворуч. Ви знаєте, що вони знаходяться праворуч, але протягом декількох тижнів ви вмикаєте двірники, коли ви хочете увімкнути поворотні сигнали.

З киданням порно справа виглядає приблизно так само: у перші дні спусковий механізм буде спрацьовувати у визначений час. Ви будете думати що хочете сеансу, тому протидіяти промиванню мізків необхідно з самого початку, і це приведе до того, що ці сигнали і тригери швидко зникнуть. При використанні методу сили волі, оскільки користувач вірить, що приносить себе у жертву, він сумує через це та чекає поки бажання підуть, що не видаляє цих спускових механізмів, а насправді збільшує їх. Аналогічно думкам гуру, користувач, який кидає, починає думати коли він вже стане богом, і навіть вимагає, щоб у нього не було таких думок, що асфальтує дорогу до самоненависті та невдачі.

Найпоширенішими тригерами є час на самоті, особливо на соціальних зустрічах з друзями. Екс-користувач, який використовує інші методи, вже є нещасним через відсутність своєї звичної опори або задоволення. Їхні друзі знаходяться зі своїми партнерами та ведуть себе інтимно. Користувач же або самотній, або не "отримує" нічого від свого партнера, і тепер більше не отримує задоволення від того, що має бути приємним спілкуванням з друзями. Водні гірки в їхній голові ведуть їх до порно, що набагато легше, ніж намагатися завоювати свого партнера.

Оскільки право на секс асоціюється у них з благополуччям, тепер вони отримують потрійний удар, і промивання мізків збільшується. Якщо вони рішучі та можуть протриматися достатньо довго, то вони нарешті приймають це і продовжують жити. Але частина промивання мізків все ще залишається — це другий найбільш нещасний аспект: коли користувач кинув, але навіть після декількох років досі бажає "одного останнього візиту до гарему". Вони сумують за ілюзією, яка існує тільки у їхній голові, і марно катують себе.

Навіть з використанням EasyPeasy, реакція на тригери є найбільш поширеною невдачею. Колишній користувач розглядає інтернет-порно як плацебо або цукрову пігулку, та думає: "*Я знаю, що порно нічого для мене не робить, але якщо я буду думати, що воно щось мені дає, тоді у деяких випадках це буде корисно.*" Цукрова пігулка, хоч і не дає ніякої фізичної допомоги, може бути сильним психологічним засобом для полегшення справжніх симптомів, і через це є корисною. Але інтернет-порно та мастурбація це не цукрові пігулки. Чому? Тому що порно саме створює симптоми які воно полегшує, і з плином часу взагалі перестає полегшувати їх повністю.

Можливо, вам бути легше зрозуміти ефект, якщо мова йтиме про людину, яка не використовує, або про успішного користувача який кинув декілька років тому. Візьмемо випадок користувача, який втрачає свого партнера. В такі моменти доволі часто їм кажуть: "*Відвідай гарем один раз, це допоможе заспокоїтись.*" Якщо вони прийняли пропозицію, то вони не отримають заспокійливого ефекту, тому що дофамінова залежність відсутня, так само як і синдром відміни. В найкращому випадку це лише дасть їм короткочасне психологічне піднесення.

Але після того як сеанс закінчився, початкова проблема все ще тут. Більше того, вона збільшиться, тому що людина тепер страждає від синдрому відміни і має вибір: терпіти його, або полегшувати його шляхом повторних поїздок на водних гірках, щоб почати ланцюгову реакцію страждань заново. Все, що дало їм порно — це короткочасне психологічне піднесення, таке саме, якого можна було досягти книгою або гарним фільмом, а може навіть і поганим. Багато не-користувачів та екс-користувачів стали знову залежними у результаті таких випадків. Запамʼятайте: вам не потрібен приплив дофаміну, і ви тільки ще більше катуєте себе, коли продовжуєте вважати це якоюсь опорою або стимулом. Немає потреби бути нещасним.

Оргазми не роблять стосунки гарними, частіше за все вони їх руйнують. Також памʼятайте, що не завжди ті, хто публічно демонструють прояви прихильності, отримують задоволення за будь-якого приводу. Інтимністю краще за все насолоджуватися на самоті, де партнери можуть робити це без сорому. Не обовʼязково бути дофаміновим наркоманом, який бажає оргазму. Якщо це відбувається як природній результат серії життєвих подій — це чудово, але насолоджуйтесь подіями та життям без нього.

Після відмови від концепції порно як задоволення самого по собі, багато користувачів думають: "*Якби ж тільки було чисте інтернет-порно.*" Чисте мʼяке порно існує, і всі, хто його пробують, швидко переконуються що це марна трата часу. Запамʼятайте, що ви використовуєте порно лише для отримання дофамінового задоволення. Як тільки ви позбавитесь від дофамінової тяги до порно, у вас відпаде необхідність відвідувати свій онлайн-гарем.

Незалежно від того, чи була викликана ця тяга реальними симптомами дофамінової відміни чи тригерами, прийміть це. Фізичного болю немає, і з правильним настроєм це не буде проблемою. Не переживайте про синдром відміни — це відчуття саме по собі не таке погане. Проблема у асоціації з бажанням та послідуючому відчутті синдрому відміни. Замість того, щоб сумувати через це, визнайте: "*Я знаю що це таке — це синдром відміни після порно. Це те, від чого користувачі страждають все життя і те, що тримає їх залежними. Ті, хто не використовують, не відчувають цих тортур — це ще одне з багатьох зол цієї залежності. Чи не чудово це, що я очищую свій мозок від цього зла!*"

Іншими словами, протягом наступних трьох тижнів всередині вашого тіла буде маленька травма, але протягом цього часу і на залишок вашого життя з вами буде відбуватися щось чудове. Ви звільнитесь від гидкої хвороби, при чому бонуси значно переважать легку тимчасову травму, і ви будете насолоджуватися синдромом відміни. Він стане моментами задоволення, як захоплююча гра по знищенню порно-паразита, який живе всередині вашого шлунку. Ви маєте морити його голодом протягом трьох тижнів, поки він намагається обманом затягти вас у пастку, щоб зберегти своє життя.

Іноді він буде намагатися зробити вас нещасним. Іноді ви будете захоплені зненацька. Ви отримаєте інтернет-посилання на порно, або знайдете щось онлайн і забудете про те, що ви зупинились, що викличе легке відчуття позбавлення при згадуванні. Будьте готовими до цих хитрощів завчасно, і якою б не була спокуса, памʼятайте, що вона існує тільки через монстра всередині вашого тіла, і кожного разу, коли ви опираєтесь спокусі, ви завдаєте ще одного фатального удару в цій битві.

Що б ви не робили, не намагайтесь забути про порно. Це одна тих з речей, яка викликає години депресії у користувачів які використовують метод сили волі. Вони намагаються прожити кожен день з надією, що вони нарешті забудуть про це. Це як намагатися заснути перед важливим днем — чим більше ви переживаєте за це, тим важче це зробити. У будь-якому разі, ви не зможете забути про нього, тому що протягом перших декількох днів маленький монстр буде постійно нагадувати вам про це, і ви не зможете його уникати. Поки поруч є ноутбуки, смартфони та журнали, ви матимете постійні нагадування.

Суть у тому, що вам не потрібно забувати, оскільки нічого поганого не трапляється. Насправді трапляється щось чудове, і навіть якщо ви думаєте про це тисячу разів на день, **смакуйте кожним моментом, нагадуйте собі як чудово знову бути вільним. Нагадуйте собі про величезне щастя від того, що вам більше не потрібно катувати себе.** Як було сказано раніше, ви побачите, що тяги стануть моментами радості, і здивуєтесь, як швидко ви забудете про порно.

Що б ви не робили, *не сумнівайтесь у своєму рішенні*. Коли ви почнете сумніватися, ви почнете сумувати і все стане гірше. Замість цього, використовуйте момент смутку і перетворіть його на стимул. Якщо причина у депресії, тоді нагадайте собі що її *спричиняє* порно. Якщо друг надіслав вам інтернет-посилання, з гордістю скажіть йому: "*Я радий повідомити, що мені це більше не потрібно.*" Це засмутить його, але коли він побачить що вас це не турбує, він буде на півшляху до того, щоб приєднатися до вас.

**Памʼятайте: ви маєте дуже потужні причини для зупинки використання порно.** Нагадуйте собі про витрати та спитайте у себе, чи ви справді хочете ризикувати порушенням роботи вашого тіла та розуму, і жити під прокляттям слабкості до кінця своїх днів. Не забувайте про спроби маленького монстра зменшити небезпеку для себе, і більше всього, памʼятайте, що це відчуття лише тимчасове, і кожен момент є ближчим до вашої мети.

Більшість користувачів бояться, що вони мають витрачати залишок своїх життів на подолання "автоматичних тригерів". Іншими словами, вони думають, що вони мають жити, використовуючи психологію та обманюючи себе, що їм не потрібне порно. Це не так. Памʼятайте, що оптимісти бачать пляшку напівповною, а песимісти бачать її напівпорожньою. У випадку порнографії пляшка порожня, а користувач бачить її повною. У використанні порно немає ніяких переваг. Користувачу промили мізки, щоб він думав що переваги існують. Як тільки ви почнете казати собі що порнографія вам нецікава або непотрібна, через якийсь час вам навіть не потрібно буде нагадувати собі про це, ви самі побачите чудову правду. Це останнє, що вам потрібно зробити. Але переконайтесь, що це не останнє, що ви зробите у своєму житті.
