# Лише один маленький перегляд

Це загибель багатьох, хто використовує метод сили волі. Вони проживуть три-чотири дні і потім зроблять один перегляд, щоб отримати приплив дофаміну. Вони не усвідомлюють, який руйнівний вплив це має на їхній моральний стан.

Для більшості користувачів, їхній перший перегляд порно-сайту був не такий гарний, як секс із реальною людиною. Чисті кліпи дають їхньому свідомому розуму піднесення. Вони думають: "*Добре, це було не так приємно. Я втрачаю тягу і мені не подобаються такі шокуючі речі.*" Насправді, це працює навпаки. Запамʼятайте, насолода від оргазму це не та причина, через яку ви кинули порно. Якби користувачі використовували порно тільки заради оргазму, вони б ніколи не дивилися більше одного кліпу. Єдина причина, чому ви потребували порно — це для годування маленького монстра. Просто подумайте, яким дорогоцінним цей один перегляд має бути після чотирьохденного голодування. Ваш свідомий мозок цього не знає, але кайф, який отримало ваше тіло, комунікує з вашою підсвідомістю і вся ваша підготовка обертається у прах. Десь у кутку вашого мозку буде маленький голос, який казатиме що вам потрібно ще, неважливо яку логіку ви маєте.

Один маленький перегляд має два руйнівні ефекти:

1.  Це тримає маленького монстра живим у вашому тілі.

2.  Навіть гірше, це тримає великого монстра живим у вашій голові. Якщо ви мали свій "останній перегляд", буде простіше мати ще один.

Порно — це мишоловка без сиру, тільки з отрутою. Якщо ви використовуєте метод сили волі, тоді ви маєте переконати себе не хапати сир, але EasyPeasy дає вам бачити, що це отрута. Ви не маєте уникати цього, ви просто не будете підходити до мишоловки.

Понад усе, памʼятайте:

*"Лише один перегляд" — це те, як люди стають залежними з самого початку.*
