# Чи буде мені складніше?

Існують безмежні комбінації факторів, які визначають як легко кожному користувачеві буде кинути. Для початку, кожен з нас має свій власний характер, карʼєру, особисті обставини, вибір часу, обмін речовин, тощо. Через деякі професії кинути може бути важче, ніж іншим, але якщо вважати, що промивання мізків було видалено, це не має бути складно. Подивіться на наступні декілька прикладів.

Іноді це важко для медиків. Ми думаємо, що їм має бути легше, тому що вони знають більше про ефекти порно, і хоча це дає більш рішучі причини для зупинки, від цього не стає легше зупинитися. Причини такі:

1.  Постійне розуміння ризиків для здоровʼя створює страх, а це одна з умов, через яку ми вважаємо за потрібне полегшувати симптоми відміни.

2.  Робота лікаря дуже напружена і зазвичай вони не можуть полегшувати додаткові стреси синдрому відміни поки працюють.

3.  Вони мають додатковий стрес провини, тому що відчувають, що вони мають ставити приклад для інших людей. Це створює більше тиску на них і збільшує відчуття позбавлення.

Після важкого робочого дня, коли їхній стрес моментально полегшується порно, цей сеанс стає неправильно прикріплений до відчутого полегшення. Через неправильну асоціацію ідей, порно отримує довіру над усією ситуацією і раптово стає дуже цінним коли ви кидаєте і проходите через синдром відміни. Це ознака звичайного користувача і застосовується до кожної ситуації, де користувач змушений утримуватись протягом довгих періодів. З використанням методу сили волі користувач є жалюгідним, тому що він позбавлений та не отримує насолоди від втоми та сну, які приходять після сеансу. Його відчуття втрати сильно збільшується. Але, якщо ви зможете спочатку видалити промивку мізків та сум за порно, можна насолоджуватись перервою та сном, поки тіло досі бажає амінних трансмітерів — серотоніну, норепінефіну та дофаміну.

Інша складна ситуація це нудьга, особливо коли вона поєднується з періодами стресу. Типові приклади це студенти та батьки-одинаки, які мають напружену, але монотонну роботу. Під час спроби зупинки з використанням методу сили волі одинока людина має великі періоди в які вона сумує за своєю "втратою", що в свою чергу збільшує відчуття депресії. Знову ж таки, цього можна легко уникнути, якщо ви маєте правильний настрій. Не переживайте через те, що вам постійно щось нагадує, що ви перестали використовувати порно. Використовуйте такі моменти, щоб радіти з того факту, що ви звільняєте себе від злого монстра.

Якщо ви маєте позитивний настрій, ці тяги стануть моментами задоволення. Памʼятайте, що будь-який користувач, неважливо якого він віку, статі, розуму або професії, може побачити, що кидати легко, якщо **він виконує всі інструкції.**

## Основні причини для невдачі

Існує дві основні причини для невдачі. Перша — це вплив зовнішніх стимулів — реклама, онлайн-новини, інтернет браузинг, тощо. Користувачі потрапляють у слабкий момент, або навіть починають заздрити, коли бачать інтимність у соціальних сценаріях. Ця тема вже була обговорена достатньо. Використовуйте цей момент, щоб нагадати собі, що не існує такого поняття як один візит або один перегляд. Радійте з того факту, що ви зламали ланцюги психічного рабства. Памʼятайте, що користувач заздрить вам, і ви маєте співчувати їм, бо вони цього потребують.

Інша причина це поганий день. Запамʼятайте перед тим як ви почнете, що незалежно від того чи ви є користувачем, є хороші та погані дні. Дощ йде для священника і для вбивці. Життя відносне, і ви не можете мати піднесень без падінь. Проблема з методом сили волі полягає у тому, що як тільки користувач матиме поганий день, він починатиме сумувати за візитом до гарему, що тільки погіршить проблему. Не-користувач краще екіпірований щоб витримувати стрес, не тільки фізично, але і психічно. Якщо ви маєте поганий день протягом періоду відміни, просто візьміть його за горло; нагадайте собі, що погані дні існували коли ви були залежним, інакше ви б ніколи не вирішили зупинитися. Замість того щоб сумувати за цим, прийміть це: *"Добре, сьогодні не такий гарний день, але порно це не вилікує. Завтра буде краще, і я хоча б маю чудовий бонус — я кинув цю жахливу залежність."*

Коли ви порно-користувач, ви маєте блокувати свій мозок до негативів порно. Користувачі ніколи не мають туману в голові, вони просто почуваються "трохи не дуже". Коли ви маєте неминучі життєві проблеми і ви відчуваєте думку бажання порно, ви почуваєтесь щасливим та веселим? Звичайно ні. Коли ви зупиняєтесь, є тенденція винуватити все, що йде не так, на той факт, що ви зупинилися.

Якщо робота викликає стрес, ви думаєте: "*У такі часи як зараз, я б мав сеанс.*" Це правда, але важлива забута річ це те, що порно не вирішило б проблеми, і ви просто караєте себе, коли сумуєте за опорою, якої не існує. Ви створюєте неможливу ситуацію, коли ви нещасні через те, що ви не можете мастурбувати на порно, але будете ще більш нещасними, якщо ви це зробите. *Ви знаєте, що ви зробили правильне рішення зупинитися, тож навіщо карати себе, сумніваючись над цим рішенням?*

Памʼятайте, підхід з гарним настроєм необхідний завжди.
