# Замінники

Деякі приклади замінників включають обмеження порно-журналами, статичними інтернет картинками, використання порно-дієт, тощо. **НЕ ВИКОРИСТОВУЙТЕ НІЯКІ З НИХ**. Вони лише ускладнюють ситуацію, а не роблять її легшою. Якщо ви відчуваєте тягу і використовуєте замінник, це просто продовжить її, що зробить лише гірше. Що ви насправді хочете цим сказати — це те, що вам потрібне порно, щоб заповнити порожнечу. Це буде як здатися викрадачеві, або на істерику дитини, просто продовжуючи тягу та тортури. В будь-якому разі, замінники не полегшать тягу. Ви відчуваєте потяг за амінокислотами у мозку, і все, що зроблять замінники — це змушуватимуть вас думати про порно. Памʼятайте такі речі:

1.  Замінників порно не існує.

2.  Вам не потрібне порно. Це не їжа, а отрута. Коли приходить тяга, нагадуйте собі, що саме користувачі страждають від синдрому відміни, а не ті, хто не вживає. Сприймайте тягу тим, чим вона насправді є — ще одним злом наркотику. Дивіться на неї як на смерть монстра.

3.  Інтернет-порно створює порожнечу, воно не заповнює її. Чим швидше ви навчите свій мозок, що вам не потрібно дивитися, тим швидше ви будете вільним. Конкретно, уникайте будь-чого, що нагадує порно, таке як чоловічі журнали, фільми, романтичні новели та реклама. Це не означає бути замкнутим — ви можете розмовляти про романтику або секс, але не про порно. Завжди є спосіб розрізнити це. Це правда, що мала частина користувачів які намагаються кинути, використовує мʼяке порно або порно дієти, щоб успішно кинути (з їхньої перспективи), та приписують свій успіх такому використанню. Але, вони кидають *не зважаючи* на їхнє використання, а не завдяки ньому. Це погано, що багато хто досі рекомендує такі рішення.

У цьому немає нічого дивного, тому що якщо ви не розумієте повністю порно пастку, використання дієти або мʼяких замінників звучать дуже логічно. Це засновано на думці, що коли ви намагаєтесь кинути порно, ви маєте подолати двох сильних ворогів:

-   Знищити звичку.

-   Пережити жахливі фізичні синдроми відміни.

Якщо ви маєте подолати двох потужних ворогів, то розумно боротися з ними по черзі, а не одночасно. Тому теорія каже, що коли ви спочатку зупиняєте використання порно, ви обмежуєтесь одним разом у тиждень, або використовуєте безпечне порно. Потім, коли звичка зруйнована, ви поступово зменшуєте використання, і тим самим боретесь із кожним ворогом окремо.

Це звучить логічно, але така тактика базується на неправильній інформації. Порно — це не звичка, а дофамінова залежність, і справжній фізичний біль від синдрому відміни майже непомітний. Чого ви намагаєтесь досягти коли кидаєте — це вбивства двох монстрів у своєму тілі та голові настільки швидко, як це можливо. Все, що роблять замінники — це продовжують життя маленького монстра, а це, в свою чергу, продовжує промивання мізків. EasyPeasy дозволяє вам легко кинути відразу, знищуючи промивання мізків до вашого останнього сеансу. Маленький монстр скоро буде мертвий, і навіть поки він вмирає, це не буде такою проблемою, аніж коли ви були користувачем.

Подумайте, як ви можете вилікувати наркотичну залежність якщо будете рекомендувати той самий наркотик? В інтернеті є багато історій про тих, хто кинув використання важкого порно, але підсів на "безпечні" альтернативи, піддавшись на виправдання маленького монстра. Не будьте обдуреним тим фактом, що безпечне порно не є гидким — так само було з вашим першим кліпом. Всі замінники мають один і той самий ефект, як і будь-яке порно. Дехто навіть починає заїдати, але хоча пусте відчуття бажання сеансу є таки самим як голод за їжею, одне не замінить інше. Насправді, якщо є щось, що збільшить ваше бажання дивитися порно — це набивання себе їжею. Як було пояснено раніше, порно-дієти та безпечне порно тільки поставлять вас у центрі перетягування канату, де опір до бажання буде таким дратівливим, що ви відчуватимете полегшення, відвідуючи свій улюблений онлайн-гарем.

Головне зло замінників це продовження справжньої проблеми — промивання мізків. Вам треба замінник застуди, коли вона закінчилася? Звичайно ні. Коли ви кажете, що вам потрібна заміна для порно, ви насправді кажете, що ви робите жертву. Депресія від методу сили волі спричинена тим фактом, що користувач вірить у те, що він робить жертву. Все, що ви будете робити — це замінювати одну проблему іншою. Немає задоволення у напиханні себе їжею, цигарками або алкоголем. Ви просто станете товстим, нещасним і майже відразу повернетесь до наркотику.

Звичайним користувачам важко ігнорувати думки, що вони позбавлені своєї маленької нагороди, як ті, хто не може зайти онлайн на період часу протягом подорожей, сімейних справ, тощо. Хтось каже: "*Я б не знав як відпочивати, якби не порно.*" Це доводить думку — часто перерву беруть не тому що користувач потребує або навіть хоче її, а тому що наркомани — ким вони насправді є — відчайдушно хочуть полегшити тягу.

Памʼятайте, порно-сеанси ніколи не були справжніми винагородами. Вони були еквівалентом носіння малих черевиків для того, щоб отримати задоволення коли ви знімаєте їх. Тож якщо ви відчуваєте, що ви маєте отримати маленьку винагороду (нехай це буде ваш замінник); поки ви працюєте та носите малі черевики, і не дозволяєте собі їх зняти до обіду, потім ви відчуваєте чудовий момент розслаблення та задоволення, коли знімаєте їх. Можливо, ви відчуваєте, що це було б нерозумно. Ви абсолютно праві. Можливо, це важко побачити, поки ви досі у пастці, але це те, що роблять користувачі. Також важко побачити, що скоро вам не буде потрібна ця маленька "нагорода", і що скоро ви будете відчувати справжнє співчуття до ваших друзів, які досі у пастці, та гадатимете чому вони не можуть цього побачити.

Але, якщо ви продовжите обманювати себе, що візит до онлайн-гарему був справжньою нагородою, або що вам потрібні замінники, ви будете почуватись позбавленим та нещасним. Є шанси, що ви знову впадете у цю огидну пастку знову. Якщо ви потребуєте справжнього відпочинку як його потребують домогосподарки, вчителі, лікарі та інші робітники, ви скоро будете насолоджуватись цим відпочинком навіть більше, тому що вам не потрібно бути залежним. Памʼятайте, що вам не потрібні замінники. Тяги — це бажання дофаміну, і вони скоро зникнуть. Нехай це буде вашою опорою на наступні декілька днів, а потім насолоджуйтесь звільненням свого тіла та розуму від рабства та залежності.
