# Чи маю я уникати спокусливих ситуацій

Поки що порада була прямою і вас просилось вважати її як інструкцію, а не як пропозицію. Є вагомі практичні причини для цієї поради, і ці причини були підтверджені тисячами досліджень. Що стосується питання чи потрібно уникати спокус, то тут справа інша. Кожен користувач має вирішити це сам. Але, можна зробити дві корисні пропозиції, щоб допомогти вам. Саме страх майбутнього синдрому відміни змушує нас використовувати порно все життя, і цей страх складається з двох окремих стадій.

**Стадія Перша - "*Як я можу вижити без порно?*"**

Цей страх — це панічне відчуття, яке має користувач коли він одинокий, або коли має асексуального, незацікавленого або недоступного партнера. Цей страх не спричинений синдромом відміни, а є психологічним страхом залежності, який полягає у тому, що ми не зможемо вижити без сексу та оргазму. Він стає найбільшим під час кидання, коли наш синдром відміни знаходиться на найнижчому рівні. Це страх невідомого, той тип страху, коли люди навчаються пірнати у воду.

Трамплін знаходиться на висоті одного метру над водою, але здається ніби це шість метрів. Вода сягає шести метрів глибини, але виглядає ніби це лише метр. Якщо ви впевнені у тому, що розібʼєте свою голову, то для стрибка потрібна сміливість. Стрибок це найважча частина, і якщо ви знайдете у собі сміливість це зробити, то далі буде легко! Це пояснює, чому багато користувачів із великою силою волі ніколи не намагалися зупинитися, або у них виходить прожити без порно лише декілька днів, коли вони кидають. Насправді, існують такі користувачі на порно дієті, які після рішення зупинитися йдуть у "запій" та ескалують до важких кліпів більш швидше, ніж якби вони не вирішували зупинитися. Це рішення спричиняє паніку, яка є стресом, та створює бажання піти до гарему. Але зараз ви не можете цього робити, через що ви думаєте що є позбавленими, а це збільшує стрес.

Тригер активується швидко, коли догорає запал і ви відкриваєте браузер. Не переживайте, ця паніка тільки психологічна. Ви залежні від страху. Правда у тому, що ви не є залежними, навіть коли все ще використовуєте порно. Не панікуйте і стрибайте.

**Стадія Друга - Довгостроковий страх**

Друга стадія є довгостроковою і включає у себе страх, що деякі ситуації у майбутньому не будуть приємними, або що ви не зможете справлятися з травмою без порно. Не переживайте, якщо ви можете стрибнути, то ви побачите, що все буде навпаки. Уникання спокуси ділиться на дві категорії.

1.  "*Я розпочну порно-дієту раз у чотири дні. Я почуватимусь більш впевнено, якщо буду знати, що я можу зайти у інтернет, якщо мені стане важко. Якщо я зазнаю невдачі, то нічого страшного, я просто додам додаткові дні до мого наступного циклу.*"

    Рівень невдач у людей, які роблять це є **набагато більшим**, ніж у тих, хто повністю кидає. Зазвичай, це через той факт, що якщо ви маєте поганий момент протягом періоду відміни, то вам дуже легко відкрити браузер і відвідати гарем з виправданнями, які були написані вище. Якщо ви маєте принизливість явно порушувати власні правила, то ви скоріше за все подолаєте спокусу. В будь-якому разі, тяга скоріше за все вже б пройшла, якби ви її затримали. Але, головна причина високого рівня невдач у цих випадках, це коли користувач не відчував себе повністю відданим зупинці з самого початку. Памʼятайте дві необхідні речі для успіху:

    -   Впевненість.

    -   "*Чи не чудово це, що я більше не потребую порно?*"

   У будь-якому разі, чому ви взагалі потребуєте сеансу? Якщо вам досі потрібен візит у гарем, перечитайте цю книгу спочатку. Ви щось не зрозуміли. Виділіть час, щоб вбити великого монстра, який промиває вам мізки.

2.  "*Чи маю я уникати стресових випадків або соціальних зустрічей протягом періоду відміни?*"

   У випадку стресових ситуацій так. Немає сенсу класти на себе додатковий тиск. У випадку соціальних подій, такі як бари або клуби, то навпаки. Виходьте і насолоджуйтесь собою відразу, вам не потрібен секс чи порно, навіть коли ви залежні. Виходьте і радійте тому факту, що вам не потрібно займатися сексом чи дивитися порно, це швидко доведе чудову правду, що життя набагато краще без цього. Просто думайте над тим, наскільки краще вам буде, коли маленький монстр покине вас, разом з тими противними думками.
