# Момент одкровення

Зазвичай через три тижні після кидання порно екс-користувачі відчувають момент одкровення. Небо стає яскравішим, і це той момент, коли промивання мізків закінчується повністю. Коли замість того, щоб казати собі, що ви не маєте дивитися порно, ви раптово розумієте, що останній звʼязок із ним лопнув і ви можете насолоджуватися своїм життям, не потребуючи його знову. Також зазвичай з цього моменту ви починаєте дивитися на користувачів як на обʼєкти співчуття.

Ті, хто використовують метод сили волі, не відчувають цього моменту, тому що хоч вони і раді бути екс-користувачами, але вони продовжують думати що вони роблять жертву. Чим більше ви були залежним, тим більш чудовим є цей момент, і він триває усе життя. Хоча у житті існує багато радощів, але повторити справжні відчуття неможливо. Щастя не потребувати порно це трохи інше. Якщо ви почуваєтесь не дуже добре і потребуєте піднесення, нагадуйте собі як чудово не бути залежним від цієї жахливої залежності. Багато описують це як одну з найвеличніших подій їхнього життя. У багатьох випадках момент одкровення приходить не після трьох тижнів, а після декількох днів.

У моєму випадку, це сталося перед закінченням мого останнього візиту до гарему. Я впевнений, що багато читачів, навіть перед тим як вони дочитають книгу до кінця, скажуть щось подібне: "*Ні слова більше. Я бачу це чітко, я знаю що мені більше не потрібне порно.*" Спираючись на відгуки, які я отримую, це трапляється часто. В ідеалі, якщо ви виконуєте усі інструкції і розумієте психологію повністю, це має статися з вами відразу.

Не зважаючи на те, що було сказано, що для того, щоб помітний фізичний синдром відміни зник, потрібно приблизно пʼять днів, і приблизно три тижні, щоб екс-користувач став повністю вільним, такі настанови можуть спричинити дві проблеми. По-перше, люди можуть думати, що вони мають страждати від пʼяти днів та трьох тижнів. По-друге, екс-користувач схильний думати: "*Якщо я зможу протриматись пʼять днів або три тижні, то я можу очікувати справжній прилив сил наприкінці цього періоду.*"

Але, вони можуть прожити пʼять приємних днів або три приємних тижні, після яких підуть жахливі дні, які трапляються з усіма і не мають нічого спільного із залежністю, а спричинені іншими факторами життя. Потім наші екс-користувачі, які чекають моменту одкровення, замість цього відчувають депресію. Це може знищити їхню впевненість. Так само, якби не було ніяких настанов, екс-користувач міг прожити все своє життя, і чекати, що щось настане. Це те, що трапляється з великою більшістю, яка використовує метод сили волі.

Люди часто питають про важливість пʼяти днів та трьох тижнів. Це періоди взяті навмання? Ні. Хоча вони не визначають дати, вони відображають накопичення відгуків багатьох років. Приблизно після пʼяти днів після зупинки екс-користувач перестає бачити залежність як своє основне заняття. Більшість екс-користувачів відчувають одкровення десь у цьому періоді, зазвичай у стресових або соціальних ситуаціях, з якими колись не можна було справитись або насолоджуватись без візиту гарему. Ви різко починаєте розуміти, що ви не тільки насолоджуєтесь та справляєтесь з цим, але й думки про порно ніколи вам не трапляються. З цього моменту зазвичай починається спокійне плавання. Тоді ви побачите, що ви вільний.

З мого досвіду та досвіду багатьох інших, хто намагається кинути за допомогою *методу сили волі*, десь на третьому тижні найсерйозніші спроби кинути зазнають невдачі. Зазвичай після трьох тижнів ви відчуваєте, що ви втратили бажання дивитися порно. Ви маєте довести це собі, тому ви відкриваєте браузер і йдете до свого гарему. Ви почуваєтесь дивно, що доводить той факт, що ви кинули. Але у процесі ви змастили водні гірки, завдячуючи свіжому потоку дофаміну, якого ваше тіло бажало останні три тижні. Як тільки ви закінчуєте, дофамін починає покидати ваше тіло. У вас знову зʼявляється маленький голос, який каже: "*Ти ще не кинув, ти хочеш ще.*"

Ви не повертаєтесь відразу, тому що ви не хочете підсісти знову, та дозволяєте пройти якомусь безпечному періоду. Коли ви спокушаєтесь наступного разу, ви вже можете сказати собі: "*Я не підсів, тож немає нічого поганого у тому, якщо я зроблю це ще раз.*" Але ви вже на своєму шляху вниз по слизькому схилу. Ключ до цієї проблеми — це не чекати моменту одкровення, а зрозуміти, що коли ви закрили браузер, то ви закінчили. Ви відрізали потік кисню своєму маленькому монстру. Ніяка сила на Землі не може завадити вам бути вільним, хіба що ви сумуєте через це, або чекаєте одкровення. Йдіть та насолоджуйтесь життям; справляйтеся з цим з самого початку. Цей момент скоро настане.
