# Останній візит

Тепер, коли ви вирішили з вибором часу, ви готові відвідати свій гарем востаннє. До того, як ви це зробите, перевірте дві необхідні речі.

1.  Чи відчуваєте ви впевненість, що у вас все вийде?

2.  Ви маєте відчуття приреченості, чи відчуття схвильованості від того, що зараз ви досягнете чогось чудового?

Якщо ви маєте якісь сумніви, спочатку перечитайте книгу. Памʼятайте, що ви ніколи не вирішували потрапити у пастку порно — це пастка зроблена так, щоб тримати вас все життя. Для того щоб втекти, ви маєте зробити позитивне рішення, що ви зараз зупинитесь, і зробити свій останній візит.

Памʼятайте, що єдина причина, чому ви досі читали цю книгу — це тому що ви дуже хочете кинути. Тож зробіть це позитивне рішення зараз, прийнявши урочисту присягу, що коли ви закриєте приватне вікно у браузері, неважливо буде це легко, чи ні, ви ніколи не відвідаєте свого гарему знову. Можливо, ви переживаєте через те, що ви робили цю присягу вже декілька разів у минулому і досі зазнаєте невдачі, або що ви маєте пройти через жахливу травму. Не бійтеся, найгірша річ, яка може статися — це те, що ви зазнаєте невдачі, тому вам **абсолютно нічого** втрачати, але є що отримати.

Перестаньте навіть думати про невдачу — чудова правда у тому, що кинути не тільки дуже легко, але також ви можете справді насолоджуватися процесом. Цього разу ви будете використовувати EasyPeasy! Все, що вам потрібно — це виконувати прості інструкції.

1.  Зробіть урочисту присягу зараз і зробіть це щиро.

2.  Переглядайте картинки та кліпи на вашому улюбленому сайті свідомо, та дивіться на відчайдушні спроби адміністраторів сайту, акторів та навіть аматорів показати шок, новизну та надприродність їхніх відео, і спитайте себе де у цьому є задоволення.

3.  Коли ви нарешті закриєте браузер, не робіть це з відчуттям "*Я більше ніколи не маю відвідувати онлайн-гарем*", або "*Мені не дозволено більше відвідувати*", а замість цього робіть це з відчуттям свободи: "*Чи не чудово це? Я вільний! Я більше не раб порно! Мені більше ніколи в житті не доведеться відвідувати ці брудні сайти!*"

4.  Памʼятайте, що протягом декількох наступних днів у вашому животі буде маленький порно-саботажник. Ви можете помічати лише бажання отримати сеанс. Ми говорили про маленького порно-монстра як про легке фізичне бажання дофаміну. Взагалі це неправильно, і важливо розуміти чому. Через те, що для смерті маленького порно монстра потрібно три тижні, екс-користувачі вважають що він продовжить відчувати бажання після фінального візиту до гарему, і тому вони мають використовувати силу волі, щоб опиратися спокусам протягом цього періоду. Це не так, тіло не бажає дофаміну, який виділяється від порно; цього бажає тільки мозок.

Якщо ви маєте це бажання подивитися порно у наступні декілька днів, ваш мозок має простий вибір. Він може або розглядати це відчуття таким, яким воно є насправді — пустим невпевненим відчуттям, яке було спричинене першим візитом до порносайту і продовжене кожним наступним візитом, або сказати собі **"ЄЄЄЄЄ! Я НЕ-КОРИСТУВАЧ!"**

Або, ви можете почати тягнутися до порно і страждати залишок свого життя. Задумайтесь, чи не буде це дурницею? Сказати: "*Я ніколи не хочу знову дивитися порно*" і потім жити та казати: "*Я б хотів зайти подивитися*"? Це те, що роблять люди, які використовують метод сили волі, і немає нічого дивного у тому, що вони почуваються такими нещасними. Вони проводять залишок свого життя сумуючи за чимось, чого вони відчайдушно сподіваються ніколи не мати. Немає нічого дивного у тому, що лише одиниці досягають успіху, і що вони ніколи не почуваються повністю вільними.

> *"Запамʼятайте цю картинку у себе в голові, тому що вона може сильно допомогти у подоланні зовнішніх стимулів, які вас відволікають. Уявіть, що ви спокійно сидите та даєте дзвонити телефону, ігноруєте дзвінок, і не рухаєтесь за його командою. Хоча ви знаєте, що він дзвонить, ви більше не звертаєте на нього уваги, або не підкоряєтесь йому. Також, запамʼятайте той факт, що зовнішній сигнал сам по собі не має ніякої сили над вами, та ніякої сили щоб сколихнути вас. Ви підкорялись йому у минулому, відповідали на нього просто через звичку. Ви можете, якщо ви хочете, створити звичку не відповідати на нього.*
>
> *"Також зверніть увагу на те, що ваша здатність не відповідати на дзвінок не має у собі ніякої дії, зусилля, або опору чи боротьби — ви не робите нічого, повністю спокійні. Ви лише розслабляєтесь, ігноруєте сигнал та дозволяєте його поклику залишитися без відповіді. Дзвінок телефону це символічна аналогія до будь-якого зовнішнього стимулу, якому ви звикли віддавати контроль, а тепер навмисне обираєте змінити цю звичку.*"
>
> ---  Максвел Мальтз, *Нова Психо-кібернетика* Роз. 12.

Тільки ваші сумніви та очікування ускладнюють кидання, ***тому ніколи не сумнівайтесь у своєму рішенні***, тому що ви знаєте що ви зробили правильно. Якщо ви починаєте сумніватися у вашому виборі, ви ставите себе у безвихідну ситуацію, коли ви є нещасним поки бажаєте візиту, але не можете його отримати. Неважливо яку систему ви використовуєте, що ви намагаєтесь досягнути коли кидаєте порно? Ніколи більше не дивитися? Ні! Багато екс-користувачів роблять це, але живуть далі, відчуваючи себе позбавленими.

Яка різниця між користувачами і не-користувачами? Не-користувачі не мають ніякої потреби чи бажання дивитися порно, вони не мають тяг, і не мають розвивати силу волі для того, щоб не дивитися порно. Це те, чого ви намагаєтесь досягти, і це повністю у ваших силах. Ви не маєте чекати, щоб перестати бажати порно або ставати не-користувачем, це зроблено у той момент, коли ви закриваєте той останній сеанс у браузері, перекривши постачання дофаміну: **ВИ ВЖЕ ЩАСЛИВИЙ НЕ-КОРИСТУВАЧ!**

Ви залишитесь щасливим не-користувачем якщо:

1.  Ви ніколи не будете сумніватися у своєму рішенні.

2.  Ви не чекатимете, коли ви станете не-користувачем. Якщо ви це зробите, ви просто чекатимете поки нічого не настане і створите фобію.

3.  Ви не намагатиметесь *не* думати про порно, або чекати приходу "моменту одкровення", створюючи фобію.

4.  Ви не використовуватимете замінники.

5.  Ви будете бачити всіх інших користувачів такими, якими вони є насправді, і жалітимете їх, замість того щоб заздрити їм.

Не зважаючи на хороші або погані дні, не змінюйте своє життя тільки через те, що ви кинули. Якщо ви це зробите, ви робитимете справжню жертву, коли у цьому немає потреби. Памʼятайте, ви не втратили життя. Ви не втратили нічого. Навпаки, ви вилікували себе від жахливої хвороби і втекли з підступної вʼязниці. З плином днів і покращенням вашого фізичного та психічного здоровʼя, піднесення здаватимуться вам ще вищими, а падіння менш низькими, ніж коли ви були користувачем. Коли ви будете думати про порно протягом наступних декількох днів або на залишок свого життя, думайте:

***“УРАААА! Я НЕ-КОРИСТУВАЧ!"***

## Останнє попередження

Ніякий користувач не почав би знову, якби йому дали шанс повернутися у минуле до того, як він підсів, зі знаннями, які він має зараз. Десятки тисяч тих, хто успішно кинули залежність багатьох років, ведуть цілком щасливі життя, тільки щоб потрапити у пастку знову. Я вірю, що ця книга допоможе вам зупинитися відносно легко. Але знайте, що користувачі, які легко зупинилися, можуть підсісти знову з такою самою легкістю. **Не потрапляйте у цю пастку.**

Неважливо як давно ви зупинились, або впевнені, що ви ніколи не підсядете знову, зробіть правилом на все ваше життя ніколи не дивитися порно, ні за яких причин. Опирайтесь усім алюзіям та натякам у медіа, та памʼятайте як вони пропихують свою картину "відкритості", коли приносять порно у мейнстрім, не знаючи що порно, інтернет-порно, та компульсивна мастурбація є вбивцями відносин та особистого відчуття благополуччя для великого числа чоловіків та деяких жінок.

Памʼятайте, що перший перегляд чи візит нічого для вас не зробить. Ви не матимете синдрому відміни, який потрібно полегшувати, і через це ви будете почуватися жахливо. Все, що це зробить, це доставить задоволення від потоку дофаміну у ваш розум та мозок, і маленький голос у вашій голові буде казати вам, що ви хочете іще одного сеансу. Після цього ви матимете вибір: або бути жалюгідним якийсь час, або починати цей брудний ланцюжок подій знову.
