# Зворотній звʼязок

Війна ведеться не проти користувачів, а проти пастки порно-індустрії, і ведеться через одну просту причину, що мені це подобається. Кожного разу, коли я чую про користувача, який тікає з вʼязниці, я відчуваю величезне задоволення. Але це задоволення не було без значного роздратування, в основному спричинене двома категоріями порно-користувачів. Не зважаючи на попередження у попередньому розділі, я завжди дивуюся числом тих, хто легко кидають, але потім знову підсідають і бачать, що вони не можуть звільнитися цього разу.

Це як знаходити когось, хто провалився по шию у болото. Ви допомагаєте їм вилізти і вони вдячні за це, але шість місяців потому пірнають назад у те саме болото. Користувачі, яким легко кидати і легко починати, знову створюють особливу проблему. Коли ви звільнитесь, ***БУДЬ ЛАСКА, БУДЬ ЛАСКА, НЕ РОБІТЬ ТУ САМУ ПОМИЛКУ.*** Вони думають, що такі люди починають знову через те, що вони досі залежні і сумують за дофаміном. Насправді, їм настільки легко зупинятися, що вони перестають боятися порно. Вони думають: "*Я можу мати випадковий сеанс, і навіть якщо я підсяду знову, мені буде легко зупинитися.*"

Але це так не працює, тому що порно кинути легко, але залежність контролювати неможливо. Єдина річ, яка необхідна для того, щоб кинути порно, це не використовувати його.

Люди зазвичай повертаються назад до порно, тому що вони не зрозуміли слово "easy" у EasyPeasy.

Уявіть як хтось сидить на холодній бетонній підлозі у холодній кімнаті. На стіні навпроти них є вікно, у якому видно чудовий весняний день — дерева легко колихаються, співають пташки — поруч із відчиненими дверима.

Чи потрібна сила волі для того, щоб вийти з цієї холодної кімнати? Ні! Можливо, втекти важче, ніж залишитись? Звичайно ні! (Насправді, це трохи легше, тому що тіло рухається та зігрівається). Навіщо комусь у своєму розумі поміщати себе у таку ситуацію та спричиняти місяці або роки роздратування, якщо тільки він не був обдурений?

EasyPeasy відкриває штори, щоб користувач міг бачити вулицю і міг видалити **помилкові уявлення** про те, як погано може бути на вулиці і як зручно користувачеві у цій кімнаті.

Інша категорія дратуючих користувачів — це ті, хто бояться зробити спробу зупинитися, або коли вони роблять це, то вважають це великою боротьбою. Головні складнощі для них є наступними.

**Страх невдачі.**

:   Немає ніякої ганьби у невдачі, але не намагатися кинути це просто тупість. Дивіться на це з іншої сторони: ви ні від чого не ховаєтесь. Найгірша річ, що може трапитись, це те, що ви зазнаєте невдачі. В такому випадку ви не станете гіршим, ніж ви є зараз. Просто подумайте, як чудово було б досягти успіху. Якщо ви не зробите спробу, то ви вже гарантовано зазнали невдачі.

**Страх болю та нещасності.**

:   Не переживайте за це, просто подумайте: яка погана річ може статися з вами, якщо ви більше ніколи не дивитиметесь порно? Абсолютно нічого. Жахливі речі стануться якщо ви дивитиметесь, перечитайте записи про Ваги Паскаля. У будь-якому разі, паніка була спричинена дофаміном і скоро зникне. Найбільше досягнення — це звільнитися від цього страху. Чи ви справді вірите, що користувачі готові мати згасаючі пенетрації, невпевнене сексуальне виконання, або ілюзорне задоволення, яке вони отримують від порно? Якщо ви знаходитесь з іншими людьми, і вони вас пригнічують, втечіть від них та підіть у гараж, пустий офіс, або деінде.

  Якщо ви відчуваєте, що хочете плакати, не соромтесь. Сльози — це природній спосіб полегшення напруги. Ніхто коли не плакав, не почуваючись краще після цього. Одна з жахливих речей, яку ми робимо з молодими чоловіками — це кажемо їм не плакати. Вони намагаються боротися зі слізьми, але ми бачимо лише скреготіння щелепи. Ми вчимо себе не показувати емоцій, але ми не маємо накопичувати їх всередині. Кричіть, або вчиніть істерику. Вдарте щось. Вважайте свою боротьбу як матч у боксі, який не можна програти. Ніхто не може зупинити час, у кожен момент який проходить маленький монстр всередині вас помирає. Насолоджуйтесь неминучою перемогою.

**Невиконання інструкцій.**

:   Неймовірно, але деякі користувачі кажуть, що цей метод не спрацював для них. А потім вони описують, як вони ігнорували не одну, а майже всі інструкції. Для розуміння, всі інструкції підсумовані в кінці цього розділу.

**Нерозуміння інструкцій.**

:   Головні проблеми такі:

    "*Я не можу перестати думати про порно.*"

    :   Звичайно не можете, і якщо ви спробуєте, то ви створите фобію та станете нещасним. Це як намагатися спати вночі: чим більше ви намагаєтеся заснути, тим складніше це зробити. Неважливо чи думаєте ви про порно девʼяносто відсотків свого життя, важливо те, що ви думаєте. Якщо ви думаєте "*Ех, я хочу піти подивитися порно*", або "*Коли я буду вільним?*", то ви будете нещасним. Якщо ви замість цього думаєте "*УРААААА! Я вільний*", тоді ви будете щасливим.

    “*Коли маленький порно-монстр помре?*"

    :   Потік дофаміну покидає ваше тіло дуже швидко, але неможливо сказати коли тіло перестане страждати від легкого фізичного відчуття відміни від дофаміну. Це пусте, невпевнене відчуття, яке ідентичне звичайному голоду, депресії, чи стресу. Все, що робить порно — це збільшує його рівень. Тому ті користувачі, які кидають методом сили волі, ніколи не впевнені чи вони кинули, навіть коли їхнє тіло перестало страждати від синдрому відміни від дофаміну. Якщо вони страждають від природного голоду або стресу, їхній мозок досі каже їм, що це дійсна причина щоб отримати їхній сеанс. Суть у тому, що вам не потрібно чекати поки тяга піде. Вона така легка, що ми навіть не знаємо що вона є. Ми тільки відчуваємо її як бажання. Коли ви виходите від стоматолога, ви чекаєте поки щелепа перестане боліти? Звичайно ні, ви продовжуєте жити. Навіть якщо ваша щелепа досі болить, ви маєте гарний настрій.

        Не чекайте на те, поки зникне синдром відміни, тому що ви створюєте сумніви, коли постійно запитуєте: "*Як довго це займе часу? Чи я взагалі вільний, якщо я не почуваюсь по іншому?*" Страх — це справжня тяга. Тому ви створюєте сумніви, коли ви чекаєте, поки життя стане кращим, після того як кинули. Синдром відміни непомітний до того моменту, коли ви починаєте його боятися, а постійні покращення мозку відбуваються повільно. Тому якщо ви будете чекати на те, поки стане краще, це відчуватиметься ніби нічого не відбувається, що у свою чергу створює сумніви.

    "*"Момент одкровення" ще не настав.*"

    :   Якщо ви чекатимете на це, ви просто створите ще одну фобію. Колись я зупинився на три тижні, використовуючи метод сили волі. Коли я розмовляв зі старим другом, він спитав мене як я почуваюсь.
        "*Я зміг вижити три тижні*" — відповів я.
        Він спитав: "*Що ти маєш на увазі?*"
        Я уточнив: "*Я прожив три тижні без порно.*"
        Він сказав: "*Що ти збираєшся робити? Виживати все своє життя? На що ти чекаєш? Ти вже це зробив. Ти не-користувач.*"

        Я подумав, "*Він абсолютно правий, на що я чекаю?*" На жаль, через відсутність розуміння цієї пастки, я повернувся до використання, але я запамʼятав його слова. Ви стаєте не-користувачем у той момент, коли ви закриваєте свій браузер. Важливо бути щасливим не-користувачем з самого початку.

    "*Я досі бажаю порно.*"

    :   Тоді ви дуже дурні. Як ви можете казати, що ви не-користувач і потім казати, що ви хочете порно? Це протиріччя. Якщо ви кажете, що ви хочете порно, то це означає, що ви хочете бути користувачем. Не-користувачі не хочуть відвідувати огидні сайти. Ви вже знаєте ким ви хочете бути, тож досить себе наказувати.

    "*Я відмовився від життя.*"

    :   Чому? Все, що ви маєте зробити — це перестати вбивати себе і почати накопичувати енергію. Вам не потрібно зупиняти життя. Це так просто, наступні декілька днів ви матимете легку травму у житті. Ваше тіло буде страждати від майже непомітного запалення від синдрому відміни та пошуку дофаміну. Тепер, запамʼятайте: ви не є гіршим, ніж ви були. Це те, від чого ви страждали усе своє життя, кожного разу коли ви спали, були у церкві, супермаркеті або бібліотеці. Це не турбувало вас коли ви були користувачем, і якщо ви не зупинитесь, то ви продовжите страждати від цього до кінця свого життя.

    Порно і оргазми не роблять події, вони позбавляють вас від них. Навіть коли ваше тіло досі бажає дофаміну, їжа та соціальні події є чудовими. Життя чудове — ходіть на соціальні зустрічі, навіть якщо там є голі танцюристи. Памʼятайте: це не ви позбавлені від чогось, а користувачі. Кожен із них хотів би бути на вашому місці, якби вони тільки знали як це. Насолоджуйтесь бути центром уваги. Зупинка використання порно це чудова тема для розмови, ви отримуєте те, чого вони не можуть отримати. Ваші друзі та ровесники будуть здивовані побачити що ви, раніше соромʼязливий і втомлений, зараз щасливий і радісний. Ви будете насолоджуватись життям з самого початку, не потрібно заздрити кожному пікаперу на вечірках, вони б заздрили вам — якби вони тільки знали.

    "*Я нещасний та роздратований*"

    :   Це невиконання інструкцій. Визначте, яких саме. Деякі люди розуміють і вірять усьому що написано, але все одно починають з поганого почуття, ніби трапляється щось жахливе. Ви не тільки робите те, що ви хочете робити, але і те, що кожен користувач на планеті хотів би також. З будь-яким методом для зупинки, екс-користувач намагається досягти конкретного настрою, тому кожна думка, яка повʼязана з порно має закінчуватись словами: "*УРААА! Я ВІЛЬНИЙ!*" Якщо це ваша ціль, то навіщо чекати? Починайте з цього настрою і ніколи не втрачайте його. Альтернатив немає.

    "*Я мав гарний тиждень / місяць / пів року, але я повернувся у пастку.*"

    :   Памʼятайте: страх це тяга. Коли ви піддаєтеся бажанню, це генерує більше страху, годує ослабленого маленького монстра і змушує не-користувача думати, що він залежний на життя. Насправді, його концептуалізація промивання мізків не змінилася, але він дав дофамін цій думці. Це, за визначенням, падіння вперед, але це також невиконання інструкцій. Знайдіть ці інструкції внизу та радійте.

## Контрольний список

Якщо ви виконуєте ці інструкції, ви не можете зазнати невдачі:

1.  Зробіть урочисту присягу що ви ніколи-ніколи не підете онлайн до свого гарему, *АБО* перейдете на статичні картинки, *АБО* перейдете на еротичну графіку, *АБО* на будь-що, що створює надприродні стимули, і виконуйте її.

2.  Запамʼятайте: немає нічого втрачати. Це не означає, що ви будете кращим як не-користувач (ви вже це знаєте); і це не означає що ви отримуєте деяке задоволення або опору від порно, оскільки по іншому ви б цього не робили. Це означає що *у порно немає справжнього задоволення чи опори*. Це просто ілюзія, це як бити свою голову об стіну, щоб отримати задоволення коли ви зупинитесь.

3.  Не існує такого поняття як підтверджений користувач. Ви просто один із сотні мільйонів хто потрапив у цю пастку. Як мільйони інших екс-користувачів, які колись думали, що вони не можуть кинути, ви кинули.

4.  Якщо у будь-який час у вашому житті вам потрібно зважити мінуси і плюси порно, висновок завжди буде "*Зупинись. Ти дурень!*" Ніщо ніколи не змінить це. Так було завжди і так завжди буде. Коли ви зробили, як ви вирішили, правильне рішення, ніколи не катуйте себе сумнівами. Ваги Паскаля ідеально застосовуються до порно, без шансів програшу, великими шансами виграшу і великими шансами уникнення втрат.

5.  Не намагайтесь не думати про порно, або переживати що ви думаєте про нього постійно. Коли ви думаєте про нього сьогодні, завтра, або все своє життя, думайте **"УРААА! Я НЕ-КОРИСТУВАЧ!"**

6.  *Не* використовуйте будь-яку форму замінника. **Не** тримайте свій ноутбук поруч з собою поки ви спите. **Не** уникайте пʼєс, фільмів або журналів. **Не** змінюйте стиль свого життя будь-яким чином тільки через те, що ви зупинилися. Якщо ви виконуєте інструкції вище, то ви скоро відчуєте "момент одкровення", але:

7.  Не чекайте поки настане "момент одкровення". Просто живіть, насолоджуйтесь піднесеннями і справляйтеся з падіннями. Ви побачите, що цей момент настане дуже швидко.
