# Допомагайте тим, хто досі знаходяться на тонучому кораблі

Сучасні порно-користувачі панікують, коли відчувають зміни у тому, як порно сприймається чоловіками і жінками. Залежна природа інтернет-порно починає частіше вивчатися, і тепер по праву вважається як щось інше від традиційної порнографії. Легкість і доступність збільшує сумніви навіть у серцях тих, хто підтримує порно. Вони також відчувають, що різні елементи намагаються захопити їхній хрестовий похід за свободою слова та думки. Дикий захід неконтрольованого інтернету робить майже неможливим увести вікові обмеження до надприродніх стимулів. На жаль, це не закінчиться скоро, але сотні тисяч користувачів зупиняються, і багато користувачів знають про дослідження, які показують схожість між порно та залежністю від наркотиків. Кожного разу, коли користувач покидає тонучий корабель, ті, хто залишаються на ньому, стають більш нещасними.

Кожен користувач інстинктивно знає, що саботажувати себе і витрачати час перед двовимірними пікселями дуже смішно, що перевантажує його мозок та створює нейронні звʼязки, які гарантують погане сексуальне життя. Якщо ви досі не думаєте, що це смішно, спробуйте поговорити із порно журналом, коли ви знаходитесь у центрі вашого міста і запитайте у себе в чому різниця. Тільки в одному — так ви не зможете отримати задоволення від тепла та інтимності. Якщо ви можете перестати купувати алкоголь і цигарки кожного разу, коли ви купуєте продукти у магазині, то ви точно можете зупинити відвідування онлайн-гарему. Користувачі не можуть знайти раціональних причин щоб дивитися порно, але вони не почуваються так безглуздо, якщо інші люди також роблять це.

Користувачі відверто брешуть про свою звичку, не тільки дослідникам і людям поруч, але і самим собі. Вони мають це робити. Їм необхідне промивання мізків, якщо вони хочуть залишити собі хоч трохи самоповаги. Вони відчувають потребу виправдати свою "звичку" не тільки для *самих себе*, але і для не-користувачів. Вони завжди рекламують несправжні переваги порно підступними способами.

Якщо користувач зупиняється за допомогою методу сили волі, він досі почувається позбавленим та зазвичай стає плаксою. У результаті користувач тільки переконується наскільки він правий у тому, що він має продовжувати використовувати. Якщо екс-користувач успішно кине звичку, тоді він стає вдячним за те, що йому не потрібно жити, постійно саботуючи себе та витрачаючи енергію, у нього немає потреби виправдовуватись. Памʼятайте, це страх тримає голову користувача у піску, він починає сумніватися у своїй поведінці тільки тоді, коли починає зупинятися. Допоможіть користувачеві видалити ці страхи. Скажіть їм як чудово жити не у вʼязниці, як чудово прокидатися вранці та відчувати себе у формі та здоровим замість того, щоб бути без енергії та відчувати самовідразу, як чудово бути вільним від рабства та мати можливість насолоджуватися всім у своєму житті, і бути вільним від чорних тіней. Або ще краще, дайте їм цю книгу.

Важливо не принижувати одруженого користувача і казати йому, що він свідомо руйнує свої відносини, або що це у якомусь сенсі зрада. Є поширене помилкове уявлення, що екс-користувач найчастіше дорікає всіх у цьому аспекті. Ця думка має якесь підґрунтя, але зазвичай воно виникає через зупинку методом сили волі. Воно зʼявляється через те, що екс-користувач хоч і кинув залежність, але ще досі тримає у собі частину промивання мізків, і досі вірить, що він зробив жертву. Він почувається вразливим і його природній захисний механізм — це атакувати порно-користувача.

Це може збільшити его екс-користувача, але це ніяк не допоможе користувачеві. Все, що це зробить — це відкине користувача назад, змусить його відчувати себе більш жалюгідним, і його потреба у порно зросте. Хоча зміна у медичному відношенні до інтернет-порно є основною причиною, чому багато користувачів кидають, через це не стає легше кинути. Насправді, від цього навіть складніше. Більшість сучасних користувачів вважають, що вони зупиняються в основному через вплив на здоровʼя. Але це не завжди правда.

Хоча великі ризики здоровʼю це, очевидно, головна причина для кидання, користувачі саботажували свою впевненість роками і це не зробило ніякої різниці. Основна причина, чому користувачі зупиняються — це тому що суспільство починає бачити порно без маски. Таким, яким воно є насправді — наркотичною залежністю. Багато партнерів тепер ставлять питання, якщо ви відкриваєте свій ноутбук посеред ночі.

Повне блокування порно в деяких країнах, або недоступність інтернету є класичними прикладами дилеми користувачів, які подорожують. Зазвичай вони вважають, що це допоможе їм зменшити їхнє використання. У результаті, замість одного або двох днів, від яких вони б не отримали задоволення, вони утримуються увесь тиждень. Але протягом цього навʼязаного періоду утримання вони психічно позбавлені та чекають своєї нагороди, і їхнє тіло також бажає сеансу. Ох, яким цінним буде цей візит до онлайн-гарему, коли вони зможуть зайти знову.

Примусове утримання насправді не зменшує використання, тому що користувач потурає собі навіть більше, коли він може побути на самоті. Все це лише вкорінює у голові користувача цінність інтернет-порно і те, яким залежним він є від нього. Найбільш підступний аспект це примусове утримання має ефект на підлітків. Ми дозволяємо крадіям "свободи вираження" (порно продюсерам), цілитись на бідних підлітків, щоб підсадити їх. Потім, у найстресовіший період їхнього життя, коли через їхні марення вони потребують порно більше всього, ми шантажуємо їх у кидання через біль, якого вони завдають самі собі.

Багато хто не може так робити, і не зі своєї вини змушені страждати від почуттів провини решту свого життя. Багато хто досягає успіху і є задоволеними. Вони думають: *\"Добре. Поки що я робитиму так і після того як це закінчиться, я все одно вилікуюсь.\"* Потім наступає біль та страх перед вибором професії та інших дорослих проблем, які супроводжуються найбільшим "кайфом" їхнього життя — пошуком роботи. Біль та страх проходять, тепер вони почуваються у безпеці, а старий спусковий механізм знову починає працювати. У них ще залишилася частина промивання мізків, і до того, як зникне запах нового робочого компʼютера, користувач вже буде на порозі свого улюбленого онлайн-гарему. Радість від цієї події блокує неприємні відчуття у їхній свідомості, вони не мають бажання знову попадатися на гачок, але тільки один перегляд не зможе нашкодити\... Пізно! Вони вже знову підсіли.

Старе бажання від маленького монстра зʼявиться знову, і навіть якщо вони не підсядуть відразу, депресія після кайфу скоріше за все наздожене їх. Дивно, що хоча героїнові наркомани знаходяться поза законом, суспільство допомагає таким людям. Давайте приймемо таке саме відношення до порно-користувачів. Вони не роблять це тому що вони хочуть, а тому що вважають, що їм це потрібно. На відміну від героїнового наркомана, зазвичай вони роками страждають від психічних та фізичних тортур. Ми завжди говоримо, що швидка смерть краща за повільну, тому не заздріть бідним порно-користувачам. ***Вони заслуговують на вашу жалість.***
