# Поради не-користувачам

## Нехай ваші друзі-користувачі прочитають цю книгу

Спершу, вивчіть зміст цієї книги і спробуйте поставити себе на місце користувача. Не змушуйте їх читати цю книгу, стверджуючи, що вони руйнують своє здоровʼя, або граються з вогнем. Вони знають це краще за вас. Користувачі не продовжують дивитися порно через те, що вони отримують задоволення від нього, чи тому що вони цього хочуть. Вони кажуть це самі собі та іншим людям лише для того, щоб зберегти свою самоповагу. Вони роблять це через те, що вони залежні від порно, тому що вони думають, що це їх розслабляє, дає їм сміливість або впевненість (задоволення або підтримку), і тому що вони думають, що життя ніколи не буде приємним без "сексу" — хоча б їхньої версії. Якщо ви спробуєте і силою змусите користувача зупинитись, вони почуватимуться як загнаний у кут звір і бажатимуть свого гарему навіть більше. Це може перетворити їх на секретних користувачів, і порно стане навіть більш цінним у їхній голові.

Замість цього, сконцентруйтеся на іншому. Приєднайте їх до компанії екс-користувачів (блоги, форуми, Your Brain On Porn, NoFap, тощо, але будьте обережними із просуванням методу сили волі). Дайте їм послухати екс-користувачів, щоб вони розповіли як вони також думали що вони залежні на все життя і наскільки краще жити не будучи користувачем. Як тільки ви переконаєте їх у тому, що вони можуть зупинитися, їхній розум почне відкриватися. Потім почніть пояснювати про марення, які спричинені синдромом відміни. "Викид дофаміну" не тільки не дає їм піднесення, окрім цього вони руйнують свою впевненість та роблять себе роздратованими та втомленими.

Тепер вони мають бути готовими самі прочитати цю книгу, з очікуваннями, що вони читатимуть історії про невпевнені збудження, затухаючі пенетрації, імпотенцію, тощо. Поясніть, що цей підхід зовсім інший і посилання на хворобу це лише маленькі частини матеріалу.

Якщо коротко, не дайте цьому всьому померти у темноті. Розповідайте своїм друзям, але не поводьтеся дивно. Якщо ви спробуєте "виграти" розмову чи сперечатися, ви лише збільшите їхній страх.

## Чи варто розповідати своїй другій половинці?

Чи варто мені казати своїй жінці, дівчині, чи партнеру про мою звичку, щоб вони допомогли кинути? Є декілька факторів, які грають роль.

Якщо ви вже зазнавали невдач кинути за допомогою методу сили волі і вже сказали про це своєму партнеру, скажіть їм про ваш новий підхід і дозвольте їм прочитати цю книгу. Вони можуть допомогти вам і мотивувати протягом періоду відміни.

Якщо ви тільки почали розуміти про існування порно пастки і не намагалися кинути у минулому, спочатку використайте EasyPeasy самі. Як було розказано раніше, це має бути приємним досвідом. Але якщо вам важко, попросіть їхньої допомоги. Будьте відкритим та вразливим зі своїм партнером. Це зміцнить ваші відносини.

Якщо ви отримуєте задоволення від кидання порно і вам не важко через невизначеність, то немає причин казати про це партнеру. Якщо це не була проблема у минулому, дайте їй зникнути. Але будьте готовими, що ваш партнер гадатиме чому ви виглядаєте, почуваєтесь і працюєте краще!

## Мій партнер кидає порно

Порнографія це збочений знищувач відносин, і якщо кинути можна миттєво, то лікування триває якийсь час. Багато користувачів виливають їхню злість на партнерів та їхніх коханих через ірраціональні вірування які виникли через цю залежність. Така поведінка проявляється у гаслайтингу, брехні та маніпулятивній поведінці. Так трапляється не у всіх користувачів, але зазвичай трапляється у пізніх стадіях хвороби. Хоча така поведінка може проявлятися через порно залежність, важливо знати про неї, і якщо її було помічено, розглядайте можливість відвідування терапевта, який спеціалізується у сексуальних залежностях.

Якщо ваш партнер знаходиться у періоді відміни, вважайте що вони страждають, навіть якщо це не так. Не намагайтеся мінімізувати це, та не говоріть, що зупинятися легко, вони можуть зробити це самі. Замість цього, продовжуйте казати їм якими гордими ви є за них, як краще вони виглядають, як солодко бути з ними, і наскільки простіше вони є в цілому. Особливо важливо продовжувати робити це, тому що коли користувач робить спробу зупинки, їм може допомогти ейфорія від спроби та похвали, яку вони отримують від близьких їм людей. Але вони швидко забувають про це, тому продовжуйте хвалити їх.

Через те, що вони не розмовляють про порно, ви можете подумати що вони забули і не хочуть щоб ви їм нагадували. У випадку методу сили волі зазвичай відбувається повністю навпаки, тому що екс-користувач схильний бути одержимим нічим іншим. Тому не бійтесь підняти цю тему і продовжувати хвалити їх (вони скажуть вам, якщо вони не захочуть щоб ви їм нагадували).

Зробіть все можливе, щоб полегшити їх від напруги протягом періоду відміни та думайте про те, як зробити їхнє життя цікавим та приємним. Це також може бути випробувальним періодом для не-користувачів, які ніколи не мали залежності. Якщо один член групи роздратований, це може спричинити роздратування для всіх інших. Тому потрібно передбачити це — якщо екс-користувач почувається роздратованим, то він може виприснути це все на вас. Але не мстіться їм, у цей час вони потребують вашу похвалу та симпатію найбільше. Якщо ви самі почуваєтесь роздратованим, що зрозуміло, намагайтеся не показувати цього.

Одна з ігор, якою буде грати користувач під час спроби кинути за допомогою методу сили волі — це починати істерики зі сподіваннями, що їхній партнер або друзі скажуть: *"Я не можу дивитися на те, як ти страждаєш. Заради богів, просто візьми свою отруту."* Таким чином, користувачеві не потрібно втрачати обличчя, оскільки він не "здається", а йому дали інструкцію. Якщо екс-користувач спробує таке зробити, ні в якому разі не заохочуйте їх на повторення. Замість цього скажіть: *"Якщо це те, що порно робить для тебе, дякувати богу ти скоро будеш вільним. Як чудово, що ти знайшов сміливість кинути це."*

Памʼятайте, що у процесі зцілення приймають участь дві сторони. Коли ваш партнер кидає порно, важливо надати йому підтримку, допомогу та обмеження. Цей процес не відбувається за одну ніч, потребує довіри, комунікації та звітності. Цьому процесу допоможе ведення журналу, розвиток власних захоплень, і, найважливіше, терапія.

## Повторення

Цей розділ має вважатися за попередження тим, хто покидає пастку. Особисто я ніколи не робив повторення, тому я використаю досвід спільноти і когнітивної поведінкової терапії, щоб проілюструвати це.

По-перше, називати це повторенням непродуктивно. Ви лише послизнулися і погодували маленького монстра, що в свою чергу будить великого монстра, який промиває мізки. Користувачі, які роблять повторення (що за визначенням падіння вперед) зазвичай створюють цілий ряд ірраціональних думок:

  - "*Я ніколи не буду вільним*" - **Драматизація**
  - "*Я маю тренуватися, навчатися і бути продуктивним кожного дня свого життя*" - **Потребізація**
  - "*Сьогодні я повторив цикл ПМО, який взагалі сенс читати всі ці книги та форуми... Моєю ціллю було лише не займатись мастурбацією, але ось я — жалюгіддя, яке зробило повторення.*" - **Низька стійкість до невдач**
  - "*Мої друзі / читачі форумів / інші утримуються (n) днів, але я не можу, тому я безнадійний випадок. Вчора я почувався гарно, тому що я добре повчився та був продуктивним, але сьогодні ні... Я кочусь схилом вниз.*" - **Порівняння себе з іншими**
  - "*Я не мав мати сексуальних думок.*" - Вони самі, батьки, або їхнє суспільство у цілому встановило **жорсткі переконання** у відношенні до сексу. Спитайте себе чи ненависть до себе допомагає вам досягти своїх цілей, і якщо так, чи отримуєте ви задоволення від своєї подорожі?

Фактори, які призводять до промивання мізків кожного користувача виглядають безмежними. Ви знаєте себе краще за будь-кого, але це очевидно невиконання інструкцій. Ви побачили цінність у порнографії, але як?

На що часто не звертається увага, то це на те, що для того щоб відмінити промивання мізків потрібен час. Цей факт нічого не ускладнює, але майже кожна індустрія використовує секс, і активна протидія промиванню мізків — це свідомий процес (принаймні на початку), тому на те, щоб повністю закріпити уроки в цій книзі, потрібно скількись часу. Через це рекомендується багаторазове читання (ви можете пропускати до розділів, з якими у вас є складнощі), яке не має зайняти багато часу.

На диво розповсюджений досвід релігійних користувачів, які покидають цю пастку, це бажання щоб їм було боляче, як форма каяття. Вони легко кидають, і потім почуваються винними через це. Але навіщо саботувати себе і робити собі складнощі? Маленький монстр дуже хитрий у цьому плані.

Розрізняйте себе від маленького монстра — він був доданий порно індустрією дуже давно. Уявіть хулігана, який має істерику на шкільному подвірʼї. Що ви йому скажете? Якщо ви поступитесь йому, ви тільки зробите його сильнішим. Дехто з тих, хто кидає, годують хулігана і тим самим збільшують свою промивку мізків, але їхнє сприйняття цієї пастки не змінилося. Візьміть себе у руки, зрозумійте де ви помилились і насолоджуйтесь свободою!

Ви не є тягою до порно. Медитація — це практика відслідковувати та помічати думки, і в ній можна знайти фундаментальні уроки природи розуму. У цілому рекомендується медитувати, це також повністю сумісно з релігійними практиками. Ви не можете боротися сам із собою, або з маленьким монстром. Ви маєте безумовно любити себе та процес.

Видаліть невдачу зі свого розуму. Ось розділ із "*Медитації порнозалежного*", написаної Gulliaco (прикріплено вкінці книги).

> Оскільки перегляд порно не дає вам ніяких переваг, лише шкодить вам, і оскільки дуже дивно хотіти робити щось подібне, то я порівнюю це з питтям відбілювача. Наприклад:
>
> **Важка подорож не пити відбілювач.**
>
> Привіт! Ми є NoBleach і ми проводимо виклики по перезавантаженню, у яких учасники ("Bleachstronauts") утримуються від пиття відбілювача протягом якогось періоду часу. Неважливо, чи вашою ціллю є проста участь у місячному виклику як перевірка самоконтролю, або коли надмірне вживання відбілювача стало проблемою у вашому житті і ви хочете кинути на довший період часу, тут ви знайдете спільноту підтримки і достатню кількість ресурсів.
>
> - "*Іноді я дозволяю собі випити одну чи дві склянки відбілювача. Я знаю, що "одна крапля" це брехня, але я не думаю що одна склянка завдасть шкоди. Це не зможе знищити увесь мій прогрес, який я зробив, поки не вживав відбілювач.*"
> - "*У мене немає проблем з тим, щоб перестати пити відбілювач, але іноді я виходжу на вулицю і бачу, як хтось пʼє воду, ну знаєте, у стакані, і я уявляю, що у цьому стакані знаходиться відбілювач. Після цього я відчуваю тягу і після суперечок із собою про те, маю я робити це чи ні, я нарешті здаюсь і пʼю один стакан відбілювача на ніч.*"
> - "*Моя проблема у тому, що іноді, коли я знаходжусь один на кухні, я починаю бачити стакани, іноді я спокушаюсь відкрити контейнер, де я тримаю відбілювач, іноді я нюхаю його і... У результаті я повертаюсь туди, звідки починав. Я дуже хочу зупинитись, але я не впевнений чи зможу я це колись зробити.*"
> - "*Зупинитись пити відбілювач неможливо. Я маю на увазі, у мене завжди є рот, розумієте? Як я маю зупинитися, якщо я завжди маю горло, яке завжди нагадує мені про те, що я можу ковтати відбілювач?*"
> - "*Ех, все йшло так гарно. Цілих 19 днів без відбілювача. Головне — це навчатися з невдач! Тепер я знаю, чого треба уникати: дивитися на миючі засоби у супермаркетах. Я спробую протриматись тиждень! Я скину свій лічильник. Побажайте мені удачі!*"

> Якщо ви маєте бажання, не переживайте! Памʼятайте, що каже книга:
>
> "*Відбілювач важко кинути через те, що ми боїмося, що ми відмовляємось від нашого задоволення або опори. Страх, що якісь приємні ситуації ніколи не будуть такими самими знову. Страх, що ми не зможемо справлятися зі стресовими ситуаціями. Іншими словами, ефекти промивання мізків змушують нас вірити, що купувати відбілювач та продовжувати його пити — це необхідність для кожної людини. Більше того, це переконання, що у дешевому відбілювачі є щось, що нам потрібне, і що коли ми перестанемо його використовувати ми будемо відмовляти собі і створювати порожнечу. Запамʼятайте: відбілювач не заповнює порожнечу, він створює її!*"
>
> І я кажу:
> "*Уявіть, що ви змушені дивитися на склянку відбілювача пʼять хвилин. Спробуйте згадати один з брендів або запахів, які вам дуже сильно подобались. Можливо це супроводжується якимось звуком, або ви тільки памʼятаєте окремі деталі. Відбілювач знаходиться прямо тут, і ви не можете закрити свої очі або повернути свою голову, тому що цей відбілювач у вашій голові, ця памʼять записана у вас.*
>
> *Ви відчуваєте якусь тягу? Ви відчуваєте щось на своєму язику, або будь-яку зміну у своєму диханні? Які ваші відчуття від того, що ви згадуєте? Ідентифікуйте їх, відбілювач хоче затуманити їх, зробити їх заплутаними і змусити вас звертати увагу тільки на те, що намагається заволодіти вами.*"
>
> З тим, що написано вище, я не намагаюсь ігнорувати ваші почуття, ба більше сказати щось схоже на: "хаха я розумний ви тупий", а дати вам перспективу, щоб ви зрозуміли як легко кинути цю залежність.
> Перегляд порно це не перемикач on/off, коли ви кажете: "*О, я у ситуації Х, значить я дивитимусь порно*" Фантазії! Брехня! Як часто ви дозволяєте собі пити склянку відбілювача? Ніколи? Чому? Тому що це жахлива річ, ось чому! Як ви можете кинути свою залежність, якщо ви не бачите що порно це жахлива річ, яку ви робите собі?

## Як щодо МО (мастурбація, оргазм)?

Люди мастурбували століттями без проблем. Якщо говорити прямо, порно є проблемою.

Знаючи це, ви досі можете підсісти на МО через такі самі причини, як і на порно, через думки що вам "потрібен оргазм", ескалація, примус тіла до сексу, і просто гедоністичний пошук задоволення.

Є велика ймовірність, що порно і мастурбація стали глибоко переплетеними у вашій голові. Багато користувачів бачать, що вони закінчують повторенням у результаті мастурбації на порно фантазії. Коли ваш мозок перепрограмується, ви побачите, що це промивання мізків з часом зникає, але також гарно взяти перерву від МО на якийсь час. Також, ви маєте шукати справжнього сексу, щоб пришвидшити цей процес.

Це не інструкція, але подумайте над цим: відомо про численні переваги затримки сперми — збільшена концентрація та енергія, відсутність "туману в голові" та збільшена впевненість разом із низкою інших переваг. З особистого досвіду, існує очевидна відмінність і це все зводиться до того, як ви використовуєте цю збільшену енергію.

Якщо спекулювати без строгих наукових знань, переваги можуть звестись до декількох різних факторів.

- Після оргазму, мозок випускає пролактин, який гальмує витік дофаміну.

- Позбавлення мозку від дофамінових витоків дозволяє більше поглинання дофаміну від простого життя.

- Сперма реабсорбується потоком крові після приблизно 78 днів, і є однією з найбільших поживних речовин, яке ваше тіло може отримати.

- Перетворення сексуальної енергії у продуктивні звички дає збільшену продуктивність.

Ви також можете спробувати мати секс без оргазму, що, як було згадано раніше, є чудовим сексуальним досвідом (який часто називають Karezza). Ви можете зміцнити свою здатність робити це, виконуючи вправи Кегеля. З особистого досвіду, найлегший і найбільш ефективний спосіб розвитку цього мʼязу це зупиняти сечу під час сечовипускання (але будьте обережні і не перестарайтесь, це може спричинити додаткові проблеми). Розрізнення чуттєвої та дітородної частин сексу є одним із багатьох бонусів кидання пастки ПМО (і моїм партнерам сподобалось це також!).

## Відхилення від стандартних порад

Цей розділ є новим і був написаний трохи з побоюванням; але не зважаючи на це, він має бути.

Деякі люди, які використовують EasyPeasy бачать, що їхнє бажання дивитися порно стає настільки малим, що вони не можуть змусити себе мати останній сеанс. **У цьому немає нічого страшного**, але не дооцінюйте його силу. Обізнаний останній перегляд і закріплення того, наскільки вам не подобається ПМО, може мати потужні результати. Особисто для мене це було дуже корисно, і я був щасливим від того, що мені більше ніколи не буде потрібно цього робити. Але, ваш шлях може бути іншим.

Якщо ви вже вільний від пастки якийсь час і тільки видалили промивання мізків, тоді немає причин годувати маленького монстра, бо він вам набридатиме. Замість цього насолоджуйтесь свободою!

## Допоможіть закінчити цей скандал

Інтернет-порно — це одна з небезпек вільного суспільства. Це порося, яке годується на позитивних спробах особистих свобод. Без сумнівів, основа цивілізації, причина, через яку людство продвинулись так далеко, полягає у тому, що ми можемо передавати наші знання та досвід не тільки одне одному, але і до майбутніх поколінь. Навіть тварини вважають за необхідне захищати своє потомство від життєвих пасток.

Порно продюсери не роблять це через чисту сумлінність, справді вірячи у те, що вони допомагають людству, особливо коли залежність до інтернет-порно вивчається так широко. Можливо, в його початкових стадіях люди справді вірили, що порно навчало людей інтимності, але влада знає, що це неправда. Погляньте на будь-який сайт, вони не роблять ніяких акцентів на освіту. Позови зроблені тільки на шок, новизну та ескалацію їхніх продуктів.

Суцільне лицемірство неймовірне: як суспільство ми сильно переживаємо за шкільний булінг та обʼєктивізацію людського тіла. У порівнянні з інтернет-порно, ці проблеми незначні. Число тих залежних, хто проводить більшість свого часу з уявними піксельними людьми за рахунок їхнього здоровʼя, впевненості, енергії та часу, щорічно стає все більшим і більшим. Поки що це найбільший вбивця відносин, який руйнує сотні тисяч життів кожного року через те, що люди підсідають. Продюсери інтернет-порно не розміщають рекламу — їм не потрібно цього робити, оскільки наші біологічні бажання приводять нас на поріг їхніх гаремів. Також вони дають нам безкоштовні зразки як місцеві дилери наркотиків. Сьогодні сайти не так запасаються товаром, як заохочують відвідувачів публікувати контент.

Як розумно порно компанії показують попередження 18+ як стримуючий засіб для неповнолітніх користувачів, хоча деякі сайти навіть не намагаються цього робити. Інтернет-порно впливає на всі вікові категорії. "*Ми попередили вас про небезпеку, це ваш вибір.*" — ось їхнє ставлення. Чи роблять вони якісь кроки, щоб перевірити вік? Ні, це б збентежило їхніх клієнтів. Звичайно, якщо вікова верифікація буде уведена на законодавчому рівні, вони просто знайдуть іншу країну для операцій. Або вони заплатять деякій "еліті", щоб вони написати як заборона результувала у контрабанді і створенні мафії. Але забуто про питання, чому відміна сухого закону не результувала у зменшенні жертв від алкоголю, і невдачу закону контролювати ріст мафії.

Ми можемо вирішити цю проблему по-іншому, шляхом навчання молодших поколінь. Якщо вони можуть обійти цигарки та алкоголь коли ходять по магазину, тоді вони можуть зробити так само з інтернет-порно. Ми вже бачимо, що такі соціальні зміни як "No Nut November" та "Coomer" меми стають мейнстрімом. Користувач не має вибору більше, ніж його має героїновий наркоман. Користувачі не вирішують підсідати, вони бути загнані у підступну пастку. Якби користувачі мали вибір, єдиними користувачами завтра були б підлітки, які тільки починають, та вірять що вони можуть зупинитися коли захочуть.

До чого ці фальшиві стандарти? Чому героїнових наркоманів вважають злочинцями, але при цьому вони можуть зареєструватися як наркомани та отримувати метадон і медичне лікування, щоб кинути цей наркотик? Спробуйте зареєструватися як залежний від порно, якщо ви підете до лікаря за допомогою, вони скажуть вам: "*Не займайтеся цим так часто, використовуйте помірно*", що, як ви вже знаєте, не працює, або дадуть ліки від "депресії". Ще гірша порада — це знайти реального партнера. Серйозно? Чи знають вони користувачів, які бачать порно кращим і роблять це за спинами їхніх партнерів? Деякі люди просто не розуміють.

Залякування не допомагають користувачам зупинитися, вони лише роблять гірше. Вони тільки лякають користувачів, що робить їхнє бажання дивитися ще більшим. Такий метод також не зупиняє підлітків від того, що вони можуть підсісти. Вони знають, що порно вбиває їхнє лібідо, але вони також знають що один перегляд нічого не зробить. Через те, що залежність така поширена, скоріше чи пізніше підліток спробує один візит, через соціальний тиск чи цікавість. Через те, що безкоштовне порно жахливе, скоріше за все вони підсядуть.

Чому ми дозволяємо цьому скандалу продовжуватись? Чому уряди не зроблять відповідні кампанії? Чому нам ніхто не каже, що інтернет-порно — це наркотик і вбивча отрута, що це не розслабляє нас чи дає нам впевненість, а руйнує наші нерви? Що потрібен лише один перегляд щоб підсісти? Чому вони не можуть змусити вікову перевірку, просячи зареєстровані кредитні картки, можливо використовуючи третю особу? Компанія MindGeek, власник великої кількості порносайтів, намагається обманути владу та змусити її використовувати своє власне рішення по перевірці віку — не давайте їм цього робити! Роман Уелса *Машина часу* описує випадок у далекому майбутньому, де чоловік падає у річку. Його супутники просто сидять поруч із банком, як стадо, та не чують криків. Нелюдяно та тривожно, прямо як суспільна апатія до порно.

У суспільстві відчувається вітер змін. Снігова кулька почала котитися вниз по схилу, і я сподіваюсь, що ця книга допоможе перетворити її у лавину. Ви також можете допомогти розповсюджувати цю ідею.

Якщо ви бачите когось, хто не може кинути за допомогою методу сили волі, або хоче кинути порно, покажіть їм цей метод. Але, справжнє завдання — це зміна наративу порно в загальному. Будь ласка, подумайте над тим, щоб навчати людей в інтернеті коли ви бачите нормалізацію порно.

Час від часу, ви можете отримати негативну реакцію, але іноді коментар — це все, що потрібно. Як і багато хто до вас, ви можете очікувати отримати повідомлення від вдячних людей, які дякують вам за їхню свободу.

## Останнє попередження

Тепер ви можете насолоджуватися своїм життям як щасливий не-користувач. Для того, щоб впевнитись у цьому, вам потрібно виконувати ці прості інструкції.

1.  Тримайте наступну сторінку у закладках і повертайся до неї, коли вам потрібно.

2.  Якщо ви колись почнете заздрити іншому користувачеві, то зрозумійте, що вони заздрять вам. Ви не обділені. А вони — так.

3.  Памʼятайте, що вам не подобалось бути користувачем. Через це ви і зупинилися. Вам подобається бути не-користувачем.

4.  Памʼятайте, що немає такого поняття як лише один перегляд.

5.  Ніколи не сумнівайся у своєму рішенні більше ніколи не дивитися порно. Ви знаєте, що це було правильне рішення.

6.  Якщо ви маєте якісь складнощі, знайдіть терапевта, який розбирається у інтернет-порно. Ми можете знайти таких в інтернеті.
