# Інструкції

1.  Виконуйте усі інструкції.

2.  Будьте відкриті.

3.  Почніть з відчуття піднесення.

4.  Ігноруйте всі поради та впливи, які конфліктують з EasyPeasy.

5.  Опирайтесь будь-якій обіцянці тимчасового задоволення.

6.  Запамʼятайте: порно не дає справжнього задоволення чи підтримки, і ви не робите ніякої жертви. Немає чого втрачати і немає ніяких причин почуватися позбавленим.

7.  Не чекайте ні на що, кидайте зараз!

8.  Зробіть рішення ніколи більше не дивитися порно і ніколи не піддавайте це сумніву.

9.  Памʼятайте, що немає такого поняття як лише один перегляд.

10. Ніколи не дивіться порно знову.

## Афірмації

-   Я вільний від рабства порно.

-   Мені легко ігнорувати думки про порно.

-   Бувайте думки, бувайте бажання. Ось і зникають мої тяги.

-   Я фокусую свій підсвідомий розум на подоланні порно залежності.

-   Порно викрадає мій час, енергію та життєву силу.

-   З кожним днем перемогти порнографію стає все простіше у всіх аспектах.

-   Я насолоджуюсь та ціную свій спосіб життя без порнографії — сильний, щасливий, легкий і невимушений.

-   Коли я дивлюсь назад і думаю про свій прогрес, це дає мені велику радість та гордість за себе.

-   Кожного разу, коли я бачу інших порно-користувачів, у мене зʼявляється більше мотивації, щоб самому розірвати цей ланцюг.

-   Вся ця накопичена енергія зцілює моє тіло та розум. Тепер я можу виконувати більш продуктивну та складну роботу, націлену на досягнення своїх цінностей та цілей.

-   Мій мозок повертається у здоровий стан та тренується завдяки тому, що я *не* роблю того, що робив раніше.

-   Тепер вся ця стримувана сила волі йде на те, щоб справлятися з легкими стресами та викликами життя.

-   Чудово, я вільний і більше не є рабом!
