# Łatwa metoda

Celem tej książki jest prowadzenie cię na nowy stan umysłu. W przeciwieństwie do zwyczajnych metod rzucenia -- przy którym zaczynasz się czuć jakbyś wspiął się na Mount Everest i spędzał następne kilka tygodni pożądać i czuć się pozbawiony -- od razu zaczynasz z odczuciem euforii, jakbyś był uleczony z okropnej choroby. Od tej pory, im dalej przejdziesz przez życie, tym częściej będziesz patrzył na ten okres z czasu i zastanawiał się jak w ogóle skorzystałeś z porno. Będziesz patrzył na innych użytkowników porno z żalem, zamiast z zazdrością.

Pod warunkiem, że nie jesteś kimś, kto był wcześniej uzależniony (czytając dla drugiej połówki) albo rzucił (lub jest na dniu postu "diety pornograficznej"), jest niezbędne, żebyś nadal używał jej dopóki nie skończysz książki do końca. To może wyglądać jako sprzeczność i tak instrukcja kontynuacji masturbowania się do pornografii spowoduje więcej sprzeciwu niż co innego, ale im dalej będziesz czytał, tym twoja chęć do oglądania porno się stopniowo zmniejszy. **Potraktuj tą instrukcję poważnie: Próbowaniem wcześniej rzucić nie zyskasz nic.**

Większość nie skończy książki, ponieważ czują, że muszą coś poświęcić, niektórzy nawet celowo czytają jedną linię dziennie po to, żeby przełożyć to złe wydarzenie. Popatrz na to w ten sposób, co masz do stracenia? Jak nie przestaniesz do końca, nie jesteś gorszy niż teraz. To przez definicję Zakładu Pascala, zakład gdzie nie masz nic do stracenia i duże szanse na wielkie zyski.

Nawiasem mówiąc, jeżeli nie oglądałeś pornografii przez kilka dni lub tygodni, ale nie jesteś pewien czy jesteś użytkownikiem, byłym użytkownikiem, lub w ogóle nie jesteś, zatem nie używaj porno do masturbacji w czasie czytania. Właściwie,już jesteś nie-użytkownikiem, musimy pozwolić twojemu mózgowi dogonić twoje ciało. Na końcu książki, będziesz wesołym nie-użytkownikiem. EasyPeasy jest kompletnym przeciwieństwem normalnej metody, gdzie pokazuje znaczące wady pornografii i mówi:  
*"Jakbym tylko mógł pójść dalej bez porno, w końcu chęć odejdzie i będę mógł się cieszyć życiem, wolnym od niewolnictwa."*  
To jest logiczny sposób, aby się do tego zabrać, z tysiącami, którzy zaprzestali każdego dnia używając tej metody. Jednakże, jest to bardzo trudne aby osiągnąć sukces z następujących powodów:

**Zatrzymanie PMO nie jest prawdziwym problemem.**
Za każdym razem kiedy kończysz swoją sesję, przestałeś już używać tego. Możesz mieć mocne motywy na pierwszym dniu swojego "jeden-na-cztery" diecie pornograficznej żeby powiedzieć *“Nie chcę już korzystać z porno lub się masturbować.”* Wszyscy tego chcą, a ich motywy są jeszcze mocniejsze niż mógłbyś sobie wyobrazić. Prawdziwy problem pojawia się w dniu drugim, dziesiątym, lub dziesięć tysięcznym gdzie w słabych momentach zrobisz ‘tylko małe zerknięcie’, chcesz kolejnego i nagle jesteś znowu uzależniony.

**Świadomość zagrożeń zdrowotnych rodzi więcej strachu, czyniąc go trudniejszym do zatrzymania.**
Powiedz użytkownikom, że to niszczy ich płodność i pierwsze co zrobią to będą sięgać po coś, co podwyższy ich dopaminę:  papieros, alkohol, lub nawet włączenie przeglądarki w szukaniu porno.

**Wszystkie powody zaprzestanie tak naprawde utrudniają.**
To przez dwa powody. Po pierwsze, jesteśmy nieustannie zmuszani, aby poddać naszego ’małego przyjaciela’ albo jakiś rekwizyt, nałóg albo przyjemność (w jakikolwiek sposób użytkownik na to spojrzy). Po drugie, tworzą "zasłonę".Nie masturbujemy dla powodów, dla których musimy przestać. Prawdziwym pytaniem jest, dlaczego chcemy lub potrzebujemy to robić?

Z metodą EasyPeasy, my (na początku) zapominamy powody dla których zaprzestaliśmy, zmierzamy się z problemem pornografii i pytamy się następujących pytań:

1.  Co porno dla mnie robi?

2.  Czy naprawdę się nią cieszę?

3. Czy naprawde muszę przechodzić przez życie sabotażując mój umysł i moje ciało?

Piękną prawdą jest to, że *każda pornografia* nic dla ciebie w ogóle robi. Pozwól mi to wyjaśnić, nie chodzi o to, że wady bycia użytkownikiem przewyższają zalety, chodzi o to, że nie ma ***żadnych*** zalet w parzeniu na pornografię.

Większość użytkowników znajdują potrzebę w racjonalizowaniu powodu użycia porno, ale powody, które znajdują to tylko błędy i iluzje.

Po pierwsze, usuniemy te błędy i iluzje. W rzeczywistości, wkrótce zauważysz, że nie ma co poświęcać. Nie tylko to, ale są też cudowne, pozytywne korzyści z bycia nie PMO-wcem, z dobrobytem i szczęściem jako te dwie z wielu korzyści. Wcześniej iluzje mówiące, że życie nie będzie aż tak przyjemne bez pornografii -- zdając sobie sprawę, że nie tylko życie jest bardziej przyjemne bez niej, nawet nieskończenie bardziej --  i jak te odczucia bycia pozbawionym czegoś lub przegapienia czego zwalczone, wrócimy do przemyślenia dobrobytu i szczęścia oraz tuzin innych powodów rzucenia porno. Te zrealizowania staną się pozytywnym wsparciem, aby pomóc ci osiągnąć to, czego chcesz: cieszenie się z życia wolnego od niewolnictwa przez uzależnienie od porno!


