# Dlaczego zatrzymanie tego jest ciężkie?

Wszyscy użytkownicy czują, że jakieś zło ich opętało. We wczesnych latach, to było proste pytanie do *"Przestanę, ale nie dzisiaj"*. W końcu postępujemy do wierzenia, że nie mamy wystarczającej siły woli aby przestać, lub to, że jest coś nieodłącznego w porno, że musimy go mieć aby cieszyć się życiem. Uzależnienie od pornografii jest jak wyszarpanie się z śliskiej otchłani: Zbliżając się do szczytu, widzimy słońce, ale widzimy, że zjeżdżamy z powrotem kiedy nasze samopoczucie spada. Ostatecznie otwieramy przeglądarkę , masturbujemy się i czujemy się okropnie.

Zapytaj się użytkownika, *"Jakbyś mógł wrócić do czasu przed bycia uzależnionym, z wiedzą, którą masz teraz, zacząłbyś korzystać z pornografii?"*

*"NIE MA MOWY!"* byłoby odpowiedzią.

Zapytaj się potwierdzonego użytkownika, kogoś kto broni internetowej pornografii i nie wieży w niszczenie umysłu lub zmniejszenia aktywności receptorów dopaminy: *"Czy zachęcasz swoje dzieci do używania porno?"*

*"NIE MA MOWY!"* znowu byłoby odpowiedzią.

Porno jest nadzwyczajną enigmą. Jak wcześniej mówiłem, problemem nie jest wyjaśnienie dlaczego jest łatwo zaprzestać, jest nim wyjaśnienie dlaczego jest trudno zaprzestać. Prawdziwym problemem jest wyjaśnienie dlaczego ktokolwiek robi to *po* zdobyciu wiedzy o uszkodzeniach neurologicznych. Po części zaczynamy, ponieważ reszta dziesięciu milionów już to robi, jednakże ci wszyscy żałują, że w ogóle zaczęli, mówiąc nam jak to jest żyć na drugim biegu. Nie do końca im wierzymy, że nie im nie podoba, kiedy kojarzymy to z wolnością lub byciem ’seks-kształconym’, i ciężko pracujemy, byśmy sami byli uzależnieni. Wtedy spędzamy resztę naszego życia mówiąc tego, by tego nie robić i próbować samemu wykopać ten nawyk, często myśląc, że jesteśmy w tym wyjątkowi.

Spędzamy też znaczącą część czasu czując się beznadziejnie i nędznie . ’Kształcąc’ się z nadprzyrodzonym sprawia, że preferujemy i przedłużamy te zimne obrazki, nawet jak są ciepłe, prawdziwe są dostępne. Przez ciągły wzrost i spadek dopaminy wywołanym przez PMO, skazujemy się na dożywotnią izolację, drażliwość, złość, stress, fatygę i dysfunkcję seksualną. Używając porno, z brakiem najlepszych części seksu i połączenia, skończymy czując się czujemy się nędznie i z winną .

W rzeczywistości, czytając tu i na innych stronach o uzależniających i destrukcyjnych możliwościach internetowej pornografiireading, stajemy się bardziej nerwowi i beznadziejni! Jakim to jest kiedy to robisz,nie chcesz, ale pragniesz to? Użytkownicy gardzą sobą przy każdym razie, kiedy czytają o hipofrontalności oraz o odczulaniu, za każdym razem używają za plecami zaufanej partnerki i za każdym razem nie mogą zdobyć się na ćwiczenia po dziennej sesji. W przeciwnym przypadku, inteligentna i racjonalna istota ludzka spędza całe dni pogardzie. Ale najgorsze z tego wszystkiego, co użytkownicy otrzymują od znoszenia tych okropnych cieni z tyłu swojego umysłu? **Absolutnie nic!**

Mógłbyś sobie teraz pomyśleć *"Wszystko w porządku, znam to, ale jak już jesteś uzależniony na tych rzeczach, jest bardzo trudno przestać."* Ale dlaczego jest tak trudne? Niektórzy powiedzą, że to przez silne symptomy odstawienia, ale wkrótce nauczysz się, że rzeczywiste symptomy odstawienia są w rzeczywistości bardzo łagodne. To jest wyraźne, kiedy rozważysz to, że większość PMOwców żyli i umierali bez zdania sobie sprawę, że są uzależnieni.

Niektórzy mówią, że internetowe porno jest darmowe  internet porn is free i w związku z tym ludzkość powinna żądać tą biologiczną bonanzę, ale to nieprawda—jest uzależniające i działa tak samo jak każdy narkotyk. Zapytaj się użytkownika, który przysięga, że on lubi tylko 'erotykę' jak na przykład magazyny Playboya, czy kiedykolwiek przekroczył linię 'niebezpiecznego porno'. Jakby byli szczerzy , prędzej przyznaliby się do czasów, w którym racjonalizować przekroczenie tej linii, niż w ogóle nie używania niej.

Przyjemność też nie ma nic z tym wspólnego. Uwielbiam jeść langusty, ale nigdy nie doszłoby do tego, gdzie musiałbym jeść langusty codziennie. Tak jak z innymi rzeczami w życiu, lubimy je kiedy je wykonujemy, ale nie siedzimy czując się pozbawionym kiedy nie robimy tego.

Niektórzy mówią:  
*"Jest kształcące!"* Więc jak cię to rozwinęło jako osobę?
*"To jest seksualna satysfakcja!"* Więc dlaczego cię to izoluje i sprawia, że czujesz nienasycony głód?
*"To jest uczucie uwolnienia!"* Uwolnienia ze stresów prawdziwego życia? Ok, przez godzinę, zanim uderzy z powrotem na ciebie? Jakie stresy to rozwiązało?
*"Pomaga mi zasnąć"* Zatem dlaczego inny dobrze zasypiają bez tego? Jest [wiele](https://www.sleepfoundation.org/insomnia/treatment/meditation) naukowo wykazanych [metod](https://www.sleepfoundation.org/insomnia/treatment/cognitive-behavioral-therapy-insomnia) na [naprawę](https://www.amazon.com/Uvex-Blocking-Computer-SCT-Orange-S1933X/dp/B000USRG90) snu, i [w większym stopniu](https://www.menshealth.com.au/what-is-the-military-method-the-technique-that-promises-to-help-you-sleep-in-2-minutes).

Wielu wierzy, że porno zwalcza nudę, ale nuda to samopoczucie. Porno przyzwyczai cię dop szukania nowości od zaraz, powodując, że stajesz się coraz bardziej znudzony dopóki nie weźmiesz udziału w pogoni za niczym dla tego właściwego filmiku, stając się coraz bardziej przywiązany do szukania wszystkiego, co wyzwala nowość, silne emocje i wreszcie obrzydzający szok.

Niektórzy mówią, że robią tylko dlatego, że ich przyjaciele i każdy, kto ich zna robią to. Jeżeli tak jest, módl się, żeby twoi przyjaciele nie zaczęli odcinać sobie głów, aby wyleczyć ból głowy! Większość użytkowników, którzy o tym myślą podchodzą do konkluzji, że to jest po prostu nawyk. To nie jest doprawdy wyjaśnieniem, ale obniżając wszelkie zwyczajne, racjonalne wyjaśnienia, wydaje się być to jedyną pozostałą wymówką. Niestety, jest równie nielogiczna. Każdego dnia w naszym życiu zmieniamy nawyki,  niektóre z nich bardzo przyjemne. Mieliśmy wyprane mózgi, aby wierzyć, że PMO jest nawykiem i to, że nawyki są trudne do przerwania.

Czy nawyki są łatwe do złamania? Kierowcy w USA mają nawyk do prowadzenia po prawej stronie jezdni, jednak kiedy podróżują zagranicą, łamią nawyk bez żadnego zaostrzenia. Kiedy dostajesz nową pracę, nakładasz sobie inną rutynę, z czego nawyki się zmieniają. Może potrwać chwilę do przyzwyczajenia, a to nic jak przerwanie dożywotnia walka uzależnieniem od pornografii. Tworzymy i niszczymy nawyki każdego dnia naszego życia, zatem dlaczego jest nam ciężko złamać nawyk, który przez niego czujemy się pozbawieni kiedy nie używamy, który bardzo chcielibyśmy i tak złamać, kiedy jedyne co musimy zrobić to *przestać to robić?*

Odpowiedzią jest to, że porno nie jest nawykiem, *jest uzależnieniem!* Dlatego wydaje nam się być tak ciężkim, aby ’zrezygnować’. Większość użytkowników nie rozumie uzależnienia i wierzą, że otrzymują prawdziwą przyjemność lub podporę od porno. Wierzą, że robią prawdziwe poświęcenie jak rzucą.

Piękną prawdą jest to, że kiedy zrozumiesz prawdziwą naturę uzależnienia od pornografii oraz powodów dla których używasz, przestaniesz korzystać z tego, tak porostu. W ciągu trzech tygodni, jedyną zagadką będzie to, dlaczego znalazłeś potrzebę w używaniu porno tak długo jak mogłeś i dlaczego nie możesz przekonać innych użytkowników *jak miłe jest nie bycie PMOwcem!*

## Złowieszcza pułapka

Internetowe porno jest subtelną i złowieszczą pułapką, nad którą człowiek i natura się połączyli aby ją wynaleźć. Niektórzy z nas nawet ostrzegali o zagrożeniach, ale nie wierzymy jak nas porno nie cieszy. Ale co doprowadza nas do tego na pierwszym miejscu? Zazwyczaj to darmowe próbki od amatorów i profesjonalistów, którzy udostępniają. Tak pułapka się zrodziła. Jeśli zamiast tego ostrzegły przed zagrożeniami, z którymi się wpakujemy zanim zrobimy nasze pierwsze zaglądnięcie,alarm zacząłby dzwonić.

Ale dzwony nie dzwonią. Chyba to jest szokująca natura wielu klipów, które zapewniają nasze młode umysły, że nigdy nie będziemy uzależnimy, myśląc tak, bo nie cieszymy się nimi i to że możemy zaprzestać kiedy chcemy. Być może zobaczenie niewinności materiału softcore nie uruchamia alarmu, podobnie jak umiejętne lawirowania, którymi naciągacz może zagrać, aby kierować naszymi umysłami. Jako inteligentne istoty ludzkie, zrozumieliśmy dlaczego połowa dorosłej populacji była systematycznie uzależniona od czegoś tnącego nasz sam potencjał do wykonywania tego, co oglądamy. Ciekawość zbliża nas do progu drzwi uzależnienia, ale nie odważy się kliknąć na miniaturki, na które zerkamy, bojąc się że przyciągną lub ześlą nas na niebezpieczną oraz niemoralną ścieżkę. I jak przypadkowo klikniemy na jedną, często naszą jedyną chęcią jest odejść od strony najszybciej jak możliwe, w czasie kiedy jesteśmy bardziej rozpaczliwie ciekawi.

Raz ten proces się zacznie, jesteśmy w pułapce. Od tej pory spędzamy resztę naszego życia próbując zrozumieć dlaczego to robimy, mówiąc naszym dzieciom, aby nie zaczynać i w dziwnych czasach próbując samemu uciec. Pułapka jest stworzona tak, że próbujemy i przestajemy tylko z powodu ’wypadku’, czy to sprawność seksualna, utrata kariery lub związku, niedobór popędu lub po prostu poczucie się trędowatym. Zaraz po zaprzestaniu, mamy więcej stresu przez napady odstawienne i z metodą, na którą polegliśmy na usunięcie tego stresu jest już niedostępna.
Nasze postanowienie na rzucenie wtedy, dowodzi, że jest chwiejny. Po kilku dni tortur przekonujemy samych siebie, że wybraliśmy zły czas na rzucenie, decydują że poczekamy na okresy bez stresu, w którym po przybyciu usuwa nasze powody na pierwotne przestanie. Oczywiście ten okres w pełni nie przyjdzie i zaczynamy wierzyć, że nasze życie ma skłonność do stania się jeszcze bardziej stresującym. Zostawiamy ochronę naszych rodziców oraz nacisk w pracy , prowadzenie domu, hipotekę, kupowanie schronienia i wychowywanie dzieci zaczyna tłoczyć nasze życia. Ale to wszystko jest iluzją. Najbardziej stresującym fragmentem życia każdego stworzenia, są właściwie we wczesnym dzieciństwie i w okresie dojrzewania.


Mamy tendencję do mylenia odpowiedzialności ze stresem. Życie użytkownika -- jak narkomana -- z automatu staje się mniej stresującym, ponieważ porno nie relaksuje nas lub nie uspokaja nerwów, jak niektórzy próbują nam wmówić. Jest odwrotnie. Powoduje, że jesteśmy bardziej zestresowani, jak kontynuujemy użycie, z każdą obciążającą nas winą następstwem późnej nocy kładąc więcej słomy na plecy wielbłąda. Nawet użytkownicy, którzy wykopią nawyk---jak większość robi tak raz lub więcej razy przez całe ich życia---może prowadzić perfekcyjnie szczęśliwe życia, jednak nagle znowu stają się uzależnieni. Wędrująć po pornograficznym labiryncie, nasze myśli stają się mgliste i spędzamy resztę naszego życia próbując uciec. Większość odnosi sukces, tylko żeby spaść do złowieszczej pułapki następnego dnia.

Rozwiązanie problemu uzależnienia od porno jest jak zagadka. Jest złożona i trudna. Ale raz rozwiązując zagadkę, jest prosta i fajna  i zastanowisz się dlaczego o tym nie pomyślałeś! EasyPeasy zawiera rozwiązanie do tej łamigłówki, wyprowadzają cię z labiryntu, nigdy już nie wędrując po niej. **Jedyne co musisz zrobić to podążać za każdą instrukcją, słowo do słowa**. Jednakże, jeśli obierzesz **zły kierunek przez przeskakiwanie rozdziałów**, lub **przemijanie przez książkę z zawrotną prędkością** bez ostrożnego podjęcia zamierzonego wysiłku na twój pierwszy czas czytania, wtedy reszta instrukcji jest bezsensowna.

Każdy może znaleźć łatwy sposób na zaprzestanie, ale musimy najpierw ustanowić fakty. Nie, nie fakty stworzone do przestraszenia ciebie, jest już tutaj więcej informacji niż potrzebujemy. Jeśli to cię by zatrzymało, już byś przestał. Ale dlaczego jest nam ciężko przestać? Odpowiedzenie tego wymaga od nas poznania prawdziwego powodu dla którego używamy porno, sprowadzając do dwóch czynników. One to są:

-   Natura i internetowe porno.

-   Społeczne pranie mózgu.

Użytkownicy porno są inteligentnymi, racjonalnymi istotami ludzkimi. Wiedzą, że podejmują ogromne ryzyko na przyszłość, więc spędzają wiele czasu na racjonalizowanie swoich ’nawyków’. Ale w środku użytkownicy porno wiedzą, że są głupcami, wiedząc że nie musieli korzystać z porno przed zostaniem uzależnionym. Większość pamięta, że ich ich pierwsze ’zerknięcie’ było mieszanką wstrętu i nowej ciekawości. Wtedy specjalizują się w lokalizowaniu, filtrowaniu i zaznaczaniu stron, ciężko pracując na bycie uzależnionym.

Najbardziej nieznośne jest to, że jest poczucie dla nieuzależnionych -- większość kobiet, starsi mężczyźni oraz ludzie żyjących w krajach, gdzie pornografia z internet z szybką prędkością jest niedostępna -- nic nie przegapiają patrzą na tą sytuację ze śmiechem. Przez likwidację tych czynników w następnych rozdziałach, ty też zrozumiesz tą złowieszczą pułapkę!


