# Z czego rezygnuję?

**Z absolutnie niczego!** Porno trudno jest porzucić ze względu na strach, że pozbawiamy się przyjemności lub podpory. Strach, że pewne przyjemne sytuacje już nigdy nie będą całkiem takie same. Strach, że pozostaniesz niezdolny do radzenia sobie w sytuacjach stresowych. Innymi słowy, są to efekty prania mózgu, które zwodzi nas w przekonanie, że seks - i w konsekwencji orgazm - jest koniecznością dla wszystkich istot ludzkich. Co więcej, jest to przekonanie, że w pornografii internetowej jest coś, czego potrzebujemy i że kiedy przestaniemy z niej korzystać, odmówimy sobie i stworzymy pustkę.

Niech to będzie jasne dla twojego umysłu: **Porno nie wypełnia tej pustki,** ***ono ją tworzy!***

Nasze ciała to najbardziej wyrafinowanymi obiektami na naszej planecie. Niezależnie od tego, czy wierzysz w inteligentny projekt, dobór naturalny, czy kombinację obu, nasze ciała są tysiące razy bardziej efektywne niż człowiek! Nie jesteśmy w stanie stworzyć najmniejszej żywej komórki ani cudów wzroku, reprodukcji i różnych powiązanych systemów obecnych w naszych ciałach czy mózgach. Gdyby ten stwórca lub proces miał na celu poradzenie sobie z nadprzyrodzonymi bodźcami, zostalibyśmy wyposażeni w inne systemy nagradzania. Nasze ciała są wyposażone w awaryjne urządzenia ostrzegawcze i ignorujemy je na własną zgubę.

## Nie ma z czego rezygnować

Po oczyszczeniu małego potwora z ciała i prania mózgu (dużego potwora) z umysłu, nie będziesz chciał ani masturbować się często, ani używać do tego pornografii internetowej . Istnieje wiele znanych i nieznanych, jeśli chodzi o uzależnienie od pornografii, przy czym wielu w środowisku medycznym nie ma pojęcia o kwestionowaniu lub określaniu kogoś jako uzależnionego od pornografii. Wiele zgłoszonych objawów jest błędnie oznaczonych pod innymi przyczynami. Nie chodzi o to, że użytkownicy są generalnie głupimi ludźmi, chodzi o to, że są nieszczęśliwi bez porno. Złapani między diabłem a błękitnym morzem, powstrzymujący się i nieszczęśliwi, ponieważ nie mogą używać porno lub nieszczęśliwi, ponieważ są winni i zaczynają gardzić sobą z tego powodu. Kiedy pojawiają się objawy, takie jak ból dolnej części pleców lub dysfunkcja seksualna, ich umysły są rozdarte między przyjęciem odpowiedzialności a patrzeniem w inną stronę.

Kolejna analogia palacza, wszyscy widzieliśmy palaczy, którzy wymyślają wymówki, aby wymknąć się na podstępne puszczanie dymka i widzimy prawdziwy nałóg w działaniu. Uzależnieni nie robią tego dla przyjemności, zamiast tego robią to, ponieważ bez tego są nieszczęśliwi.

Dla wielu ich pierwsze doświadczenie seksualne zakończyło się orgazmem, więc nabyli przekonanie, że nie mogą cieszyć się seksem bez niego. W przypadku mężczyzn porno jest reklamowane jako pomoc w uprawianiu seksu, czasem nawet jako nauka pewności siebie podczas aktu. To bzdura, warunkowanie nadprzyrodzonymi bodźcami udaje się tylko sprowadzić w dół.

Nie tylko nie ma z czego rezygnować, ale można uzyskać ogromne pozytywne korzyści. Kiedy użytkownicy rozważają rzucenie palenia, zwykle koncentrują się na zdrowiu i męskości. Są to ważne i istotne powody, ale ja osobiście uważam, że największe zyski są psychologiczne:

-   Powrót do swojej pewności siebie i odwagi.

-   Wolność od niewolnictwa.

-   Nie musisz już dłużej mieć tych okropnych czarnych cieni z tyłu głowy i gardzić sobą.

## Pustka, pustka, ta piękna pustka!

Wyobraź sobie, że na twojej twarzy pojawiło się przeziębienie, więc idziesz do farmaceuty, a on daje ci darmową maść do wypróbowania. Nakładasz maść i natychmiast znika. Po tygodniu pojawia się ponownie, więc wracasz do farmaceuty i pytasz, czy mają jeszcze jakąś maść. Farmaceuta mówi: "Jasne, zatrzymaj tubkę, może ci się przydać później".

Nakładasz maść i voila, ból znika po raz kolejny. Ale za każdym razem, gdy ból powraca, staje się większy i bardziej bolesny, a odstępy czasu stają się coraz krótsze. W końcu ból obejmuje całą twarz i jest niemiłosiernie bolesny, a powraca co pół godziny. Wiesz, że maść usunie go tymczasowo, ale bardzo się martwisz. Czy ból w końcu rozprzestrzeni się na całe twoje ciało? Czy przerwa zniknie całkowicie? Idziesz do lekarza i nie mogą tego wyleczyć, więc próbujesz innych rzeczy, ale nic nie pomaga oprócz maści.

Teraz jesteś już całkowicie zależny od maści, nigdy nie wychodzisz z domu bez upewnienia się, że masz ze sobą tubkę. Jeśli wyjeżdżasz za granicę, upewniasz się, że zabierasz ze sobą kilka tubek. Oprócz obaw o swoje zdrowie, aptekarz pobiera od ciebie opłatę w wysokości stu dolarów za tubkę. Nie masz wyboru, musisz zapłacić.

Natykasz się na artykuł omawiający to i dowiadujesz się, że to nie dzieje się tylko z tobą, wiele osób cierpi na ten sam problem. W rzeczywistości, społeczność medyczna odkryła, że maść nie faktycznie wyleczyć ból, a zamiast tego tylko bierze go pod powierzchnią skóry. To maść spowodowała, że wrzód urósł, więc wszystko, co musisz zrobić, aby pozbyć się wrzodu, to przestać używać maści i zniknie on w odpowiednim czasie.

Czy nadal stosowałbyś maść? Czy potrzeba by było siły woli, żeby nie używać maści? Gdybyś nie wierzył w ten artykuł, mogłoby być kilka dni obaw, ale kiedy zdałbyś sobie sprawę, że ból zaczyna się poprawiać, potrzeba lub chęć użycia maści odeszłaby. Czy byłbyś nieszczęśliwy? Oczywiście, że nie! Miałeś okropny problem, który uważałeś za nieuleczalny, ale teraz znalazłeś rozwiązanie. Nawet gdyby minął rok, zanim ból zniknął, każdego dnia, gdy się poprawiał, myślałbyś o tym, jak wspaniale się czujesz. To jest właśnie magia rzucenia pornografii.

Bolące nie są bóle ciała, brak normalnego pożądania, słabnące podniecenie, słabnąca penetracja, zmarnowany czas spędzony na dwuwymiarowych obrazach, poczucie naruszenia uprawnień i gardzenie ludźmi, którzy cię złapali lub co gorsza gardzenie sobą. To wszystko są dodatki do obolałości.

Bolączka sprawia, że zamykamy się na te wszystkie rzeczy, to to paniczne uczucie chęci posiadania poprawki. Nieużytkownicy nie cierpią z powodu tego uczucia. Najgorszą rzeczą, jaką kiedykolwiek cierpimy jest strach, a największym zyskiem jest pozbycie się tego strachu. Jest on wywołany przez pierwszą sesję, dalej wzmacniany i powodowany przez każdą następną.

Niektórzy użytkownicy są "szczęśliwi", zaślepieni przez swoje przebiegłe małe potwory i tak przechodzą przez ten sam koszmar, podsuwając fałszywe argumenty, aby spróbować usprawiedliwić swoją głupotę.

*Tak miło być wolnym!*


