# Oszczędzanie czasu

Zazwyczaj, kiedy użytkownicy próbują przestać, głównymi powodami są zdrowie, religia i piętno partnera. Częścią prania mózgu przez ten okropny narkotyk jest czyste niewolnictwo, człowiek ciężko walczył o zniesienie niewolnictwa w wielu częściach świata - jednak użytkownik spędza życie cierpiąc z powodu narzuconego sobie niewolnictwa. Nie są świadomi faktu, że kiedy pozwalają sobie na używanie pornografii, żałują, że są jej użytkownikami. Jedynym momentem, kiedy porno staje się cenne, jest czas, kiedy "próbujemy" ograniczyć lub powstrzymać się od niego, albo kiedy abstynencja jest na nas wymuszana.

Nie można wystarczająco często powtarzać, że pranie mózgu utrudnia odstawienie porno, im więcej rozwiejemy zanim zaczniemy, tym łatwiej osiągniemy swój cel. Potwierdzeni użytkownicy, którzy nie wierzą w to, że porno ma jakikolwiek negatywny wpływ na ich zdrowie (zaburzenia erekcji wywołane przez porno, hipofrontalność, itp.) i nie prowadzą mentalnej wojny, są zazwyczaj młodsi lub samotni z okazjonalnym partnerem seksualnym. Tak więc, wewnętrzne sprzężenie zwrotne jest utracone ze względu na charakter ich młodości lub jest zbyt rzadkie, aby być obserwowane i rejestrowane.

Lepszym argumentem dla młodszego użytkownika jest spędzony czas, raczej mówiąc "*Nie mogę uwierzyć, że nie martwisz się o czas, który spędzasz.*". Generalnie oczy im się rozjaśniają, czują się pokrzywdzeni, jeśli atakuje się ich ze względów zdrowotnych lub piętna społecznego, ale na czas...  
"*Oh, mogę sobie na to pozwolić. To tylko x godzin tygodniowo i myślę, że warto, to mój jedyny zastępca przyjemności.*"

"*Wciąż nie mogę uwierzyć, że się nie martwisz. Załóżmy półgodzinną średnią dzienną, która obejmuje fizyczny drenaż wycofania dopaminy, spędzasz około pełny dzień roboczy co dwa tygodnie. Jestem pewien, że zgodzisz się, że pół godziny dziennie to bardzo ostrożne oszacowanie. Czy myślałeś o tym, ile czasu spędzisz w swoim życiu? Co robisz w tym czasie? Rozwijasz prawdziwe relacje? Nie, twoja ulubiona gwiazda porno nie ma dla ciebie współczucia, tylko dlatego, że spędziłeś tyle czasu na ich filmach - wyrzucasz czas w błoto! Nie tylko to, w rzeczywistości używasz ten czas, aby zrujnować swoje zdrowie fizyczne, niszcząc sobie nerwy i pewność siebie, aby cierpieć całe życie w niewoli, bólu, melancholii i rozczulaniu się. Z pewnością musi cię to martwić, prawda?"

Jest to widoczne w tym momencie -- zwłaszcza w przypadku młodszych użytkowników -- że nigdy nie uważali tego za nałóg na całe życie. Od czasu do czasu obliczają czas, jaki tracą w ciągu tygodnia i to jest wystarczająco niepokojące. Bardzo sporadycznie, i tylko wtedy, gdy myślą o zaprzestaniu, szacują, ile wydają w ciągu roku, co jest przerażające - ale przez całe życie jest nie do pomyślenia. Jednakże, ponieważ jesteśmy w trakcie kłótni, potwierdzony użytkownik powie odruchowo, *"Mogę sobie na to pozwolić, to tylko tyle na tydzień "*, wyciągając na siebie rutynę sprzedawcy encyklopedii.

Czy odrzuciłbyś ofertę pracy, która płaci twoją obecną roczną pensję, a także daje ci miesiąc wolnego każdego roku? Każdy użytkownik podpisałby ją w mgnieniu oka i zająłby się wyszukiwaniem ofert wakacyjnych w egzotycznych miejscach. Pomyślenie jak spędzić cały miesiąc bez pracy byłoby największym problemem do rozwiązania. W każdej rozmowie z potwierdzonym użytkownikiem (i proszę pamiętać, że nie jest to ktoś taki jak ty, kto planuje przestać) nikt nigdy nie skorzystał z tej oferty. Dlaczego nie?

Często w tym momencie potwierdzony użytkownik powie: "*Posłuchaj, tak naprawdę nie martwię się o aspekt pieniężny.*". Jeśli myślisz wzdłuż tych linii zadaj sobie pytanie, dlaczego nie jesteś zaniepokojony. Dlaczego w innych aspektach twojego życia pójdziesz do wielkich kłopotów, aby zaoszczędzić kilka dolarów tu i tam, ale spędzić tysiące zabijając swoje szczęście i wisząc swoje wydatki?

Każda inna decyzja, którą podejmiesz w swoim życiu, będzie rezultatem analitycznego procesu ważenia zalet i wad, aby dojść do racjonalnej decyzji. Może to być zła decyzja, ale będzie wynikiem racjonalnego odjęcia. Ilekroć jakikolwiek użytkownik rozważa plusy i minusy korzystania z internetowego porno, kilkanaście razy pada odpowiedź: **"PRZESTAŃ UŻYWAĆ! JESTEŚ FRAJEREM!"** Dlatego wszyscy użytkownicy używają nie dlatego, że chcą czy decydują, ale dlatego, że nie mogą przestać. Oni ***muszą*** używać porno, a więc piorą sobie mózg, trzymając głowę w piasku.

Potwierdzeni użytkownicy powinni pamiętać, że sytuacja będzie się tylko gwałtownie pogarszać, wraz z pojawianiem się kolejnych badań i coraz większą liczbą osób mówiących o złych skutkach pornografii internetowej. Dziś to niemedyczni ludzie dyskutują o efektach, jutro będzie to na liście badań diagnostycznych twojego lekarza. Minęły już czasy, kiedy użytkownik mógł ukryć "przestój" za stresem związanym z pracą w swoim życiu seksualnym, twój partner będzie pytał, dlaczego siedzisz na laptopie późno w nocy. Biedny użytkownik - już czujący się nieszczęśliwy - teraz chce, aby ziemia się otworzyła i połknęła go.

Dziwne jest to, że wielu ludzi zapłaci dobre pieniądze za członkostwo w siłowni i osobistych trenerów, aby zbudować mięśnie i wyglądać wyrzeźbiony, wiele w ich wyobrażonej (i rzeczywistej) desperacji zwracając się do zabiegów, takich jak zwiększenie testosteronu z wątpliwych i niebezpiecznych skutków ubocznych. Jednak w tej grupie jest wiele osób, które skorzystałyby z zaprzestania praktyki systematycznie niszczącej naturalne systemy relaksacyjne ich mózgu.

Dzieje się tak dlatego, że wciąż myślą wypranym mózgiem użytkownika. Wytrzyj na chwilę piasek z oczu. Internetowe porno to reakcja łańcuchowa i to łańcuch na całe życie i jeśli nie przerwiesz tego łańcucha, to pozostaniesz użytkownikiem do końca życia. Oszacuj, jak myślisz, ile czasu spędzisz na porno przez resztę swojego istnienia, oczywiście ilość będzie różna w zależności od osoby, ale załóżmy, że jest to półtora roku godzin pracy. Wyobraź sobie, że jutro na twoim dywanie leży czek z loterii na półtora roku twojej pensji? Tańczyłbyś z zachwytu, więc zacznij tańczyć! Już niedługo zaczniesz otrzymywać te świadczenia!

Jeśli myślisz, że to pokrętny sposób postrzegania, to jeszcze się ośmieszasz. Rozpracuj, ile czasu byś zaoszczędził, gdybyś nie zerknął na pierwszy rzut oka na samym początku.


Wkrótce podejmiesz decyzję o skorzystaniu z ostatniej sesji (jeszcze nie teraz, pamiętaj o instrukcjach!), pozostając nieużywającym poprzez nie wpadanie ponownie w pułapkę. Wszystko, co musisz zrobić, aby pozostać nieużywającym, to nie używać pornografii i unikać "tylko jednego spojrzenia". Pamiętaj, że jeśli to zrobisz, będzie cię to kosztować tyle, ile szacowałeś, że zyskasz na wynagrodzeniu.

Jeśli doradzasz komuś w sprawie jego uzależnienia od pornografii, powiedz mu, że zna kogoś, kto odrzucił ofertę pracy, która wypłaca mu obecną roczną pensję, a także daje mu cały miesiąc płatnego czasu wolnego. Na pytanie, kto jest tym idiotą, powiedz im: ***"Ty!"*** To niegrzeczne, ale czasami trzeba zdobyć punkt w mniej niż uprzejmy sposób.


