# Zdrowie

Jest to obszar, gdzie pranie mózgu jest największe w przypadku użytkowników - szczególnie młodych i samotnych - którzy myślą, że są świadomi zagrożeń dla zdrowia, ale nie są. Wielu oszukuje się mówiąc, że są gotowi zaakceptować konsekwencje. Jeśli twój router internetowy miał funkcję, która odtwarzała dźwięk alarmu z ostrzeżeniem, gdy trafisz na stronę porno, mówiąc: "Do tej pory uchodziło ci to na sucho, ale jeśli zostaniesz jeszcze minutę, twoja głowa wybuchnie". Czy zostałbyś? Jeśli masz wątpliwości co do odpowiedzi spróbuj podejść do klifu, stanąć na krawędzi z zamkniętymi oczami i wyobrazić sobie, że masz do wyboru albo rzucić porno, albo podejść z zawiązanymi oczami.

Nie ma wątpliwości, jaki byłby twój wybór, ale chowając głowę w piasek i mając nadzieję, że obudzisz się pewnego ranka i nie będziesz chciał już oglądać porno, nic nie osiągniesz. Użytkownicy nie mogą pozwolić sobie na myślenie o zagrożeniach dla zdrowia, jeśli to zrobią iluzoryczna przyjemność uzależnienia ujdzie. To wyjaśnia, dlaczego terapie szokowe są tak nieskuteczne w pierwszych etapach wychodzenia z nałogu, tylko nie-użytkownicy są w stanie zdobyć się na czytanie o destrukcyjnych zmianach w mózgu.


Weźmy na przykład tą częstą rozmowę z użytkownikami, ogólnie tymi młodszymi.

> **Me:** "Dlaczego chcesz przestać?"
>
> **User:** "*Czytałem na blogu mistrza podrywu, że jest dobre zaprzestać przez cztery dni, abym się wzmocnił.*"
>
> **Me:** "Nie obawiasz się zagrożeń dla zdrowia?"
>
> **User:** "*Nie, mógłbym jutro trafić pod autobus.*"
>
> **Me:** "Ale czy byś celowo trafił pod autobus?"
>
> **User:** "*Oczywiście że nie.*"  
>
> **Me:** "Czy przechodząc przez jezdnię nie zadajesz sobie trudu, by spojrzeć w lewo i w prawo?"
>
> **User:** "*Oczywiście że zadaję.*"

Właśnie, zadają sobie wiele trudu, żeby nie wpaść pod autobus, a szanse na to są jak tysiące do jednego. Jednak użytkownik ryzykuje niemal pewność, że zostanie okaleczonym przez swój nałóg i wydaje się być zupełnie nieświadomy. Taka jest siła prania mózgu, porno internetowe to wilk w owczej skórze. Czy to nie dziwne, że gdybyśmy uważali, że samolot ma najmniejszą wadę, nie wsiedlibyśmy do niego - nawet jeśli ryzyko jest miliony do jednego - a jednak w przypadku pornografii mamy pewność większą niż jeden do czterech i najwyraźniej nie zwracamy na to uwagi? Co z tego ma użytkownik? **Absolutnie nic!**

Innym powszechnym mitem jest depresja czy drażliwość. Wiele młodszych osób nie martwi się o swoje zdrowie, bo nie cierpi na żadną depresję czy melancholię. Depresja czy stres nie jest chorobą, tylko objawem. Młodsi ludzie w ogóle nie czują drażliwości czy depresji powstałej dzięki naturalnej zdolności ich organizmu do wytwarzania większej ilości dopaminy. W miarę jak się starzeją lub życie napotyka poważne komplikacje, ich już uszczuplone zasoby są przepracowane i doświadczają pełnych objawów. Kiedy starsi użytkownicy czują się zestresowani, przygnębieni lub rozdrażnieni, to dlatego, że mechanizmy awaryjne natury chronią układ nerwowy przed nadmiernym zalewem dopaminy poprzez przycinanie receptorów. Użytkownik rozwija również inne zmiany neurologiczne, które utrzymują ich w rutynie.

Pomyśl o tym w ten sposób, jeśli miałeś ładny samochód i pozwoliłeś mu zardzewieć, nie robiąc nic z tym, byłoby to dość głupie. Szybko stałby się nieruchomą kupą rdzy, niezdolną do przewiezienia cię gdziekolwiek. Nie byłby to jednak koniec świata, bo to tylko kwestia pieniędzy. Ale twoje ciało jest pojazdem, który niesie cię przez życie. Wszyscy mówimy, że nasze zdrowie jest naszym największym atutem, zapytaj dowolnego chorego milionera. Większość z nas może przypomnieć sobie chorobę lub wypadek w naszym życiu, podczas którego modliliśmy się o wyzdrowienie. Będąc użytkownikiem porno, nie tylko pozwalasz, by rdza dostała się do środka i nic z tym nie robisz, ale systematycznie niszczysz ten jedyny pojazd, który służy ci do przejścia przez całe życie.

Zmądrzej. Nie musisz tego robić, pamiętaj, że to nie robi *absolutnie nic dla ciebie*. Tylko na chwilę wyjmij głowę z piasku i zadaj sobie pytanie, czy gdybyś wiedział z całą pewnością, że twoja następna sesja rozpocznie proces, który sprawi, że zupełnie nie będziesz reagował na kogoś, kogo głęboko kochasz, to czy nadal byś używał? Rozmawiając z ludźmi, którym się to przytrafia, z pewnością nie spodziewali się, że im się to przytrafi, a najgorszą rzeczą nie jest sama choroba, ale świadomość, że sami ją na siebie sprowadzili. Spróbuj sobie wyobrazić, jak czują się ludzie, którzy "nacisnęli guzik", dla nich pranie mózgu się skończyło. Spędzają resztę życia myśląc: "*Dlaczego tak długo oszukiwałem się, że muszę się masturbować do internetowego porno? Gdybym tylko miał szansę się cofnąć!*".

Przestań się oszukiwać, masz taką szansę. To reakcja łańcuchowa, jeśli zaangażujesz się w kolejną sesję porno, doprowadzi cię ona do kolejnej i kolejnej. To już się z tobą dzieje. EasyPeasy nie obiecuje terapii szokowej, więc jeśli już zdecydowałeś, że zamierzasz przestać, poniższe informacje nie będą dla ciebie szokujące. Jeśli nie, pomiń *resztę tego rozdziału* i wróć do niego po przeczytaniu reszty książki.

O szkodach, jakie internetowe porno wyrządza w naszym życiu seksualnym i samopoczuciu psychicznym, napisano już w wielu badaniach. Problem w tym, że do czasu podjęcia decyzji o zaprzestaniu nie chcą wiedzieć. Fora i grupy mentorskie są stratą czasu, ponieważ porno nakłada zasłony na oczy. Jeśli niechcący przeczytają, pierwszą rzeczą, którą robią, jest otwarcie ulubionej stronę Hub. Użytkownicy porno mają tendencję do myślenia o szczęściu, stresie i zagrożeniach związanych z seksem jako o sprawie typu hit-and-miss, jak nadepnięcie na minę lądową.

Wbij sobie to do głowy, to już się dzieje. ***Za każdym razem, gdy otwierasz stronę porno, wyzwalasz zatopienie dopaminą i opioidy zaczynają działać. Neuronowe ślizgi wodne są nasmarowane i jazda prowadzi cię gładko przez kolejne kroki, twój mózg już poddał się scenariuszowi. Układ nerwowy jest teraz zalany dopaminą, a ponieważ to już kolejny raz, receptory dopaminy zamykają się i mały potwór wykorzystuje ten lekki spadek przyjemności w porównaniu z ostatnim razem, aby poprowadzić cię dalej przez czerwoną linię do bardziej szokującego porno lub zachowania, aby uwolnić więcej dopaminy. Więcej nowości, więcej dopaminy i mały potwór mówi ci, żebyś kontynuował. Tak wiele zdjęć i filmów w jednej sesji wyzwala nadnaturalny bodziec, wstrzykując więcej chemikaliów do mózgu i napędzając cię do kontynuacji.

Przez cały czas twoje receptory otrzymują informacje, żeby wyłączyć się w odpowiedzi na zalew. Orgazm tylko zwiększa ten efekt i prowadzi do wycofania. Wypierasz się, ponieważ mały potwór pragnie jego poprawki bez prawdziwego bólu i dyskomfortu. Groźba posiadania zaburzeń erekcji przeraża wielu, dlatego blokują ją ze swojego umysłu i przysłaniają ją strachem przed zatrzymaniem. To nie jest tak, że strach jest większy, ale rzucenie dziś jest natychmiastowe. Po co patrzeć na negatywne strony? Być może to się nie stanie, po związaniu się z rzucić do tego czasu i tak.

Mamy tendencję do myślenia o porno jako przeciąganie liny, po jednej stronie jest strach: "*To niezdrowe, brudne i zniewalające.*". Po drugiej stronie pozytywy: "To moja przyjemność, mój przyjaciel, moja podpora". Wydaje się, że nigdy nie przychodzi nam do głowy, że ta strona to także strach; nie chodzi o to, że lubimy porno, tylko o to, że bez niego jesteśmy zwykle nieszczęśliwi. Uzależnieni od heroiny, pozbawieni jej, przechodzą przez nieszczęście, ale wyobraźcie sobie radość, kiedy wreszcie mogą wbić igłę w żyłę i zakończyć to straszne pragnienie. Spróbujcie sobie wyobrazić, jak ktokolwiek mógłby uwierzyć, że czerpie przyjemność z wbijania podskórnej strzykawki w żyłę. Osoby nieuzależnione od heroiny nie cierpią na to uczucie paniki, a heroina nie łagodzi tego uczucia, tylko je wywołuje.

Nieużywający nie czują się nieszczęśliwi, jeśli nie wolno im korzystać z porno - to tylko użytkownicy cierpią z tego powodu. Internetowe porno nie łagodzi tego uczucia, lecz je wywołuje. Strach przed negatywnymi konsekwencjami nie pomaga użytkownikom w rzuceniu, porównując to uczucie do chodzenia po polu minowym. Jeśli uda ci się uciec, to w porządku, ale jeśli miałeś pecha, to wszedłeś na minę i spotkałeś się z konsekwencjami. Jeśli znałeś ryzyko i byłeś gotów je podjąć, co to miało wspólnego z kimś innym? Uzależnieni w tym stanie zazwyczaj rozwijają następujące taktyki unikania.

"***W końcu będziesz stary i tak stracisz swoją sprawność seksualną...***"  

Oczywiście, że stracisz, ale sprawność seksualna nie ma nic z tym wspólnego -- mówimy tu o niewolnictwie. Nawet jeśli ma to związek z czymś, czy to logiczny powód na celowe odcinanie się?"

"***Jakość życia jest ważniejsza od samego życia.***"  

  Dokładnie! Czy sugerujesz, że jakość życia osoby uzależnionej jest większa niż kogoś, kto nie jest uzależniony? Czy naprawdę wierzysz, że jakość życia osoby uzależnionej jest lepsza niż osoby nieuzależnionej. Życie spędzone na chowaniu głowy w piasek i byciu nieszczęśliwym nie brzmi jak przyjemne.

"***Jestem singlem i nie planuje ustatkować się w przyszłości, więc czemu nie?***"

Nawet gdyby to była prawda, czy jest to logiczny powód do zabawy z neurologicznymi mechanizmami kontroli impulsów? Czy można sobie wyobrazić, że ktoś jest na tyle głupi, by rozbierać się do naga, gdy tylko jest sam, niezależnie od tego, jak bardzo jest pewien, że nikogo się nie spodziewa? **To właśnie robią skutecznie użytkownicy porno!**

Postępujące zżeranie naszych obwodów nagrody nadmierną stymulacją i czynienie ich niezdolnymi do radzenia sobie z normalnymi stresami życiowymi nie pomaga w cieszeniu się życiem z entuzjazmem i wigorem. Porno i masturbacja zastąpiły naturalny apetyt seksualny, jak tabliczka czekolady zastępująca prawdziwe jedzenie. Nic dziwnego, że wielu lekarzy i psychologów wiąże teraz różne problemy ze zdrowiem psychicznym z przyczynami fizjologicznymi. Społeczność medyczna głównego nurtu twierdzi, że porno nigdy nie zostało naukowo udowodnione jako bezpośrednia przyczyna problemów zgłaszanych przez osoby przyznające się do winy, ale publiczne przyznanie się do swojej seksualnej niezdolności jest tak wstydliwym wydarzeniem, że dlaczego ktokolwiek miałby to robić, jeśli nie był naprawdę przejęty - znalazłszy przyczynę i wyeliminowawszy ją z własnego życia?

EasyPeasy pomoże ci pozbyć się porno i stać się szczęśliwym byłym użytkownikiem. Żadnego porno, masturbacji wspomaganej porno czy niepotrzebnych orgazmów. Jedyną pomocą będzie dotyk, zapach i aromat Twojego partnera. Jak chleb pełnoziarnisty po dobrze rozwiniętym apetycie, nie będziesz już chciał wysokofruktozowego syropu kukurydzianego z internetowego porno. Dowody tak przytłaczające, że nie trzeba ich udowadniać; kiedy walę młotkiem w kciuk, to boli, nie trzeba tego udowadniać. Stres związany z pornografią internetową ma wpływ na inne aspekty życia użytkowników, predysponując wielu do zwrócenia się do narkotyków, takich jak papierosy i alkohol, aby sobie poradzić, w niektórych przypadkach nawet zwracając gospodarza do rozważenia samobójstwa.

Użytkownicy cierpią również złudzenia, że złe skutki porno są przesadzone. Jest odwrotnie, nie ma wątpliwości, że porno internetowe jest główną przyczyną dysfunkcji seksualnych i wielu innych problemów. Ile rozwodów zostało spowodowanych przez porno? Nie ma wiarygodnych sposobów, aby to wiedzieć, ale wyszukiwania społeczności internetowych sugerują, że liczba ta rośnie gwałtownie.

Jest taki odcinek *Przyjaciół*, w którym faceci, którzy otrzymywali ciągłe darmowe porno w telewizji, zaczęli się zastanawiać, dlaczego dziewczyna dostarczająca pizzę nie poprosiła o sprawdzenie ich "wielkiej sypialni". Kiedy jesteś uzależniony, nieodmiennie rzutujesz fantazje porno na prawdziwe kobiety. Wyobraź sobie, co nieostrożna lub nawet przypadkowy kontakt z porno na ciemnych stronach internetu może zrobić z kimś, kto już jest w punkcie krytycznym swojego życia. Walka z tymi wywołanymi przez porno myślami będzie poważnym obciążeniem dla ich zdrowia psychicznego.

Oto kolejny eksperyment myślowy, powiedzmy, że ktoś przychodzi do ciebie i mówi, że niekoniecznie chce orgazmu, ale bardzo chce się kochać, nawet penetracyjnie. Chcą to robić tak długo i tak daleko, jak tylko można bez orgazmu -- ale jeśli się zdarzy, to w porządku. Zapewniam Cię o fenomenalnym nowym doświadczeniu seksualnym znacznie lepszym niż jakiekolwiek inne, jeśli nawet dostaniesz taką propozycję. Spróbuj.

Efekty prania mózgu sprawiają, że mamy tendencję do myślenia jak człowiek, który po upadku ze 100-piętrowego budynku, cytuje się, że powiedział, gdy przeleciał obok pięćdziesiątego piętra, "*Jak na razie dobrze!". Myślimy, że skoro do tej pory nam się udawało, to jeszcze jedna sesja porno nie zrobi różnicy. Zobacz to w inny sposób, "nawyk" jest ciągłym łańcuchem na całe życie, z każdą sesją tworzącą potrzebę następnej. Kiedy zaczynasz nawyk, zapalasz lont. Problem w tym, że nie wiesz, jak długi jest lont. Za każdym razem, gdy poddajesz się sesji porno, jesteś o krok bliżej do wybuchu bomby. *SKĄD BĘDZIESZ WIEDZIAŁ, CZY TO JUŻ NASTĘPNA?

## Złowieszcze czarne cienie 

Użytkownikom bardzo trudno jest uwierzyć, że porno rzeczywiście powoduje te niepewne uczucia, kiedy wychodzisz późno w nocy po kłótliwym dniu w domu lub pracy. Nieużywający nie cierpią na to uczucie, to porno je wywołuje.

Inną wielką radością z odstawienia porno jest wolność od złowrogich czarnych cieni z tyłu naszych umysłów. Wszyscy użytkownicy wiedzą, że są głupcami zamykając się przed złymi skutkami pornografii. Przez większość naszego życia jest to automatyczne, ale czarne cienie zawsze czają się w naszych podświadomych umysłach, tuż pod powierzchnią. Kilka z cudownych korzyści płynących z odstawienia pornografii jest świadomych, jak na przykład strata czasu i czysta głupota kochania się z dwuwymiarowym obrazem.

Ostatnie rozdziały zajmowały się znacznymi zaletami bycia nieużytkownikiem, ale w interesie uczciwości konieczne jest przedstawienie zrównoważonego rachunku. Dlatego na następnej stronie wymienione są zalety bycia użytkownikiem.

# Zalety bycia użytkownikiem porno


