# Metoda siły woli

Jest to fakt akceptowany w społeczeństwie, że bardzo trudno jest przestać używać pornografię. Książki i fora doradzające, jak przestać, zwykle zaczynają się od tego, jak bardzo jest to trudne. Prawda jest taka, że jest to śmiesznie łatwe. Zrozumiałe jest kwestionowanie tego stwierdzenia, ale najpierw po prostu się nad tym zastanów. Jeśli twoim celem jest przebiegnięcie mili w cztery minuty, to *to* jest trudne i będziesz musiał przejść lata ciężkich treningów, a nawet wtedy być może będziesz fizycznie niezdolny.

Jednak wszystko, co musisz zrobić, aby zaprzestać oglądania porno, to nie oglądać go i/lub nie masturbować się więcej. Nikt nie zmusza cię do masturbacji (poza tobą samym) i w przeciwieństwie do jedzenia czy wody, nie jest ona potrzebna do przeżycia. Więc jeśli chcesz przestać to robić, dlaczego miałoby to być trudne? W rzeczywistości nie jest. To użytkownicy utrudniają to sobie poprzez stosowanie siły woli lub jakiejkolwiek metody, która zmusza użytkownika do poczucia, że dokonuje jakiegoś poświęcenia. Zastanówmy się nad tymi metodami.

Nie decydujemy się na zostanie użytkownikami, jedynie eksperymentujemy z magazynami porno lub stronami internetowymi, a ponieważ są one okropne (tak jest, okropne), poza naszym pożądanym klipem, jesteśmy przekonani, że możemy przestać, kiedy tylko zechcemy. Na początku oglądamy te kilka pierwszych klipów, kiedy chcemy i przy specjalnych okazjach. Zanim się zorientujemy, nie tylko odwiedzamy te strony regularnie i masturbujemy się, kiedy chcemy - masturbujemy się do nich codziennie. Porno stało się częścią naszego życia, zapewniając, że potrzebujemy połączenia z internetem gdziekolwiek się udajemy. Wierzymy wtedy, że jesteśmy upoważnieni do miłości, seksu, orgazmu i łagodzących stres właściwości porno. Nie przychodzi nam do głowy, że te same klipy i aktorzy nie zapewniają nam tego samego stopnia pobudzenia i zaczynamy walczyć z czerwoną linią, aby uniknąć "złego porno". W rzeczywistości masturbacja i internetowe porno ani nie poprawiają naszego życia seksualnego, ani nie zmniejszają stresu, jedynie użytkownicy wierzą, że bez orgazmu nie mogą cieszyć się życiem ani radzić sobie ze stresem.


Zwykle długo zajmuje nam uświadomienie sobie, że jesteśmy uzależnieni, ponieważ cierpimy na złudzenie, że użytkownicy oglądają porno, ponieważ czerpią z tego przyjemność - a nie dlatego, że ***potrzebują*** tego. Kiedy nie "cieszymy się" porno, co nigdy nie może się zdarzyć, chyba że dodana zostanie nowość, szok lub eskalacja, mamy złudzenie, że możemy przestać w każdej chwili. To jest pułapka pewności siebie, "*nie lubię porno, więc mogę przestać, kiedy chcę*". Tylko że nigdy nie wydaje się, że "chcemy" przestać.

Pierwsze próby są zazwyczaj wczesne - wywołane spotkaniem z partnerem i zauważeniem, że nie jest on "wystarczający" po pierwszych randkach. Innym częstym powodem jest zauważenie skutków zdrowotnych obecnych w codziennym życiu.

Niezależnie od przyczyny, użytkownik zawsze poczeka na stresującą sytuację, czy to zdrowotną, czy seksualną. Gdy tylko przestają, mały potwór zaczyna być głodny. Użytkownik pragnie wtedy czegoś, co napompuje jego dopaminę, np. papierosów, alkoholu lub ich ulubionego - internetowego porno - z ich haremem oddalonym tylko o kliknięcie. Schowek na porno nie znajduje się już w piwnicy, jest wirtualny i dostępny z każdego miejsca. Jeśli ich partner jest w pobliżu lub są z przyjaciółmi, nie mają już dostępu do swojego wirtualnego haremu, co sprawia, że są jeszcze bardziej przygnębieni.

Jeśli użytkownik zetknął się z materiałami naukowymi lub społecznościami internetowymi, będzie toczył ciągnięcie liny w swoim umyśle, opierając się pokusom i czując się pozbawionym. Ich sposób na zwykle rozładowanie stresu jest teraz niedostępny, doznając potrójnego ciosu. Prawdopodobnym rezultatem po tym okresie tortur jest kompromis - "*ograniczę się*" lub "*wybrałem zły czas*", a może "*poczekam aż stres zniknie z mojego życia*". Jednakże, gdy stres minie, nie ma powodu, by przestać i użytkownik nie decyduje się na ponowne rzucenie palenia aż do następnego stresującego momentu.


Oczywiście nigdy nie ma odpowiedniego momentu, ponieważ życie dla większości ludzi staje się bardziej stresujące. Wychodzimy spod opieki naszych rodziców, wchodzimy w świat zakładania domu, brania kredytów hipotecznych, posiadania dzieci i bardziej odpowiedzialnej pracy. Tak czy siak - życie użytkownika nie może stać się mniej stresujące, ponieważ porno w rzeczywistości powoduje stres. Im szybciej użytkownik przechodzi do etapu eskalacji, tym bardziej jest zestresowany i tym bardziej rośnie jego uzależnienie od iluzji.

W rzeczywistości jest to iluzja, że życie staje się bardziej stresujące, a porno - lub podobna kula - tworzy tę iluzję. Zostanie to omówione bardziej szczegółowo później, ale po tych początkowych niepowodzeniach użytkownik zwykle polega na możliwości, że pewnego dnia obudzi się i po prostu nie będzie chciał się masturbować lub używać porno, itp. Tę nadzieję rozpalają zwykle historie zasłyszane od innych byłych użytkowników, "*Nie byłem poważny, dopóki nie miałem zanikającej penetracji, wtedy nie chciałem już używać porno i przestałem się masturbować".

Nie oszukuj się, sonduj te plotki, a odkryjesz, że nigdy nie są tak proste, jak się wydaje. Zazwyczaj użytkownik już przygotowywał się do zatrzymania i jedynie wykorzystał incydent jako odskocznię. Częściej w przypadku ludzi, którzy zatrzymują się "tak po prostu", doznali szoku; być może odkrycie przez ich partnera, incydent samodostrzegania dostępu do porno, że nie ich normalnej orientacji seksualnej lub mieli dysfunkcji seksualnej przestraszyć się. "*To jest po prostu rodzaj osoby, którą jestem.*" Przestań się oszukiwać. To się nie stanie, jeśli nie sprawisz, że to się stanie.

Rozważmy bardziej szczegółowo, dlaczego metoda siły woli jest tak ciężka. Przez większość naszego życia przyjmujemy podejście "głowa w piasek", "*Jutro przestanę*". W dziwnych momentach coś wywoła próbę zaprzestania. Mogą to być obawy o zdrowie, męskość lub analiza samego siebie i uświadomienie sobie, że tak naprawdę nie sprawia nam to przyjemności. Niezależnie od przyczyny, zaczynamy rozważać plusy i minusy porno. Seks dzieli się na tantryczny (dotyk, zapach, głos) i propagacyjny (orgazm); jest to jeden z głównych kluczy do otwarcia naszego umysłu, bez tego ważnego rozróżnienia będzie zamieszanie, które prowadzi do porażki. Na racjonalnej ocenie dowiadujemy się tego, co wiedzieliśmy przez całe życie, wniosek jest po tysiąckroć powtarzany "***PRZESTAŃ TO OGLĄDAĆ!***".

Gdybyś usiadł i przyznał punkty zaletom zatrzymania się i porównał je z zaletami porno, to łączna liczba punktów za zatrzymaniem się znacznie przewyższyłaby wszelkie "wady". Jeśli zastosujesz zakład Pascala , to rzucając pornografię nie tracisz prawie nic, mając wysokie szanse na zyski i *nie* wyższe na straty. Chociaż użytkownik wie, że będzie mu lepiej jako osobie nie korzystającej z usług, przekonanie o tym, że się poświęca, działa na niego jak płachta na byka. Chociaż to iluzja, jest potężna. Nie wiedzą dlaczego, ale użytkownik ma przekonanie, że podczas dobrych i złych chwil w życiu, sesje wydają się pomagać. Nawet przed rozpoczęciem próby, społeczne pranie mózgu wzmocnione dodatkowo przez pranie mózgu z ich własnego uzależnienia jest następnie połączone z jeszcze potężniejszym praniem mózgu o tym, jak trudno jest "zrezygnować".

Słysząc historie tych, którzy zatrzymali się na wiele miesięcy i nadal desperacko pragną i rachunki niezadowolonych rzucających, po zatrzymaniu i spędzając resztę swojego życia opłakiwaniu faktu, że chcieliby mieć sesję. Opowieści o użytkownikach zatrzymujących się na wiele miesięcy lub lat, żyjących szczęśliwie tylko po to, aby mieć jedno "zerknięcie" na porno i nagle są ponownie zaczepione. Prawdopodobnie znają kilka osób w zaawansowanym stadium choroby, widocznie niszczących się i wyraźnie nie cieszących się życiem - a jednak nadal używają. Dodatkowo, prawdopodobnie sami doświadczyli jednego lub więcej takich doświadczeń.

Zamiast więc zaczynać od uczucia: "*Świetnie! Słyszałeś nowinę? Nie muszę już oglądać porno!", zamiast tego zaczynają z uczuciem zagłady i przygnębienia - jak przy próbie zdobycia Everestu - i fałszywie stwierdzają, że jak już ten mały potwór wczepi się w ciebie, to jesteś uzależniony na całe życie. Wielu użytkowników rozpoczyna próbę od przeproszenia swoich dziewczyn lub żon: "*Patrzcie, próbuję zrezygnować z porno. Prawdopodobnie będę drażliwy przez następne kilka tygodni, spróbuj ze mną wytrzymać.*". Większość prób jest skazana na zagładę jeszcze przed ich rozpoczęciem.

Załóżmy, że użytkownik przetrwał kilka dni bez sesji, odzyskuje podniecenie i zaczyna dochodzić do siebie. Nie otworzyli swoich ulubionych stron Hub i w konsekwencji podniecają się normalnymi używkami, na które wcześniej odpłynęli. Powody, dla których zdecydowali się przestać w pierwszej kolejności, szybko znikają z ich myśli, tak jak zobaczenie złego wypadku drogowego podczas jazdy samochodem. Spowolnienie na chwilę, ale tupanie nogą na przepustnicy następnym razem jesteś późno na spotkanie.

Po drugiej stronie wojny jest mały potwór, który wciąż nie ma swojej poprawki. Nie ma fizycznego bólu - gdybyś miał to samo uczucie z powodu przeziębienia, nie przestałbyś pracować ani nie wpadłbyś w depresję, tylko wyśmiałbyś to. Wszystko, co użytkownik wie, to że chce odwiedzić swój harem. Mały potwór wie o tym i uruchamia wielkiego potwora piorącego mózgi, powodując, że ta sama osoba, która kilka godzin lub dni wcześniej wymieniła wszystkie powody, aby przestać, teraz desperacko szuka każdej wymówki, aby zacząć ponownie. Zaczynają mówić takie rzeczy jak:

-   "*Życie jest zbyt krótkie, może wybuchnąć bomba, mogę jutro wejść pod autobus. Zostawiłem to za późno. Mówią, że wszystko daje uzależnienie w dzisiejszych czasach.*"

-   "*Wybrałem nie tą porę.*"

- "*Powinienem był poczekać do świąt, po moich wakacjach/testach, po tym stresującym wydarzeniu w moim życiu.*"

- "*Nie mogę się skoncentrować, robię się drażliwy i źle usposobiony, nie mogę nawet prawidłowo wykonywać swojej pracy.*"

- "*Moja rodzina i przyjaciele nie będą mnie kochać. Spójrzmy prawdzie w oczy, dla dobra wszystkich muszę zacząć od nowa. Jestem potwierdzonym uzależnionym od seksu i nie ma mowy, że kiedykolwiek będę znów szczęśliwa bez orgazmu.*"

- "*Nikt nie może przetrwać bez seksu.*" (Pranie mózgu przez dobrze myślących ludzi, którzy nie biorą pod uwagę rozróżnienia między tantryczną i propagacyjną częścią seksu).

- "*Wiedziałem, że to się stanie, mój mózg jest 'uwrażliwiony' przez DeltaFosB z powodu zmian dotkniętych skokami dopaminy z powodu mojego przeszłego nadmiernego używania pornografii. Uczulenia nie można 'nigdy' usunąć z mózgu.*"

Na tym etapie użytkownik zwykle się poddaje. Odpalając przeglądarkę, wzrasta schizofrenia. Z jednej strony jest ogromna ulga związana z zakończeniem głodu, ponieważ mały potwór w końcu dostaje swoją poprawkę; z drugiej strony orgazm jest okropny i użytkownik nie może zrozumieć, dlaczego to robi. To dlatego użytkownik myśli, że brakuje mu siły woli. W rzeczywistości nie jest to brak siły woli, wszystko, co zrobili, to zmiana zdania i podjęcie całkowicie racjonalnej decyzji w świetle najnowszych informacji.

"*Jaki jest sens bycia zdrowym lub bogatym, jeśli jesteś nieszczęśliwy?"

Absolutnie żaden! O wiele lepiej mieć krótsze przyjemne życie niż długie nieszczęśliwe. Na szczęście dla nieużytkownika jest to nieprawda, ponieważ życie jest nieskończenie przyjemniejsze. Nieszczęście, które na nie cierpi użytkownik, nie wynika z odstawienia narkotyków - choć początkowo jest przez nie wywoływane - rzeczywista agonia to walka w umyśle spowodowana przez wątpliwości i niepewność. Ponieważ użytkownik zaczyna od poczucia, że się poświęca, zaczyna się czuć pozbawiony, co jest formą stresu.

Jednym z takich stresujących momentów jest ten, w którym mózg mówi im, żeby "zerknęli"; chcą się cofnąć, gdy tylko się zatrzymają. Ale ponieważ przestali, nie mogą tego zrobić, a to sprawia, że są jeszcze bardziej przygnębieni i ponownie uruchamiają spust. Kolejnym czynnikiem utrudniającym rzucenie jest oczekiwanie na to, że coś się wydarzy. Jeżeli twoim celem jest zdanie egzaminu na prawo jazdy, to po jego zdaniu jest pewne, że osiągnąłeś swój cel. W ramach metody siły woli wewnętrzna narracja brzmi - "*Jeśli uda mi się wystarczająco długo wytrzymać bez internetowego porno, to chęć jego oglądania w końcu minie.*". Można to zobaczyć w praktyce na forach internetowych, gdzie uzależnieni opowiadają o swoich seriach lub dniach abstynencji.

Jak powiedziano wyżej, agonia, którą przechodzi użytkownik, jest psychiczna i spowodowana niepewnością. Mimo że nie ma bólu fizycznego, to i tak ma potężne skutki. Teraz nieszczęśliwy i niepewny, użytkownik jest daleki od zapomnienia, teraz pełen wątpliwości i obaw.

-   "*Jak długo to pragnienie będzie trwało?*"

-   "*Czy kiedyś znów będę szczęśliwy?*"

-   "*Czy kiedykolwiek będę chciał nawet wstawać rano z łóżka?*"

-   "*Jak będę mógł sobie radzić ze stresem w przyszłości?*"

Użytkownik czeka na poprawę sytuacji, ale podczas gdy oni wciąż opłakują, "harem" staje się coraz cenniejsze. W rzeczywistości coś się dzieje, ale podświadomie, jeśli uda im się przetrwać tygodnie bez otwierania przeglądarki, pragnienie małego potwora znika. Jednak, jak stwierdzono wcześniej, objawy odstawienia dopaminy i opioidów są tak łagodne, że użytkownik nawet nie jest ich świadomy. W tym czasie, wielu użytkowników czuje, że "kopnęli go" i tak zerkają, aby to udowodnić, wysyłając je z powrotem w dół zjeżdżalni wody. Po dostarczeniu dopaminy do organizmu, jest teraz mały głos z tyłu ich umysłu mówiący "*Chcesz jeszcze jednego.*" W rzeczywistości, oni kopnęli to, ale zaczepili się ponownie.

Jako dziecko oglądałeś kreskówki i zgodnie z neuronauką tworzyłeś dla nich ścieżki neuronowe (DeltaFosB). Gdybyś chciał zniechęcić dziecko do oglądania, zabrałbyś, czy te ścieżki nadal istnieją i przeprowadziłbyś ankietę wśród dorosłych na temat tego, dlaczego nie lubią już oglądać swoich ulubionych kreskówek z dzieciństwa. Po pierwsze, dostępna jest lepsza rozrywka, a po drugie, kreskówki po prostu nie mają w sobie tej magii. W przypadku metody siły woli po prostu odmawiasz dziecku kreskówki, ale w przypadku EasyPeasy upewniasz się, że nie widzi ono w niej żadnej wartości. Co jest lepsze?

Użytkownik zazwyczaj nie wchodzi od razu w kolejną sesję, myśląc "*Nie chcę się znowu uzależnić!*" i pozwala, by minął bezpieczny okres godzin, dni, a nawet tygodni. Były użytkownik może wtedy powiedzieć: "*Cóż, nie dałem się zaczepić, więc mogę bezpiecznie odbyć kolejną sesję.*". Wpadli z powrotem w tę samą pułapkę, co przy pierwszym uruchomieniu i są już na śliskim stoku.

Użytkownicy, którzy odnoszą sukcesy stosując metodę siły woli, zazwyczaj uważają, że jest to długie i trudne, ponieważ podstawowym problemem jest pranie mózgu. Długo po tym, jak fizyczne uzależnienie umarło, użytkownik wciąż marudzi i jest nieszczęśliwy. W końcu, po przeżyciu tej długotrwałej tortury, zaczyna im świtać, że nie zamierzają się poddać, przestają się mazać i akceptują, że życie toczy się dalej i jest przyjemne bez porno. Jest znacznie więcej porażek niż sukcesów, tym, którym się udało, przechodzą przez swoje życie w stanach zagrożenia, pozostawieni z pewną dozą prania mózgu, które mówi im, że porno faktycznie daje im impuls. To wyjaśnia, dlaczego wielu użytkowników, którzy zatrzymali się na długi okres, kończy się na ponownym rozpoczęciu później.

Wielu byłych użytkowników będzie miało okazjonalną sesję jako "specjalną ucztę" lub aby przekonać się, jak silna jest ich samokontrola. Tak właśnie jest - ale jak tylko ich sesja się skończy, dopamina zaczyna się ulatniać i mały głosik z tyłu głowy zaczyna ich skłaniać do kolejnej. Jeśli zdecydują się wziąć udział, wydaje się, że nadal są pod kontrolą, nie ma szoków, eskalacji ani poszukiwania nowości, więc mówią - "*Cudownie! Chociaż nie bardzo mi się to podoba, nie dam się wciągnąć. Po świętach / tym urlopie / tej traumie, przestanę.*" Mało kto wie, że wodne ślizgi ich mózgu zostały nasmarowane jeszcze bardziej.

Za późno, już są na haczyk! Pułapka, z której zdołali się wydostać, znów upomniała się o swoją ofiarę.

Jak powiedziano wcześniej, przyjemność nie wchodzi w grę. Nigdy nie było! Gdybyśmy oglądali z powodu przyjemności, nikt nie pozostałby na stronach z rurkami dłużej niż potrzeba, aby zakończyć czyn. Niezależnie od tego, lepszym sposobem na samozadowolenie są wspomnienia. Zakładamy, że lubimy internetowe porno tylko dlatego, że nie możemy uwierzyć, że bylibyśmy na tyle głupi, by się uzależnić, gdybyśmy nie czerpali z tego przyjemności. Większość użytkowników nie ma pojęcia o bodźcach ponadnormatywnych, poszukiwaniu nowości czy szoku i nawet po przeczytaniu o nich nie wierzy, że ich używanie jest motywowane przez ewolucyjne okablowanie obwodu nagrody. Dlatego tak wiele porno jest podświadome, gdybyś był świadomy zmian neurologicznych i musiał uzasadnić, że kosztuje cię to w przyszłości, nawet iluzja przyjemności by zniknęła.

Gdy próbujemy zablokować umysł na złe strony, czujemy się głupio. Gdybyśmy musieli się z tym zmierzyć, byłoby to nie do zniesienia! Jeśli obserwujesz użytkownika w akcji, zobaczysz, że są szczęśliwi tylko wtedy, gdy są nieświadomi, że używają. Kiedy są świadomi, zwykle czują się nieswojo i przepraszają. Porno karmi małego potwora, więc po oczyszczeniu go z ciała wraz z praniem mózgu (duży potwór), nie będziesz miał ani potrzeby, ani ochoty na oglądanie!


