# Uważaj przed zmniejszaniem 

Wielu użytkowników ucieka się do zmniejszania jako kroku w kierunku zatrzymania, lub jako próba kontrolowania małego potwora. Wielu zaleca redukcję lub "dietę pornograficzną" jako środek podnoszący na duchu. Korzystanie z redukcji jako krok do zatrzymania jest ***fatalne.*** To te próby cięcia w dół, które trzymają nas w pułapce na resztę naszego życia. Ogólnie rzecz biorąc, cięcie w dół następuje po nieudanych próbach zatrzymania. Po kilku godzinach lub dniach abstynencji użytkownik mówi coś w rodzaju:

"*Nie mogę zmierzyć się z myślą o pójściu spać bez odwiedzenia mojego internetowego haremu, więc od teraz będę używać porno tylko raz na cztery dni lub oczyszczać moją kolekcję 'złego porno'. Jeśli uda mi się przestrzegać tej porno diety, będę mógł ją tam utrzymać albo jeszcze bardziej ograniczyć.*"
 
 
Pewne straszne rzeczy teraz się dzieją:

1.  Tkwią w najgorszym ze wszystkich światów, wciąż uzależnieni od internetowego porno i utrzymujący potwora przy życiu nie tylko w swoim ciele, ale i w umyśle.

2.  Życzenie sobie życia w oczekiwaniu na kolejną sesję.

3.  Przed obcięciem, kiedy tylko chcieli odwiedzić swój harem, odpalali swoją przeglądarkę i przynajmniej częściowo złagodzili swoje napady odstawienia. Teraz oprócz normalnych stresów życia, powodują się cierpią na napady odstawienia przez większość ich życia, co czyni ich jeszcze bardziej nieszczęśliwymi i w bardziej złym nastroju.

4.  Podczas rozpieszczania się, ani nie cieszyli się większością sesji, ani nie zdawali sobie sprawy, że używają nadprzyrodzonych bodźców. To było automatyczne, jedyna wizyta w haremie, którą cieszyli się była jedna po okresie abstynencji.
Teraz, kiedy czekają dodatkową godzinę na każdą wizytę w haremie, "cieszą się" każdą z nich. Im dłużej czekają, tym bardziej 'przyjemna' wydaje się być każda sesja, ponieważ 'przyjemność' w sesji nie jest sama sesja - jest to zakończenie wzburzenia spowodowanego przez pragnienie - czy to lekkie fizyczne pragnienie, czy mentalne przygnębienie. Im dłuższe cierpienie, tym bardziej 'przyjemna' staje się każda sesja.

Podstawową trudnością w odstawieniu nie jest neurologiczne uzależnienie, które jest łatwe. Użytkownicy przestają bez problemu przy różnych okazjach - śmierć bliskiej osoby, sprawy rodzinne lub zawodowe, itp. Pójdą powiedzmy dziesięć dni bez dostępu i nie będzie im to przeszkadzać. Ale gdyby przeszli te same dziesięć dni, kiedy mogliby mieć dostęp do porno, wyrywali by sobie włosy z głowy.


Wielu użytkowników dostanie szansę w ciągu dnia pracy i wstrzyma się od głosu, przejdzie przez Victoria's Secret, baseny i tak dalej bez zbędnych utrudnień. Wielu powstrzyma się, jeśli będą musieli tymczasowo spać na kanapie, aby zrobić miejsce dla gościa, lub sami będą odwiedzać. Nawet w barach Go-Go czy na plażach nudystów nie doszło do zamieszek. Użytkownicy są niemal zadowoleni, że ktoś lub coś mówi im, że nie mogą oglądać porno. W rzeczywistości użytkownicy, którzy chcą rzucić, czerpią tajemniczą przyjemność z przechodzenia przez długie okresy bez wizyt w haremie, co daje im nadzieję, że być może pewnego dnia nigdy nie będą tego chcieli.

Prawdziwym problemem przy rzucaniu jest pranie mózgu, iluzja uprawnienia, że porno internetowe jest jakimś rekwizytem lub nagrodą i życie nigdy nie będzie takie samo bez niego. Daleko od wyłączenia porno, wszystko, co zmniejszenie osiąga jest pozostawiając uczucie niepewności i nieszczęścia, przekonując, że najcenniejszą rzeczą na tej ziemi jest nowy klip, który przegapiłeś, że nie ma sposobu, że będziesz szczęśliwy ponownie bez oglądania go.

Nie ma nic bardziej żałosnego niż użytkownik, który próbował się ograniczyć. Cierpiący na złudzenie, że im mniej oglądają porno, tym mniej będą chcieli odwiedzać internetowe haremy. W rzeczywistości jest odwrotnie, im mniej oglądają porno, tym dłużej cierpią na napady odstawienia i tym bardziej "cieszą się" z ulgi, jaką przynosi im odstawienie. Zauważą jednak, że ich ulubiony gatunek nie trafia w sedno. Ale to ich nie powstrzyma, jeśli strony Hub byłyby poświęcone tylko jednej gwieździe lub gatunkowi, żaden użytkownik nigdy nie poszedłby więcej niż raz.

Trudne do uwierzenia? Jaki jest najgorszy moment samokontroli, który się odczuwa? Czekanie przez cztery dni, a potem przeżywanie kulminacji. W takim razie, jaki jest najcenniejszy moment dla większości użytkowników na czterodniowej diecie porno? Tak jest, ta sama kulminacja po odczekaniu czterech dni! Czy naprawdę wierzysz, że masturbujesz się, aby cieszyć się orgazmem, czy bardziej racjonalne wyjaśnienie, że potrzebujesz złagodzić napady odstawienia pod wpływem iluzji, że masz do tego prawo?

Usunięcie prania mózgu jest niezbędne, aby usunąć złudzenia dotyczące porno, zanim zgasisz tę ostatnią sesję. Jeśli nie usunąłeś iluzji, że sprawia ci to przyjemność, zanim zamkniesz to okienko, nie ma sposobu, byś mógł to potem udowodnić, nie wpadając ponownie w sidła. Kiedy najeżdżasz na zakładki i zapisane zdjęcia, zadaj sobie pytanie, gdzie jest chwała w tym działaniu. Być może uważasz, że tylko niektóre klipy są w dobrym guście, np. te o zwyczajowej lub ulubionej tematyce. Jeśli tak, to po co męczyć się z oglądaniem innych filmików czy tematów? Bo weszło Ci to w nawyk? Dlaczego ktoś miałby nawykowo zaśmiecać swój mózg i się marnować? Po miesiącu nic nie jest inne, dlaczego klip porno miałby być inny?

Możesz to sprawdzić sam, znajdź ten gorący klip z zeszłego miesiąca, żeby udowodnić, że jest inny. Następnie ustaw sobie przypomnienie i obejrzyj ten sam klip po miesiącu bez porno. Będzie on trafiał (prawie) w te same miejsca co w zeszłym miesiącu. Ten sam klip będzie inny po spotkaniu towarzyskim, na którym zostałeś odrzucony lub przetestowany przez potencjalnego partnera. Powód - uzależniony nigdy nie może być w pełni szczęśliwy, jeśli ten mały potwór pozostaje niezaspokojony.

Gdzie w tym wszystkim jest satysfakcja? Po prostu są nieszczęśliwi, jeśli nie mogą złagodzić objawów odstawienia. Różnica między oglądaniem porno a nie, to różnica między byciem szczęśliwym a nieszczęśliwym. Dlatego właśnie porno internetowe wydaje się być lepsze. Natomiast użytkownicy, którzy wchodzą na swoje strony z samego rana dla porno, są nieszczęśliwi niezależnie od tego, czy je oglądają, czy nie.

Zmniejszanie nie tylko nie działa, ale jest najgorszą formą tortury. Nie działa, bo początkowo użytkownik ma nadzieję, że wpadając w nawyk coraz mniej, zmniejszy swoją chęć oglądania porno. To nie jest nawyk, to jest uzależnienie. Naturą każdego uzależnienia jest pragnienie więcej i więcej, a nie mniej i mniej. Dlatego, aby ograniczyć, użytkownik musi ćwiczyć siłę woli i dyscyplinę przez resztę życia. Tak więc, zmniejszenie oznacza siłę woli i dyscyplinę na zawsze. Zatrzymanie się jest o wiele łatwiejsze i mniej bolesne, istnieją dosłownie dziesiątki tysięcy przypadków, w których redukcja nie powiodła się.

Problemem zatrzymania nie jest uzależnienie od dopaminy, z którym łatwo sobie poradzić. To błędne przekonanie, że porno daje przyjemność, wywołane początkowo przez pranie mózgu otrzymane zanim zaczęliśmy używać, a następnie wzmocnione przez rzeczywiste uzależnienie. Wszystko, co robi redukcja, to dalsze wzmacnianie tego błędnego przekonania, do tego stopnia, że porno całkowicie zdominuje ich życie i przekona ich, że najcenniejszą rzeczą na ziemi jest ich uzależnienie.

Garść przypadków, które odniosły sukces, zostały osiągnięte przez stosunkowo krótki okres redukcji, po którym nastąpiło rzucenie z dnia na dzień. Ci użytkownicy przestali pomimo redukcji, a nie dzięki niej. Wszystko to przedłużało agonię, nieudane próby pozostawiały użytkowników nerwowymi wrakami i jeszcze bardziej przekonanymi, że są uzależnieni na całe życie. To zwykle wystarcza, aby utrzymać ich powrót do ich online harem dla przyjemności i podpory, lub inny odcinek przed następną próbą.

Redukcja pomaga jednak zobrazować bezsensowność porno, jasno ilustrując, że wizyty w haremie nie są przyjemne po okresach abstynencji. Trzeba walić głową w mur (cierpieć przez napady odstawienia), żeby było miło po zatrzymaniu. W związku z tym, wybory są takie:

1.  Zmniejszanie przez życie i cierpienie na nałożoną samemu sobie torturę, z którą i tak nie dałbyś rady.

2.  Zwiększanie torturowania samego siebie, co jest bezsensu.

3.  Bycie dla siebie miłym i całkowicie odciąć się od pornografii.

Innym aspektem, który pokazuje redukcja jest to, że nie ma czegoś takiego jak dziwna lub okazjonalna wizyta w haremie. Internetowe porno to reakcja łańcuchowa, która będzie trwała przez resztę twojego życia, chyba że podejmiesz pozytywny wysiłek, aby ją przerwać.

**Pamiętajcie: Zmniejszanie, w dół ciebie pociągnie**


