# Tylko jedno zerknięcie

"Tylko jedno zerknięcie" jest mitem, który musisz się pozbyć ze swojego umysłu:

-   To *tylko jedno zerknięcie* wprowadziło nas na zaczęcie na pierwszym miejscu.

-   To *tylko jedno zerknięcie*, które przeciąga nas w ciężkim okresie lub przy specjalnej okazji, w których klękamy po próbach zaprzestania.

-   To *tylko jedno zerknięcie*, które po sukcesie z przerwaniem uzależnienia, wysyła nas z powrotem do pułapki. Czasami po to, żeby potwierdzić, że nie potrzebujemy już porno i jedna wizyta w haremie to właśnie sprowadza tą potrzebę.

Efekty uboczne porno będą straszne i przekonują użytkownika, że już nigdy więcej nie wpadnie w sidła - ale już w nie wpadł. Użytkownik czuje, że coś, co czyni go tak nieszczęśliwym i winnym, nie powinno go do tego skłonić, a jednak to zrobił.

To właśnie myśl o "jednej specjalnej sesji" często powstrzymuje użytkowników od zaprzestania, tej po długiej podróży na konferencję, ciężkim dniu w pracy, kłótni z dziećmi lub incydencie, w którym twój partner odrzuca ci z seksu. Wbij sobie ***twardo*** do głowy, że nie ma czegoś takiego jak 'tylko jedno zerknięcie'. To reakcja łańcuchowa, która będzie trwała do końca życia, jeśli nie zostanie przerwana. Mit o dziwnych, wyjątkowych okazjach sprawia, że użytkownicy opłakują po zatrzymaniu. Wyrób sobie nawyk, że nigdy nie widzisz sesji "nic wielkiego", to fantazja. Ilekroć myślisz o porno, widzisz brudne życie spędzone za ekranem za przywilej zniszczenia siebie psychicznie i fizycznie, życie w niewoli i beznadziei. To nie jest przestępstwo, jeśli twoje erekcje są niepewne, ale to jest, gdy można być szczęśliwszym w dłuższej perspektywie, ale zamiast tego wybrać poświęcić, że dla krótkotrwałej "przyjemności".

To dobrze, że nie zawsze możemy wymyślić "coś do zrobienia" dla pustki; robienie tego nie jest realistycznie możliwe w każdym przypadku przez całe nasze życie. Możemy zaplanować większość z nich, ale czasami po prostu się zdarza. Dobre i złe czasy również się zdarzają, niezależnie od porno. Ale wbij sobie to jasno do głowy, porno to nie jest to. Tkwisz albo w nieszczęściu przez całe życie, albo w żadnym, nie marzyłbyś o zażyciu cyjanku tylko dlatego, że lubisz smak migdałów, więc przestań karać się okazjonalną sesją "nic wielkiego". Zapytaj użytkownika z problemami, "*Gdybyś miał możliwość cofnięcia się do czasu, zanim się uzależniłeś, czy zostałbyś użytkownikiem?". Odpowiedź nieuchronnie brzmi: "*Ty chyba sobie żartujesz!". A jednak każdy użytkownik ma taki wybór każdego dnia swojego życia, dlaczego więc się na niego nie decyduje? Odpowiedzią jest strach. Strach, że nie mogą przestać lub że życie bez niego nie będzie takie samo.

Przestań się okłamywać! Możesz to zrobić, każdy może. Jest to śmiesznie proste, ale żeby tak było, trzeba sobie w głowie wyklarować pewne podstawy.

1.  Nie ma czego się poświęcać, tylko wspaniałe i pozytywne korzyści do zdobycia.

2.  Nigdy nie przekonywuj siebie do dziwnego "nic wielkiego lub "tylko jedno zerknięcie". To nie istnieje. Jest tu tylko żywot brudu oraz niewolnictwa.

3.  Nie ma nic innego w tobie, każdy użytkownik może znaleźć sposób na zaprzestanie.

Wielu użytkowników wierzy, że są potwierdzonymi uzależnionymi lub mają uzależniające osobowości. Dzieje się tak zazwyczaj w wyniku czytania nadmiernych ilości szokujących neuronauk. Nie ma czegoś takiego, nikt nie rodzi się z potrzebą masturbowania się do klipów wideo, zanim stał się uzależniony. To narkotyk cię zaczepia, a nie natura twojego charakteru czy osobowości. Natura uzależniających bodźców nadprzyrodzonych każe ci wierzyć, że tak właśnie jest. Jednak istotne jest usunięcie tego przekonania, ponieważ jeśli wierzysz, że jesteś uzależniony, będziesz nim, nawet po tym, jak mały potwór w twoim ciele już dawno nie żyje. Niezbędne jest usunięcie całego tego prania mózgu.


