# Zwykli użytkownicy

Ciężcy użytkownicy mają tendencję do zazdroszczenia zwyczajnym użytkownikom porno, wszyscy spotkaliśmy te postacie: "*Och, mogę przejść cały tydzień bez sesji, to mi naprawdę nie przeszkadza". Chcielibyśmy być tacy jak oni. To może być trudne do uwierzenia, ale żaden użytkownik nie lubi być użytkownikiem. Nigdy nie zapominaj:  


| *Żaden użytkownik nigdy nie zdecydował się nim zostać, dorywczo lub w inny sposób,**

| *Wszyscy użytkownicy czują się głupio, **dlatego** *

| *Wszyscy użytkownicy muszą okłamywać siebie i innych w próżnej próbie usprawiedliwienia swojej głupoty.*


Fanatycy golfa chwalą się tym, jak często grają i chcą grać, więc dlaczego użytkownicy chwalą się tym, jak rzadko się masturbują? Jeśli to jest prawdziwe kryterium, to na pewno wyróżnieniem jest to, że w ogóle się nie masturbują, prawda?

Gdyby ktoś powiedział ci: "*Mogę iść cały tydzień bez marchewki i nie przeszkadza mi to w najmniejszym stopniu*", pomyślałbyś, że rozmawiasz z wariatem. Jeśli lubiłem marchewki, dlaczego miałbym chcieć iść cały tydzień bez nich? Gdybym ich nie lubił, to dlaczego miałabym wygłaszać takie oświadczenie? Więc kiedy użytkownik komentuje, że przetrwał tydzień bez sesji, próbuje przekonać siebie - i ciebie - że nie ma problemu. Ale nie byłoby potrzeby składania oświadczenia, gdyby nie mieli problemu. W tłumaczeniu, ten komentarz brzmi: "*Udało mi się przetrwać cały tydzień bez porno.*". Jak każdy użytkownik, mając nadzieję, że po tym uda im się przetrwać resztę życia. Tylko udało się przetrwać tydzień, czy wyobrażasz sobie jak cenna musiała być potem sesja, czując się pozbawionym przez cały tydzień?

To dlatego zwyczajni użytkownicy są skutecznie bardziej zahaczeni niż ciężcy, nie tylko iluzja przyjemności jest większa, ale mają mniejszą motywację do rzucenia, ponieważ spędzają mniej czasu, a zatem są mniej narażeni na ryzyko zdrowotne. Sporadycznie mogą doświadczyć dysfunkcji seksualnej, ale nie są pewni, co ją spowodowało, więc winą obarcza się inne czynniki. Pamiętaj, że jedyną przyjemnością, jaką otrzymują użytkownicy, jest cykl dopaminowy poszukiwania i łagodzenia napadów odstawienia, co zostało już wyjaśnione. Przyjemność jest iluzją, wyobraź sobie małego porno potwora jako prawie niezauważalne swędzenie, którego przez większość czasu nie jesteśmy świadomi.

Jeśli masz stałe swędzenie, naturalną tendencją jest drapanie go. Ponieważ obwody nagrody stają się coraz bardziej odporne na dopaminę i opioidy, naturalną tendencją jest edżowania, eskalowania, brania na upór, szukania nowości, szukania szoku, itd. Istnieją cztery główne czynniki, które powstrzymują użytkowników przed oglądaniem łańcucha.

**Czas.**
Większość nie może sobie pozwolić na to.

**Zdrowie.**
Aby ulżyć swędzeniu, musimy skonsumować wszystkie darmowe materiały, które są dostępne, a następnie niektóre. Zdolność do radzenia sobie z tego rodzaju obżarstwem jest różna u każdego człowieka, w różnych okresach i sytuacjach życiowych. To działa jak automatyczny ogranicznik.

**Dyscyplina.**
Narzucona przez społeczeństwo lub pracę użytkownika, przyjaciół i krewnych; być może nawet przez samego użytkownika w wyniku naturalnej wojny toczącej się w umyśle każdego użytkownika.

**Imaginacja.**
Brak wyobraźni obniża szok, nowość i inne wartości klipu na zasadzie subiektywnej.

Łatwo jest myśleć o użytkownikach typu "non-casual" jako słabych, nie potrafiących zrozumieć, dlaczego inni są w stanie ograniczyć swój "pobór". Ciężcy użytkownicy powinni jednak pamiętać, że większość casuali jest po prostu niezdolna do oglądania łańcuchowego, wymagającego bardzo silnej wyobraźni i wytrzymałości. Niektórzy z tych użytkowników, którym ciężcy użytkownicy zazdroszczą, nie są fizycznie w stanie zrobić więcej, albo nie pozwala im na to praca, społeczeństwo lub własna nienawiść do uzależnienia się.

Korzystne może być podanie kilku definicji.

**Nieużytkownik**

Ktoś, kto nigdy nie wpadł w modlitwę do pułapki, ale nie powinien mieć pretensji. Są nie-użytkownikiem tylko dzięki szczęściu lub łasce dobroci. Wszyscy użytkownicy byli przekonani, że nigdy nie dadzą się złapać w pułapkę, a niektórzy nie-użytkownicy wciąż próbują okazjonalnej sesji.

**Zwyczajny użytkownik**

Wśród których są dwie podstawowe klasyfikacje:

1.  Użytkownik, który wpadł w pułapkę, ale nie zdaje sobie z tego sprawy - nie zazdrość takim użytkownikom. Oni tylko próbują nektaru z ust dzbana i najprawdopodobniej wkrótce staną się ciężkimi użytkownikami. Pamiętajcie, że tak jak wszyscy alkoholicy zaczynali jako przypadkowi pijaczkowie, tak samo wszyscy użytkownicy zaczynają od przypadkowości.

2.  Użytkownik, który był wcześniej ciężkim użytkownikiem, a więc myśli, że nie może przestać. Ci użytkownicy są najsmutniejsi ze wszystkich i dzielą się na różne kategorie, z których każda wymaga osobnego komentarza.

**Użytkownik typu "raz dziennie"**

Jeśli cieszą się swoim prawem do orgazmu, dlaczego używają pornografii internetowej tylko raz dziennie? Jeśli mogą to przyjąć lub porzucić, to po co w ogóle się męczyć? Pamiętaj, że "nawyk" to w rzeczywistości walenie głową w mur, żeby się zrelaksować po zaprzestaniu. Użytkownik raz dziennie łagodzi swoje bóle odstawienia przez mniej niż godzinę każdego dnia. Mimo że nie jest świadomy, resztę dnia spędza waląc głową w ten mur, robiąc to przez większość swojego życia. Używają raz dziennie, bo nie mogą ryzykować złapania, ani zepsucia swojego zdrowia neurologicznego. Łatwo jest przekonać ciężkiego użytkownika, że nie sprawia mu to przyjemności, ale znacznie trudniej przekonać przypadkowego. Każdy, kto przeszedł przez próbę ograniczenia palenia, wie, że to najgorsza tortura ze wszystkich i prawie gwarancja, że będziesz uzależniony do końca życia.

**Odrzucony użytkownik**

Domagają się prawa do orgazmu każdego dnia, ale ich partner seksualny nie zawsze chętnie spełnia to żądanie. Początkowo używają pornografii internetowej, aby wypełnić tę pustkę, ale po przejściu przez ekscytującą "zjeżdżalnię wodną" wpadają w pułapkę cyklu nowości, szoku, nadprzyrodzonych obrazów itp. W rzeczywistości cieszą się z odrzucenia przez partnera, ponieważ stanowi to dla nich pewną wymówkę. Jeśli internetowe porno daje ci tak wiele, to po co w ogóle męczyć się z partnerem? Zamiast tego uwolnij ich. Nie cieszą się nawet sesjami, kiedy muszą "nosić" swojego partnera w myślach. W pewnym momencie szukają swojego realnego partnera, który da im pretekst do zapuszczenia się w ciemne doliny internetu.

**Użytkownik porno-diety**

Znany również jako "*Mogę przestać, kiedy tylko chcę. Robiłem to tysiące razy!*"

Jeśli uważają, że dieta pomaga wprowadzić ich w nastrój do podrywania partnerów, to dlaczego w ogóle są na diecie raz na cztery dni? Nikt nie jest w stanie przewidzieć przyszłości, co jeśli przypadek spotkania nastąpił godzinę po Twojej zaplanowanej sesji? Ponadto, jeśli okazjonalne "czyszczenie rury" jest dobre dla rozładowania napięcia, to dlaczego nie pionować codziennie? Udowodniono, że masturbacja nie jest konieczna do utrzymania zdrowych narządów płciowych, a porno w internecie nie jest w ogóle potrzebne. Nawet jeśli tak jest, to żaden "guru" podrywu, który czytał o szkodach neurologicznych, nie będzie zalecał oglądania superstymulującego porno. Prawda jest taka, że oni nadal są uzależnieni. Choć pozbyli się fizycznego uzależnienia, to nadal pozostają z podstawowym problemem, jakim jest pranie mózgu. Za każdym razem mają nadzieję, że przestaną na dobre, ale wkrótce znów wpadają w tę samą pułapkę.

Większość użytkowników właściwie zazdrości tym stoperom i starterom i myśli o tym, jakie "szczęście" ma stosujący dietę, że potrafi kontrolować swoje używanie. Nie dostrzegają jednak, że osoba stosująca dietę nie kontroluje swojego używania - kiedy używa, chciałaby tego nie robić. Przechodzą przez kłopoty z zaprzestaniem, a potem zaczynają czuć się pozbawieni i znów wpadają w pułapkę, żałując, że tego nie zrobili. Otrzymują najgorsze z obu światów. Jeśli się nad tym zastanowić, to jest to prawda w życiu użytkowników, kiedy pozwala im się na sesję - biorąc ją jako uprawnioną lub żałując, że jej nie mają. Tylko w przypadku pozbawienia porno staje się cenne. Syndrom "zakazanego owocu" jest jednym z okropnych dylematów użytkowników. Nigdy nie mogą wygrać, bo mażą o micie, iluzji. Jest tylko jeden sposób, w jaki mogą wygrać, przestając moping przez zaprzestanie pornografii!

**Użytkownik "Tylko oglądam porno statyczne/łagodne/domowe"**

Tak, każdy tak robi na początku, ale czyż nie jest to niesamowite, jak średnia wartość szokująca tych klipów wydaje się szybko rosnąć i zanim się zorientujemy, czujemy się pozbawieni (tolerancji)? Brakuje nowości w statycznym porno, więc płacimy za filiżankę smaru i zjeżdżamy w dół po zjeżdżalni w kierunku pretensji i poczucia winy. Najgorsze, co możesz zrobić, to używać zdjęć partnera (oczywiście za zgodą) do masturbacji. Dlaczego? Ponieważ w tym procesie ponownie uzbrajasz swój mózg do poszukiwania, szukania i różnorodności wywołanych dopaminowych spłukań. Chemicznie, porno ślizgacze wodne w mózgu budują DeltaFosB, więc będziesz miał trudności, gdy będziesz z nimi w czasie rzeczywistym.

Inną pułapką w tej kategorii jest "amatorskie" i "domowe" porno. Większość z nich to podróbki i dobrze o tym wiesz, dodatkowo nie zatrzymasz się na pierwszym, który rzuci ci się w oczy, zamiast tego kontynuując poszukiwania. Pamiętaj, że to nie tylko orgazm, którego szuka mózg, ale nowość polowania daje zjeżdżalni wodnej dreszczyk emocji. Treść porno nie jest problemem - czy to amatorskie czy profesjonalne - to przypływ dopaminy w mózgu powodujący wzrost tolerancji i nasycenia. Porno niszczy normalną pracę mózgu, masturbacja dezorientuje reakcję mięśnie-mózg; orgazm zalewa mózg opioidami i sprawia, że następnym razem ścieżka staje się łatwiejsza.

**Użytkownik "Przestałem, ale mam okazjonalne spojrzenia"**

W pewnym sensie, użytkownicy zerkający są najbardziej żałośni ze wszystkich. Albo przechodzą przez swoje życie wierząc, że są pozbawieni, albo częściej, okazjonalne zerkanie staje się dla nich dwoma. Zjeżdżają w dół po śliskim stoku, prędzej czy później wracając do bycia ciężkimi użytkownikami. Ponownie wpadają w tę samą pułapkę, w którą wpadli w pierwszej kolejności.

Istnieją jeszcze dwie kategorie zwyczajnych użytkowników. Pierwszą z nich jest typ masturbujący się do obrazów lub klipów z najnowszych seks taśm celebrytów trafiających do wiadomości, lub czegoś, co "przynieśli do domu" z ich "przypadkowego" oglądania w szkole lub pracy. Ci ludzie są tak naprawdę tylko nieużytkownikami, ale czują, że coś ich omija. Chcą być częścią akcji, a większość z nas zaczynała w ten sposób. Następnym razem zauważ, że po pewnym czasie celebryta z twojej fantazji nie robi już tego dla ciebie. Im bardziej "nieosiągalny" jest cel twojej fantazji, tym bardziej frustrujące jest wycofanie się z orgazmu.

Druga kategoria zyskuje ostatnio na znaczeniu, co najlepiej opisuje przypadek, który został udostępniony w sieci.

Pewna profesjonalna kobieta od wielu lat czytała internetowe opowiadania porno i nigdy nie używała więcej lub mniej niż raz każdej nocy. Nawiasem mówiąc, była kobietą o bardzo silnej woli. Większość użytkowników zastanawiałaby się, dlaczego chciała przestać w pierwszej kolejności -- chętnie wskazując, że nie było ryzyka PIED, lub PE w jej przypadku (nieprawda). Nie używała nawet statycznych obrazów, historie były o wiele bardziej oswojone niż jakiekolwiek materiały, których oni sami używają na co dzień.

Popełniają błąd zakładając, że zwykli użytkownicy są szczęśliwsi i mają większą kontrolę. Może i mają większą kontrolę, ale na pewno nie są szczęśliwi. W przypadku tej kobiety, nie była ona zadowolona ze swojego partnera ani z prawdziwego seksu, a także bardzo rozdrażniona, gdy reagowała na codzienne stresy i napięcia. Jej najbliżsi nie byli w stanie dociec, co ją trapi. Nawet jeśli poprzez racjonalizację przekonała się, że nie boi się swojego użycia, to i tak nie potrafiła cieszyć się prawdziwymi związkami, które nieodmiennie wiążą się z wzlotami i upadkami. Jej mózgowy ośrodek nagrody nie był w stanie wykorzystać normalnych destresorów obecnych w życiu w wyniku codziennego zalewania dopaminą. Późniejsza regulacja receptorów mózgowych spowodowała, że w większości przypadków stała się melancholijna. Jak większość, miała wielki strach przed ciemną stroną pornografii i traktowaniem kobiet - przed swoim pierwszym razem. W końcu padła ofiarą społecznego prania mózgu i wypróbowała swoją pierwszą stronę. W przeciwieństwie do większości, którzy kapitulują i stają się użytkownikami łańcucha - po zobaczeniu obrzydliwych klipów z przemocą, oparła się zsunięciu.

Wszystko, co kiedykolwiek cieszysz się w porno, to zakończenie pragnienia, które zaczęło się przed nim, czy to prawie niezauważalne fizyczne pragnienie, czy też psychiczne tortury związane z brakiem możliwości podrapania się po swędzeniu. Internetowe porno samo w sobie jest trucizną, dlatego tylko po okresach odstawienia cierpisz na iluzję czerpania z niego przyjemności. Podobnie jak w przypadku głodu czy pragnienia, im dłużej się je odczuwa, tym większa jest przyjemność, gdy w końcu się je uśmierzy. Popełniając błąd polegający na przekonaniu, że porno to tylko przyzwyczajenie, myślą: "Jeśli uda mi się ograniczyć to do pewnego poziomu lub tylko na specjalne okazje, mój mózg i ciało to zaakceptują. Wtedy mogę nadal używać na tym poziomie lub zmniejszyć go dalej, jeśli będę chciał.*"

Wyjaśnij sobie w głowie, że "nawyk" nie istnieje. Porno to uzależnienie, z naturalną tendencją do łagodzenia napadów odstawienia, a nie ich znoszenia. Utrzymanie go na poziomie, na którym obecnie jesteś, wymagałoby od ciebie ogromnych ilości dyscypliny i siły woli przez resztę życia; ponieważ ośrodek nagrody twojego mózgu staje się odporny na dopaminę i opioidy, chce więcej i więcej, a nie mniej i mniej.

W miarę jak porno zaczyna stopniowo niszczyć twój system nerwowy, odwagę, pewność siebie i kontrolę impulsów, stajesz się coraz bardziej niezdolny do oporu, aby zmniejszyć odstęp między każdą sesją. To dlatego w pierwszych dniach możemy wziąć to lub zostawić. Jeśli dostaniemy znak, że coś jest nie tak psychicznie lub fizycznie, po prostu przestajemy. Nie zazdrość tej kobiecie, kiedy oglądasz tylko raz na dwadzieścia cztery godziny, wydaje się, że to najcenniejsza rzecz na ziemi, zamieniając porno w "zakazany owoc". Przez wiele lat ta biedna kobieta znajdowała się w centrum wojny.

Nie mogąc przestać używać, a jednocześnie bojąc się eskalacji do strumieniowych klipów. Przez dwadzieścia trzy godziny i dziesięć minut, przez każdy z tych dni musiała walczyć z pokusą i brakiem uczuć do swojego chłopaka. Potrzeba było ogromnej siły woli, by zrobić to, co zrobiła, co ostatecznie doprowadziło ją do łez. Takie przypadki są rzadkie, ale spójrz na to logicznie: Albo jest prawdziwa podpora lub przyjemność w porno, albo nie ma. Jeśli jest, to kto chce czekać godzinę, dzień, czy nawet tydzień? Dlaczego miałbyś być pozbawiony tej kuli lub przyjemności w międzyczasie? Jeśli nie ma prawdziwej podpory czy przyjemności, to po co męczyć się z wizytą w swoim internetowym haremie?

Oto kolejny przypadek człowieka typu "raz na cztery dni", który opisuje swoje życie w następujący sposób:

> "*Mam czterdzieści lat, cierpiałem na PIED (z ang. zaburzenie erekcji spowodowane pornografią) z prawdziwymi kobietami, a nawet podczas korzystania z porno, czyli przez większość czasu. Minęło trochę czasu, odkąd miałem pełną erekcję. Przed przejściem na dietę porno raz na cztery, zwykłem spać spokojnie przez całą noc po sesji. Teraz budzę się co godzinę w nocy i tylko o tym mogę myśleć. Nawet podczas snu śnią mi się moje ulubione klipy. W dni po mojej zaplanowanej sesji czuję się całkiem przygnębiony, dieta pochłania całą moją energię. Moja DP (Druga połówka) zostawiłaby mnie w spokoju, ponieważ jestem tak źle nastawiony i jeśli nie może wyjść, nie chce mieć mnie w domu. Idę na jogging na zewnątrz, ale mój umysł ma obsesję na tym punkcie.
>
> *W zaplanowanym dniu zaczynam planować wcześniej w nocy, bardzo się denerwując, jeśli coś dzieje się wbrew moim planom. Wycofuję się z rozmów i ulegam (tylko po to, by później żałować) w pracy i w domu. Nie jestem kłótliwym facetem, ale nie chcę, aby temat lub rozmowa mnie powstrzymała. Pamiętam okazje, kiedy wybierałem głupie walki z moją DP. Czekam na godzinę dziesiątą, a kiedy nadchodzi, moje ręce trzęsą się niekontrolowanie. Nie zaczynam czynu od razu -- ponieważ są nowe filmy, które zostały dodane -- i "rozejrzeć się". Mój umysł mówi mi, że skoro głodziłem się przez cztery dni, to zasługuje na 'specjalny' klip, który musi być wart czasu spędzonego na poszukiwaniach. W końcu zadowalam się jednym lub dwoma, ale chcę, aby były trwałe, abym mógł 'przetrwać' przez następne cztery dni, więc poświęcam więcej czasu na dokończenie czynu.*"  

Oprócz innych kłopotów, ten biedny człowiek nie ma pojęcia, że leczy się trucizną. Najpierw cierpi na "syndrom zakazanego owocu", a potem zmusza swój mózg do wypłukiwania dopaminy. Porównywalnie, jego receptory dopaminy nie są tak ścięte, ale on smaruje porno zjeżdżalnie wodne, szukając, szukając “edgingu”, nowości, urozmaicenia, szoku i niepokoju, aby przetrwać następne cztery dni. Pewnie wyobrażacie sobie tego człowieka jako żałosnego imbecyla, ale tak nie jest. Jako były sportowiec zamieniony na byłego sierżanta piechoty morskiej, nie chciał się od niczego uzależnić. Jednak po powrocie z wojny szkolił się jako technik informatyk w programie odwykowym dla weteranów. 

Wchodząc do pracy cywilnej, był dobrze opłacanym informatykiem w banku i dostał laptopa, którego mógł zabrać do domu. Był to rok, w którym znane osobistości społeczne "wyciekły" do sieci swoje filmy porno i było o tym głośno. Następnie wpadł w sidła, spędzając resztę życia płacąc przez nos i rujnując się fizycznie i psychicznie. Gdyby był zwierzęciem, społeczeństwo już dawno uwolniły go od nieszczęścia, a jednak wciąż pozwalamy zdrowym psychicznie i fizycznie młodym nastolatkom na uzależnienie się. Możesz myśleć, że ten przypadek i notatki są przesadzone, ale ten przypadek -- choć ekstremalny -- jest daleki od unikalności. Istnieją dziesiątki tysięcy podobnych historii. Czy możesz być pewien, że wielu jego przyjaciół i znajomych zazdrościło mu tego, że jest człowiekiem raz na cztery lata? Jeśli myślisz, że to nie mogło przydarzyć się Tobie, **przestań się oszukiwać**.

**TO JUŻ SIĘ DZIEJE.**

Podobnie jak inni uzależnieni użytkownicy porno są notorycznymi kłamcami, nawet wobec samych siebie. Muszą być. Większość zwykłych użytkowników oddaje się pornografii znacznie więcej razy i przy znacznie większej liczbie okazji, niż się do tego przyznaje. W wielu rozmowach z tzw. użytkownikami "dwa razy w tygodniu" przyznają, że zrobili to więcej niż trzy lub cztery razy w danym tygodniu. Poczytaj na reddicie, NoFap i forum restartu historii użytkowników, a przekonasz się, że albo liczą dni, albo czekają na porażkę. Nie musisz zazdrościć casual userom, nie musisz też używać, życie jest nieskończenie słodsze bez tego. Weźmy następujący dziennik:

"*Zaczęło się od prostego wyzwania, żeby nie dotykać swojego faraona przez jeden dzień i nie móc. Nie myślę już o masturbacji, nie przechodzi mi to przez myśl. To jest możliwe, obiecuję wam. Bogactwa, które czekają na tych, którzy są w stanie - są niesamowite.*"

Nastolatki są na ogół trudniejsze do wyleczenia, nie dlatego, że trudniej im przestać, ale dlatego, że nie wierzą, że są uzależnione lub znajdują się w początkowym stadium pułapki. Generalnie cierpią na złudzenie, że automatycznie przestaną przed drugim etapem.

Rodzice dzieci, które brzydzą się pornografią internetową, nie powinni mieć fałszywego poczucia bezpieczeństwa. Wszystkie dzieci brzydzą się ciemnymi stronami pornografii, zanim staną się zaczepione. W pewnym momencie ty też to robiłeś. Nie dajcie się też nabrać na kampanię strachu, pułapka jest taka sama jak zawsze. Dzieci wiedzą, że pornografia internetowa jest bodźcem nadprzyrodzonym, ale wiedzą też, że jedna "wizyta" czy "spojrzenie" nie załatwi sprawy. Na pewnym etapie może na nie wpłynąć partner, kolega z klasy lub pracy.

Proszę nie popadać w samozadowolenie w tej kwestii. Niezdolność społeczeństwa do zapobiegania uzależnieniu młodzieży od pornografii internetowej i innych używek jest być może najbardziej niepokojącym aspektem tego uzależnienia. Mózgi dorastających dzieci są znacznie bardziej plastyczne i konieczne jest ich edukowanie i ochrona. Jeśli nie jesteś pewien, od czego zacząć, dobrym źródłem informacji jest książka YourBrainOnPorn, która pozwoli Ci zapoznać się z neurobiologią. Nawet jeśli podejrzewasz, że twój nastolatek może być już zaczepiony, książka zapewnia fundamentalne zrozumienie w pomaganiu komuś w ucieczce. W przeciwnym razie, polecam tę książkę!


