# Nawyk społeczny?

Zdrowie umysłu i ciała to podstawowe powody, dla których *powinniśmy* chcieć przestać - ale zawsze tak było. Nie potrzebujemy badań naukowych i wiedzy z zakresu neuronauki, żeby powiedzieć nam, że porno jest uzależniające i może potencjalnie zniszczyć nasze życie. Nasze ciała są najbardziej wyrafinowanymi obiektami na planecie i każdy użytkownik wie od pierwszej sesji, że bodźce mogą pójść w nadmiar i stać się trujące.

Jedynym powodem, dla którego kiedykolwiek angażujemy się w porno, jest nakładanie się cyklu na nasze ewolucyjne programowanie. Internetowe porno jest wysoce dostępne, darmowe i strumieniowe dwadzieścia cztery godziny na dobę. Kiedyś porno uważano za nieszkodliwe, ale było to w czasach, gdy obrazy były statyczne, a filmy wymagały wycieczki do lokalnego sklepu po kasetę VHS.

Dziś powszechnie uważa się - nawet przez samych użytkowników - że porno jest super bodźcem i tworzy uzależnienie. W dawnych czasach silny mężczyzna nie przyznawał się, że się masturbuje, przy czym palant był określeniem uwłaczającym. W każdym pubie, klubie czy barze większość mężczyzn z dumą chciałaby zabrać kobietę do domu i uprawiać prawdziwy seks. Dziś pozycja jest zupełnie odwrotna dla uzależnionego od pornografii internetowej, dzisiejszy mężczyzna zdaje sobie sprawę, że zaczyna czuć, że nie potrzebuje kobiety. W sieci dyskutuje o doświadczeniach, opracowuje strategie i bada możliwości. Dzisiejszy silny mężczyzna nie chce być uzależniony od narkotyków. Dzięki rewolucji społecznej wszyscy użytkownicy poważnie zastanawiają się nad zaprzestaniem pornografii internetowej i masturbacji. Dzisiejsi użytkownicy uważają porno za bezużyteczne i szkodliwe zajęcie.

Najbardziej znaczącym trendem zauważonym na forach jest coraz większy nacisk na antyspołeczne aspekty porno, czasy kiedy człowiek chwalił się seksem i orgazmami każdego dnia są powoli zastępowane realizacją niewolnictwa wobec potwora porno.

Jedynym powodem, dla którego ludzie kontynuują po edukacji jest to, że nie udało im się przestać lub są zbyt przerażeni, aby spróbować. Istnieje szerokie spektrum zainteresowania tematem, niektórzy powstrzymują się od porno, masturbacji i orgazmu - z partnerami lub bez. Praktyki, które oddzielają tantryczne i propagacyjne części seksu, takie jak podtrzymanie nasienia i Karezza, są omawiane i przyjmowane w dużych ilościach. Wiele z wyżej wymienionych niepowodzeń jest w rzeczywistości upadkiem do przodu, co w pewnym sensie przynosi korzyści osobom je praktykującym. Po rozpoczęciu trasy bez PMO znajdziesz najlepsze dopasowanie, które odnosi się do twojego życia, zachęca się do opracowania własnego planu na orgazmy po zrozumieniu i praktykowaniu separacji seksualnej. Niezależnie od trasy, zobaczysz wartość w ograniczeniu liczby razy przepłukać swój mózg z chemikaliami przez orgazm, i nigdy więcej widząc porno, seks i orgazm jako przyjemność lub podpory dla swojego emocjonalnego ja.

Różne popularne społeczności internetowe założone przez nie-użytkowników są poświęcone rzucaniu nie tylko porno, ale także masturbacji. Strony te są ostatecznie korzystne dla uciekających, ale większość notatek wskazuje im na próbę siły woli. Konsekwencją obsesji na seriach i innych środków jest użalanie się nad sobą i brak uniesień. Duża część prania mózgu żyje i ma się dobrze. W końcu ktoś się załamuje i następuje efekt domina, inni użytkownicy dowiadują się, że nie są jedyni. Jednak ich wysiłki nie idą na marne, idą do przodu, choć z dużą ilością samookaleczeń, ponieważ wyłączają swoje przeglądarki, ale nie pragnienia i potrzeby. EasyPeasy działa odwrotnie, wyłączając najpierw potrzebę i pragnienie, zanim wyłączy się przeglądarkę. Każdego dnia coraz więcej użytkowników opuszcza tonący statek, a ci, którzy na nim zostali, są przerażeni, że będą ostatnimi.

**NIECH TO NIE BĘDZIE TY!**


