# Wyczucie czasu

Oprócz oczywistym odniesieniem, że to nie robi ci nic dobrego i że teraz jest właściwy czas, aby przestać, czas jest ważny. Społeczeństwo traktuje internetowe porno lekceważąco, jako lekko niesmaczny nawyk, który nie szkodzi twojemu zdrowiu. To nieprawda. To 
jest narkomania, choroba i niszczyciel relacji w społeczeństwie. Najgorsza rzeczą, jaka dzieje się w życiu większości użytkowników, jest popadnięcie w ten okropny nałóg. Jeśli pozostają uzależnieni, dzieją się potworne rzeczy. Dlatego ważne jest wyczucie czasu, aby dać sobie prawo do właściwego wyleczenia.

Po pierwsze, zidentyfikuj czasy lub okazje, w których porno wydaje się być dla ciebie ważne. Jeśli jesteś biznesmenem, który używa go do złudzenia rozładowania stresu -- wybierz stosunkowo luźny okres lub wakacje. Jeśli używasz porno głównie w okresach nudy lub relaksu, to obowiązuje zasada odwrotna. Niezależnie od tego, potraktuj próbę poważnie i uczyń ja najważniejszą rzeczą w swoim życiu.

Wybiegnij w przyszłość na okres trzech tygodni i spróbuj przewidzieć każde wydarzenie, które może doprowadzić do porażki. Okoliczności takie jak wyjazdy na konferencje, wyjazd partnera poza miasto itp. nie musza Cie zniechęcać, pod warunkiem, że przewidujesz je 
z wyprzedzeniem i nie czujesz, że zostaniesz pozbawiony. Nie próbuj w międzyczasie ograniczać, bo to tylko stworzy złudzenie, że odmawianie jest przyjemne. W rzeczywistości pomaga zmuszenie się do oglądania i posiadania jak największej ilości sesji porno. 
Podczas ostatniej sesji i ostatniego razu miej na uwadze rozczarowanie wynikające z nasycenia, niespełnione oczekiwania, wszelkie bóle ciała, efekty odstawienia, rozczulanie się i melancholie. Myśl o tym, jak cudownie będzie, gdy pozwolisz sobie przestać to 
robić.

**NIEWAŻNE CO ROBISZ, NIE WPADNIJ W PUŁAPKĘ MÓWIENIA "NIE TERAZ, PÓŹNIEJ" I ODSTAWIENIA GDZIE TEGO POZA MYŚLI. WYPRACUJ SWÓJ ROZKŁAD I CZEKAJ NA NIEGO.**

Pamiętaj, że *nie rezygnujesz z niczego*. Wręcz przeciwnie, otrzymacie wspaniałe pozytywne korzyści.

Przez lata medycyna postrzegała porno jako nieszkodliwe, nie znając różnicy między oswojonym statycznym porno z dawnych lat a najnowszym doświadczeniem streamowaniu wirtualnej rzeczywistości. Problem polega na tym, że choć każdy użytkownik konsumuje internetowe porno wyłącznie po to, by zaspokoić wywołany nim głód dopaminowy, to nie uzależnienie od substancji chemicznej zahacza o użytkownika, ale samouszkodzenie mózgu wynikające z uzależnienia. Inteligentna osoba da się nabrać na sztuczkę zaufania, ale tylko głupiec będzie sie na nią dalej nabierał, gdy zorientuje się, że to sztuczka. Na szczęście większość użytkowników nie jest głupcami, tylko tak im się wydaje. Każdy użytkownik ma swoje własne, prywatne pranie mózgu. Dlatego też wydaje się, że istnieje tak zróżnicowany zakres w typach uzależnionych, służący jedynie dalszemu pogłębianiu tajemnic.

Podczas gdy korzyścią z oryginalnej książki było rzucenie nikotyny (jednego z najszybszych i najbardziej uzależniających narkotyków znanych człowiekowi), było przyjemnie zaskakujące uświadomienie sobie, że filozofia głoszona w oryginalnej książce jest nadal solidna, gdy jest dostosowana. Nagromadzona wiedza i wyzwanie, które Carr i ja podejmujemy, to jak przekazać tę wiedzę każdemu indywidualnemu użytkownikowi. Fakt, ze wiem, iż każdy użytkownik może nie tylko łatwo przestać, ale może faktycznie cieszyć sie 
procesem, jest nie tylko bezcelowy, ale niezwykle frustrujący, chyba ze użytkownik może być uświadomiony. W swojej oryginalnej książce Allen Carr wyjaśnia swoją kontrowersyjną poradę:

>"Wiele osób mówiło mi: *"Mówisz: "Kontynuuj palenie, aż skończysz książkę" To ma tendencje do sprawiania, że palacz bierze wieki, aby przeczytać książkę lub po prostu jej nie kończy. Kropka. Dlatego powinieneś zmienić instrukcje." To brzmi logicznie, ale wiem, 
że gdyby instrukcja brzmiała: *"Przestań natychmiast"*, niektórzy palacze nawet nie zaczęli czytać książki. Na początku konsultował sie ze mną pewien palacz. Powiedział: *"Naprawdę nie chce szukać twojej pomocy, wiem, ze mam silna wole. W każdym innym obszarze 
mojego życia mam kontrole. Dlaczego wszyscy ci inni palacze rzucają palenie dzięki własnej sile woli, a ja muszę przychodzić do pana?"* Kontynuował: "Myślę, ze mógłbym to zrobić sam, gdybym mógł palić, kiedy to robię."\"*

Społeczeństwo uważa, że rzucenie palenia jest niezwykle trudne, więc czego potrzebuje palacz, gdy coś jest trudne? Naszego małego przyjaciela, naszej podpory. Ucieczka od palenia wydaje się być podwójnym ciosem, nie tylko jest trudne zadanie do wykonania - które jest wystarczająco trudne - ale podpora, na której zwykle polegamy przy takich okazjach nie jest dostępna. Być może prawdziwym pięknem tej metody jest to, że nie musisz "poddawać się" podczas przechodzenia przez proces; pozbywając sie początkowo wszystkich lęków i wątpliwości, więc po zakończeniu ostatniej sesji już cieszysz się wolnością.

Dlatego w tym hackbooku ta sama rada zostanie zachowana. Bez względu na to, jak wiele mówi się, że będzie to łatwe i przyjemne, będzie ogromna większość, która nie będzie w stanie tego zaakceptować z powodu osobistego prania mózgu na temat tego, jak trudne jest 
rzucenie palenia.

Wyczucie czasu to jedyny rozdział, który powoduje, że poważnie kwestionuje oryginalną radę Allena. Przede wszystkim, jeśli wyzwalacze obejmują stres biurowy, a następnie wybierając wakacje, aby podjąć próbę i odwrotnie. Nie jest to najłatwiejszy sposób, zamiast tego wybieraj to, co uważasz za najbardziej *trudny* czas. Czy to stres, obowiązki społeczne, koncentracja czy nuda, gdy już udowodnisz, że radzisz sobie i cieszysz się życiem w najgorszych sytuacjach, każda inna będzie przyjemna. Ale gdyby to była rada, czy w
ogóle podjąłbyś próbę?

Oto analogia: moja siostra i ja zamierzamy pływać razem. Przychodzimy na basen w tym samym czasie, ale rzadko kończymy pływanie razem. Powodem jest to, że ona zanurza jeden palec i pół godziny później faktycznie pływa. To powolna tortura, z góry wiem, że na pewnym etapie, bez względu na to, jak zimna jest woda, będę musiał ja w pewnym momencie odważyć. Więc nauczyłem sie robić to w prosty sposób: Nurkowanie prosto do środka. Wyobraź sobie, że mógłbym nalegać, że jeśli nie zanurkuje prosto do wody, to nie umie pływać. Gdyby tak było, nie płynęłaby w ogóle. Czy widzisz tu problem?

Z informacji zwrotnych wynika, że wielu użytkowników skorzystało z oryginalnej porady dotyczącej pomiaru czasu, aby opóźnić to, co ich zdaniem będzie "złowieszczym dniem". Moje kolejne myśli dotyczyły użycia podobnej techniki jak w rozdziale "zalety porno", cos w stylu -- *"Odmierzanie czasu jest bardzo ważne, a w następnym rozdziale zostaniesz poinformowany o najlepszym czasie na podjęcie próby. "*, a na następnej stronie jest po prostu masywne *"TERAZ!"* To jest w rzeczywistości najlepsza rada, ale czy skorzystałbyś z niej? Być może najbardziej subtelnym aspektem pułapki, jest to, że kiedy mamy autentyczny stres w naszym życiu, to nie jest właściwy czas, aby przestać, ale w czasach bez stresu nie mamy ochoty na zakończenie tortur. Zadaj sobie następujące pytania:

1. Czy kiedy po raz pierwszy trafiłeś na porno, naprawdę zdecydowałeś, że będziesz od niego uzależniony do końca życia, nie mogąc nigdy przestać? ***Oczywiście, że nie!***

2. Czy zamierzasz kontynuować resztę swojego życia, nie mogąc nigdy przestać? ***Oczywiście, że nie!***

Więc kiedy przestaniesz? Jutro? W przyszłym roku? W następnym roku? Czy nie jest to pytanie, które zadajesz sobie od czasu, gdy po raz pierwszy zdałem sobie sprawę, że jesteś uzależniony? Czy masz nadzieję, że pewnego ranka obudzisz się i nie będziesz juz chcial oglądać? Przestań się oszukiwać, z każdym uzależnieniem jest się stopniowo bardziej uzależnionym, a nie mniej. Zamierzasz czekać aż faktycznie zaczniesz czuć, że wstanie z łóżka jest trudniejsze niż sama masturbacja? To byłoby trochę bez sensu.

Prawdziwa pułapka jest przekonanie, że teraz nie jest właściwy czas - jutro zawsze będzie łatwiej. Wierzymy, że prowadzimy stresujące życie, ale w rzeczywistości tak nie jest. Większość prawdziwego stresu została usunięta z naszego życia. Wychodząc z domu nie żyjesz w strachu przed atakiem dzikich zwierząt, większość nie zastanawia się, skąd będzie pochodził ich następny posiłek lub czy będzie miał dach nad głową. Pomyśl o życiu dzikiego zwierzęcia, za każdym razem, gdy królik wychodzi ze swojej nory, przez całe życie czeka go Wietnam. Ale królik sobie z tym radzi, ma adrenalinę i inne hormony, my też. Prawda jest taka, że najbardziej stresujące okresy w życiu każdego stworzenia to wczesne dzieciństwo i dorastanie. Ale trzy miliardy lat selekcji naturalnej wyposażyły nas w umiejętność radzenia sobie ze stresem i wielu z tych, którzy dorastają w trudnych warunkach, prowadzi normalne życie.

Banalne jest powiedzenie: "Jeśli nie masz zdrowia, nie masz nic", ale to absolutna prawda. Kiedy czujesz się silny fizycznie i psychicznie, możesz cieszyć sie wzlotami i radzić sobie z upadkami. Wielu myli odpowiedzialność ze stresem, a odpowiedzialność staje się stresująca tylko wtedy, gdy nie czujemy się wystarczająco silni, by sobie z nią poradzić. To co niszczy większość to nie stres, praca czy starość, ale złudne kłamliwe kule, do których się zwracają.

Spójrz na to w ten sposób, ze juz zdecydowałem, ze nie zostaniesz w tej pułapce do końca życia. Dlatego w pewnym momencie - niezależnie od tego, czy jest to dla ciebie łatwe czy trudne - będziesz musiał przejść przez proces uwalniania się. Porno to nie nawyk czy przyjemność, to uzależnienie i choroba. Ustaliliśmy, że jutro nie będzie łatwiej, ale będzie coraz gorzej. Czas na pozbycie się go jest **teraz** - lub tak blisko teraz, jak tylko możesz. Pomyśl tylko, jak szybko mija każdy tydzień naszego życia. Pomysł, jak milo będzie cieszyć sie reszta życia bez coraz większych cieni wiszących nad tobą. Pod warunkiem, że zastosujesz się do wszystkich instrukcji, nie będziesz musiał nawet czekać pięciu dni czy trzech tygodni. Nie tylko łatwo będzie Ci rzucić, ale **będziesz się tym cieszyć!**