# Czy przegapię frajdę?

**Nie!** Gdy mały porno potwór umrze, gdy twoje ciało przestaje pragnąć dopaminy, a porno ślizgi wodne w twoim mózgu szybko zaczną zanikać z powodu braku "smarowania", wszelkie pozostałe pranie mózgu zniknie. Nie tylko znajdziesz się zarówno fizycznie i psychicznie lepiej wyposażone do obsługi stresu i napięcia życia, ale będziesz cieszyć się dobre czasy w pełni.

Jest tylko jedno niebezpieczeństwo, to jest wpływ tych, którzy nadal używają seksu jako ich podpory i przyjemności. *Trawa drugiego człowieka jest zawsze bardziej zielona" jest powszechna w wielu aspektach naszego życia i łatwo ją zrozumieć. Dlaczego w przypadku porno - z wadami tak ogromnymi w porównaniu do iluzorycznych "zalet" - były użytkownik ma tendencję do zazdroszczenia tym, którzy wymagają seksu i pornografii jako kuli u nogi?

Z całym tym praniem mózgu z dzieciństwa, to całkiem zrozumiałe, że wpadliśmy w tę pułapkę. Dlaczego więc - po uświadomieniu sobie, że pornografia to robota głupiego i udało nam się zerwać z nałogiem - wracamy prosto w tę samą pułapkę? To wpływ społecznego prania mózgu, w którym porno jest kojarzone z seksem, przedstawionym jako coś normalnego. Były użytkownik ma ból! Niepewne poczucie pustki, że są samotni (co i tak nie jest przestępstwem) powoduje uczucie niepokoju i popycha ich do jazdy na wodnej zjeżdżalni. To rzeczywiście ciekawa anomalia, szczególnie jeśli weźmie się pod uwagę tę obserwację - nie tylko każdy nieużywający na świecie jest szczęśliwy, że tak jest, ale każdy użytkownik na świecie, nawet z ich wypaczonym, uzależnionym, wypranym z mózgu umysłem cierpiącym na ułudę przyjemności lub relaksu, życzy sobie, żeby nigdy nie został uzależniony w pierwszej kolejności. Dlaczego więc niektórzy byli użytkownicy zazdroszczą?

1. Tylko jedno spojrzenie. Pamiętaj, że to nie istnieje. Przestań widzieć odosobnioną okazję i zacznij patrzeć na to z punktu widzenia użytkownika porno. Być może ty im zazdrościsz, ale oni nie pochwalają siebie i zazdroszczą tobie. Gdybyś tylko mógł jakoś klinicznie obserwować innego użytkownika, bo oni mogą być najpotężniejszym impulsem ze wszystkich, który pomoże ci z tego wyjść. Zauważ, jak szybko otwierają wiele zakładek i okien przeglądarki? Szybko przewijają ważne fragmenty, szybko nudzą się klipami i biegają po całej gamie gatunków wywołujących nowość, szok, niepokój itp. Zauważ szczególnie, że czynność ta wydaje się być automatyczna. Pamiętaj - nie sprawia im to przyjemności, chodzi o to, że nie mogą się bez tego cieszyć. Następnego ranka, budząc się z osłabioną wolą, utraconą energią i załzawionymi oczami, będą musieli nadal dusić się przy pierwszym pojawieniu się stresu i napięcia. Czeka ich całe życie pełne brudu, słabego zdrowia psychicznego i zniszczonej pewności siebie -- całe życie niszczenia siebie z czarnymi cieniami z tyłu umysłu. Aby osiągnąć jaki cel? Iluzji, że dostajesz to, na co "zasługujesz" i cholernej przyjemności?

2. Drugim powodem, dla którego niektórzy byli użytkownicy mają napady, jest to, że użytkownik porno robi coś - np. samozaspokajanie - a nieużytkownik nie robi tego, więc ma tendencję do czucia się pozbawionym. Wyjaśnij sobie w głowie, że to nie nieużywający jest pozbawiony, ale biedny uzależniony jest pozbawiony:

	- Zdrowia

	- Energii

	- Pewności siebie

	- Spokoju w umyśle

	- Odwagi

	- Ciszy

	- Wolności

	- Szacunku do samego siebie

Wyjdź z nawyku zazdroszczenia użytkownikom porno i zacznij postrzegać ich jako nieszczęśliwe, żałosne istoty, którymi naprawdę są. Wiem, sam byłem kiedyś jednym z najgorszych. Dlatego właśnie czytasz tę książkę, a nie tych, którzy nie potrafią stawić czoła i dalej się oszukują.

Nie zazdrościłbyś narkomanowi heroiny, a jak w przypadku wszystkich uzależnień od narkotyków, twoje nie będzie lepsze. Z każdym rokiem będzie coraz gorzej - jeśli dziś nie cieszysz się z bycia użytkownikiem, to jutro będziesz się cieszył jeszcze mniej. Nie zazdrość innym użytkownikom, współczuj im. Uwierz mi: ***Potrzebują twojej litości!***