# Czy mogę rozdzielić?

Ten mit jest przede wszystkim rozpowszechniany przez użytkowników próbujących zatrzymać się na metodzie siły woli, którzy wykonują gimnastykę umysłową i rozpoczynają rutynę Jekylla i Hyde'a: "*Porno jest dla mojego alter ego, a prawdziwy romans w życiu jest dla mojej strony związkowej". Nic bardziej mylnego -- porno zjeżdżalnie wodne, DeltaFosB i zmiany neurologiczne przegonią romans w prawdziwym życiu, czyniąc go mniej pożądanym. Mr Hyde zdecydowanie unieważni instrukcje doktora Jekylla.

Jeśli używasz pornografii internetowej, trenujesz siebie do roli podglądacza, lub wymagającego opcji kliknięcia do czegoś bardziej pobudzającego przy najmniejszym spadku poziomu dopaminy. Albo, ciągłe poszukiwanie *poprostu dla* odpowiedniej sceny dla maksymalnego efektu. Dodatkowo, możesz masturbować się w skulonej pozycji lub oglądać smartfona w łóżku w nocy, ostatecznie pożądając tych wskazówek bardziej niż bodźców z prawdziwego życia. Seks jest sprzeczny z niemal każdym aspektem haremu online, więc nie ma szans przy porównaniu. Wspomnienia stworzone, gdy jesteś młody, są potężne i długotrwałe, więc rozbicie tych pornograficznych zjeżdżalni wodnych i przewijanie lub tworzenie nowych trwa dłużej. Nie znaczy to jednak, że jest to trudniejsze.

Za każdym razem, gdy jeździsz na "pornograficznej zjeżdżalni wodnej", smarujesz ją, utrzymując nerwy świeże i gotowe do wystrzału. Kiedy parkujesz obok restauracji typu fast food, zapach smażalni unosi się w twoich nozdrzach i sprzedaż jest już dokonana. Podobnie, zjeżdżalnie porno w twoim mózgu są gotowe, by cię wciągnąć i są otwarte dwadzieścia cztery godziny na dobę. Każda wskazówka lub wyzwalacz zapala twój obwód nagrody z obietnicą seksu - tylko, że to nie jest seks. Niemniej jednak komórki nerwowe utrwalają te skojarzenia z podnieceniem seksualnym, wypuszczając nowe gałęzie, aby wzmocnić połączenia. Im więcej korzystasz z porno, tym silniejsze stają się te połączenia nerwowe. Efektem końcowym jest to, że ostatecznie możesz *potrzebować* bycia podglądaczem, potrzebować klikania na coraz to nowsze materiały, potrzebować porno, żeby zasnąć, lub potrzebować szukać idealnego zakończenia, żeby wykonać zadanie.

Jak w przypadku każdej substancji lub narkotyku behawioralnego, organizm buduje odporność i narkotyk przestaje całkowicie łagodzić pangi odstawienia. Jak tylko użytkownik porno zamyka sesję, chcą kolejny i szybko, stały głód pozostaje niezaspokojony. Naturalną skłonnością jest eskalacja, aby uzyskać dopaminowy przypływ. Jednak większość użytkowników nie może tego zrobić z jednego lub obu następujących powodów.

**Pieniądze:** Nie stać ich na subskrypcję płatnych stron porno.

*Zdrowie:* Ciało może znieść tylko tyle, albo skoki dopaminy, albo orgazmy. Plus, orgazmy faktycznie wyzwalają chemikalia, aby zmniejszyć dopaminowe płukanie. To musi być, to jest po prostu sposób, w jaki działa ciało.

Kiedy mały potwór opuści twoje ciało, kończy się okropne uczucie niepewności. Twoja pewność siebie powraca, wraz z cudownym uczuciem szacunku do samego siebie, uzyskując pewność, że możesz przejąć kontrolę nad swoim życiem i używając go jako odskoczni do rozwiązania innych problemów. Jest to jedna z wielu wspaniałych zalet uwolnienia się od jakiegokolwiek uzależnienia.

Mit o przedziałach jest jedną z wielu sztuczek, jakie mały potwór płata twojemu umysłowi. Sztuczki te sprawiają, że trudniej jest przestać - z powodu niemożliwego do zaspokojenia permanentnego głodu - powodując, że wielu użytkowników zwraca się ku papierosom, ciężkiemu piciu lub nawet twardszym narkotykom, aby zaspokoić pustkę.

Ludzie są zwierzętami oceniającymi, zarówno siebie, jak i innych. Oglądanie porno z partnerem jest niesatysfakcjonujące, ponieważ oboje oceniacie wzajemnie swoje osiągnięcia względem narracji. Czy chcesz mieć Brada Pitta w swojej sypialni, nawet jeśli jest na plakacie? Żadna osoba nie może się równać z haremem, w którym każde "doświadczenie" jest odgrywane, scenariuszowane, reżyserowane przez profesjonalistów i natychmiast dostępne dwadzieścia cztery godziny na dobę.