# Unikaj fałszywych zachęt

Wielu użytkowników metody siły woli próbuje zwiększyć swoją motywację poprzez konstruowanie fałszywych zachęt. Istnieje wiele takich przykładów, typowym jest nagradzanie się prezentami po nieoglądaniu porno przez miesiąc. Wydaje się to być logicznym i rozsądnym podejściem, ale w rzeczywistości jest fałszywe, ponieważ każdy szanujący się użytkownik wolałby kontynuować codzienne oglądanie porno, niż nagradzać się własnoręcznie przygotowanym prezentem. To rodzi wątpliwości w umyśle użytkownika, ponieważ nie tylko będzie musiał powstrzymać się od oglądania pornografii przez *trzydzieści dni*, ale nie jest pewien, czy będzie się nawet *cieszył* dniami bez pornografii. Ich jedyna przyjemność lub podpora została odebrana! Wszystko to zwiększa rozmiar poświęcenia, które użytkownik czuje, że czyni, teraz jeszcze bardziej cenne w jego umyśle.

Inne przykłady to:

-   Przestanę, żeby się zmusić do życia towarzyskiego i bardziej prawdziwego seksu.

-   Przestanę, żeby jakaś magiczna energia pomogła mi przeskoczyć przez konkurencję i dostać partnera, do którego dążę.

-   Przestanę, żeby mógł zobowiązać się do niemarnowania swojej energii i entuzjazmu pornografią, dążąc do powiększenia w sobie pragnienia.

Są one prawdziwe, mogą być skuteczne i może w końcu dostaniesz to, czego chcesz - ale pomyśl nad tym przez chwilę. Jeśli dostaniesz to, czego chciałeś, po odejściu nowości poczujesz się pozbawiony; jeśli nie, będziesz czuł się nieszczęśliwy. Tak czy inaczej, prędzej czy później znów wpadniesz w tę samą pułapkę.

Powiązanie rzucenia palenia z fałszywą zachętą tylko zwiększa wątpliwości, ponieważ jeśli nie dostaniesz zachęty (a nawet jeśli dostaniesz), zaczniesz myśleć o wątpliwościach, takich jak "*Czy rzucenie palenia rzeczywiście poprawi moje życie? Jeśli rzucę i nie dostanę tego, czego chcę, to czy użyłem metody poprawnie? "*. Myśli takie jak te zwiększają uczucia poświęcenia i dlatego tworzą napady.

Innym typowym przykładem są pakty internetowe lub forumowe, mają one tę zaletę, że eliminują pokusy na pewne okresy. Jednak na ogół zawodzą z następujących powodów:

1.  Zachęta jest fałszywa, dlaczego miałbyś chcieć przestać tylko dlatego, że inni ludzie tak robią? Wszystko, co to osiąga, to tworzenie dodatkowej presji i zwiększa poczucie poświęcenia. To dobrze, jeśli wszyscy użytkownicy autentycznie chcą przestać w jednym konkretnym czasie -- ale nie można ich zmusić do zatrzymania, chociaż wszyscy potajemnie chcą. Dopóki nie są na to gotowi, pakt tworzy dodatkową presję, która tylko zwiększa ich chęć oglądania. To zmienia ich w tajnych widzów, jeszcze bardziej zwiększając poczucie uzależnienia.

2.  Uzależnienie od siebie Stosowanie metody siły woli rodzi uczucia poddania się okresowi pokuty, podczas którego czekają, aż chęć zniknie. Jeśli ulegną, pojawia się poczucie porażki. Przy stosowaniu metody willpower przynajmniej jeden z uczestników na pewno się podda, dając pozostałym uczestnikom wymówkę, na którą czekali. To nie ich wina, oni by wytrzymali, ale "Fred" ich zawiódł. Prawda jest taka, że większość z nich już oszukiwała.

3.  Dzielenie się zasługami jest odwrotnością uzależnienia. Odstawienie pornografii daje wspaniałe poczucie osiągnięcia, a kiedy robi się to samemu, uznanie, jakie otrzymuje się od przyjaciół i internetowych kumpli, może być ogromnym impulsem w ciągu pierwszych kilku dni. Jednak gdy wszyscy robią to w tym samym czasie, kredyt musi być dzielony, a impuls jest w konsekwencji zmniejszony.

4.  Innym klasycznym przykładem jest obietnica guru. Zatrzymanie się da ci szczęście, ponieważ nie jesteś już zaangażowany w przeciąganie liny, twój mózg zaczyna przewijać i odzyskuje kontrolę nad impulsami. Musisz jednak pamiętać, że to nie sprawi, że staniesz się bogiem seksu lub wygrasz na loterii. Nikogo poza tobą nie obchodzi w najmniejszym stopniu, czy przestaniesz oglądać porno. Nie jesteś słabą osobą, jeśli używasz porno trzy razy dziennie i masz PIED*, ani silną osobą, jeśli jesteś uzależniony i nie masz.

* Porn-Induced Erectile Dysfunction (Rozdział 12)

Przestań się oszukiwać. Jeśli nie powstrzymała ich oferta dziesięciu miesięcy pracy za dwunastomiesięczną pensję w ciągu roku, albo ryzyko odcięcia zdolności twojego mózgu do radzenia sobie z codziennym stresem i napięciem, albo narażenie się na posiadanie niezawodnej erekcji, albo dożywotnie psychiczne i fizyczne tortury i niewolnictwo, to powyższe kilka fałszywych zachęt nie robi najmniejszej różnicy, udaje się tylko sprawić, że poświęcenie wydaje się gorsze. Zamiast tego, skup się na drugiej stronie:

\"Co ja z tego mam? Dlaczego muszę oglądać porno?"

Patrz na drugą stronę wojny i zadaj sobie pytanie, co porno robi dla ciebie. *ABSOLUTNIE NIC.* Dlaczego muszę to robić? *NIE MUSISZ! TYLKO TAK SIĘ KARZESZ.* To zakład Pascala: nie masz prawie nic do stracenia (zanikające pobudzenie), szanse na duże zyski (pełne i niezawodne pobudzenie, dobrostan psychiczny i szczęście) i żadnych szans na dużą stratę.

Dlaczego więc nie zadeklarować swojego odejścia z pracy znajomym i rodzinie? Cóż, to sprawi, że będziesz dumnym byłym uzależnionym lub byłym użytkownikiem, a nie podnieconym i szczęśliwym nieużytkownikiem. To może przestraszyć swojego partnera trochę, ponieważ mogą one zobaczyć to jako schemat, aby mieć więcej seksu, w rodzaju sposobu "new-age". Mogą też obawiać się, że zamienisz się w maszynę do uprawiania seksu, trudno to wyjaśnić, chyba że są otwarci.

Każda próba nakłonienia innych do pomocy w rzuceniu palenia daje więcej mocy temu małemu potworowi. Wypieranie go z umysłu i całkowite ignorowanie go daje efekt w postaci próby *nie* myślenia o nim. Zamiast tego bądź uważny, jak tylko zauważysz myśli, wskazówki (sam w domu) lub nieobecne myśli, powiedz sobie: "Świetnie, nie jestem już niewolnikiem porno. Jestem wolny i szczęśliwy, aby poznać różnice w seksie!"* To odetnie tlen do myśli i zatrzyma go od spalania w kierunku popędów i pragnień. W tym aspekcie praktykowanie medytacji z uważnością (mindfulness) może być pomocne w depersonalizacji myśli.


