# Łatwy sposób na zaprzestanie

Ten rozdział zawiera instrukcje dotyczące łatwego sposobu zatrzymania oglądania porno. Pod warunkiem, że będziesz postępował zgodnie z instrukcjami, przekonasz się, że zatrzymanie się waha się od stosunkowo łatwego do przyjemnego! Pod warunkiem, że będziesz postępował zgodnie z poniższymi instrukcjami, zatrzymanie porno jest śmiesznie proste, wszystko co musisz zrobić to dwie rzeczy.

1.  Podjąć decyzję, że nigdy nie zamierzasz oglądać porno ponownie.

2.  Nie smuć się z tego powodu. Raduj się.

Pewnie pytasz: "*Po co ta reszta książki? Dlaczego nie mogłeś tego powiedzieć na pierwszym miejscu?*". Cóż, odpowiedź jest taka, że w końcu smuciłeś się nad tym i w konsekwencji ostatecznie zmieniłbyś swoją decyzję. Prawdopodobnie zrobiłeś to już wiele razy wcześniej.

Jak już powiedziano, porno jest subtelną, złowrogą pułapką. Głównym problemem zatrzymania się nie jest uzależnienie od dopaminy -- które z pewnością jest problemem, ale nie podstawowym -- jest nim pranie mózgu. Dlatego najpierw trzeba zniszczyć wszystkie mity i złudzenia. Zrozum swojego wroga, poznaj jego taktykę, a łatwo go pokonasz. Po spędzeniu dużej części mojego życia w czarnej depresji podczas próby rzucenia, po ostatecznym wydostaniu się z niej, przeszedłem od razu do zera, bez żadnego złego momentu. Było to przyjemne nawet w okresie odstawienia i od tego czasu nigdy nie miałem najmniejszych problemów. Wręcz przeciwnie, była to jedna z najwspanialszych rzeczy, jakie wydarzyły się w moim życiu.

Moja ostateczna próba była inna. Jak wszyscy użytkownicy w dzisiejszych czasach, problem był poważnie przemyślany w moim umyśle. Do tej pory, po porażce, rutynowo pocieszałem się myślą, że następnym razem będzie łatwiej. Nigdy nie przyszło mi do głowy, że będę musiał iść tą drogą do końca życia, ta myśl napełniła mnie przerażeniem i zacząłem bardzo głęboko myśleć na ten temat.

Zamiast podświadomie odpalać przeglądarkę, przeanalizowałem swoje odczucia i potwierdziłem to, co już wiedziałem. Nie cieszyłem się porno i uważałem je za brudne i obrzydliwe. Zacząłem przyglądać się osobom nieużywającym porno, mieszkającym w innych częściach świata lub starszym, które nigdy nie poznały stron Hub. Do tego czasu, zawsze uważałem nie-użytkowników za nieśmiałych, nietowarzyskich, drobiazgowych ludzi. Jednakże, badając ich, gdy się pojawiali, wydawali się być - jeśli w ogóle - silniejsi i bardziej zrelaksowani. Wydawali się być w stanie poradzić sobie ze stresem i napięciem w życiu i wydawali się cieszyć funkcjami społecznymi bardziej niż użytkownicy porno. Z pewnością mieli więcej blasku i radości niż oni.

Zacząłem rozmawiać z byłymi użytkownikami. Do tego momentu zawsze uważałem ich za zmuszonych do rezygnacji z powodów zdrowotnych lub religijnych i zawsze potajemnie tęsknili za wizytą w haremie. Kilka osób powiedziało, *"Dostajesz dziwne napady, ale są one tak rzadkie, że nie warto się nimi przejmować. "* Większość zamiast tego powiedziała, *"Tęsknisz? Chyba żartujesz! Życie nigdy nie było lepsze!"* Nawet porażki były dla nich upadkiem do przodu, nie potępiali się i bezwarunkowo akceptowali zamiast tego. Jak trener, który zaakceptuje błąd autentycznie złotego gracza. Rozmowy z byłymi użytkownikami zniszczyły kolejny mit, który zawsze miałem w głowie, że jest we mnie jakaś nieodłączna słabość, dopóki nie dotarło do mnie, że wszyscy przechodzą przez ten prywatny koszmar.

Zasadniczo powiedziałem sobie: "Wielu ludzi przestaje teraz brać i prowadzi doskonale szczęśliwe życie, ja nie musiałem tego robić, zanim zacząłem i pamiętam, że musiałem ciężko pracować, aby przyzwyczaić się do tego syfu. Więc dlaczego muszę to robić teraz? "* W każdym razie nie cieszyłem się porno, nienawidząc całego plugawego rytuału i nie chciałem spędzić reszty życia w niewoli tego obrzydliwego nałogu. Powiedziałem wtedy do siebie tak:

*"Czy to ci się podoba czy nie, ukończyłeś swoją ostatnią sesję."*

Wiedziałem, właśnie od tego momentu, że nigdy nie będę miał innej sesji ponownie. Nie spodziewałam się, że będzie łatwo, tylko odwrotnie. W pełni wierzyłem, że zapisałem się na miesiące czarnej depresji i spędzenie reszty mojego życia mając okazjonalne napady. Zamiast tego, od samego początku było absolutnie błogo.

Dużo czasu zajęło mi ustalenie, dlaczego było to takie łatwe i dlaczego nie doświadczyłam tych przerażających bólów odstawienia. Powodem jest to, że nie istnieją, to wątpliwości i niepewność, która tworzy pangs. Piękna prawda jest taka, że ***łatwo jest zatrzymać porno.*** To tylko niezdecydowanie i ubolewanie, który czyni to trudne. Nawet podczas uzależnienia, użytkownicy mogą przejść przez stosunkowo długie okresy w niektórych czasach bez niego. Cierpisz tylko wtedy, gdy chcesz, ale nie możesz go mieć.

Dlatego kluczem do ułatwienia jest sprawienie, by zaprzestanie było pewne i ostateczne. Nie z nadzieją, ale *ze świadomością*, że już to zrobiłeś, że podjąłeś decyzję. Nigdy nie wątp, ani nie kwestionuj tego, wręcz przeciwnie - zawsze się ciesz! Jeśli możesz być pewien od samego początku, będzie to łatwe. Ale jak można być pewnym od samego początku? Dlatego właśnie reszta książki jest niezbędna. Istnieją pewne zasadnicze punkty, które trzeba sobie wyjaśnić w umyśle, zanim się zacznie:

1.  Uświadom sobie, że możesz to osiągnąć. Nie ma w tobie nic innego i jedyną osobą, która może sprawić, że będziesz oglądać, jesteś ty sam. Nie ta gwiazda, która nigdy w najśmielszych snach nie pomyślała o tym, że może zostać wykorzystana do zmniejszenia męskości.

2.  Nie ma absolutnie nic, z czego można by zrezygnować. Wręcz przeciwnie, można zyskać ogromne pozytywne korzyści. Nie tylko, że będziesz zdrowszy i bogatszy, ale będziesz bardziej cieszyć się dobrymi czasami i będziesz mniej nieszczęśliwy podczas złych.

3.  Nie ma czegoś takiego jak podglądanie czy odwiedzanie. Pornografia to narkomania i reakcja łańcuchowa, jęcząc o dziwnej wizycie będziesz tylko niepotrzebnie karać siebie.

4.  Zobacz porno nie jako nawyk typu "chłopcy będą chłopcami", który może cię zranić, ale jako uzależnienie od narkotyków. Zmierz się z faktem, że czy ci się to podoba czy nie, **masz chorobę.** Nie odejdzie ona dlatego, że chowasz głowę w piasek. Pamiętaj, że jak wszystkie wyniszczające choroby, nie tylko trwa przez całe życie, ale ulega wykładniczemu pogorszeniu. Najłatwiejszy czas na jej wyleczenie jest teraz.

5.  Oddziel chorobę -- neurologiczne uzależnienie -- od sposobu myślenia o byciu użytkownikiem lub nie. Wszyscy użytkownicy, gdyby mieli możliwość powrotu do czasu, zanim stali się uzależnieni, skoczyliby na tę okazję. Ty masz taką możliwość dzisiaj! Nawet nie myśl o tym jako o "poddaniu się".

Po podjęciu ostatecznej decyzji, że masz za sobą ostatnią wizytę, będziesz już nieużytkownikiem. Użytkownik to jeden z tych biednych nieszczęśników idących przez życie niszcząc się porno. Nieużytkownik to ktoś, kto tego nie robi. Kiedy już podejmiesz tę ostateczną decyzję, osiągnąłeś już swój cel. Ciesz się tym faktem, nie siedź i nie czekaj, aż chemiczne uzależnienie minie. Wyjdź z domu i natychmiast ciesz się życiem. Życie jest cudowne, nawet gdy jesteś uzależniony, a każdy dzień będzie o wiele lepszy, gdy nie będziesz.

Kluczem do ułatwienia rzucenia jest pewność, że uda ci się zachować całkowitą abstynencję podczas okresu odstawienia (maksymalnie trzy tygodnie). Jeśli jesteś w odpowiednim nastawieniu, będzie to śmiesznie łatwe.

Na tym etapie, jeśli otworzyłeś swój umysł zgodnie z prośbą na początku, będziesz już zdecydowany, że zamierzasz uciec. Powinieneś teraz mieć uczucia podniecenia, jak pies napinający się na smyczy, nie mogąc się doczekać, by zerwać zjeżdżalnie wodne porno z DeltaFosB . Jeśli masz uczucie zagłady i ponurości, będzie to z jednego z następujących powodów:

1.  Coś nie zgrało się w twoim umyśle. Przeczytaj ponownie pięć powyższych punktów i zadaj sobie pytanie, czy wierzysz w ich prawdziwość. Jeśli masz wątpliwości co do któregokolwiek punktu, przeczytaj ponownie odpowiednie fragmenty książki.

2.  Boisz się samej porażki. Nie martw się, po prostu czytaj dalej, a odniesiesz sukces. Cały biznes związany z internetowym porno to sztuczka zaufania na gigantyczną skalę. Inteligentni ludzie nabierają się na sztuczki pewności siebie, ale tylko głupiec, dowiedziawszy się o sztuczce, dalej się oszukuje.

3.  Zgadzasz się ze wszystkim, ale nadal jesteś nieszczęśliwy. Nie bądź!!! Otwórz oczy, dzieje się coś cudownego. Masz zamiar uciec z więzienia, koniecznie zacznij z odpowiednim nastawieniem: *"To cudowne, że jestem nieużywającym!"*.

Wszystko, co należy teraz zrobić, to utrzymać cię w tej ramie umysłu podczas okresu odstawienia, a następne kilka rozdziałów dotyczy konkretnych punktów, które ci to umożliwią. Po okresie wycofania nie będziesz musiał myśleć w ten sposób, będziesz myślał automatycznie, a jedyną zagadką w twoim życiu będzie to, dlaczego nie widziałeś tego wcześniej. Jednak dwa ważne ostrzeżenia.

- Opóźnij plan ostatniej wizyty do czasu, aż skończysz książkę.

- Wielokrotnie wspominano o trwającym do trzech tygodni okresie odstawienia, co może być przyczyną nieporozumień. Po pierwsze, możesz podświadomie poczuć, że musisz cierpieć przez trzy tygodnie. Wcale tak nie jest. Po drugie, unikaj pułapki myślenia *"Jakoś muszę się powstrzymać przez trzy tygodnie, a potem będzie dobrze "* Nic magicznego nie wydarzy się w rzeczywistości po trzech tygodniach, nie poczujesz się nagle jak osoba nieużywająca, ponieważ tak naprawdę nie czują się oni inaczej niż użytkownicy. Jeśli ubolewanie o zatrzymaniu podczas trzech tygodni, we wszystkich prawdopodobieństwie nadal będziesz ubolewał o tym po trzech tygodniach. Podsumowując, jeśli możesz zacząć już teraz mówiąc *"Nigdy więcej nie będę używał, czyż to nie wspaniałe? "*, po trzech tygodniach wszystkie pokusy znikną. Natomiast jeśli powiesz: *"Jeśli tylko uda mi się przetrwać te trzy tygodnie bez porno "*, to po upływie trzech tygodni będziesz umierał na wizytę w haremie.

Pomyśl o tym w ten sposób -- twój mózg chce utrzymać status quo, więc jeśli będziesz miał przekonanie, że rzucając palenie tracisz coś dobrego, to oczywiście będziesz czuł się okropnie. Nie da się zmusić siebie do tego, żeby czuć się w określony sposób, jeśli Twój mózg w to nie wierzy. Dlatego tak ważne jest, aby przejść przez trud usunięcia iluzji, że pornografia w ogóle coś ci daje. Dzięki temu wiesz, że nic nie poświęcasz.

Zaburzenie seksualne ma wiele wspólnego z twoim mózgiem i świadomością. Internetowe porno przeprogramowuje obwód nagrody w twoim mózgu i daje twojemu umysłowi nastawienie na "zwątpienie". To zwątpienie w siebie bez wątpienia spowoduje dysfunkcję seksualną. Posiadanie całego pożądania w górnej części, ale znoszenie braku podniecenia w dolnej jest najgorszą rzeczą, jaka może się zdarzyć w twoim sposobie myślenia. Libido idące w parze z romantyzmem jest eliksirem młodości, który możesz mieć aż do śmierci. Utrzymasz prawdopodobieństwo na wysokim poziomie rzucając palenie, ale to nie jest jedyny ani główny zysk. To twoja wolność od niewolnictwa!


