# Okres odstawienny

Przez okres do trzech tygodni po ostatniej sesji możesz być poddany napadom odstawienia. Składają się na nie dwa całkiem odrębne, ale jednak odrębne czynniki:

1.  Dopaminowe napady odstawienia. Puste, niepewne uczucie podobne do głodu, identyfikowane jako zachcianki lub uczucie "coś muszę zrobić".

2.  Psychologiczne wyzwalacze pewnych bodźców zewnętrznych, takich jak reklamy, przeglądanie stron internetowych, rozmowy telefoniczne itp.

Brak zrozumienia i rozróżnienia tych dwóch odrębnych czynników utrudnia osiągnięcie sukcesu przy użyciu metody siły woli i jest powodem, dla którego wielu, którym się to udaje, kończy się ponownym wpadnięciem w pułapkę. Chociaż napady odstawienia dopaminy nie powodują fizycznego bólu, nie lekceważ ich siły. Mówimy o "bólach głodowych", jeśli nie jemy przez dzień; może być burczenie w brzuchu, ale nie ma fizycznego bólu. Mimo to, głód jest potężną siłą i prawdopodobnie staniemy się bardzo drażliwi, gdy zostaniemy pozbawieni jedzenia. Jest to podobne do sytuacji, gdy nasze ciało pragnie dopaminy, z tą różnicą, że nasze ciało potrzebuje jedzenia, a nie trucizny. Przy odpowiednim nastawieniu, bóle odstawienia są łatwe do pokonania i znikają bardzo szybko.

Po kilkudniowej abstynencji metodą siły woli, pragnienie przypływu dopaminy szybko znika. To właśnie drugi czynnik -- pranie mózgu -- powoduje trudności. Użytkownik wyrobił sobie nawyk łagodzenia objawów odstawienia w określonych porach i przy określonych okazjach, co powoduje skojarzenie wyobrażeń (*"Jestem napalony, więc muszę oglądać porno "* lub "Jestem w łóżku z laptopem i muszę mieć sesję, żeby czuć się szczęśliwym*"). Efekt najlepiej zobrazować na przykładzie: Masz samochód i kierunkowskaz jest po lewej stronie, ale na następnym jest po prawej. Wiesz, że jest po lewej, ale przez kilka tygodni włączasz wycieraczki, gdy chcesz wskazać.

Zatrzymywanie się jest podobne, podczas wczesnych dni mechanizm spustowy będzie działał w określonych momentach. Będziesz myślał o tym, że chcesz sesję, więc dlatego przeciwdziałanie praniu mózgu jest niezbędne od samego początku i spowoduje, że te wskazówki i wyzwalacze szybko znikną. W metodzie siły woli, użytkownik wierzy, że się poświęca, użala się nad tym i czeka, aż popędy odejdą; daleko od usunięcia tych mechanizmów wyzwalających i faktycznie je zwiększa. Podobnie w przypadku myślenia guru, użytkownik zaczyna się zastanawiać, kiedy stanie się Bogiem, a nawet żąda, żeby nie miał takich myśli, torując sobie drogę do samouwielbienia i porażki.

Częstym czynnikiem wyzwalającym jest czas spędzony w samotności, szczególnie podczas spotkań towarzyskich z przyjaciółmi. Były użytkownik, który stosuje inne metody rzucania, jest już nieszczęśliwy z powodu poczucia, że został pozbawiony swojej zwykłej kuli lub przyjemności. Ich przyjaciele są ze swoimi partnerami i zachowują się intymnie. Użytkownik jest albo samotny lub nie "dostaje" żadnego od swojego partnera, a teraz już nie cieszy się tym, co powinno być przyjemną okazją społeczną. Ich istniejące ślizgi wody mózgowej prowadzą ich do porno, co jest łatwiejsze niż próba uwiedzenia swojego partnera.

Z powodu skojarzenia prawa do seksu z ich dobrobytem, teraz cierpią potrójny cios i pranie mózgu jest rzeczywiście zwiększone. Jeśli są zdecydowani i mogą wytrzymać wystarczająco długo, w końcu akceptują swój los i zaczynają żyć dalej. Jednak część prania mózgu nadal pozostaje, drugim najbardziej żałosnym aspektem jest to, że użytkownik rzucił palenie, ale nawet po kilku latach nadal pragnie "tylko ostatniej wizyty w haremie" przy pewnych okazjach. Tęsknią za iluzją, która istnieje tylko w ich umyśle i niepotrzebnie się torturują.

Nawet w EasyPeasy, reagowanie na bodźce jest najczęstszym błędem. Były użytkownik ma tendencję do traktowania pornografii internetowej jako rodzaju placebo lub pigułki cukrowej. Myśląc: "Wiem, że porno nic mi nie robi, ale jeśli myślę, że robi, to przy pewnych okazjach będzie pomocne". Cukierkowa pigułka, choć nie daje faktycznej fizycznej pomocy, może być potężną pomocą psychologiczną łagodzącą prawdziwe objawy i dlatego jest korzystna. Internetowe porno i nałogowa masturbacja nie są jednak cukrowymi pigułkami. Dlaczego? Porno tworzy objawy, które łagodzi i przestaje je całkowicie łagodzić.

Być może łatwiej będzie ci zrozumieć ten efekt, gdy odniesiesz go do osoby nieużywającej pornografii lub do skutecznego użytkownika, który rzucił ją na kilka lat. Weźmy przypadek użytkownika, który traci swojego partnera, jest to dość powszechne w takich chwilach z najlepszymi intencjami, aby powiedzieć: "*Miej jedną wizytę w haremie, to pomoże ci się uspokoić.*". Jeśli oferta zostanie przyjęta, nie będzie miała efektu uspokajającego, ponieważ nie ma uzależnienia od dopaminy, a zatem nie ma pangs odstawienia. W najlepszym wypadku wszystko, co zrobi, to da im chwilowy impuls psychologiczny.

Nawet po zakończeniu sesji, pierwotna tragedia jest tam. W rzeczywistości, to będzie zwiększona, ponieważ osoba teraz cierpi napady odstawienia, wybór jest wytrzymując je, lub ulgę poprzez powtarzanie zjeżdżalni wodnych przejażdżki rozpocząć łańcuch nieszczęścia wszystko od nowa. Wszystko porno dostarczył był przelotny impuls psychologiczny, taki sam, który mógł być osiągnięty przez książkę lub filmy typu "feel-good", nawet przez zły. Wiele osób nieużywających i byłych użytkowników stało się ponownie uzależnionych w wyniku takich sytuacji. Wyjaśnij to sobie w głowie: Nie potrzebujesz przypływu dopaminy i tylko torturujesz siebie dalej, kontynuując traktowanie jej jako jakiegoś rekwizytu lub pobudzenia. Nie ma potrzeby, aby być nieszczęśliwym.

Orgazmy nie tworzą dobrych relacji; najczęściej je rujnują. Pamiętaj też, że nie jest do końca prawdą, że ci, którzy publicznie okazują uczucia, cieszą się z każdej okazji. Intymność najlepiej przeżywać na osobności, gdzie partnerzy mogą reagować bez zakłopotania, nie musisz być uzależniony od dopaminy wywołującej orgazm. Jeśli zdarza się to jako naturalny wynik serii wydarzeń życiowych, to dobrze, ale ciesz się okazją i życiem bez niej.

Po porzuceniu koncepcji porno jako przyjemnego samego w sobie, wielu użytkowników myśli "*Gdyby tylko istniało czyste internetowe porno*". Istnieje czyste soft porno, a każdy kto go spróbuje szybko przekonuje się, że to strata czasu. Uzyskaj jasność w swoim umyśle, że jedynym powodem, dla którego używasz porno jest uzyskanie dopaminowego zalania. Gdy pozbędziesz się dopaminy, nie będziesz miał potrzeby odwiedzania swojego internetowego haremu.

Niezależnie od tego, czy pangi są spowodowane rzeczywistymi objawami odstawienia dopaminy, czy też mechanizmami spustowymi, zaakceptuj je. Fizyczny ból jest nieistniejący i z odpowiednią ramą umysłu nie będzie problemem. Nie martw się o wycofanie, samo uczucie nie jest złe. To skojarzenie z pragnieniem, a następnie uczucie odmowy, które jest problemem. Zamiast się nad tym użalać, uznaj to: "*Wiem, co to jest, to napad odstawienia od pornografii. To jest to, co użytkownicy cierpią przez całe życie i utrzymuje ich w uzależnieniu. Osoby nieużywające porno nie cierpią z tego powodu, jest to kolejne zło tego kłamliwego nałogu. Czy to nie cudowne, że oczyszczam to zło z mojego mózgu!"*.

Innymi słowy, przez następne trzy tygodnie będziesz miał lekką traumę wewnątrz swojego ciała, ale w ciągu tych tygodni i przez resztę swojego życia będzie się działo coś cudownego. Pozbędziesz się okropnej choroby, której korzyści znacznie przewyższają lekką traumę, a także będziesz cieszyć się bólami odstawienia. Staną się one chwilami przyjemności, jak ekscytująca gra w głodzenie tasiemca pornograficznego żyjącego w twoim żołądku. Musisz głodzić go przez trzy tygodnie, podczas gdy on próbuje oszukać cię, aby dostać się do łóżka, aby utrzymać go przy życiu.

Czasami będzie próbowało cię unieszczęśliwić. Czasami zostaniesz zaskoczony. Otrzymasz adres URL do porno lub natkniesz się na coś online i zapomnisz, że się zatrzymałeś, lekkie uczucie deprywacji, gdy sobie przypomnisz. Bądź przygotowany na te sztuczki z wyprzedzeniem i niezależnie od pokusy, wbij sobie do głowy, że jest tam tylko z powodu potwora w twoim ciele i za każdym razem, gdy oprzesz się pokusie, zadajesz kolejny moralny cios w walce.

Cokolwiek robisz, nie próbuj zapomnieć o porno. Jest to jedna z rzeczy, która powoduje, że PMOwcy używający metody siły woli godzinami popadają w depresję. Próbują przebrnąć przez każdy dzień mając nadzieję, że w końcu po prostu o tym zapomną. To tak jak z niemożnością zaśnięcia - im bardziej się o to martwisz, tym trudniej jest to zrobić. W każdym razie nie będziesz w stanie o tym zapomnieć, przez pierwsze kilka dni "mały potwór" będzie ci o tym przypominał i nie będziesz w stanie go uniknąć. Podczas gdy wokół nadal będą laptopy, smartfony i czasopisma, będziesz miał ciągłe przypomnienia.

Chodzi o to, że nie masz potrzeby zapominać, nic złego się nie dzieje. W rzeczywistości dzieje się coś wspaniałego i cudownego i nawet jeśli myślisz o tym tysiąc razy dziennie, **rozkoszuj się każdą chwilą, przypominaj sobie jak cudownie jest być znowu wolnym. Przypomnij sobie o czystej radości z tego, że nie musisz się już torturować.** Jak powiedziano wcześniej, przekonasz się, że pangi stają się chwilami przyjemności, będąc zaskoczonym, jak szybko potem zapomnisz o porno.

Cokolwiek zrobisz, *nie wątp w swoją decyzję*. Kiedy zaczniesz wątpić, zaczniesz się użalać i będzie jeszcze gorzej. Zamiast tego, wykorzystaj ten moment zwątpienia i przekształć go w impuls do działania. Jeśli przyczyną jest depresja, przypomnij sobie, że porno ją wywołało. Jeśli przyjaciel poda ci adres URL, z dumą powiedz: "*Cieszę się, że już tego nie potrzebuję". To ich zaboli, ale gdy zobaczą, że nie przeszkadza ci to, będą w połowie drogi, by do ciebie dołączyć.

**Pamiętaj: masz niesamowicie silne powody, aby przestać w pierwszej kolejności.** Przypomnij sobie o kosztach i zadaj sobie pytanie, czy naprawdę chcesz ryzykować nieprawidłowe funkcjonowanie swojego ciała, umysłu i prosty fakt, że będziesz żył pod zaklęciem przez resztę swojego życia. Miej na uwadze wysiłki małego potwora, aby zminimalizować zagrożenia, a przede wszystkim pamiętaj, że uczucie jest tylko tymczasowe, a każda chwila to moment bliżej Twojego celu.

Niektórzy użytkownicy obawiają się, że będą musieli spędzić resztę życia na odwracaniu "automatycznych wyzwalaczy". Innymi słowy, wierząc, że będą musieli przejść przez całe życie oszukując samych siebie, że nie potrzebują porno poprzez stosowanie psychologii. To nie jest tak, pamiętaj, że optymista widzi butelkę w połowie pełną, a pesymista w połowie pustą. W przypadku pornografii butelka jest pusta, a użytkownik widzi ją jako pełną. Korzystanie z internetowego porno nie ma żadnych zalet. To użytkownik został poddany praniu mózgu, aby myśleć, że są. Kiedy zaczniesz mówić sobie, że nie potrzebujesz ani nie chcesz porno, w bardzo krótkim czasie nie będziesz musiał nawet tego mówić, sam widząc piękną prawdę. To ostatnia rzecz, którą musisz zrobić; upewnij się, że nie jest to ostatnia rzecz, którą robisz.



