# Tylko jedno małe zerknięcie

To jest zguba wielu używających metody siły woli. Przechodzą przez trzy lub cztery dni, a następnie mają dziwne zerknięcie, aby je obejść. Nie zdają sobie sprawy z niszczącego wpływu, jaki ma to na ich morale.

Dla większości użytkowników, ich pierwsze spojrzenie na stronie harem w Hub nie było tak dobre, jak seks z prawdziwą osobą. Klipy, które są czyste, są dalekie i rzadkie, dając ich świadomym umysłem impuls. Myśląc: "*Dobrze, to nie było do końca wszystko, co przyjemne. Tracę ochotę i nie jestem już tak nastawiony na szokujące rzeczy*". W rzeczywistości jest odwrotnie. Uzyskaj jasność w swoim umyśle, przyjemność z orgazmu nie była powodem, dla którego rzuciłeś porno. Gdyby użytkownicy byli tam dla samego orgazmu, nigdy nie oglądaliby więcej niż jednego klipu. Jedynym powodem, dla którego potrzebowałeś porno, było karmienie tego małego potwora. Pomyśl tylko, po głodzeniu przez cztery dni, jak cenne musiało być dla niego to jedno zerknięcie. Twój świadomy umysł jest nieświadomy, ale poprawka, którą otrzymało twoje ciało, jest przekazywana do twojej podświadomości, a całe twoje solidne przygotowanie zostanie podważone. Będą to małe głosy z tyłu twojego umysłu mówiące mimo całej logiki sesje są cenne i że chcesz jeszcze jedną.

To małe podglądanie ma dwa szkodliwe skutki:

1.  Utrzymuje przy życiu małego potwora w twoim ciele.

2.  Co gorsza, utrzymuje przy życiu wielkiego potwora w twoim umyśle. Jeśli miałeś 'ostatnie zerknięcie' łatwiej będzie mieć następne.

Porno to pułapka na myszy bez sera, tylko trucizna. Używając siły woli musisz przekonać siebie, żeby nie chwytać sera, ale EasyPeasy pozwala ci zobaczyć, że to trucizna. Nie musisz jej unikać, wystarczy, że nie będziesz w nią wchodził.

Przede wszystkim jednak pamiętaj:

*"Tylko jedno zerknięcie" to sposób, w jaki ludzie wpadają w uzależnienie w pierwszej kolejności."*


