# Czy będzie to dla mnie trudniejsze?

Istnieje nieskończona ilość kombinacji czynników decydujących o tym, jak łatwo każdy z użytkowników rzuci. Na początek każdy z nas ma swój własny charakter, karierę, osobiste uwarunkowania, czas, metabolizm itd. Niektóre zawody mogą utrudniać rzucenie, ale pod warunkiem usunięcia prania mózgu wcale nie musi tak być. Weźmy kilka poniższych przykładów.

Czasami jest to trudne dla członków zawodu lekarza. Myślimy, że lekarzom powinno być łatwiej, ponieważ są bardziej świadomi skutków, ale chociaż dostarcza to bardziej zdecydowanych powodów do zaprzestania, nie czyni tego łatwiejszym do osiągnięcia. Powody są następujące:

1.  Stała świadomość zagrożeń dla zdrowia wywołuje strach, jeden z warunków, w których potrzebujemy złagodzenia napadów odstawienia.

2.  Praca lekarza jest niezwykle stresująca i zazwyczaj nie są oni w stanie rozładować dodatkowego stresu, jakim są stany odstawienne, podczas pracy.

3.  Mają dodatkowy stres związany z poczuciem winy, poczuciem, że powinni dawać przykład reszcie społeczeństwa. To nakłada na nich większą presję i zwiększa poczucie deprywacji.

Po ciężkim dniu w pracy, kiedy ich stres jest chwilowo łagodzony przez porno, sesja ta staje się nieprawidłowo związana z doświadczoną ulgą. Z powodu tego błędnego skojarzenia porno dostaje zasługi za całą sytuację, stając się nagle bardzo cenne przy rzucaniu i przechodzeniu przez napady odstawienia. Jest to forma zwyczajnego użytkownika i odnosi się do każdej sytuacji, w której użytkownik jest zmuszony do długotrwałej abstynencji. W metodzie siły woli użytkownik jest nieszczęśliwy, ponieważ jest pozbawiony i nie cieszy się zmęczeniem i snem, który przychodzi po sesji. Ich poczucie straty jest znacznie zwiększone. Jeśli jednak najpierw uda się usunąć pranie mózgu i snucie się dotyczące porno, przerwą i snem można się cieszyć nawet wtedy, gdy organizm łaknie przekaźników aminowych -- serotoniny, noradrenaliny i dopaminy.

Inną trudną sytuacją jest nuda, zwłaszcza w połączeniu z okresami stresu. Typowym przykładem są studenci i samotni rodzice, praca jest stresująca, a jednocześnie monotonna. Podczas próby zatrzymania się metodą siły woli, osoba samotna ma długie okresy, w których może użalać się nad swoją "stratą", co z kolei zwiększa uczucie depresji. Ponownie, to może być łatwo pokonać, jeśli rama umysłu jest prawidłowy. Nie przejmuj się tym, że ciągle przypominasz sobie, że przestałeś uprawiać pornografię. Wykorzystaj takie chwile, aby cieszyć się z faktu, że pozbyłeś się tego złego potwora.

Jeśli masz pozytywne nastawienie, to te napady staną się chwilami przyjemności. Pamiętaj, że każdy użytkownik bez względu na wiek, płeć, inteligencję czy zawód może znaleźć łatwe i przyjemne zatrzymanie pod warunkiem, że **podążasz za wszystkimi instrukcjami.**

## Główne przyczyny niepowodzeń

Istnieją dwie podstawowe przyczyny niepowodzeń. Pierwsza to wpływ bodźców zewnętrznych -- reklama, artykuł informacyjny w sieci, przeglądanie internetu itp. Znajdują się w słabym momencie, a nawet stają się zazdrośni, gdy widzą intymność w scenariuszach społecznych. Ten temat został już obszernie omówiony. Wykorzystaj ten moment, aby przypomnieć sobie, że nie ma czegoś takiego jak jedna wizyta czy podglądanie. Ciesz się z faktu, że przerwałeś łańcuch mentalnego niewolnictwa. Pamiętaj, że użytkownik Ci zazdrości i powinieneś mu współczuć, bo tego potrzebuje.

Drugi powód to posiadanie złego dnia. Zanim zaczniesz, uświadom sobie, że niezależnie od tego, czy jesteś użytkownikiem, czy nie, będziesz miał dobre i złe dni. Deszcz pada zarówno na papieża jak i na mordercę. Życie jest względne i nie można mieć wzlotów bez upadków. Problem z metodą siły woli polega na tym, że jak tylko użytkownik ma zły dzień, zaczyna się mizdrzyć do wizyty w "haremie", co jeszcze bardziej potęguje problem. Nieużytkownik jest lepiej przygotowany do radzenia sobie ze stresem i obciążeniami, nie tylko fizycznymi, ale i psychicznymi. Jeśli masz zły dzień podczas okresu odstawienia po prostu wziąć go na brodę, przypomnij sobie, że złe dni istniały, gdy byłeś uzależniony, inaczej nie zdecydowałbyś się zatrzymać. Zamiast ubolewania nad tym, uznaj to zamiast: *"Ok, więc dzisiaj nie jest tak dobrze, ale porno tego nie wyleczy. Jutro będzie lepiej i przynajmniej mam cudowną premię - rzuciłem ten okropny nałóg "*.

Kiedy jesteś użytkownikiem porno, musisz zablokować swój umysł na negatywy porno. Użytkownicy nigdy nie mają mgły mózgowej, są po prostu "trochę przygnębieni". Kiedy masz nieuniknione życiowe kłopoty i doświadczasz myśli o chęci posiadania porno, czy jesteś szczęśliwy i radosny? Oczywiście, że nie. Kiedy już przestaniesz, pojawia się tendencja do obwiniania wszystkiego, co idzie źle, o to, że przestałeś.

Jeśli praca cię stresuje, myślisz: "*W takich chwilach miałbym sesję*". To prawda, ale ważną rzeczą, o której się zapomina jest to, że porno nie rozwiązało problemu, a ty po prostu karzesz się ubolewaniem za iluzoryczne podpory. Tworzysz niemożliwą sytuację, nieszczęśliwy, ponieważ nie możesz masturbować się do porno, a jednak będziesz jeszcze bardziej nieszczęśliwy, jeśli to zrobisz. *Wiesz, że podjąłeś właściwą decyzję zaprzestając tego, więc po co karać się wątpiąc w swoją decyzję?

Pamiętaj, że pozytywne podejście psychiczne jest niezbędne -- zawsze.


