# Zamienniki

Niektóre przykłady zamienników obejmują ograniczanie się do magazynów porno, statycznych obrazów internetowych, porno-diet itp. **NIE UŻYWAJ ŻADNEGO Z NICH.** One sprawiają, że jest trudniej, a nie łatwiej. Jeśli dostaniesz napad i użyjesz substytutu, to tylko przedłuży to pangę, czyniąc ją trudniejszą. Tak naprawdę mówisz, że potrzebujesz porno, żeby wypełnić pustkę. To będzie jak poddanie się porywaczowi lub dziecięcej furii, tylko utrzymywanie nadchodzących bólów i przedłużanie tortur. W każdym razie, substytuty nie łagodzą bólów. Twoje pragnienie jest dla aminokwasów w mózgu, wszystko, co to zrobi, to utrzyma cię w myśleniu o porno. Zapamiętaj te punkty:

1.  Nie ma substytutu dla porno.

2.  Nie potrzebujesz porno. To nie jest jedzenie, to trucizna. Kiedy nadejdą bóle, przypomnij sobie, że to użytkownicy cierpią na bóle odstawienne, a nie osoby nieużywające. Zobacz je za to, czym są, kolejnym złem narkotyku. Zobacz je jako śmierć potwora.

3.  Internetowe porno tworzy pustkę; nie wypełnia jej. Im szybciej nauczysz swój mózg, że nie musisz oglądać, tym szybciej będziesz wolny. W szczególności unikaj wszystkiego, co przypomina porno, jak magazyny dla mężczyzn, filmy, powieści romantyczne i reklamy. To nie jest bycie zamkniętym umysłem, to jest w porządku, aby mówić o romansie i seksie, ale nie porno. Zawsze można znaleźć sposób na to, kiedy i gdzie można dyskryminować. Prawdą jest, że niewielki odsetek użytkowników, którzy próbują rzucić korzystanie z softcore porn lub diet porno, odnoszą sukces (z własnej perspektywy) i przypisują swój sukces temu korzystaniu. Jednak rzucają oni *pomimo* używania pornografii, a nie z jej powodu. To niefortunne, że wielu nadal zaleca te środki.

Nie jest to zaskakujące, ponieważ jeśli nie rozumiesz w pełni pułapki porno, dieta lub miękki substytut brzmi bardzo logicznie. Opiera się na przekonaniu, że kiedy próbujesz rzucić porno, masz dwóch potężnych wrogów do pokonania:

	- Przełamanie nawyku.

	- Przetrwanie strasznych fizycznych bólów odstawienia.

Jeśli masz dwóch potężnych wrogów do pokonania, to rozsądnie jest nie walczyć z nimi jednocześnie, ale po kolei. Tak więc teoria mówi, że kiedy po raz pierwszy przestajesz używać porno, obcinasz do raz w tygodniu lub używasz bezpiecznego porno. Następnie, gdy nawyk zostanie przełamany, stopniowo zmniejszaj podaż, w ten sposób zwalczając każdego wroga osobno.

Brzmi to logicznie, ale jest oparte na błędnych informacjach. Porno nie jest nawykiem, ale uzależnieniem od dopaminy, a rzeczywisty fizyczny ból z odstawienia jest prawie niedostrzegalny. To, co próbujesz osiągnąć podczas rzucania, to zabicie obu potworów w twoim ciele i mózgu tak szybko, jak to możliwe. Wszystkie techniki zastępcze przedłużają życie małego potwora, a to z kolei przedłuża pranie mózgu. EasyPeasy ułatwia natychmiastowe rzucenie palenia, zabijając pranie mózgu przed ostatnią sesją. Mały potwór wkrótce będzie martwy, a nawet podczas umierania nie będzie stanowił większego problemu niż wtedy, gdy byłeś użytkownikiem.

Pomyśl tylko, jak można leczyć uzależnienie od narkotyku poprzez polecanie tego samego narkotyku? W sieci można znaleźć wiele historii o tych, którzy przestali korzystać z hardcorowego porno w internecie, ale są uzależnieni od "bezpiecznych" alternatyw, dając się nabrać na usprawiedliwienia swojego małego potwora. Nie dajcie się zwieść temu, że bezpieczne porno nie jest okropne - tak samo było z tym pierwszym szybkim klipem. Wszystkie substytuty mają dokładnie takie same efekty jak każde porno. Niektórzy nawet zaczynają jeść, ale choć puste uczucie chęci na sesję jest nieodróżnialne od głodu jedzenia, jedno nie zaspokoi drugiego. W rzeczywistości, jeśli jest coś, co jest zaprojektowane, aby sprawić, że chcesz porno, to jest to napychanie się jedzeniem. Jak już wcześniej wyjaśniono, diety porno i bezpieczne porno postawią cię jedynie w środku wojny, a opór wobec pokusy będzie tak irytujący, że poczujesz ulgę odwiedzając swój ulubiony internetowy harem.

Głównym złem substytutów jest przedłużanie prawdziwego problemu - prania mózgu. Czy potrzebujesz substytutu grypy, gdy się skończy? Oczywiście, że nie. Mówiąc, że potrzebujesz substytutu dla porno, tak naprawdę mówisz, że się poświęcasz. Depresja związana z metodą siły woli jest spowodowana tym, że użytkownik wierzy, że się poświęca. Wszystko, co będziesz robić, to zastępowanie jednego problemu innym. Nie ma żadnej przyjemności w opychaniu się jedzeniem, papierosami czy alkoholem. Będziesz tylko gruby, nieszczęśliwy i w krótkim czasie wrócisz do narkotyku.

Zwyczajnym użytkownikom trudno jest odrzucić przekonanie, że są pozbawieni swojej małej nagrody, tak jak ci, którzy nie mogą wejść do Internetu w okresie czasu podczas podróży, wydarzenia rodzinnego itp. Niektórzy mówią: "*Nie wiedziałbym jak się zrelaksować, gdyby nie porno*". To dowodzi sedna sprawy, często przerwa jest brana nie dlatego, że użytkownik potrzebuje lub nawet chce, ale dlatego, że uzależniony -- a tym właśnie są -- desperacko potrzebuje podrapać swędzenie.

Pamiętaj, że sesje porno nigdy nie były prawdziwymi nagrodami. Były odpowiednikiem noszenia ciasnych butów po to, żeby mieć przyjemność z ich zdejmowania. Więc jeśli czujesz, że musisz mieć małą nagrodę, niech to będzie twój substytut; podczas pracy załóż buty lub bieliznę o rozmiar za małą, i nie pozwól sobie na ich zdjęcie, dopóki nie zrobisz sobie przerwy, a następnie przeżyj cudowny moment relaksu i satysfakcji, kiedy zostaną zdjęte. Być może uważasz, że byłoby to raczej głupie. Masz całkowitą rację. To może być trudne do wizualizacji, gdy wciąż jesteś w pułapce, ale to właśnie robią użytkownicy. Trudno też sobie wyobrazić, że wkrótce nie będziesz potrzebował tej małej "nagrody" i że wkrótce będziesz patrzył na znajomych, którzy wciąż są w pułapce ze szczerym politowaniem i zastanawiał się, dlaczego nie widzą sensu.

Jeśli jednak nadal będziesz się oszukiwać, że wizyta w internetowym haremie była prawdziwą nagrodą, albo że potrzebujesz jej substytutu, będziesz się czuł pozbawiony i nieszczęśliwy. Są szanse, że w końcu znów wpadniesz w obrzydliwą pułapkę. Jeśli potrzebujesz prawdziwej przerwy, jak robią to gospodynie domowe, nauczyciele, lekarze i inni pracownicy, wkrótce będziesz cieszyć się tą przerwą jeszcze bardziej, ponieważ nie będziesz musiał się uzależniać. Pamiętaj, że nie potrzebujesz substytutu. Napady są łaknieniem dopaminy i wkrótce znikną. Niech to będzie twój rekwizyt na najbliższe dni i ciesz się pozbywaniem swojego ciała i umysłu z niewoli i uzależnienia.


