# Czy powinienem unikać kuszących sytuacji?

Dotychczasowa porada była bezpośrednia i prosiła o traktowanie jej raczej jako instrukcji niż sugestii. Istnieją solidne, praktyczne powody dla tej porady i te powody zostały poparte tysiącami studiów przypadków. W kwestii tego, czy należy próbować unikać pokus, czy nie, nie jest to prawdą. Każdy użytkownik będzie musiał sam podjąć decyzję. Można jednak podać dwie pomocne sugestie, które pomogą Ci w tym procesie. To strach przed przyszłymi bólami odstawienia, które utrzymują nas przy używaniu porno przez resztę naszego życia, a strach ten składa się z dwóch odrębnych faz.

**Faza pierwsza - "*Jak mogę przetrwać bez pornografii?*"**

Ten strach jest panicznym uczuciem, którego doświadcza użytkownik, gdy jest samotny lub ma aseksualną, niezainteresowaną lub niedostępną partnerkę. Lęk ten nie jest spowodowany stanami odstawienia, ale psychologicznym strachem przed uzależnieniem, niemożnością przetrwania bez seksu i orgazmu. Szczytuje on, kiedy na skraju rzucenia, kiedy twoje bóle odstawienia są najniższe. Jest to strach przed nieznanym, taki, jaki mają ludzie, którzy uczą się nurkować.

Deska do nurkowania ma wysokość jednej stopy, ale wydaje się, że ma sześć stóp. Woda ma sześć stóp głębokości, ale wydaje się, że ma jedną stopę. Trzeba mieć odwagę, żeby się wystrzelić, będąc przekonanym, że rozbije się głowę. Wystrzelenie się jest najtrudniejszą częścią, jeśli znajdziesz odwagę, by to zrobić, reszta jest łatwa! To wyjaśnia, dlaczego wielu użytkowników o silnej woli nigdy nie próbowało przestać, lub może przetrwać tylko kilka dni, gdy to zrobią. W rzeczywistości są tacy użytkownicy na porno dietach, którzy po podjęciu decyzji o zatrzymaniu, faktycznie nadużywają i eskalują do ostrzejszych klipów szybciej niż gdyby nie zdecydowali się zatrzymać. Decyzja ta wywołuje panikę, która jest stresująca i wyzwala sygnał do podjęcia wycieczki do haremu. Ale teraz nie można go mieć, co prowadzi do myśli o deprywacji i potęguje stres.

Spust aktywuje się szybko, gdy bezpiecznik wybuchnie, a ty odpalisz przeglądarkę. Nie martw się, panika jest tylko psychologiczna. To strach, od którego jesteś uzależniony. Piękna prawda jest taka, że nie jesteś, nawet gdy wciąż jesteś uzależniony. Nie wpadaj w panikę i wystrzel się.

**Faza druga - Długoterminowy strach**

Druga faza jest długotrwała, wiąże się z lękiem, że pewne sytuacje w przyszłości nie będą przyjemne lub nie będziesz w stanie poradzić sobie z traumą bez porno. Nie martw się, jeśli uda Ci się uruchomić siebie, stwierdzisz, że jest wręcz przeciwnie. Samo unikanie pokus dzieli się na dwie kategorie.

1.  "*Piszę się na dietę porno raz na cztery dni. Będę czuł się pewniej wiedząc, że mogę wejść do internetu, jeśli będzie ciężko. Jeśli nie uda mi się to w porządku, po prostu dodam dodatkowe dni do mojego następnego cyklu.*"

    Wskaźnik niepowodzeń u ludzi robiących to jest **znacznie wyższy** niż u tych, którzy całkowicie rezygnują. Wynika to głównie z faktu, że jeśli masz zły moment w okresie odstawienia, łatwo jest wskoczyć na przeglądarkę i odwiedzić harem z powyższymi wymówkami. Jeśli masz upokorzenie w postaci wyraźnego złamania własnych zasad jak roztrzaskana szyba, jesteś bardziej skłonny do pokonania pokusy. W każdym razie, napad prawdopodobnie już by minął, gdybyś zwlekał. Jednak główną przyczyną wysokiego wskaźnika niepowodzeń w tych przypadkach jest to, że użytkownik nie czuł się w pełni zaangażowany w zatrzymanie się w pierwszej kolejności. Pamiętaj, że dwa niezbędne elementy do osiągnięcia sukcesu to:

    - Pewność.

    - "*Czy to nie cudowne, że nie potrzebuję już porno?*"

    W obu przypadkach, po co u licha potrzebujesz sesji? Jeśli nadal musisz odwiedzać swój harem, najpierw przeczytaj ponownie książkę. Coś nie do końca się zgrało. Poświęć czas na zabicie wielkiego potwora piorącego mózg w twoim umyśle.

2.  "*Czy powinienem unikać stresujących lub społecznych okazji podczas okresu odstawienia?"

    W przypadku sytuacji stresowych, tak. Nie ma sensu nakładać na siebie niepotrzebnej presji. W przypadku wydarzeń społecznych, takich jak bary czy kluby, rada jest odwrotna. Wyjdź i ciesz się sobą od razu, nie potrzebujesz seksu ani propagacyjnej strony seksu, nawet gdy jesteś uzależniony od porno. Wyjdź i ciesz się tym, że nie musisz uprawiać seksu ani propagacyjnej strony seksu, to szybko udowodni Ci piękną prawdę, że życie jest o wiele lepsze bez tych presji. Pomyśl tylko, o ile lepiej będzie, gdy mały potwór Cię opuści, razem z tymi potrzebującymi myślami.


