# Moment objawienia

Zazwyczaj w ciągu trzech tygodni po ucieczce, byli użytkownicy doświadczają momentu objawienia. Niebo wydaje się jaśniejsze i jest to moment, w którym pranie mózgu całkowicie się kończy. Kiedy zamiast wmawiać sobie, że nie musisz oglądać porno, nagle zdajesz sobie sprawę, że ostatnia nić została przerwana i możesz cieszyć się resztą swojego życia, nie potrzebując już nigdy więcej. To również od tego momentu zazwyczaj zaczynasz patrzeć na użytkowników jak na obiekty litości.

Osoby rzucające palenie metodą siły woli zazwyczaj nie doświadczają tego momentu, bo choć cieszą się, że są byłymi użytkownikami, to nadal idą przez życie wierząc, że się poświęcają. Im bardziej byłeś uzależniony, tym bardziej cudowny jest ten moment i trwa on przez całe życie. Chociaż w życiu jest wiele radości, nie da się odtworzyć rzeczywistego uczucia ich doświadczania. Radość z tego, że nie musisz już oglądać porno jest inna, jeśli masz doła i potrzebujesz zastrzyku energii, przypomnij sobie, jak pięknie jest nie być uzależnionym od tego okropnego nałogu. Wielu wymienia to jako jedno z największych wydarzeń w swoim życiu. W większości przypadków moment objawienia następuje nie po trzech tygodniach, ale po kilku dniach.

W moim własnym przypadku stało się to przed zakończeniem mojej ostatniej wizyty w haremie. Jestem pewien, że wielu czytelników tutaj, zanim jeszcze dotarli do końca rozdziałów, powiedziałoby coś w stylu "*Nie musisz mówić więcej. Widzę to wszystko tak wyraźnie, że wiem, że już nigdy nie będę potrzebował porno*". Na podstawie otrzymanych informacji zwrotnych, zdarza się to często. W idealnej sytuacji, jeśli zastosujesz się do wszystkich instrukcji i całkowicie zrozumiesz psychologię, powinno ci się to przydarzyć natychmiast.

Chociaż stwierdza się, że potrzeba około pięciu dni na zauważalne fizyczne wycofanie się, a około trzech tygodni na całkowite uwolnienie się byłego użytkownika, takie wytyczne mogą powodować dwa problemy. Pierwszym z nich jest to, że sugestia jest wszczepiona w umysły ludzi, że będą musieli cierpieć przez okres od pięciu dni do trzech tygodni. Drugi jest taki, że były użytkownik ma tendencję do myślenia "*Jeśli uda mi się przetrwać przez pięć dni lub trzy tygodnie, to pod koniec tego okresu mogę spodziewać się prawdziwego wzmocnienia".

Mogą jednak mieć pięć przyjemnych dni lub trzy przyjemne tygodnie, po których następują katastrofalne dni, które uderzają w każdego, a które nie mają nic wspólnego z uzależnieniem, lecz są spowodowane innymi czynnikami w naszym życiu. Wtedy nasz były użytkownik, który czeka na moment objawienia, doświadcza zamiast tego depresji. To może zniszczyć ich pewność siebie. Analogicznie, gdyby nie było żadnych wytycznych, były użytkownik mógłby spędzić resztę życia, czekając, aż nic się nie wydarzy. Tak właśnie dzieje się ze zdecydowaną większością tych, którzy przestają stosować metodę siły woli.

Ludzie często pytają o znaczenie pięciu dni i trzech tygodni. Czy są to po prostu okresy wylosowane znienacka? Nie, choć nie są to konkretne daty, to odzwierciedlają nagromadzone przez lata informacje zwrotne. Około pięć dni po zaprzestaniu to czas, kiedy były użytkownik przestaje mieć uzależnienie jako główne zajęcie swojego umysłu. Większość byłych użytkowników doświadcza objawienia wokół tego okresu, zazwyczaj w sytuacjach stresowych lub społecznych, które w pewnym momencie nie były w stanie poradzić sobie lub cieszyć się bez wizyty w haremie. Nagle uświadamiasz sobie, że nie tylko cieszysz się lub radzisz sobie z tym, ale myśl o porno nigdy nawet nie przyszła ci do głowy. Od tego momentu jest to zwykle proste żeglowanie. Wtedy wiesz, że jesteś wolny.

To zarówno moje, jak i doświadczenie wielu innych osób próbujących zatrzymać się przy użyciu metody siły woli, że około trzy tygodnie to okres, w którym większość poważnych prób zatrzymania się zawodzi. Co się zwykle dzieje, to że po około trzech tygodniach czujesz, że straciłeś chęć oglądania porno. Musisz to sobie udowodnić, więc wskakujesz na przeglądarkę, aby odwiedzić swój harem. To dziwne uczucie, udowadniając, że go kopnąłeś. Ale w procesie smarujesz zjeżdżalnię wodną DeltaFosB dzięki świeżemu pędowi dopaminy, czego twoje ciało łaknęło przez ostatnie trzy tygodnie. Jak tylko skończysz ten czyn dopamina zaczyna opuszczać twoje ciało. Mały głos pojawia się ponownie, "*Nie kopnąłeś go, chcesz jeszcze jednego.*"

Nie pędź z powrotem od razu, ponieważ nie chcesz dostać hooked ponownie, pozwalając bezpieczny okres, aby przejść. Kiedy będziesz miał kolejną pokusę, będziesz mógł powiedzieć sobie: "*No cóż, nie dałem się znowu złapać, więc nie ma nic złego w posiadaniu kolejnego.*" Jesteś już na drodze w dół śliskiego zbocza. Kluczem do problemu nie jest czekanie na moment objawienia, ale uświadomienie sobie, że po zamknięciu przeglądarki to już koniec. Odciąłeś dopływ tlenu do swojego małego potwora. Żadna siła na ziemi nie może przeszkodzić ci w byciu wolnym, *chyba że będziesz się nad tym użalał lub czekał na objawienie.* Idź i ciesz się życiem; radź sobie z nim od samego początku. Ten moment wkrótce nadejdzie.


