# Ostatnia wizyta

Po ustaleniu czasu, jesteś gotowy, aby odwiedzić swój harem po raz ostatni. Zanim to zrobisz, sprawdź dwie najważniejsze rzeczy.

1.  Czy czujesz się pewny sukcesu?

2.  Czy masz poczucie zagłady i ponurości, czy poczucie podniecenia, że zaraz osiągniesz coś cudownego?

Jeśli masz jakiekolwiek wątpliwości, najpierw ponownie przeczytaj książkę. Pamiętaj, że nigdy nie zdecydowałeś się wpaść w pułapkę porno, ale pułapka ta została zaprojektowana tak, by zniewolić cię na całe życie. Aby się z niej wydostać, musisz podjąć pozytywną decyzję, że właśnie się zatrzymujesz i dokonujesz ostatniej wizyty.

Pamiętaj, że jedynym powodem, dla którego przeczytałeś do tej pory tę książkę, jest to, że bardzo chciałbyś uciec. Podejmij więc teraz tę pozytywną decyzję, składając uroczyste ślubowanie, że kiedy zamkniesz swoje prywatne okno przeglądarki, niezależnie od tego, czy będzie to łatwe czy trudne, nigdy więcej nie odwiedzisz swojego haremu. Być może obawiasz się, że złożyłeś to ślubowanie kilka razy w przeszłości i ciągle ci się nie udaje, albo że będziesz musiał przejść przez straszną traumę. Nie obawiaj się, najgorsze, co może się zdarzyć, to porażka, a zatem nie masz ***absolutnie nic*** do stracenia, a tak wiele do zyskania.

Ale przestań nawet myśleć o porażce, piękna prawda jest taka, że nie tylko śmiesznie łatwo jest rzucenie, ale możesz faktycznie cieszyć się tym procesem. Tym razem użyjesz EasyPeasy! Wszystko, co musisz zrobić, to podążać za prostymi instrukcjami o.

1.  Złóż teraz uroczyste ślubowanie i miej je na myśli.

2.  Przeglądaj świadomie zdjęcia i klipy na swojej ulubionej stronie Hub, przyglądając się desperackim próbom administratorów stron, aktorów, a nawet amatorów, aby wzmocnić szok, nowość i nadprzyrodzoność swoich wyrobów i zadaj sobie pytanie, gdzie jest przyjemność.

3.  Kiedy w końcu zamkniesz przeglądarkę, nie rób tego z poczuciem "*Nigdy więcej nie wolno mi odwiedzić innego haremu online*" lub "*Nie wolno mi odwiedzić innego*", ale zamiast tego z poczuciem wolności, jak "*Czy to nie wspaniałe? Jestem wolny! Nie jestem już niewolnikiem porno! Nie muszę już nigdy w życiu odwiedzać tych brudnych stron*".

4.  Bądź świadomy, że przez kilka dni w twoim żołądku będzie siedział mały porno sabotażysta. Możesz być świadomy tylko uczucia pragnienia sesji. Mały potwór porno został określony jako lekki fizyczny głód dopaminy. Ściśle mówiąc jest to błędne i ważne jest, aby zrozumieć dlaczego. Ponieważ potrzeba aż trzech tygodni, aby ten mały potwór umarł, byli użytkownicy wierzą, że mały potwór będzie nadal pragnął po ostatniej wizycie w haremie online i dlatego muszą używać siły woli, aby oprzeć się pokusie w tym okresie. To nie jest tak, ciało nie pożąda dopaminy wywołanej przez porno; tylko mózg pożąda.

Jeśli w ciągu następnych kilku dni dopadnie cię uczucie chęci zerknięcia, twój mózg ma prosty wybór. Może albo zinterpretować to uczucie jako to, czym ono faktycznie jest - pustym, niepewnym uczuciem zapoczątkowanym przez pierwszą wizytę na stronie porno online i dalej utrwalonym przez każdą następną, i powiedzieć sobie **"HURAA! NIE JESTEM UŻYTKOWNIKIEM!"**.

Albo możesz zacząć pożądać porno i cierpieć przez resztę życia. Pomyśl przez chwilę, czy to nie byłaby niesamowicie głupia rzecz do zrobienia? Powiedzieć sobie: "*Nigdy więcej nie chcę oglądać porno*", a potem spędzić resztę życia na mówieniu: "*Chętnie bym się odwiedził*"? To właśnie robią osoby stosujące metodę siły woli i nic dziwnego, że czują się tak nieszczęśliwi. Spędzają resztę życia rozpaczliwie rozpaczając nad czymś, na co mają desperacką nadzieję, że nigdy nie będą mieli. Nic dziwnego, że tak niewielu się udaje, a ci nieliczni, którzy to robią, nigdy nie czują się całkowicie wolni.

> *"Uzyskaj ten mentalny obraz wyraźnie w swoim umyśle, ponieważ może on być całkiem pomocny w pokonywaniu mocy zewnętrznych bodźców, które mogą ci przeszkadzać. Zobacz siebie siedzącego spokojnie, pozwalającego dzwonić telefonowi, ignorującego jego sygnał, niewzruszonego jego poleceniem. Chociaż jesteś tego świadomy, nie masz już nic przeciwko temu ani nie jesteś mu posłuszny. Zrozum również wyraźnie w swoim umyśle fakt, że sygnał zewnętrzny sam w sobie nie ma nad tobą władzy, nie ma mocy, by cię poruszyć. W przeszłości byłeś mu posłuszny, reagowałeś na niego, czysto z przyzwyczajenia. Możesz, jeśli chcesz, wyrobić w sobie nowy nawyk nie reagowania.*
>
> Zauważ również, że brak reakcji nie polega na robieniu czegoś, podejmowaniu wysiłku, opieraniu się czy walce, ale na nie robieniu niczego - na odpoczynku od robienia. Dzwonek telefonu jest symboliczną analogią do każdego innego bodźca zewnętrznego, nad którym możesz nawykowo sprawować kontrolę, a teraz zdecyduj się bardzo świadomie zmienić ten nawyk.*"
>
> ---  Maxwell Maltz, "Psychocybernetyka” Rozdział 12. 

Tylko zwątpienie i czekanie utrudnia rzucenie, ***więc nigdy nie wątp w swoją decyzję***, bo wiesz, że jest ona właściwa. Jeśli zaczniesz w nią wątpić, postawisz się w sytuacji bez wyjścia. Nieszczęśliwy będąc spragnionym wizyty, ale nie mogąc jej mieć. Niezależnie od tego, jakiego systemu używasz, co próbujesz osiągnąć, rzucając porno? Nigdy więcej nie oglądać? Nie! Wielu byłych użytkowników tak robi, ale przez resztę życia czuje się pozbawiona.

Jaka jest różnica między użytkownikami a nieużytkownikami? Nieużytkownicy nie mają żadnej potrzeby, ani pragnienia oglądania porno, są pozbawieni pragnień i nie muszą ćwiczyć siły woli, żeby go nie oglądać. To jest to, co próbujesz osiągnąć i jest to całkowicie w twojej mocy, aby to zrobić. Nie musisz czekać, aby przestać pożądać porno lub stać się nie-użytkownikiem, to jest zakończone w momencie, gdy zamkniesz to ostatnie okno przeglądarki, odcinając dopływ dopaminy: **JESTEŚ JUŻ SZCZĘŚLIWYM NIEUŻYTKOWNIKIEM!**

Pozostaniesz szczęśliwym nieużytkownikiem pod warunkiem, że:

1.  Nigdy nie wątpisz w swoją decyzję.

2.  Nie czekasz, aby stać się nieużytkownikiem. Jeśli to zrobisz, będziesz jedynie czekał, aż nic się nie wydarzy i stworzysz fobię.

3.  Nie starasz się *nie* myśleć o porno lub czekać na 'moment objawienia', tworząc fobię.

4.  Nie używasz zamienników.

5.  Widzisz wszystkich innych użytkowników takimi, jakimi są naprawdę i raczej współczujesz im niż zazdrościsz.

Niezależnie od tego, czy są to dobre czy złe dni, nie zmieniaj swojego życia tylko dlatego, że rzuciłeś. Jeśli to zrobisz, będziesz się naprawdę poświęcać, kiedy nie ma takiej potrzeby. Pamiętaj, że nie zrezygnowałeś z życia. Nie zrezygnowałeś z niczego. Wręcz przeciwnie, wyleczyłeś się z okropnej choroby i uciekłeś z podstępnego więzienia. W miarę upływu dni i poprawy twojego zdrowia - zarówno fizycznego, jak i psychicznego - wzloty będą większe, a upadki mniejsze niż wtedy, gdy byłeś użytkownikiem. Kiedykolwiek pomyślisz o porno w ciągu najbliższych kilku dni lub przez resztę życia, pomyśl:

***"HURAA! NIE JESTEM UŻYTKOWNIKIEM!"***

## Ostatnie ostrzeżenie

Żaden użytkownik, gdyby dać mu szansę powrotu do czasów sprzed uzależnienia z wiedzą, którą posiada obecnie, nie zdecydowałby się na rozpoczęcie. Dziesiątki tysięcy osób, którym udało się zerwać z nałogiem, przez wiele lat wiodą doskonale szczęśliwe życie, tylko po to, by ponownie wpaść w pułapkę. Ufam, że ta książka pomoże ci znaleźć stosunkowo łatwe do zatrzymania. Ale ostrzegam, użytkownicy, którzy znajdują to łatwe do zatrzymania znaleźć to tak samo łatwo, aby rozpocząć ponownie, **nie wpadnij w tę pułapkę.**

Bez względu na to, jak długo zatrzymałeś się na lub jak pewny, że nigdy nie zamierzasz stać się ponownie uzależniony, uczyń to regułą dla życia, aby nie oglądać porno z jakiegokolwiek powodu. Oprzyj się aluzjom i insynuacjom w mediach, i pamiętaj, jak pchają swój wizerunek "otwartości" przez wprowadzenie porno do głównego nurtu; nieświadomy, że porno, porno internetowe i kompulsywna masturbacja są zabójcami związków i osobistego poczucia dobrobytu dla ogromnej liczby mężczyzn i niektórych kobiet.

Pamiętaj, że pierwsze zerknięcie czy wizyta nic ci nie zrobi. Nie będziesz miał żadnych objawów odstawienia, które mógłbyś złagodzić i poczujesz się okropnie. Co to będzie zrobić, to umieścić przyjemność dopaminy pęd do swojego umysłu i mózgu, a mały głos z tyłu umysłu będzie powiedzieć, że chcesz inny jeden. Wtedy masz do wyboru bycie nieszczęśliwym przez jakiś czas, lub rozpoczęcie całego brudnego łańcucha ponownie.


