# Komentarz

Wojna nie toczy się przeciwko użytkownikom, ale przeciwko pułapce branży porno, a prowadzona jest z tego prostego powodu, że sprawia mi to przyjemność. Za każdym razem, gdy słyszę o użytkowniku uciekającym z więzienia, doznaję uczucia ogromnej przyjemności. Ale ta przyjemność nie obyła się bez znacznej frustracji, spowodowanej głównie przez dwie kategorie użytkowników porno. Pomimo ostrzeżenia z poprzedniego rozdziału, jestem nieustannie zaskoczony liczbą tych, którym łatwo jest przestać, ale później wpadają w sidła i stwierdzają, że następnym razem im się nie uda.

To tak, jakbyś znalazł kogoś po szyję w bagnie i miał się pod nim znaleźć. Pomagasz wyciągnąć ich i są wdzięczni, ale potem, sześć miesięcy później nurkuje prosto do bagna. Użytkownicy, którzy uważają, że łatwo zatrzymać się i zacząć ponownie stanowią szczególny problem, jednak kiedy dostajesz wolne ***PROSZĘ CIĘ, PROSZĘ, NIE RÓB TEGO SAMEGO BŁĘDU.*** Wierzą, że tacy ludzie zaczynają ponownie, ponieważ są nadal uzależnieni i brakuje im dopaminy. W rzeczywistości zatrzymanie się jest dla nich tak łatwe, że tracą strach przed porno. Myślą: "*Mogę mieć dziwną sesję, a nawet jeśli znowu się uzależnie, łatwo będzie mi przestać*".

Obawiam się, że to po prostu nie działa w ten sposób, łatwo jest zatrzymać porno, ale niemożliwe jest kontrolowanie uzależnienia. Jedną rzeczą niezbędną do zatrzymania porno jest nieużywanie go.

Ludzie zazwyczaj wracają do porno, ponieważ źle rozumieją "easy" (łatwość) w easypeasy.

Wyobraź sobie, że ktoś siedzi na zimnej betonowej podłodze w mroźnym pomieszczeniu. Na ścianie naprzeciwko niego jest okno pokazujące idealny wiosenny dzień na zewnątrz - drzewa delikatnie się kołyszą, ptaki ćwierkają - tuż obok niezamkniętych drzwi. 

Czy trzeba mieć siłę woli, żeby wyjść z tego mroźnego pokoju? Nie! Czy ucieczka jest trudniejsza niż pozostanie? Oczywiście, że nie! (W rzeczywistości jest to trochę łatwiejsze, ponieważ ciało się porusza). Dlaczego ktokolwiek przy zdrowych zmysłach postawiłby się w takiej sytuacji, powodując sobie miesiące lub lata frustracji, chyba że został oszukany?

Easypeasy odsuwa zasłony, aby użytkownik mógł wyraźnie widzieć na zewnątrz i aby usunąć **złudzenia** co do tego, jak straszne może być to, co dzieje się na zewnątrz i jak komfortowo użytkownik znajduje się w pokoju.

Inna kategoria sfrustrowanych użytkowników to ci, którzy są zbyt przestraszeni, aby podjąć próbę zatrzymania się, lub gdy już to zrobią, uważają to za wielką walkę. Główne trudności wydają się być następujące.

**Strach przed porażką.**

:   Nie ma hańby w porażce, ale brak próby to zwykła głupota. Spójrz na to w ten sposób, że chowasz się przed niczym. Najgorsze, co może się zdarzyć, to porażka, a wtedy nie jesteś w gorszej sytuacji niż teraz. Pomyśl tylko, jak wspaniale byłoby odnieść sukces. Jeśli nie podejmiesz próby, już zagwarantowałeś sobie porażkę.

**Strach przed bólem i przed poczuciem nieszczęścia**.

:   Nie przejmuj się tym, tylko pomyśl: co strasznego mogłoby Ci się przydarzyć, gdybyś już nigdy nie oglądał porno? Absolutnie nic. Straszne rzeczy *staną się*, jeśli to zrobisz, przeczytaj ponownie notatki na temat Zakładu Pascala. W każdym razie, panika jest spowodowana dopaminą i wkrótce zniknie. Największym zyskiem jest pozbycie się tego strachu. Czy naprawdę wierzysz, że użytkownicy są przygotowani na zanikające penetracje, zawodną sprawność seksualną, czy złudną przyjemność, którą czerpią z porno? Jeśli zauważysz, że wpadasz w panikę, pomoże ci głębokie oddychanie. Jeśli jesteś z innymi ludźmi i oni cię dołują, ucieknij od nich i idź do garażu, pustego biura lub gdzieś indziej.

    Jeśli masz ochotę się rozpłakać, nie wstydź się. Płacz jest w naturze sposobem na rozładowanie napięcia. Nikt nigdy nie wypłakał się porządnie, nie czując się po tym lepiej. Jedną z okropnych rzeczy, jakie robimy młodym mężczyznom, jest warunkowanie ich, by nie płakali. Możesz zobaczyć, jak próbują walczyć z łzami, ale obserwuj, jak szczęka zgrzyta. Uczymy się, aby nie pokazywać emocji, ale nie mamy ich butelkować w środku. Krzyczeć, krzyczeć lub mieć napady złości. Kopnij coś. Potraktuj swoją walkę jak pojedynek bokserski, którego nie możesz przegrać. Nikt nie może zatrzymać czasu, każda mijająca chwila sprawia, że ten mały potwór wewnątrz ciebie umiera. Ciesz się swoim nieuchronnym zwycięstwem.

**Nieprzestrzeganie instrukcji.**

:   Niewiarygodnie, niektórzy użytkownicy mówią, że metoda ta nie zadziałała w ich przypadku. Następnie opisują, jak zignorowali nie tylko jedną instrukcję, ale praktycznie wszystkie. Dla jasności, są one podsumowane jako lista kontrolna na końcu tego rozdziału.

**Niezrozumienie instrukcji.**

:   Główne problemy, które się pojawiają to:

    "*Nie mogę przestać myśleć o porno.*

    :   Oczywiście, że nie możesz, a jeśli spróbujesz, stworzysz fobię, stając się nieszczęśliwym. To tak jak z próbą zaśnięcia w nocy; im bardziej się starasz, tym trudniej. Nie ma znaczenia, czy myślisz o porno przez dziewięćdziesiąt procent swojego życia, ważne jest to, co myślisz. Jeśli myślisz "*Och, uwielbiam oglądać porno*" lub "*Kiedy będę wolny?*", będziesz nieszczęśliwy. Jeśli zamiast tego będziesz myślał "*HURAA! Jestem wolny!*" będziesz szczęśliwy.

    "*Kiedy ten mały porno potwór umrze?*"

    :   Dopaminowe zalanie opuszcza twoje ciało bardzo szybko, ale nie sposób powiedzieć, kiedy twoje ciało przestanie cierpieć z powodu lekkiego fizycznego uczucia odstawienia dopaminy. To puste, niepewne uczucie jest identyczne jak normalny głód, depresja czy stres. Wszystko, co robi porno, to zwiększenie jego poziomu. To dlatego użytkownicy, którzy przestają stosować metodę siły woli, nigdy nie są do końca pewni, czy udało im się ją wykopać, nawet po tym, jak ich ciało przestało cierpieć z powodu odstawienia dopaminy. Jeśli cierpią na normalny głód lub stres, ich mózg nadal mówi im, że jest to ważny powód, aby domagać się swojej uprawnionej sesji. Chodzi o to, że nie trzeba czekać na pragnienie, aby przejść, to jest tak lekkie, że nawet nie wiemy, że jest tam, tylko znając go jako uczucie pragnienia. Czy po wyjściu od dentysty czekasz aż przestanie cię boleć szczęka? Oczywiście, że nie, wracasz do życia. Nawet jeśli szczęka nadal boli, jesteś podniecony.

        Nie czekaj, aż wycofanie odejdzie, bo stworzysz wątpliwości, ciągle zadając sobie pytanie "*Jak długo to potrwa? Czy jestem nawet wolny, jeśli nie czuję się inaczej?*". Strach jest faktycznym napadem, dlatego czekanie na to, że po odstawieniu życie stanie się lepsze, stworzy wątpliwości. Odstawienie jest niezauważalne, chyba że się go boisz, a wykładnicze ulepszenia w neurologii są powolne, więc jeśli czekasz, aby poczuć się inaczej, będzie się czuć, jakby nic się nie działo, tworząc wątpliwości.

    *" "Moment objawienia" jeszcze nie nadszedł. "*

    :   Jeśli czekasz na to, to tylko wywołujesz kolejną fobię, ja kiedyś zatrzymałem się na trzy tygodnie na metodzie siły woli. Czatując ze starym przyjacielem, zapytał mnie, jak sobie radzę.
        "*Przetrwałem trzy tygodnie*", odpowiedziałem.
        Zapytał: "Jak to, przeżyłeś trzy tygodnie?".
        Wyjaśniłem: "Przeżyłem trzy tygodnie bez porno".
        On powiedział: "*Co zamierzasz zrobić? Przetrwać resztę swojego życia? Na co czekasz, przecież już to zrobiłeś. Jesteś nieużytkownikiem.*"

        Pomyślałem: "*On ma całkowitą rację, na co ja czekam?". Niestety, z powodu braku zrozumienia pułapki, szybko znalazłem się z powrotem w niej, ale punkt został zauważony. Zamykając przeglądarkę stajesz się nieużytkownikiem. Ważne jest, aby od początku być szczęśliwym nieużytkownikiem.

    "*Ciągle mam ochotę na porno*"

    :   W takim razie jesteś bardzo głupi. Jak możesz twierdzić, że chcesz być nie-użytkownikiem, a potem mówić, że pragniesz porno? To jest sprzeczność. Jeśli mówisz, że chcesz porno, to mówisz, że chcesz być użytkownikiem. Nieużytkownicy nie chcą odwiedzać obrzydliwych stron Hub. Już wiesz, czym chcesz być, więc przestań się karać.

    "*Zrezygnowałem z życia.*"

    :   Dlaczego? Wystarczy, że przestaniesz się zabijać i zamiast tego zaczniesz dodawać sobie energii. Nie musisz przestać żyć w najmniejszym stopniu. To jest tak proste jak to, że przez najbliższe kilka dni będziesz miał lekką traumę w swoim życiu. Twoje ciało odczuje prawie niezauważalne nasilenie wycofania się z żądań i roszczeń o przypływ dopaminy. Teraz miej to na uwadze: nie jesteś w gorszej sytuacji niż byłeś. To jest to, co cierpiałeś przez całe swoje życie, za każdym razem, gdy spałeś, w kościele, supermarkecie czy bibliotece. Nie przeszkadzało ci to, gdy byłeś użytkownikiem, a jeśli nie przestaniesz, będziesz cierpiał to strapienie do końca życia.

        Porno i orgazmy nie tworzą okazji, one cię ich pozbawiają. Nawet gdy twoje ciało wciąż pragnie dopaminy, posiłki i okazje towarzyskie są cudowne. Życie jest wspaniałe, chodź na spotkania towarzyskie, nawet jeśli są tam nagie tancerki. Pamiętaj, że to nie ty jesteś pozbawiony, tylko oni. Każdy z nich chciałby być w twojej sytuacji, gdyby tylko wiedział. Ciesz się byciem primadonną i w centrum uwagi. Zatrzymanie porno jest wspaniałym punktem rozmowy, biorąc sekretną przyjemność, której oni nie mogą. Twoi przyjaciele i rówieśnicy będą zaskoczeni widząc, że ty, wcześniej nieśmiały i zmęczony wygląd, jesteś teraz szczęśliwy i wesoły. Będziesz cieszył się życiem od samego początku, nie ma co zazdrościć podrywaczom na imprezach, oni będą zazdrościć tobie -- gdyby tylko wiedzieli.

    "*Jestem nieszczęśliwy i rozdrażniony*"

    :   To jest porażka w wykonywaniu instrukcji. Dowiedz się, która to jest. Niektórzy ludzie rozumieją i wierzą we wszystko, co jest napisane, a mimo to zaczynają z poczuciem zagłady i ponurości, jakby działo się coś strasznego. Robisz nie tylko to, co chciałbyś zrobić, ale to, co chciałby również każdy użytkownik na planecie. Z każdą metodą zatrzymania, były użytkownik próbuje osiągnąć pewną ramę umysłu, więc każda myśl związana z porno jest przebijana przez "*HURAA! JESTEM WOLNY!*" Jeśli to jest twój cel, po co czekać? Zacznij w tej ramie umysłu i nigdy jej nie trać, nie ma alternatywy.

    "*Miałem dobry tydzień/miesiąc/sześć miesięcy, ale znowu jestem w pułapce.*"

    :   Pamiętaj, że strach jest samym napadem. Poddanie się bólowi generuje więcej strachu, karmiąc osłabionego małego potwora i udaje mu się spłoszyć nieużytkownika, aby myślał, że jest uwięziony na całe życie. W rzeczywistości, ich konceptualizacja prania mózgu nie zmieniła się, ale dali dopaminę do procesu myślowego. To jest z definicji spadanie do przodu, ale jest porażką w wykonywaniu instrukcji. Zrozum, która z nich poniżej i ciesz się.

## Lista kontrolna

Jeśli zastosujesz się do tych instrukcji, nie możesz zawieść:

1.  Złóż uroczyste ślubowanie, że nigdy, przenigdy nie wejdziesz do Internetu, aby odwiedzić swój harem *ANI* zadowolić się statycznymi zdjęciami *ANI* pogodzić się z grafiką erotyczną *ANI* czymkolwiek, co zawiera nadprzyrodzone bodźce, i trzymaj się swojego ślubowania.

2.  Wyjaśnij to sobie w swoim umyśle: Nie ma absolutnie nic, z czego można by zrezygnować. Przez to nie rozumie się, że będzie ci lepiej jako nie-PMOwiec (wiedziałeś o tym przez cały czas); ani że chociaż nie ma żadnego racjonalnego powodu, dla którego PMO, dostajesz jakąś przyjemność lub podporę z tego, ponieważ inaczej nie robiłbyś tego. Chodzi o to, że nie ma ***żadnej autentycznej przyjemności ani podpory w PMOwaniu.*** To tylko iluzja, jak walenie głową w mur, aby uzyskać przyjemność, gdy przestaniesz.

3.  Nie ma czegoś takiego jak potwierdzony PMOwiec. Jesteś tylko jednym z setek milionów, którzy dali się nabrać na tę subtelną pułapkę. Podobnie jak miliony innych  byłych PMOwców, którzy kiedyś myśleli, że nie mogą uciec, ty uciekłeś.

4.  Jeśli w dowolnym momencie swojego życia miałbyś rozważyć plusy i minusy PMOwania, przytłaczający wniosek zawsze brzmiałby "*Przestań to robić. Jesteś głupcem!*" Nic tego nigdy nie zmieni. Zawsze tak było i zawsze tak będzie. Po podjęciu decyzji, którą znasz jako właściwą, nie zadręczaj się wątpliwościami. Zakład Pascala doskonale stosuje się do PMO - brak szans na straty, wysokie szanse na zyski i wysokie szanse na uniknięcie strat.

5.  Nie próbuj nie myśleć o porno, ani nie martw się, że myślisz o nim nieustannie. Zawsze, gdy o tym myślisz, czy to dziś, jutro, czy przez resztę życia, pomyśl **"HURAA! JESTEM NIE-PMOWCEM!"**.

6.  **Nie** używaj żadnej formy zastępczej. **Nie** stawiaj sobie wyzwania, trzymając laptopa obok siebie podczas snu. **Nie** unikaj sztuk teatralnych, filmów czy czasopism. **Nie** zmieniaj w żaden sposób swojego stylu życia tylko dlatego, że przestałeś. Jeśli zastosujesz się do powyższych wskazówek, wkrótce doświadczysz "momentu objawienia", ale:

7.  Nie czekaj, aż nadejdzie 'chwila objawienia'. Po prostu zajmij się swoim życiem, ciesząc się wzlotami i radząc sobie z upadkami. Przekonasz się, że w krótkim czasie moment ten nadejdzie.


