# Pomoc tym będącym na tonącym statku

Użytkownicy porno wpadają obecnie w panikę, wyczuwając zmiany w sposobie postrzegania internetowego porno przez mężczyzn i kobiety. Uzależniający charakter porno internetowego jest coraz częściej badany, obecnie słusznie uważany za inny niż tradycyjna pornografia. Łatwość i dostępność budzi niepokój nawet w sercach zwolenników porno. Przeczuwają oni również, że ich krucjata o wolność słowa i myśli jest porywana przez różne elementy. Dziki zachód nieuporządkowanego internetu sprawia, że egzekwowanie ograniczeń wiekowych wobec nadprzyrodzonych bodźców jest niemal niemożliwe. To niefortunne, że nie skończy się to w najbliższym czasie, ale setki tysięcy użytkowników przestaje, a większość uzależnionych zdaje sobie sprawę z badań pokazujących podobieństwa między porno a uzależnieniem od substancji. Za każdym razem, gdy użytkownik opuszcza tonący statek, ci, którzy na nim zostali, czują się coraz bardziej nieszczęśliwi.

Każdy użytkownik instynktownie wie, że to niedorzeczne, aby samosabotować i spędzać czas przed dwuwymiarowymi pikselami, super-zalegając swój mózg, a w procesie rozwijając ścieżki neuronowe, które gwarantują słabą wydajność seksualną. Jeśli nadal nie uważasz, że to głupie, spróbuj porozmawiać z magazynem porno stojącym w centrum twojego miasta i zapytaj siebie, jaka jest różnica. Tylko jedna. Nie da się w ten sposób uzyskać przyjemności płynącej z ciepła i intymności. Jeśli możesz przestać kupować alkohol i papierosy za każdym razem, gdy idziesz na zakupy spożywcze, to z pewnością możesz przestać odwiedzać swój internetowy harem. Użytkownicy nie mogą znaleźć racjonalnych powodów do oglądania porno, ale nie czują się tak głupio, jeśli inni ludzie też to robią.

Użytkownicy jawnie kłamią o swoim nałogu, nie tylko badaczom i osobom z ich otoczenia, ale także samym sobie. Muszą, pranie mózgu jest niezbędne, jeśli chcą zachować trochę szacunku dla siebie. Czują potrzebę usprawiedliwienia swojego "nałogu" nie tylko przed *sobą*, ale także przed osobami nieużywającymi narkotyków. Wiecznie reklamują iluzoryczne zalety porno za pomocą subtelniejszych środków.

Jeśli użytkownik przestaje korzystać z metody siły woli, nadal czuje się pozbawiony, ma tendencję do stania się jędzą. Wszystko co robi to potwierdzenie innym użytkownikom jak bardzo mają rację kontynuując używanie. Jeśli byłemu użytkownikowi uda się wykopać nawyk, jest wtedy wdzięczny, że nie musi już przechodzić przez życie samosabotując lub marnując energię i nie ma potrzeby usprawiedliwiania się. Pamiętaj, że to strach sprawia, że użytkownik chowa głowę w piasek, kwestionując swoje zachowanie tylko wtedy, gdy przestaje. Pomóż użytkownikowi, usuwając te obawy. Powiedz im jak cudownie jest nie musieć przechodzić przez życie żyjąc w więzieniu, jak pięknie jest budzić się rano czując się sprawnym i zdrowym zamiast braku energii i nienawiści do samego siebie, jak wspaniale jest być wolnym od niewoli, móc cieszyć się całym swoim życiem i pozbyć się tych czarnych cieni. Albo jeszcze lepiej, namów ich do przeczytania tej książki.

Istotne jest, aby nie umniejszać żonatego użytkownika, wskazując, że celowo rujnuje swój związek lub jest on w jakiś sposób zdradzany czy nieczysty. Istnieje powszechne błędne przekonanie, że były użytkownik jest pod tym względem najgorszy. Koncepcja ta ma pewne uzasadnienie, ale wynika na ogół z metody powstrzymywania się za pomocą siły woli. Ponieważ były użytkownik - mimo że rzucił nałóg - nadal zachowuje część prania mózgu i nadal wierzy, że się poświęcił. Czują się bezbronni i ich naturalnym mechanizmem obronnym jest atakowanie użytkownika pornografii.

To może podnieść ego byłego użytkownika, ale nie pomaga mu w niczym. Wszystko co robi, to stawia ich pod ścianą, sprawiając, że czują się jeszcze bardziej nieszczęśliwi i w konsekwencji ich potrzeba porno jest jeszcze większa. Chociaż zmiana w podejściu instytucji medycznej do pornografii internetowej jest głównym powodem, dla którego wielu użytkowników rzuca palenie, nie czyni tego łatwiejszym. W rzeczywistości czyni to o wiele trudniejszym. Większość użytkowników uważa obecnie, że przestaje z powodów zdrowotnych. To nie jest do końca prawda.

Chociaż ogromne ryzyko zdrowotne jest oczywiście głównym powodem rzucenia, użytkownicy sabotują swoją męskość od lat i nie robi to najmniejszej różnicy. Głównym powodem, dla którego użytkownicy przestają, jest to, że społeczeństwo zaczyna widzieć porno zdemaskowane tym, czym jest: Uzależnieniem od narkotyków. Nastawienie społeczeństwa powoli się zmienia - wielu partnerów zadaje teraz pytania, jeśli w środku nocy siedzisz na swoim laptopie.

Całkowite zakazy oglądania porno w niektórych krajach lub niedostępność internetu to klasyczne przykłady dylematu podróżującego użytkownika. Generalnie przyjmują oni postawę, że pomoże im to ograniczyć spożycie. W rezultacie zamiast jednego lub dwóch dziennie, z których żaden nie sprawiłby im przyjemności, powstrzymują się od nich przez cały tydzień. Podczas tego wymuszonego okresu abstynencji jednak, nie tylko będzie psychicznie pozbawiony czekając na ich nagrodę, ich ciało jest craving zbyt. Och, jak cenna jest ta wizyta w haremie online, kiedy w końcu im się pozwoli.

Wymuszona abstynencja tak naprawdę nie zmniejsza spożycia, ponieważ użytkownik po prostu pobłaża sobie jeszcze bardziej, gdy w końcu pozwala mu się być samemu. Wszystko, co robi, to zakorzenić w umyśle użytkownika, jak cenne jest internetowe porno i jak bardzo jest od niego uzależniony. Najbardziej podstępnym aspektem tej wymuszonej abstynencji jest jej wpływ na nastolatków. Pozwalamy porywaczom "wolności słowa", producentom pornografii, aby celowali w nieszczęsnych nastolatków i w pierwszej kolejności ich uzależniali. Następnie, w prawdopodobnie najbardziej stresującym okresie ich życia, kiedy w ich złudnych umysłach porno jest im najbardziej potrzebne, szantażujemy ich, aby zrezygnowali z niego ze względu na szkody, jakie sobie wyrządzają.

Wielu nie jest w stanie tego zrobić i są zmuszeni, nie z własnej winy, do końca życia cierpieć z powodu poczucia winy. Wielu udaje się i jest z tego zadowolonych, myśląc: *\"Dobrze. Zrobię to na razie, a jak się skończy, to i tak będę wyleczony "*\. Potem przychodzi ból i strach przed znalezieniem pracy i inne zmagania dorosłych, a następnie największy "haj" w ich życiu - znalezienie pracy. Ból i strach minęły, teraz czują się bezpiecznie, stary mechanizm spustowy wraca do działania. Część prania mózgu wciąż tam jest i zanim zniknie zapach nowego laptopa do pracy, użytkownik jest u progu swojego ulubionego internetowego haremu. Uniesienie z okazji blokuje nieczyste uczucia z ich umysłu, nie mają zamiaru stać się ponownie zaczepieni, ale tylko jedno spojrzenie nie mogło zaszkodzić\... Za późno! Już są ponownie uzależnieni.

Stary głód z małego potwora zacznie się ponownie i nawet jeśli nie staną się od razu ponownie uzależnieni, depresja poposiłkowa prawdopodobnie ich złapie. To dziwne, że choć uzależnieni od heroiny są w świetle prawa przestępcami, reakcją społeczeństwa jest pomoc tym osobom. Przyjmijmy taką samą postawę wobec biednego użytkownika porno. Oni nie robią tego, bo chcą, ale dlatego, że uważają, że muszą. W przeciwieństwie do uzależnionego od heroiny, oni zazwyczaj muszą cierpieć lata po latach psychicznych i fizycznych tortur. Zawsze mówimy, że szybka śmierć jest lepsza niż powolna, więc nie zazdrość biednemu użytkownikowi porno. ***Zasługują na twoją litość.***


