# Porada dla nieużytkowników

## Skłoń swoich przyjaciół, którzy używają porno, aby przeczytali tę książkę

Najpierw naucz się treści tej książki i spróbuj postawić się na miejscu użytkownika. Nie zmuszaj ich do przeczytania tej książki, mówiąc im, że rujnują swoje zdrowie lub igrają z ogniem. Oni wiedzą to lepiej niż ty. Użytkownicy nie kontynuują oglądania porno, bo sprawia im to przyjemność lub dlatego, że chcą, tylko wmawiają to sobie i innym ludziom, aby zachować szacunek do siebie. Robią to, ponieważ są uzależnieni od porno, ponieważ myślą, że to ich relaksuje, dodaje im odwagi lub pewności siebie (przyjemność lub podpora) i ponieważ czują, że życie nigdy nie będzie przyjemne bez "seksu" -- przynajmniej ich wersji. Jeśli spróbujesz zmusić użytkownika do zaprzestania, poczuje się jak uwięzione zwierzę i będzie chciał mieć swój harem jeszcze bardziej. To może zmienić ich w skrytego użytkownika, a porno stanie się jeszcze cenniejsze w ich umyśle.

Zamiast tego skup się na drugiej stronie medalu. Wprowadź ich w towarzystwo byłych użytkowników (blogi, fora, YBOP, NoFap, itp). Namów ich, żeby opowiedzieli użytkownikowi, jak oni też myśleli, że są uwikłani na całe życie i o ile lepsze jest życie jako nieużytkownik. Kiedy już nakłonisz ich do uwierzenia, że mogą przestać, ich umysł zacznie się otwierać. Następnie zacznij wyjaśniać złudzenie stworzone przez napady odstawienia. Nie tylko "dopaminowe pędy" nie dają im zastrzyku energii, ale niszczą ich pewność siebie i sprawiają, że są drażliwi i zmęczeni.

Powinni być teraz gotowi do samodzielnego przeczytania tej książki, spodziewając się, że przeczytają strony po stronach opowieści o niepewnym pobudzeniu, zanikających penetracjach, PIED, PE (ang. Przedwczesny wytrysk) itp. Wyjaśnij, że to podejście jest zupełnie inne, a odniesienia do chorób to maleńkie ułamki materiału.

Krótko mówiąc, nie pozwól, żeby to umarło w ciemności. Powiedzcie o tym swoim znajomym, ale nie bądźcie w tym dziwni. Jeśli spróbujesz "wygrać" rozmowę lub przeprowadzić debatę, uda ci się tylko zrazić i jeszcze bardziej zwiększyć ich strach.

## Czy powinienem powiedzieć mojej bliskiej osobie?

Czy powinienem powiedzieć żonie, dziewczynie lub partnerce o swoim nałogu? Intencją jest pomoc w rzuceniu palenia. W grę wchodzi tu wiele czynników.

Jeśli już nie udaje Ci się rzucić nałogu metodą siły woli i powiedziałeś o tym swojej partnerce, powiedz im o swoim nowym podejściu i pozwól im się edukować poprzez przeczytanie książki. Będą w stanie pomóc i zmotywować cię podczas okresu odstawienia i są twierdzą, gdy mały potwór próbuje cię potknąć.

Jeśli dopiero uświadomiłeś sobie istnienie pułapki porno i nie próbowałeś w przeszłości rzucić, najpierw sam skorzystaj z EasyPeasy. Jak wyjaśniono wcześniej, powinno to być przyjemne doświadczenie. Jeśli jednak sprawia ci to trudność, poproś o pomoc. Bądź otwarty i bezbronny wobec swojego partnera, a wzmocni to wasz związek.

Pod warunkiem, że cieszysz się ucieczką i nie jest to trudne przez niezdecydowanie, nie ma zbyt wiele powodów, aby dać znać swojemu partnerowi. Jeśli w przeszłości nie było to problemem, pozwól mu umrzeć. Bądź jednak przygotowany na to, że twój partner może się zastanawiać, dlaczego wyglądasz, czujesz się i działasz lepiej!

## Mój / Moja partner/ka rzuca porno

Pornografia jest przewrotnym niszczycielem związków i o ile rzucenie może nastąpić natychmiast, o tyle wyleczenie wymaga czasu. Wielu użytkowników, ze względu na irracjonalne przekonania zrodzone z uzależnienia, wyładowuje swoją złość na partnerach i bliskich. Zachowania te przejawiają się w podświetlaniu, kłamaniu i manipulowaniu. Nie dotyczy to wszystkich użytkowników, ale jest coraz częstsze w późniejszych stadiach choroby. Podczas gdy te zachowania mogą przejawiać się od leżącego u podstaw uzależnienia od pornografii, ważne jest, aby edukować się na temat tych zachowań i jeśli są rozpoznawane, rozważyć wizytę u terapeuty specjalizującego się w uzależnieniach seksualnych.

Jeśli twój partner jest w okresie odstawienia, załóż, że cierpi, niezależnie od tego, czy tak jest, czy nie. Nie próbuj tego minimalizować, mówiąc im, że łatwo jest przestać, sami mogą to zrobić. Zamiast tego kontynuuj mówienie im, jak bardzo jesteś dumny, o ile lepiej wyglądają, o ile słodsze jest bycie z nimi i o ile łatwiejsze są w ogóle. Jest to szczególnie ważne, gdy użytkownik podejmuje próbę zatrzymania, euforia związana z tą próbą i pochwały od rówieśników mogą mu pomóc. Jednak mają oni tendencję do szybkiego zapominania, więc kontynuuj pochwały.

Ponieważ nie mówią o porno, możesz pomyśleć, że zapomnieli i nie chcą, żebyś im o tym przypominał. Zazwyczaj w przypadku metody siły woli jest zupełnie odwrotnie, ponieważ były użytkownik ma tendencję do obsesji na punkcie niczego innego. Nie bój się więc poruszać tego tematu i chwal ich, powiedzą ci, czy nie chcą, żeby im przypomnieć.

Wyjdź z siebie, aby ulżyć im w presji podczas okresu odstawienia, myśląc o sposobach uczynienia ich życia interesującym i przyjemnym. Może to być również okres próbny dla osób nie będących użytkownikami, które nigdy nie miały do czynienia z uzależnieniem. Jeśli jeden członek grupy jest rozdrażniony, może to spowodować ogólne nieszczęście. Więc przewidź to, jeśli były użytkownik czuje się rozdrażniony, może to równie dobrze wyładować na tobie, ale nie bierz odwetu, to właśnie w tym czasie najbardziej potrzebują twojej pochwały i współczucia. Jeśli sam czujesz się rozdrażniony, co jest zrozumiałe, staraj się tego nie okazywać.

Jedną ze sztuczek, jaką stosuje osoba uzależniona, próbując zrezygnować z nałogu metodą siły woli, jest wpadanie w złość, licząc na to, że partner lub przyjaciele powiedzą: "*Nie mogę znieść tego, że tak cierpisz. Na miłość boską, po prostu weź swoją truciznę*". Użytkownik nie musi zatem tracić twarzy, nie "poddaje się", został poinstruowany. Jeśli były użytkownik stosuje tę sztuczkę, w żadnym wypadku nie zachęcaj go do powrotu do nałogu. Zamiast tego powiedz: "*Jeśli to jest to, co porno robi z tobą, dzięki Bogu wkrótce będziesz wolny. Jak cudownie, że miałeś odwagę zrezygnować.*"

Pamiętaj, że w ramach podróży odzyskiwania są dwie strony uzdrawiające. Kiedy twój partner rzuca porno, ważne jest, aby mieć własną sieć wsparcia, rutyny samoopieki i granice. Ten proces nie dzieje się z dnia na dzień, wymaga zaufania, komunikacji i odpowiedzialności. Pisanie w notatniku, rozwijanie własnych pasji i co najważniejsze, terapia, wspomagają ten proces.

## Poślizg (relapse - nawrót)

Istnienie tej sekcji powinno być ostrzeżeniem dla osób wychodzących z pułapki. Osobiście nigdy nie wróciłem do nałogu, ale dla ilustracji posłużę się doświadczeniami z wywiadów z członkami społeczności oraz narzędziami z terapii poznawczo-behawioralnej.

Po pierwsze, nazywanie tego nawrotem jest bezproduktywne. Wszystko, co się stało, to że poślizgnąłeś się i nakarmiłeś małego potwora, który z kolei uruchamia dużego potwora piorącego mózg. Użytkownicy, którzy się poślizgną (co z definicji jest upadkiem do przodu), zazwyczaj wytwarzają cały szereg irracjonalnych przekonań:

  - "*Nigdy nie będę wolny*" - **katastrofizowanie**
  - "*Powinienem / muszę ćwiczyć, uczyć się i być owocnym każdego dnia w moim życiu*" (znane jako - **masturbowanie**)
  - "*Dzisiaj zPMOwałem, jaki jest sens czytania tych książek i forów... Moim celem było nawet nie M-owanie, ale oto jestem -- porażką -- nawraca.*" - **Niska tolerancja frustracji**
  - "*Moi przyjaciele / czytający forum / inni nie robią PMO przez (n) dni, ale ja nie mogę, więc jestem beznadziejnym przypadkiem. Wczoraj czułem się dobrze, ponieważ dobrze się uczyłem i byłem owocny, ale dzisiaj nie... Schodzę na dno.*" - **Ocena między sobą a innymi**
  - "Nie powinienem mieć seksualnych myśli" - Oni sami, rodzice lub całe ich społeczeństwo zainstalowało **sztywne przekonania** w stosunku do seksu. Zadaj sobie pytanie, czy samobiczowanie pomaga Ci w osiągnięciu Twoich celów, a jeśli tak, to czy czerpiesz radość z tej podróży?

Czynniki, które kulminują w praniu mózgu każdego użytkownika jest pozornie nieskończenie wiele. Znasz siebie lepiej niż ktokolwiek inny, to oczywiście nieudolność w wykonywaniu poleceń. Widziałeś wartość w pornografii, ale jak?

Co często jest pomijane, to fakt, że odwrócenie prania mózgu wymaga czasu. To nie czyni tego trudniejszym, ale prawie każda branża wykorzystuje seks, a aktywne przeciwdziałanie praniu mózgu jest procesem świadomym (przynajmniej na początku), więc pełne ugruntowanie zawartych w nim lekcji może zająć trochę czasu. Stąd zalecane jest wielokrotne czytanie (możesz pomijać rozdziały, z którymi masz trudności) i nie powinno ci to zająć dużo czasu.

Zaskakująco częstym doświadczeniem religijnych użytkowników wychodzących z pułapki jest pragnienie, aby trochę bolało, jako forma pokuty. Uważają, że rzucanie jest tak łatwe, a następnie czują się winni, że czują się w ten sposób. Ale dlaczego samosabotaż i utrudnianie? Mały potwór jest bardzo podstępny w tej kwestii.

Oddziel się od małego potwora, został on dodany przez przemysł pornograficzny dawno temu. Wyobraź sobie, że łobuz ma wybuch złości na szkolnym boisku. Co powiesz łobuzowi? Jeśli się poddasz, tylko wzmocnisz ich. Niektórzy, którzy rezygnują, w końcu karmią dręczyciela, a więc zwiększają jego pranie mózgu, ale ich konceptualizacja pułapki nie zmieniła się. Podnieś się, dowiedz się, gdzie poszedłeś źle i ciesz się wolnością!

Nie jesteś swoim popędem. Medytacja z uważnością (mindfulness) jest praktyką zauważania myśli i można w niej znaleźć fundamentalne lekcje na temat natury umysłu. Zaleca się medytację w ogóle, jest ona również całkowicie zgodna z praktyką religijną. Nie możesz walczyć z samym sobą, ani z małym potworem. Musisz bezwarunkowo kochać siebie i proces.

Ale usuń porażkę ze swojego umysłu. Oto fragment z "*Medytacji dla uzależnionych od porno*" Gulliaco (link w sekcji zasobów na końcu książki)

> Ponieważ oglądanie porno daje Ci zero korzyści, jest to coś, co tylko Ci szkodzi, a chęć robienia czegoś takiego jest skrajnie niedorzeczna, porównuję to do picia wybielacza. Proszę bardzo:
>
> **Ciężka podróż do nie picia wybielacza.**
>
> > Cześć! Jesteśmy NoBleach i organizujemy wyzwania restartowe, w których uczestnicy ("Wybielaczonauci") powstrzymują się od picia wybielacza przez pewien czas. Niezależnie od tego, czy Twoim celem jest swobodny udział w comiesięcznym wyzwaniu jako test samokontroli, czy też nadmierne picie wybielacza stało się problemem w Twoim życiu i chcesz zrezygnować z niego na dłuższy czas, znajdziesz tutaj wspierającą Cię społeczność i wiele zasobów.
>
> - "*Czasami pozwalam sobie na wypicie jednej lub drugiej szklanki wybielacza. Wiem o tym, że "jedna kropla" to kłamstwo, ale nie sądzę, żeby jedna szklanka zaszkodziła. Nie można zniszczyć wszystkich godzin, które spędziłem nie robiąc tego.*"
> - "*Nie mam problemu z zaprzestaniem picia wybielacza, ale czasami idę ulicą i widzę, że ktoś pije wodę, wiesz, w szklance, i wyobrażam sobie, że ta szklanka ma w sobie wybielacz. Wtedy mam zachciankę i po debacie z samym sobą, czy powinienem to zrobić, czy nie, w końcu poddaję się w nocy i wypijam szklankę.*"
> - "*Słuchaj, mój problem polega na tym, że czasami, kiedy jestem sam w kuchni, zaczynam widzieć szklanki, czasami skuszę się otwierając pojemnik, w którym trzymam wybielacz, czasami czuję jego zapach i... Cóż, kończę z powrotem tam, gdzie zacząłem. Jestem tak zdesperowany, żeby to przerwać, ale nie jestem pewien, czy kiedykolwiek będę w stanie
zaprzestać.*"
> - "*Przestanie picia wybielacza jest niemożliwe, w końcu zawsze mam usta, wiesz o tym? Jak mam przestać, skoro zawsze mam gardło, które przypomina mi, że mogę połknąć wybielacz?*"
> - "*O rany, szło tak dobrze, 19 całych dni bez robienia tego. Ważną rzeczą jest uczyć się z porażki! Teraz wiem, czego unikać: oglądania środków czystości w supermarkecie. Postaram się dotrwać do miesiąca! Zresetuję swój licznik. Życzcie mi powodzenia!*"

> Jeśli masz ochotę, uspokój się koleś! Pamiętaj, co mówi hackbook:
>
> "*Wybielacz jest trudny do porzucenia z powodu strachu, że pozbywamy się przyjemności lub rekwizytu. Strach, że pewne przyjemne sytuacje już nigdy nie będą całkiem takie same. Lęk, że nie będziemy w stanie poradzić sobie w sytuacjach stresowych. Innymi słowy, są to efekty prania mózgu, które wmawiają nam, że kupowanie wybielacza, a tym samym picie go, jest koniecznością dla wszystkich istot ludzkich. Jeszcze dalej, to przekonanie, że w przystępnym cenowo wybielaczu jest coś nieodłącznego, czego potrzebujemy, i że kiedy przestaniemy go używać, będziemy sobie odmawiać i tworzyć pustkę. Wyraź to w swoim umyśle: Wybielacz nie wypełnia pustki, on ją tworzy!*"
> 
> A ja mówię:
> "* Załóżmy, że jesteś zmuszony do oglądania przez pięć minut szklanki pełnej wybielacza. Spróbuj przypomnieć sobie jedną z tych marek lub zapachów, które tak bardzo ci się podobały. Może towarzyszy temu jakiś dźwięk, albo pamiętasz tylko wybrane szczegóły. Wybielacz jest tam i nie możesz zamknąć oczu ani odwrócić głowy, bo ten wybielacz jest w twoim umyśle, to wspomnienie zapisane w tobie.*"
>
> *Czy czujesz jakieś pragnienia? Czy czujesz coś na języku lub jakieś zmiany w oddychaniu? Jakie są twoje uczucia związane z tym, co sobie przypominasz? Zidentyfikuj je, wybielacz chce je zmącić, uczynić mylącymi i sprawić, że będziesz zwracał uwagę tylko na to, co chce cię złapać.*"
>
> Z powyższym, nie próbuję odrzucić Twoich uczuć, a tym bardziej powiedzieć coś w stylu "haha ja mądry Ty głupi", ale dać Ci perspektywę, abyś zdał sobie sprawę jak śmiesznie łatwo jest (i zawsze będzie) pokonać ten nałóg.
> Oglądanie porno nie jest jak włącznik/wyłącznik, gdzie mówisz "*oh well, jestem w sytuacji X, to będę oglądać porno*". Fantazje! Kłamstwa!!! Jak często pozwalasz sobie na wypicie szklanki wybielacza? Nigdy? Dlaczego? Bo to straszna rzecz, właśnie dlatego! Jak masz uciec od nałogu, jeśli nie zdajesz sobie sprawy.
że PMO jest okropną rzeczą, którą możesz sobie zrobić?

## Co z MO (masturbacją, orgazmem)?

Ludzie od wieków walą konia bez problemu. Żeby było jasne, to porno jest problemem.

To powiedziawszy, nadal można się uzależnić od MO z tych samych powodów co od porno, takich jak mentalność "potrzeby orgazmu", psychiczna eskalacja, zmuszanie ciała do seksu i po prostu zwykłe hedonistyczne poszukiwanie przyjemności.

Jest niezwykle prawdopodobne, że porno i masturbacja stały się głęboko splecione w twoim umyśle. Wielu użytkowników stwierdza, że kończy się to nawrotem choroby w wyniku masturbacji do fantazji wywołanych porno. Jak twój mózg przebudowuje, znajdziesz to pranie mózgu w końcu zanika, ale najlepiej jest zrobić sobie przerwę od MO na jakiś czas. Powinieneś również szukać prawdziwego seksu, aby przyspieszyć ten proces.

To nie jest instrukcja, ale przeanalizuj to. Zgłoszone korzyści z zatrzymania nasienia są liczne - zwiększona koncentracja i energia, usunięcie "mgły mózgowej" i zwiększona pewność siebie wraz z mnóstwem innych korzyści. Z osobistego doświadczenia wynika, że jest wyraźna różnica, a wszystko zależy od tego jak przetransformujesz tę zwiększoną energię.

Spekulując, i bez ścisłej wiedzy naukowej, korzyści mogą sprowadzać się do kilku różnych czynników.

- Po orgazmie, mózg uwalnia prolaktynę, która hamuje uwalnianie dopaminy.

- Pozbawienie mózgu dopaminy pozwala na większy pobór z po prostu życia.

- Nasienie jest ponownie wchłaniane przez krwiobieg po ~78 dniach i jest jednym z najlepszych składników odżywczych, jakie może otrzymać twoje ciało.

- Transmutacja energii seksualnej w produktywne nawyki przynosi ze sobą dodatkową warstwę produktywności.

Możesz chcieć uprawiać seks również bez orgazmu, co jak wspomniano wcześniej, jest wspaniałym doświadczeniem seksualnym. Możesz wzmocnić swoją zdolność do tego poprzez praktykowanie ćwiczeń Kegla. Z osobistego doświadczenia, najłatwiejszym i najskuteczniejszym sposobem na ukierunkowanie tego mięśnia jest zatrzymanie moczu w połowie strumienia. Oddzielenie tantrycznej i propagacyjnej części seksu jest jednym z wielu bonusów ucieczki z pułapki PMO (moje partnerki też to pokochały!).

## Odchylenia od standardowych rad

Ta sekcja jest nowa i napisana z pewną obawą; mimo to, musi być wspomniana.

Niektórzy ludzie używający EasyPeasy stwierdzają, że ich pragnienie oglądania porno staje się tak zredukowane, że nie mogą się zmusić do ostatniej sesji. **Jest to w porządku**, ale nie lekceważ potęgi posiadania jednej. Uważnie przeglądając i utrwalając tylko jak bardzo nie lubisz PMO może być naprawdę potężny. Osobiście znalazłem to naprawdę przydatne i był szczęśliwy, aby umyć ręce czyste z niego; autentycznie ulgę, aby nigdy nie mieć zrobić to kiedykolwiek ponownie. Jednak twój przebieg może się różnić.

Jeśli jesteś już wolny od tej pułapki przez jakiś czas i właśnie usunąłeś pranie mózgu, nie ma potrzeby karmić tego małego potwora, bo tylko by cię nagabywał. Zamiast tego ciesz się wolnością!

## Pomóż skończyć ten skandal

Internetowa pornografia jest jednym z zagrożeń w wolnym społeczeństwie, wykorzystującym w dobrej intencji wysiłki na rzecz wolności osobistych. Z pewnością podstawą cywilizacji - powodem, dla którego gatunek ludzki tak się rozwinął - jest to, że potrafimy przekazywać naszą wiedzę i doświadczenia nie tylko sobie nawzajem, ale i przyszłym pokoleniom. Nawet zwierzęta uważają za konieczne ostrzeganie swojego potomstwa przed życiowymi pułapkami.

Producenci pornografii nie robią tego w dobrej wierze, szczerze wierząc, że pomagają ludzkości, zwłaszcza teraz, gdy uzależnienie od pornografii internetowej jest szeroko badane. Być może w początkowym okresie ludzie szczerze wierzyli, że porno uczy ludzi intymności, ale władze wiedzą, że to fałsz. Żadna strona z pornografią nie twierdzi, że kształci. Jedyne roszczenia dotyczą szoku, nowości i eskalacji ich towarów.

Czysta hipokryzja jest niewiarygodna, jako społeczeństwo jesteśmy spięci z powodu znęcania się w szkołach i uprzedmiotowienia ludzkiego ciała. W porównaniu z pornografią internetową, te problemy to tylko pryszcze. Liczba osób uzależnionych wznosi się każdego roku na nowe wyżyny, spędzając czas z wyobrażonymi i iluzorycznymi pikselami kosztem ich zdrowia, męskości, energii i czasu. Jest to zdecydowanie największy zabójca w związkach, setki tysięcy ludzi rujnuje sobie życie każdego roku z powodu uzależnienia. Producenci internetowego porno nie reklamują się w głównych publikacjach -- nie muszą, nasze biologiczne popędy prowadzą nas w progi ich dobrze zaopatrzonych haremów, rozdających darmowe próbki niczym lokalny diler narkotyków. W dzisiejszych czasach, strony Hub nie tyle oferują towar, co zachęcają odwiedzających do zamieszczania treści.

Jakie to mądre, że firmy porno pokazują ostrzeżenia 18+ jako odstraszacze dla nieletnich użytkowników, niektóre nawet się tym nie przejmują. Internetowe porno dotyka wszystkich w każdym wieku. "*Ostrzegaliśmy cię przed niebezpieczeństwem, to twój wybór "* - to ich postawa. Czy podejmują jakieś kroki w celu weryfikacji wieku? Nie, to zniechęciłoby ich klientów. Oczywiście, jeśli weryfikacja wieku zostanie uchwalona, po prostu znajdą inny kraj, w którym będą działać. A może zapłacą jakiejś "elicie", żeby napisała o tym, jak prohibicja doprowadziła do bootlegging’u i powstania mafii? Wygodnie zapomina się o tym, dlaczego uchylenie prohibicji nie spowodowało zmniejszenia liczby ofiar związanych z alkoholem, a także o tym, że organy ścigania nie były w stanie kontrolować rozwoju mafii.

Możemy to rozwiązać inaczej poprzez edukację młodego pokolenia. Jeśli potrafią oni omijać papierosy i alkohol podczas zakupów, mogą to samo zrobić z pornografią internetową. Już teraz widzimy zmiany społeczne, takie jak "No Nut November" i memy "Coomer", które stają  się głównym nurtem. Użytkownik nie ma wyboru, tak jak nie ma go osoba uzależniona od heroiny. Użytkownicy nie decydują się na uzależnienie, są zwabieni w subtelną pułapkę. Gdyby mieli wybór, jedynymi użytkownikami jutro rano byliby nastolatkowie, którzy dopiero zaczynają, wierząc, że mogą przestać w każdej chwili, jeśli tylko zechcą.

Skąd te fałszywe standardy? Dlaczego osoby uzależnione od heroiny są postrzegane jako przestępcy, a mimo to mogą zarejestrować się jako uzależnieni i otrzymać metadon oraz odpowiednią opiekę medyczną, która pomoże im wyjść z nałogu? Po prostu spróbuj zarejestrować się jako uzależniony od porno, jeśli pójdziesz do lekarza po pomoc, oni albo powiedzą ci: "*Przestań robić to tak często, spróbuj umiaru*", co już wiesz, że nie zadziała, albo przepisze leki na twoją "depresję". Gorsza jest rada, żeby iść i znaleźć prawdziwych partnerów, poważnie? Czy oni znają użytkowników, dla których porno jest lepsze i robią to za plecami partnera? Niektórzy ludzie po prostu nie rozumieją.

Kampanie strachu nie pomagają użytkownikom przestać, tylko utrudniają to. Jedyne co robią to straszenie użytkowników, co sprawia, że chcą oglądać jeszcze więcej. Nie zapobiegają też uzależnieniu się nastolatków. Nastolatki wiedzą, że porno zabija ich libido, ale wiedzą też, że jedno zerknięcie nie załatwi sprawy. Ponieważ uzależnienie jest tak powszechne, prędzej czy później nastolatek - czy to przez presję społeczną, czy przez ciekawość - spróbuje tylko jednej wizyty. Ponieważ darmowe porno ma okropne klipy, jest prawdopodobne, że się uzależni.

Dlaczego pozwalamy, by ten skandal trwał dalej? Dlaczego rządy nie wychodzą z odpowiednimi kampaniami? Dlaczego nie mówi się nam, że porno w internecie to narkotyk i zabójcza trucizna, że nie relaksuje i nie dodaje pewności siebie, ale niszczy nerwy, wystarczy jedno spojrzenie, by się uzależnić? Dlaczego nie mogą egzekwować weryfikacji wieku, żądając zarejestrowanych kart kredytowych, być może z udziałem strony trzeciej? Mindgeek, właściciel wielu głównych stron pornograficznych, próbuje oszukać rządy, by korzystały z ich własnego rozwiązania weryfikacji wieku - nie pozwólcie im na to! *Wehikuł czasu* H. G. Well'a opisuje zdarzenie z dalekiej przyszłości, w którym człowiek wpada do rzeki. Jego towarzysze siedzą na brzegu jak bydło, nie zwracając uwagi na krzyki rozpaczy. Nieludzkie i niepokojące, podobnie jak ogólna apatia społeczeństwa wobec kryzysu porno.

Nadchodzi wiatr zmian w społeczeństwie. Kula śnieżna zaczęła toczyć się w dół wzgórza i jest nadzieja, że ta książka pomoże zmienić ją w lawinę. Ty też możesz pomóc, rozpowszechniając tę wiadomość.

W związku z tym proszę - jeśli widzisz kogoś, kto zmaga się z użyciem siły woli lub próbuje rzucić porno, uprzejmie skieruj go w stronę tej metody. Jednak prawdziwym zadaniem jest zmiana narracji wokół porno w ogóle. Proszę, rozważ wyrobienie w sobie nawyku, że jeśli widzisz w sieci, lub nawet doświadczasz normalizacji porno z pierwszej ręki, starasz się *szacunkowo* edukować i uwalniać.

Czasami możesz spotkać się z negatywną reakcją, ale czasami wystarczy tylko komentarz. Jak wielu przed tobą, możesz spodziewać się wiadomości od wdzięcznych ludzi, którzy podziękują ci za ich wolność.

## Ostatnie ostrzeżenie

Teraz możesz cieszyć się resztą swojego życia jako szczęśliwy nie-użytkownik. Aby upewnić się, że tak jest, musisz postępować zgodnie z tymi prostymi instrukcjami.

1.  Zachowaj poniższą stronę w zakładkach i odwołuj się do niej tyle razy, ile potrzebujesz.

2.  Jeśli kiedykolwiek zaczniesz zazdrościć innemu użytkownikowi, uświadom sobie, że on będzie zazdrościł Tobie. Nie jesteś pozbawiony możliwości korzystania z serwisu. Oni są.

3.  Pamiętaj, że bycie użytkownikiem nie sprawiało ci przyjemności. Dlatego właśnie przestałeś. Cieszy cię bycie nieużytkownikiem.

4.  Pamiętaj, że nie ma czegoś takiego jak tylko jedno zerknięcie.

5.  Nigdy nie wątp w swoją decyzję, aby już nigdy nie oglądać porno. Wiesz, że jest ona właściwa.

6.  Jeśli masz jakiekolwiek trudności, znajdź i skontaktuj się z terapeutą znającym się na pornografii internetowej. Listy takich możesz znaleźć w sieci.


