# Instrukcje

1.  Postępuj zgodnie ze wszystkimi instrukcjami.

2.  Zachowaj otwarty umysł.

3.  Zacznij od uczucia uniesienia.

4.  Ignoruj wszystkie rady i wpływy, które są sprzeczne z EasyPeasy.

5.  Oprzyj się każdej obietnicy tymczasowej naprawy.

6.  Wyjaśnij sobie w głowie: Porno nie dostarcza żadnej autentycznej przyjemności ani podpory i nie poświęcasz się niczemu. Nie ma z czego rezygnować i nie ma powodu, by czuć się pozbawionym.

7.  Nie czekaj z rzuceniem, zrób to teraz!

8.  Podejmij decyzję, że nigdy więcej nie będziesz oglądać i nie kwestionuj jej.

9.  Pamiętaj, że nie ma czegoś takiego jak tylko jedno zerknięcie.

10. Nigdy więcej nie oglądaj porno.

## Afirmacje

- Jestem wolny od niewoli porno.

- Łatwo jest ignorować moje myśli o porno.

- Pa pa myśli, pa pa popędy. Och, idą moje pragnienia.

- Skupiam swój podświadomy umysł, aby pokonać uzależnienie od porno.

- Porn kradnie mój czas, energię i witalność.

- Pokonanie porno staje się wykładniczo łatwiejsze dzień po dniu i w każdym aspekcie.

- Cieszę się i cenię mój wolny od porno, silny, szczęśliwy, lekki i łatwy styl życia.

- Kiedy patrzę wstecz i myślę o moich postępach, daje mi to wielką radość i dumę z siebie.

- Za każdym razem, gdy widzę innych użytkowników pornografii, mam większą motywację, by zobaczyć, jak samemu przerwać ten łańcuch.

- Cała ta nagromadzona energia uzdrawia moje ciało i umysł. Wtedy mogę wykonywać bardziej produktywną i wymagającą pracę w kierunku moich wartości i celów.

- Mój mózg wraca do właściwej formy, ćwiczony przez to, że *nie* robię tego, co wcześniej robiłem.

- Teraz cała ta spiętrzona siła woli jest wykorzystywana do radzenia sobie z lekkimi stresami i napięciami życia.

- Wspaniale, jestem wolny i nie jestem już niewolnikiem!


