#  एक आखिरी Visit

Timing decide कर ली है, तो अब तुम अपने कोठे की आखिरी visit के लिए तैयार हो। लेकिन पहले दो जरूरी चीज़ें check कर लो:

1.  क्या तुम्हें कामयाबी का पक्का यकीन है?

2.  क्या तुम डरे-सहमे हो, या exited हो कि कुछ धमाकेदार करने वाले हो?

अगर कोई doubt है तो पहले book फिर से पढ़ लो। याद रखो, तुमने कभी porn के trap में फंसने का फैसला नहीं किया था, पर ये trap बना ही ऐसा है कि जिंदगी भर का गुलाम बना दे। इससे निकलने के लिए तुम्हें एक positive फैसला लेना होगा कि तुम छोड़ रहे हो और ये तुम्हारी आखिरी visit है।

याद रखो, तुम ये book अब तक इसलिए पढ़ रहे हो क्योंकि तुम दिल से इस जेल से आज़ाद होना चाहते हो। तो अभी वो positive फैसला लो, एक पक्का वादा करो कि जब तुम private browser बंद करोगे, चाहे आसान हो या मुश्किल, तुम फिर कभी वापस उस online कोठे पर नहीं जाओगे। शायद तुम्हें tension है कि तुमने पहले भी कई बार ऐसे वादे किए हैं और fail हो गए हो, या फिर कि तुम्हें बहुत दर्द झेलना पड़ेगा। डरो मत, ज्यादा से ज्यादा बस fail होगे, मतलब कि तुम्हारे पास ***खोने को कुछ भी नहीं है*** और पाने को बहुत कुछ है।

लेकिन फेल होने के बारे में सोचना भी छोड़ो - सच्चाई ये है कि छोड़ना बेहद आसान ही नहीं, तुम इस process का मज़ा भी ले सकते हो। इस बार तुम EasyPeasy use करने वाले हो! बस इन simple steps को follow करो:

1.  अभी एक पक्का वादा करो और दिल से करो।

2.  अपनी favorite tube site पे pictures और clips को होश से देखो। देखो कैसे site वाले, actors और यहां तक कि amateurs भी shock, नया-पन और supernatural feel देने की बेकार कोशिश कर रहे हैं। खुद से पूछो - इसमें मज़ा कहां है?

3.  जब finally browser बंद करो, तो ये सोच के मत करो कि "*अब मुझे कभी online कोठा नहीं जाना" या "*मुझे जाने की इजाजत नहीं है*"। इसकी जगह आज़ादी feel करो, जैसे "*वाह बे क्या बात है! मैं आज़ाद हो गया! अब मैं porn का गुलाम नहीं हूं! मुझे जिंदगी में फिर कभी इन गंदी sites पे जाने की जरूरत नहीं!*"

4.  जान लो कि कुछ दिनों तक तुम्हारे पेट में एक छोटा सा porn का कीड़ा रहेगा। शायद तुम्हें बस session की चाहत महसूस हो। इस छोटे porn के शैतान को dopamine की हल्की सी physical craving कहा जाता है। पर सही मायने में ये गलत है, और ये समझना जरूरी है क्यों। क्योंकि इस छोटे शैतान को मरने में तीन हफ्ते लग सकते हैं, ex-users सोचते हैं कि आखिरी visit के बाद भी ये शैतान craving करता रहेगा, और इसलिए इस दौरान temptaion से बचने के लिए willpower की जरूरत पड़ेगी। ऐसा नहीं है, body को porn से मिलने वाले dopamine की craving नहीं होती; ये सिर्फ दिमाग का खेल है।

अगले कुछ दिनों में अगर एक झलक देखने की चाहत हो, तो तुम्हारे दिमाग के पास दो options हैं। या तो वो इस feeling को समझे कि ये क्या है - एक खालीपन, एक बेचैनी जो पहली बार porn sites देखने से शुरू हुई और हर बार देखने से बढ़ती गई, और खुद से बोलो **"YES बे! मैं अब FREE हूं!"**

या फिर, तुम porn के लिए तड़पते रहो और बाकी की जिंदगी इसी torture में काटो। जरा सोचो, ये कितनी बेवकूफी वाली बात होगी? एक तरफ कहो "*मैं कभी porn नहीं देखूंगा*" और फिर बाकी की जिंदगी यही रोते रहो "*एक बार देख लूं यार*"? यही वो लोग करते हैं जो willpower से छोड़ते हैं, तभी तो इतने दुखी रहते हैं। पूरी जिंदगी उस चीज के लिए रोते रहो जिसे तुम कभी न करने की दुआ मांग रहे हो। कोई हैरानी नहीं कि इतने कम लोग कामयाब होते हैं और जो होते हैं वो भी कभी पूरी तरह free फील नहीं करते।

> *‘अपने मन में एक picture बनाओ, जो बाहरी चीज़ों से परेशान होने से बचने में मदद करेगी। सोचो तुम एकदम शांत बैठे हो, phone बज रहा है, तुम उसे नजरअंदाज कर रहे हो, उसका तुम पर कोई असर नहीं है। तुम घंटी सुन रहे हो, पर अब वो तुम्हें चला नहीं सकती। ये पक्का समझ लो कि बाहर की कोई आवाज खुद में तुम पर कोई बस नहीं रखती। पहले तुम आदत से नाचते थे, अब चाहो तो नई आदत डाल सकते हो*
>
> *‘और ये भी समझो कि जवाब न देने का मतलब कुछ करना नहीं है, कोई जोर लगाना नहीं है, लड़ना-भिड़ना नहीं है - बस कुछ न करना है, शांत होना है। बस शांत रहो, घंटी को जाने दो, और उसकी आवाज को हवा में उड़ने दो। phone की घंटी तो बस एक मिसाल है, हर उस बाहरी चीज की जिसे तुमने अपने ऊपर control करने दिया है और अब उस आदत को बदलने का फैसला कर रहे हो।*'
>
> ---  मैक्सवैल माल्ट्ज़, *The New Psycho Cybernetics* Ch. 12.

Doubt और wait करने से ही छोड़ना मुश्किल हो जाता है, इसलिए ***कभी अपने फैसले पे शक मत करो*** क्योंकि तुम जानते हो ये सही फैसला है। अगर doubt करने लगे तो तुम खुद को ऐसी situation में डाल दोगे जहां से निकलना मुश्किल है। एक तरफ visit के लिए तड़पते रहोगे, दूसरी तरफ कर नहीं पाओगे। चाहे कोई भी system use कर रहे हो, porn छोड़ने से तुम क्या हासिल करना चाहते हो? कि कभी न देखो? नहीं! बहुत ex-users ऐसा करते हैं पर पूरी जिंदगी कुछ खोने का अफसोस करते रहते हैं।

users और non-users में क्या फर्क है? Non-users को न जरूरत होती है, न porn देखने की इच्छा होती है, उन्हें कोई craving नहीं होती और न ही willpower की जरूरत पड़ती है। यही तो तुम चाहते हो और ये बिल्कुल तुम्हारे हाथ में है। तुम्हें porn की craving खत्म होने या non-user बनने का इंतजार करने की जरूरत नहीं है, जैसे ही तुम आखिरी बार browser बंद करोगे और dopamine की supply काटोगे, बस हो गया काम। **तुम अभी से एक खुश non-user हो!**

तुम खुश non-user बने रहोगे अगर:

1.  कभी अपने फैसले पे शक न करो।

2.  Non-user बनने का इंतजार न करो। अगर करोगे तो बस कुछ न होने का इंतजार करते रहोगे और एक phobia बना लोगे।

3.  Porn के बारे में न सोचने की कोशिश *न* करो या 'सच्चाई के पल' आने का इंतजार न करो, वरना phobia बन जाएगा।

4.  कोई substitutes use न करो।

5.  बाकी users को वैसा ही देखो जैसे वो हैं - उनसे जलो मत, उन पर तरस खाओ।

चाहे अच्छे दिन हों या बेकार, porn छोड़ने की वजह से अपनी life मत बदलो। अगर बदलोगे तो कुछ खोने का एहसास होगा जबकि खो कुछ नहीं रहे हो। याद रखो, तुमने जीना नहीं छोड़ा है। तुमने कुछ भी नहीं छोड़ा है। उल्टा, तुमने खुद को एक खतरनाक बीमारी से छुटकारा दिला लिया है और एक चालाक jail से भाग निकले हो। जैसे-जैसे दिन बीतेंगे और तुम्हारी सेहत - physical और mental - बेहतर होगी, अच्छे moments पहले से भी ज्यादा अच्छे लगेंगे और बेकार moments उतने बेकार नहीं जितने use के time में लगते थे। अगले कुछ दिनों में या पूरी life में जब भी porn का ख्याल आए, सोचो:

***“वाह बे! मैं FREE हूं!"***

## एक आखिरी warning

किसी भी user को अगर वापस उस टाइम में जाने का मौका मिले जब वो फंसा नहीं था, और आज की knowledge भी साथ हो, तो कभी शुरू नहीं करेगा। हजारों लोग सालों तक छोड़ कर खुशी-खुशी जीते हैं, फिर भी दोबारा trap में फंस जाते हैं। मुझे उम्मीद है ये book तुम्हें आसानी से छोड़ने में मदद करेगी। लेकिन एक warning - जिन users को छोड़ना आसान लगता है, उन्का दोबारा शुरू करना भी उतना ही आसान होता है। **इस trap में मत फंसना।**

चाहे कितने भी time से छोड़ा हो या कितना भी confident हो कि दोबारा नहीं फंसोगे, एक जीवनभर का नियम बना लो - किसी भी वजह से porn नहीं देखना है। Media में जो hints और इशारे दिखें, उनसे दूर रहो। याद रखो कैसे वो 'खुलेपन' के नाम पर porn को mainstream में ला रहे हैं, और उन्हें नहीं पता कि porn और आदत की मजबूरी से masturbation करना  कितने रिश्तों को और लोगों की खुशी को बर्बाद कर रहे हैं - न सिर्फ लड़कों की, बलकी लड़कियों की भी।

याद रखो, पहली झलक या visit तुम्हारे लिए कुछ नहीं करेगी। कोई withdrawal की बेचैनी भी नहीं होंगी जो दूर करनी हों और तुम्हें बेहद गंदा feel होगा। पर इससे dopamine की kick का मज़ा तुम्हारे दिमाग में घुस जाएगा, और दिमाग में एक हलकी सी आवाज कहेगी कि एक और चाहिए। फिर तुम्हारे पास दो options होंगे - या तो कुछ time दुखी रहो, या फिर से वही गंदी chain शुरू करदो।
