# इस डूबते जहाज के लोगों की मदद करो

आजकल porn users panic में हैं। समझ रहे हैं कि लोगों की सोच बदल रही है internet porn को लेकर। Science वाले भी अब इसकी लत पर research कर रहे हैं, और कह रहे हैं कि ये पुराने type के porn से एकदम अलग चीज है। इतनी आसानी से, कहीं भी, कभी भी मिल जाना - ये बात तो porn के supporters को भी डरा रही है। और तो और, उनकी 'free speech' वाली बकवास को भी लोग challenge कर रहे हैं। Internet पे तो कोई पुलिस है नहीं, तो बच्चों को इस जहर से कैसे बचाएं? बुरी बात है कि ये सब जल्दी खत्म नहीं होने वाला, पर अच्छी बात ये है कि लाखों लोग छोड़ रहे हैं। अब तो ज्यादातर addicts को पता है कि porn की लत drugs जैसी ही है - science भी यही कह रही है। और जब भी कोई इस डूबते जहाज से बच निकलता है, जो पीछे रह गए हैं वो और दुखी हो जाते हैं।

हर यूजर के दिल में एक आवाज तो कहती है कि कितनी बेवकूफी है ये - screen पे 2D pixels को घूरते रहना, दिमाग को इतना भड़काना कि असली sex लाइफ की वाट लग जाए। अभी भी नहीं समझ आ रहा? तो एक काम करो - शहर के चौराहे पे खड़े होकर किसी porn magzine से बात करके देखो। क्या फर्क है? बस एक - उससे न तो गले लग सकते हो, न प्यार कर सकते हो। देखो भाई, अगर तुम दुकान जाकर शराब-Cigarette लेना छोड़  सकते हो, तो ये online कोठे जाना भी छोड़ सकते हो। Users के पास कोई सही वजह नहीं है porn देखने की, बस दूसरे भी देख रहे हैं इसलिए उन्हें खुद इतना गलत नहीं लगता।

यूजर्स अपनी आदत के बारे में खुलेआम झूठ बोलते हैं, न सिर्फ researchers और दूसरों से, खुद से भी। मजबूरी है - थोड़ी सी इज्जत बचानी है तो ये brainwashing जरूरी है। अपनी 'आदत' को justify करने की जरूरत उन्हें सिर्फ *खुद* से ही नहीं, दूसरों से भी लगती है। चालाकी से porn के फायदे गिनाते रहते हैं।

जो willpower से छोड़ते हैं वो खुद को कुछ खोया हुआ महसूस करते हैं, रोते-धोते रहते हैं। इससे बाकी users और पक्के हो जाते हैं कि वो सही कर रहे हैं। और अगर कोई ex-user कामयाब हो भी जाता है, तो वो बस खुश होता है कि अब उसे खुद की वाट नहीं लगानी, energy waste नहीं करनी, और किसी को कुछ explain नहीं करना। याद रखो, डर ही यूजर को रेत में सिर छुपाने को मजबूर करता है, छोड़ने के बाद ही समझ पाते हैं कि क्या गलत कर रहे थे। Users की मदद करो उनका डर निकालो। बताओ कितना मस्त है इस जेल से बाहर की जिंदगी, कितना अच्छा लगता है सुबह उठकर फिट और healthy feel करना, न कि थकेहुए और घृणितता के साथ उठना। कितनी खुशी मिलती है गुलामी से आजाद होकर, पूरी ज़िंदगी का मजा लेने में, उन काले सायों से छुटकारा पाने में। या फिर सबसे अच्छा - उन्हें ये किताब पढने को दो।

शादीशुदा users को ये कह के छोटा मत महसूस कराओ कि वो जान-बूझकर अपना रिश्ता बर्बाद कर रहा है या ये किसी तरह की बेवफाई या गंदी बात है। लोग सोचते हैं कि ex-user इस मामले में सबसे बुरा होता है। इसमें कुछ सच्चाई है, पर ये ज्यादातर willpower से छोड़ने की वजह से होता है। क्योंकि ex-user - भले ही छोड़ चुका हो - अभी भी थोड़ा brainwashed रहता है और सोचता है कि उसने कुछ खोया है। वो खुद को कमजोर महसूस करता है और बचाव में porn users पर attack करते है।

इससे ex-user का ego तो बढ़ता होगा, पर users की कोई मदद नहीं होती। उल्टा users defensive हो जाता है, और ज्यादा बेकार महसूस करता है, और फिर porn की जरूरत और बढ़ जाती है। हालांकि medical experts का internet porn के लीये बदलता रवैया एक बड़ी वजह है कि बहुत users अब छोड़ रहे हैं, पर इससे छोड़ना आसान नहीं हो जाता। असल में, और मुश्किल हो जाता है। आजकल ज्यादातर users सोचते हैं कि वो मुख्य रूप से health की वजह से छोड़ रहे हैं। पर ये पूरी सच्चाई नहीं है।

हां, health का बड़ा risk है और यही छोड़ने की primary वजह लगती है, पर सोचो - user सालों से अपनी मर्दानगी की वाट लगा रहे हैं, फिर भी कोई फर्क नहीं पड़ा। असल वजह है कि समाज अब porn को असली रूप में देख रहा है: एक नशे की लत। लोगों की सोच धीरे-धीरे बदल रही है: अब अगर कोई आधी रात को laptop पे हो तो partner सवाल पूछने लगेंगे।

कुछ देशों में porn पे पूरी ban या internet ना होना traveling users की दुविधा का एक classic उदाहरण है। आम तौर पर वो सोचते हैं कि इससे कुछ दिनों के लीये तो देखना तो कम हो ही जयेगा। दिन में एक-दो session की जगह, जिनमें मज़ा भी नहीं आता था, पूरा हफ्ता रुक जाते हैं। पर इस जबरदस्ती के रुकावट में क्या होता है? दिमाग तो अपने पुरस्कार का इंतजार कर रहा होता है, और body भी तड़प रही होती है। और जब आखिर में मौका मिलता है तो वो online कोठे की visit बहुत कीमती लगती है!

जबरदस्ती रुकना असल में intake कम नहीं करता क्योंकि जब मौका मिलता है तो users दोगुना देखता है। इससे बस users के दिमाग में ये और पक्का हो जाता है कि porn कितनी कीमती चीज है और वो इस पर कितना depend करता है। सबसे खतरनाक असर teenagers पे पड़ता है। पहले तो हम 'expression की आज़ादी' के नाम पे porn बनाने वालों को बेचारे teenagers को target करने देते हैं, उन्हें लत लगवाने के लिए। फिर उनकी ज़िंदगी के सबसे तनाव भरे समय में, जब उनके confused दिमाग को लगता है कि उन्हें porn की सबसे ज्यादा जरूरत है, हम blackmail करते हैं कि छोड़ दो, अपना नुकसान कर रहे हो।

बहुत लोग छोड़ नहीं पाते और बिना अपनी गलती के पूरी जिंदगी guilt में जीते हैं। कुछ कामयाब हो जाते हैं और खुश होते हैं, सोचते हैं, *\"ठीक है, अभी के लिए कर लेता हूं, बाद में तो वैसे भी ठीक हो जाऊंगा।\"* फिर job ढूंढने का तनाव आता है और बाकी adult problems, और फिर जिंदगी की सबसे बड़ी 'high' - job मिल जाना। तनाव खत्म, अब settle हो गए, और पुराना trigger वापस शुरू हो जाता है। दिमाग में थोड़ा brainwashing तो अभी भी है, और नई job के laptop की smell जाने से पहले ही users अपने पसंदीदा online कोठे के दरवाजे पे जा पहुचता है। खुशी के मारे पुरानी बुरी experiences भूल जाता है, लत लगाने का इरादा तो नहीं होता, पर सोचता है एक छोटी सी झलक से क्या ही हो जाएगा...पर तब तक बहुत देर हो चुकी होती है! user फिर से फंस गया होता है।

वो छोटा शैतान फिर से craving शुरू कर देगा और भले ही तुरंत लत न लगे, पर high के बाद की depression पक्का पकड़ ही लेगा। अजीब बात है ना - heroin के नशेड़ी कानून में criminal हैं, फिर भी समाज उन पर तरस खाता है। तो चलो porn users के साथ भी ऐसा ही व्यवहार करें। वो ये सब शौक से नहीं कर रहे, बस उन्हें लगता है कि करना पड़ेगा, कोई चारा नहीं है। और heroin वालों से भी बुरी बात ये है कि ये लोग सालों-साल तक दिमागी और physical torture झेलते रहते हैं। हम कहते हैं ना कि जल्दी मरना धीरे-धीरे मरने से बेहतर है, तो इन बेचारे porn users से जलन मत रखो। ***उन पर तरस खाओ यार।***
