# Instructions

1.  सारे instructions follow करो।

2.  खुले दिमाग से समझो।

3.  खुशी और जोश की feeling से शुरू करो।

4.  जो भी सलाह या influence EasyPeasy के खिलाफ जाए, उसे ignore करो।

5.  Temporary fix के किसी भी वादे में मत फंसो।

6.  दिमाग में clear कर लो: porn न तो कोई असली खुशी देता है न सहारा, और तुम कुछ खो नहीं रहे हो। छोड़ने को कुछ है ही नहीं और वंचित महसूस करने की कोई वजह नहीं है।

7.  छोड़ने का इंतजार मत करो, अभी छोड़ो!

8.  फैसला करो कि कभी दोबारा नहीं देखोगे और इस फैसले पर कभी सवाल मत करो।

9.  याद रखो "बस एक देखलूं" जैसा कुछ नहीं होता।

10. कभी भी porn मत देखो।

## सकारात्मक विचार

-   मैं porn की गुलामी से आज़ाद हूं।

-   Porn के बारे में सोच को ignore करना आसान है।

-   Bye-bye thoughts, bye-bye तड़प। देखो, cravings भी चली गईं।

-   मैं अपने subconscious mind को porn की लत से जीतने पर फोकस करता हूं।

-   Porn मेरा समय, ताकत और जीवंतता चुराता है।

-   Porn को हराना हर दिन और हर पहलू में और भी आसान होता जा रहा है।

-   मैं अपनी porn-free, मजबूत, खुश, हल्की और आसान lifestyle को enjoy करता हूं और value करता हूं।

-   जब मैं पीछे देखता हूं और अपनी progress के बारे में सोचता हूं, तो मुझे खुद पर बहुत गर्व और खुशी होती है।

-   जब भी मैं दूसरे porn users को देखता हूं, मुझे और motivation मिलता है कि मैंने वो chain तोड़ दी।

-   सारी रुकी हुई energy मेरे दिमाग और body को heal कर रही है। अब मैं अपनी values और foals के लिए ज्यादा productive और चुनौती वाले काम कर सकता हूं।

-   मेरा दिमाग वापस सही हो रहा है, क्योंकि मैं पहले जो करता था वो *नहीं* कर रहा।

-   अब वो सारी जमा willpower ज़िंदगी की छोटी-मोटी tension handle करने में use हो रही है।

-   वाह! मैं free हूं और अब गुलाम नहीं रहा!
