# 为什么很难停止？

所有用户都感觉到有什么邪恶的东西控制了他们。在早期，这只是一个简单的问题：*"我会停止的，只是不是今天"*。最终我们开始相信自己没有足够的意志力来停止，或者色情中有一些我们享受生活所必需的东西。色情成瘾就像从滑溜溜的坑里往外爬：当我们快到顶部时，看到了阳光，但发现自己随着情绪低落而滑回去。最终我们打开浏览器，当我们自慰时，感觉非常糟糕。

问一个用户，*"如果你能回到上瘾之前的时候，带着你现在的知识，你还会开始使用色情吗？"*

*"绝对不会！"*会是回答。

问一个确认的用户，一个为网络色情辩护并且不相信它会损害大脑或导致多巴胺受体下调的人：*"你会鼓励你的孩子使用色情吗？"*

*"绝对不会！"*同样是回答。

色情是一个非同寻常的谜。如前所述，问题不在于解释为什么容易停止，而是解释为什么很难停止。真正的问题是解释为什么有人在了解了神经系统损害的知识*之后*还会继续做。我们开始的部分原因是因为已经有数千万人在做，然而所有这些人都希望自己从未开始，告诉我们这就像生活在二档。我们不太相信他们不享受，因为我们把它与自由或"接受性教育"联系起来，并努力让自己上瘾。然后我们花余生告诉别人不要这样做，同时自己也试图戒掉这个习惯，常常认为自己在这方面是独特的。

我们还花相当大比例的时间感到绝望和痛苦。用超常刺激"教育"自己使我们更喜欢和渴望这些冷冰冰的图像，即使温暖的、真实的图像唾手可得。通过PMO引起的多巴胺不断飙升和下降，我们让自己终身处于孤立、易怒、愤怒、压力、疲劳和性功能障碍中。使用色情，由于缺乏性爱和连接的最佳部分，我们最终感到痛苦和内疚。

事实上，在这里和其他网站上阅读关于网络色情的成瘾性和破坏性能力的文章让我们更加紧张和绝望！这是一种什么样的爱好，当你在做的时候你希望自己不做，当你不做的时候你又渴望它？用户每次读到关于前额叶功能低下和脱敏化的文章时都鄙视自己，每次在信任他们的伴侣背后使用时都鄙视自己，每次在白天使用后无法让自己去锻炼时都鄙视自己。一个在其他方面聪明理性的人每天都处于自我蔑视中。但最糟糕的是，用户不得不忍受在他们脑海后面挥之不去的可怕阴影，他们得到了什么？**绝对什么都没有！**

你可能在想*"这一切都很好，我知道这些，但一旦你对这些东西上瘾，就很难停止。"*但为什么这么难？有些人说是因为强烈的戒断症状，但正如你很快会了解到的，实际的戒断症状非常轻微。当你考虑到许多PMO用户一辈子都没意识到他们是瘾君子时，这一点就很明显了。

有些人说网络色情是免费的，因此人类应该享受这种生物的意外之财，但这是不对的——它是令人上瘾的，其作用方式就像任何毒品一样。问一个发誓他们只享受像《花花公子》杂志那样的"情色"的用户，他们是否曾经越过界限看过"不安全的色情"。如果他们完全诚实，他们会承认自己曾经为越过那条线找借口，而不是什么都不用。

享受与此无关。我喜欢小龙虾，但我从来没有到必须每天吃小龙虾的地步。对于生活中的其他事情，我们在做的时候享受它们，但当我们不做的时候，我们不会坐在那里感到被剥夺。

有些人说：
*"这是教育性的！"*那么它是如何帮助你成长为一个人的？
*"这是性满足！"*那么为什么它让你孤立并使你感到无法满足的渴望？
*"这是一种释放的感觉！"*从现实生活的压力中释放？好的，一个小时后，这一切不是又全部压回来了吗？它解决了什么压力？
*"它帮助我入睡"*那么为什么其他人没有它也能睡得很好？有[很多](https://www.sleepfoundation.org/insomnia/treatment/meditation)经过科学证明的[方法](https://www.sleepfoundation.org/insomnia/treatment/cognitive-behavioral-therapy-insomnia)可以[修复](https://www.amazon.com/Uvex-Blocking-Computer-SCT-Orange-S1933X/dp/B000USRG90)睡眠，[而且更多](https://www.menshealth.com.au/what-is-the-military-method-the-technique-that-promises-to-help-you-sleep-in-2-minutes)。

许多人相信色情可以缓解无聊，但无聊是一种心态。色情会让你很快习惯于寻求新奇，使你越来越感到无聊，直到你最终参与那场追寻恰到好处的片段的疯狂追逐，变得越来越倾向于寻求任何能唤起新奇、强烈情感，最终是惊人震撼价值的东西。

有些人说他们这样做只是因为他们的朋友和他们认识的每个人都这样做。如果是这样，祈祷你的朋友不会开始砍掉他们的头来治疗头痛！大多数认真思考的用户得出结论，这只是一种习惯。这其实不是一个解释，但在排除了所有通常的、理性的解释之后，这似乎是唯一剩下的借口。不幸的是，这同样不合逻辑。在我们生活的每一天，我们都在改变习惯，其中一些非常令人愉快。我们已经被洗脑相信PMO是一种习惯，习惯很难打破。

习惯真的很难打破吗？美国的司机习惯在道路右侧驾驶，然而在出国旅行时，他们几乎毫无困难地打破了这个习惯。当你找到一份新工作时，你会养成不同的作息习惯，所以你的习惯会改变。这些可能需要一些适应，但这与打破一生与色情成瘾的斗争完全不同。我们每天都在养成和打破习惯，那么为什么我们发现很难打破一个让我们在没有它时感到被剥夺、在做的时候感到内疚、我们反正很想打破的习惯呢，我们所要做的只是*停止做它*？

答案是色情不是习惯，*它是成瘾！*这就是为什么它看起来如此难以"放弃"。大多数用户不了解成瘾，并相信他们从色情中获得了一些真正的快乐或支撑。他们相信如果戒掉，他们会做出真正的牺牲。

美丽的真相是，一旦你理解了色情成瘾的真正本质以及你使用它的原因，你就会停止它，就这样。三周之内，唯一的谜团将是你为什么觉得有必要使用色情这么久，以及为什么你无法说服其他用户*不做PMO者是多么美好！*

## 阴险的陷阱

网络色情是人和自然共同设计的微妙而阴险的陷阱。我们中的一些人甚至被警告过危险，但我们不相信自己怎么会不享受。但一开始是什么让我们陷入其中的呢？通常是业余爱好者和专业人士分享的免费样品。陷阱就是这样布下的。如果它在我们第一次看之前就警告我们即将进入的危险，那么警报就会尖叫。

但这些警报没有响起。也许是许多片段的令人震惊的性质让我们年轻的心放心，我们永远不会上瘾，认为因为我们不享受它们，我们可以随时停止。或者也许是柔和材料的表面无害性没有触发任何警报，就像骗子可以巧妙地编织来引导我们思想的手法。作为聪明的人，我们会理解为什么成年人口中有一半系统性地沉迷于某种正在削弱我们完成我们正在观看的事情的潜力的东西。好奇心把我们带到成瘾的门槛，但我们不敢点击我们正在瞥见的缩略图，害怕它们会让我们生病或把我们送入一条危险和不道德的道路。如果我们不小心点击了一个，通常我们唯一的愿望就是尽快离开那个页面，同时又更加绝望地好奇。

一旦这个过程开始，我们就被困住了。从现在起，我们花费余生试图理解我们为什么这样做，告诉我们的孩子不要开始，并在某些时候试图自己逃脱。陷阱被设计成这样，我们只是由于"事件"而试图停止，无论是性表现、失去职业或人际关系、缺乏动力还是仅仅是感觉像个麻风病人。一旦我们停止，由于戒断痛苦我们有更多的压力，而我们依赖来消除压力的方法现在不可用了。

我们戒掉的决心然后被证明是不稳定的。经过几天的折磨后，我们说服自己选错了戒掉的时机，决定等待没有压力的时期，而当这个时期到来时，就消除了我们最初停止的理由。当然，那个时期永远不会完全到来，我们开始相信我们的生活往往变得越来越有压力。我们离开父母的保护，工作、家务、抵押贷款、购买住所和抚养孩子的压力开始充斥我们的生活。但这是一种错觉。任何生物生命中最有压力的部分实际上是幼年和青春期。

我们倾向于混淆责任和压力。用户的生活——就像吸毒者的生活一样——自动变得更有压力，因为色情并不像有些人试图让我们相信的那样让我们放松或缓解压力。恰恰相反，它使我们在继续使用时变得更加紧张，每一次充满内疚的深夜余波都在骆驼背上增加更多稻草。即使是戒掉了这个习惯的用户——大多数人在一生中都会这样做一次或多次——也可以过着完全幸福的生活，然后突然又上瘾了。走进色情的迷宫，我们的思想变得模糊，我们花余生试图逃脱。许多人成功了，却在以后又落入阴险的陷阱。

解决色情成瘾问题是一个谜。它复杂而困难。但一旦你看到答案，它就变得简单而有趣，你会惊讶自己怎么没有想到！轻松戒色包含了这个谜题的解决方案，引导你走出迷宫，再也不会迷路。**你所要做的就是严格遵循每一条指示**。然而，如果你通过**跳章**走错了弯，或者**以闪电般的速度**飞快地读完这本书而没有在第一次阅读时仔细做出刻意的努力，那么其余的指示都是没有意义的。

任何人都可以发现停止是容易的，但我们必须首先确立事实。不，不是那些旨在吓唬你的事实，已经有足够多的信息了。如果那能阻止你，你早就停止了。但为什么我们发现很难停止？回答这个问题需要我们知道我们仍在使用色情的真正原因，归结为两个因素。它们是：

-   自然和网络色情。

-   社会洗脑。

色情用户是聪明、理性的人。他们知道自己在冒巨大的未来风险，所以花很多时间来合理化他们的"习惯"。但色情用户内心深处知道他们是傻瓜，知道他们在上瘾之前不需要使用色情。大多数人还记得他们第一次"看一眼"是厌恶和新奇好奇的混合。然后他们专门定位、过滤和收藏网站，努力让自己上瘾。

最令人恼火的是，有一种感觉，那些非成瘾者——大多数女性、年长者，以及生活在无法获得高速网络色情的国家的人——并没有错过任何东西，他们觉得这种情况很可笑。通过在接下来的章节中拆解这些因素，你也会理解这个阴险的陷阱！
