# 我放弃了什么？

**绝对什么都没有！** 色情之所以难以放弃，是因为我们害怕被剥夺了快乐或支柱。害怕某些愉快的情境将再也不会像从前一样。害怕自己将无法应对压力情境。换句话说，这是洗脑欺骗我们相信性——以及由此引申的性高潮——是所有人类的必需品。更进一步，这是相信网络色情中有某种我们需要的东西，当我们停止使用时，我们将在剥夺自己并制造一个空洞。

在你的脑海中清楚地记住这一点：**色情不是在填补空洞，** ***而是在创造空洞！***

我们的身体是这个星球上最复杂的对象。无论你相信智慧设计、自然选择还是两者的结合，我们的身体比人类创造的东西高效数千倍！我们无法创造最小的活细胞，也无法复制视觉、生殖以及我们身体和大脑中存在的各种相互关联系统的奇迹。如果这个创造者或过程打算让我们处理超常刺激，我们将会被赋予不同的奖励系统。我们的身体配备了故障安全警告装置，我们忽视这些装置将自食其果。

## 没有什么可以放弃的

一旦你从身体中清除了小怪物，从思想中清除了洗脑（大怪物），你既不会想经常自慰，也不会想使用网络色情来自慰。关于色情成瘾有许多已知和未知的东西，医学界中许多人没有概念去质疑或确定某人是否是色情成瘾者。许多报告的症状被错误地归类在其他原因下。问题不在于用户普遍是愚蠢的人，而是他们没有色情就会很悲惨。夹在魔鬼和深蓝色大海之间，戒断色情并因为无法使用而痛苦，或者因为内疚而痛苦并开始因此而鄙视自己。当他们出现下背疼痛或性功能障碍等症状时，他们的思维在接受责任和向另一边看之间撕裂。

另一个吸烟者类比：我们都见过吸烟者想出借口溜去偷抽一口，我们在这里看到了真正的成瘾在起作用。成瘾者这样做不是为了享受，而是因为没有它他们会很悲惨。

对许多人来说，他们的第一次性经历以性高潮结束，所以他们形成了没有性高潮就无法享受性的信念。对于男性来说，色情被作为性行为的辅助工具进行营销，有时甚至作为行为中自信心的教育工具。这是无稽之谈，超常刺激的条件反射只会成功地把它降低。

不仅没有什么可以放弃的，而且还有巨大的积极收获。当用户考虑戒掉时，他们倾向于专注于健康和性能力。这些是有效且重要的原因，但我个人认为最大的收获是心理上的：

-   自信和勇气的回归。

-   从奴役中获得自由。

-   不再在脑后有可怕的黑影并鄙视自己。

## 空洞，那个空洞，美丽的空洞！

想象你脸上长了一个唇疱疹，于是你去药剂师那里，他给你一个免费的软膏试用。你涂上软膏，它立刻消失了。一周后它又出现了，所以你回到药剂师那里，问他们是否还有软膏。药剂师说：*"当然；把这管留着，你以后可能需要它。"*

你涂上软膏，嘿，疱疹再次消失了。但每次疱疹复发，它都会变得更大更痛，间隔时间越来越短。最终，疱疹覆盖了你整个脸，疼痛难忍，每隔半小时就会复发。你知道软膏能暂时消除它，但你非常担心。疱疹最终会蔓延到全身吗？间隔会完全消失吗？你去看医生，他们无法治愈，所以你尝试其他方法，但除了软膏什么都没用。

到了这个时候，你完全依赖软膏，出门时总是确保带着一管。如果出国，你一定要带几管。除了对健康的担忧，药剂师向你收取每管一百美元的费用。你别无选择，只能付钱。

你偶然看到一篇讨论这个问题的文章，发现这不只是你的问题，许多人都遭受着同样的问题。事实上，医学界发现软膏实际上并不能治愈疱疹，而只是将它压到皮肤表面以下。是软膏导致疱疹越长越大，所以你要摆脱疱疹，只需要停止使用软膏，它就会随着时间的推移消失。

你还会继续使用软膏吗？不使用软膏需要意志力吗？如果你不相信这篇文章，可能会有几天的忐忑不安，但一旦你意识到疱疹开始好转，使用软膏的需求或欲望就会消失。你会感到痛苦吗？当然不会！你有一个你以为无法治愈的可怕问题，但现在你找到了解决方案。即使疱疹需要一年时间才能消失，每天随着它的改善，你都会想到自己感觉多么美好。这就是戒色的魔力。

疱疹不是身体上的疼痛、正常欲望的缺失、性唤起的减退、性能力的减弱、浪费在二维图像上的时间、对侵犯权利的感觉，以及鄙视发现你的人，甚至更糟糕的是鄙视你自己。这些都是疱疹之外的附加物。

疱疹让我们对所有这些事情关闭思想——那是一种想要满足的恐慌感。非用户不会遭受那种感觉。我们所遭受的最坏的事情是恐惧，最大的收获是摆脱那种恐惧。它是由你的第一次使用引起的，并由随后的每一次使用进一步强化和引发。

一些用户是"快乐的"，被他们狡猾的小怪物蒙蔽，因此经历着同样的噩梦，提出虚假的论点来试图为自己的愚蠢辩护。

*自由的感觉真是太好了！*
