# YouTube/Twitch/Instagram用户

这类用户应该与偶尔用户归为一类，但其影响如此阴险，以至于值得单独成章。它导致了自控力的崩溃，几乎让一位NoFap论坛用户分道扬镳：

> *"在我失败的停止尝试中，我已经坚持了三周，这次尝试是由我妻子对我不可靠的勃起和缺乏兴趣的担忧所触发的。我告诉她那不是她的原因，只是工作压力。她说：'我知道你以前处理过工作压力，但如果你是我，看着一个你爱的人有系统地摧毁自己，你会有什么感受？'这是一个我无法抗拒的论点，因此做出了停止的尝试。她知道我没有出轨，但这在某种意义上比那更糟。这次尝试在三周后结束，以与一位老朋友的激烈争吵达到顶点。直到多年后才意识到，我狡猾的思维故意触发了这场争吵，当时我感到有理由感到激动，但不认为这是巧合，因为我以前从未与这个特定的朋友争吵过，此后也没有。这显然是小怪物在起作用。*
>
> *"不管怎样，我有了我的借口。我迫切需要一个发泄，不管用什么方式。我妻子不在状态，所以我有一种'权利感'，于是我说服自己，如果我'限制'自己，避免色情网站，只看YouTube视频停留在'红线'这边，那就没问题了。但随着夜晚的发展，我妻子最终'转变了'，想要做爱，然而我已经筋疲力尽，没有了'马力'，所以我编造了一个头痛。我无法忍受想到这会给我妻子带来多大的失望。然后我逐渐回到了老路，YouTube成了我新的后宫目的地。我记得当时我相当高兴，认为这至少减少了我的消费量。最终，她指责我继续在床上忽视她。我没有意识到，但她描述了我制造争吵并冲出家门的次数。其他时候，花两个小时购买一件小物品，假装扭伤。我找了一些站不住脚的借口来逃避追求她，所以当我有了可靠的网上后宫时，事情就更难了。"*

关于YouTube用户，最糟糕的事情是它支持了他们心中的谬误——他们正在被剥夺。同时，它造成了巨大的自尊损失；一个本来诚实的人可能会迫使自己欺骗自己所爱的人。这可能已经发生了，或者仍然以某种形式发生在你身上。

Twitch、Instagram、TikTok、Twitter（以及大多数社交媒体）等网站面临的问题主要是由补充驱动的。受寻求新奇多巴胺冲动的驱使，他们欺骗自己相信自己在一个安全的网站上。记住——快感在于寻找，而不是猎杀，小怪物不在乎它的满足从哪里来。对用户来说，他们在各种网络推送中收到的"软性"内容给了他们短暂的戒断痛苦缓解，让他们保持上钩状态，等待下一次使用。

图片/视频中的模特确实很漂亮，如果他们现在在你身边，他们确实可以给你带来快乐，但那张图片不能……它根本不是真实的。你的大脑被欺骗了，就像一头公牛冲向红色斗篷，事后不明白为什么自己会那样做。人们可能会认为你只看那些图片，然后不自慰就行了。但记住，你的大脑上钩于无限的新奇，小怪物不在乎它的满足从哪里来。这是同样的陷阱。

你可能看过电视剧《神探可伦坡》。每集的主题都差不多。反派，通常是一个富有且受人尊重的商人，犯下了他确信是完美谋杀的案件，当他发现负责调查的是外表相当邋遢、毫不起眼的可伦坡探长时，他对自己的犯罪不被发现的信心更大了。

可伦坡有一个令人沮丧的习惯：在完成审讯后关上门，向嫌疑人保证他没事。但就在凶手脸上满意的表情还未消失之前，可伦坡又出现了，说"*先生，只是有一个小问题，我相信您能解释……*"嫌疑人结结巴巴，从那时起他知道可伦坡会逐渐磨垮他。不管罪行有多么严重，从那时起，同情都在凶手一边。

这些发作是类似的，不被允许越过红线获得他们"理应得到"的色情满足的紧张感，然后在完成动作后疑惑快感在哪里。害怕越线、失去控制并回到床上，只是被伴侣想要性爱的恐惧所纠缠。由于脱敏、缺乏新奇以及迟早会访问最喜欢的网上后宫的确定知识，"安全"的YouTube视频将不再令你满足。最终的羞辱和耻辱然后是当那种确定性成为事实，随即回到连续观看。

**哦，成为一个PMO用户的乐趣！**
