# 我会错过乐趣吗？

**不会！** 一旦小色情怪物死去，在你的身体停止渴望多巴胺之后，你大脑中的色情水滑梯因为缺乏"润滑"而迅速开始消退，任何残余的洗脑都会消失。你不仅会发现自己在身体和精神上都更能应对生活的压力和紧张，而且会充分享受美好时光。

只有一个危险，那就是那些仍然将性爱作为拐杖和乐趣的人的影响。*"别人家的草总是更绿"* 在我们生活的许多方面都很常见，很容易理解。为什么在色情的情况下——当缺点与虚幻的"优点"相比是如此巨大——前用户会倾向于羡慕那些将性爱和色情作为拐杖的人？

带着从童年开始的所有洗脑，我们陷入陷阱是完全可以理解的。然而，为什么——在意识到色情是一种愚蠢的游戏，并设法戒掉这个习惯之后——我们会直接走回同样的陷阱？这是社会洗脑的影响，将色情与性爱混为一谈，呈现为正常。前用户感到一阵渴望！他们单身（这本身并不是什么罪）的不安全感造成的空虚感引发焦虑，并驱使他们再次滑上水滑梯。这确实是一个奇特的异常，特别是如果考虑到这个观察：世界上不仅每一个非用户都很高兴自己不是用户，而且世界上每一个用户，即使他们扭曲、成瘾、被洗脑的思维承受着享受或放松的幻觉，也希望自己从来没有上钩过。那么，为什么一些前用户会羡慕呢？

1.  "只看一眼。"记住，它并不存在。停止看那孤立的场合，开始从色情用户的角度来看待它。你可能在羡慕他们，但他们并不认可自己，他们羡慕你。如果你能以某种方式冷静地观察另一个用户，他们可以成为帮助你脱身的最有力的动力。注意他们打开许多标签和浏览器窗口的速度有多快？快速跳到重要部分，很快就对片段感到厌倦，浏览各种类型产生新奇感、震惊感、焦虑感等。特别注意，这个行为似乎是自动的。记住——他们并不是在享受它，而是他们没有它就无法享受自己。第二天早上，带着虚弱的意志、失去的精力和朦胧的眼睛醒来，他们将不得不在压力和紧张第一次出现时继续折磨自己。他们面对着终生的污秽、糟糕的心理健康和受损的自信——一生都在用心灵背后的黑暗阴影摧毁自己。为了达到什么目的？获得你"应得的"和该死的乐趣的幻觉？

2.  一些前用户感到渴望的第二个原因是，色情用户在做某事——比如自我愉悦——而非用户没有，所以他们倾向于感到被剥夺。在你的脑海中明确这一点，被剥夺的不是非用户，而是那个可怜的成瘾者，他被剥夺了：

    -   健康

    -   精力

    -   自信

    -   内心平静

    -   勇气

    -   宁静

    -   自由

    -   自尊

摆脱羡慕色情用户的习惯，开始将他们视为真正可悲和令人同情的生物。我知道，我曾经是其中最糟糕的之一。这就是为什么你在读这本书，而不是那些无法正视现实、继续自欺欺人的人。

你不会羡慕海洛因成瘾者，就像所有毒品成瘾一样，你的成瘾不会好转。每年它都会呈指数级恶化——如果你今天不享受作为用户，明天你会更不享受。不要羡慕其他用户，同情他们。相信我：***他们需要你的同情！***
