# 对我来说会更难吗？

决定每个用户戒除难易程度的因素有无数种组合。首先，我们每个人都有自己的性格、职业、个人情况、时机、新陈代谢等。某些职业可能比其他职业更难，但只要洗脑被消除，这并不一定如此。以下面几个例子为例。

有时，医疗专业人员会觉得困难。我们认为医生应该更容易，因为他们更了解其影响，但尽管这提供了更有力的停止理由，却并不会使其更容易实现。原因如下：

1.  对健康风险的持续意识会产生恐惧，这是我们感到需要缓解戒断痛苦的条件之一。

2.  医生的工作压力极大，他们通常无法在工作期间缓解戒断痛苦带来的额外压力。

3.  他们有额外的内疚压力，认为自己应该为其他人树立榜样。这给他们施加了更多压力，增加了被剥夺感。

在辛苦工作一天后，当他们的压力暂时被色情所缓解时，那次被错误地与所经历的解脱联系在一起。由于这种错误的联想，色情获得了整个情况的功劳，在戒除和经历戒断痛苦时突然变得非常珍贵。这是一种休闲用户的形式，适用于任何用户被迫长时间戒断的情况。在意志力方法下，用户因为被剥夺而感到悲惨，无法享受一次之后的疲倦和睡眠。他们的失落感大大增加。然而，如果你能首先消除关于色情的洗脑和消沉，即使身体在渴望胺类神经递质——血清素、去甲肾上腺素和多巴胺——休息和睡眠仍然可以享受。

另一个困难的情况是无聊，特别是与压力期结合时。典型的例子是学生和单亲父母，工作既有压力又单调。在使用意志力方法戒除的尝试中，单身人士有很长的时间来为自己的"失去"而消沉，这反过来会增加抑郁感。同样，如果你的心态正确，这很容易克服。不要担心你不断被提醒你已经停止了色情。利用这些时刻为你正在摆脱邪恶怪物而欢欣鼓舞。

如果你有积极的心态，这些痛苦将成为快乐的时刻。记住，任何用户，无论年龄、性别、智力或职业，都可以发现停止色情既容易又愉快，前提是**你遵循所有的说明。**

## 失败的主要原因

失败有两个主要原因。第一个是外部刺激的影响——广告、网络新闻文章、网络浏览等。他们发现自己处于软弱的时刻，或者在社交场景中看到亲密关系时甚至会产生嫉妒。这个话题已经详细讨论过了。利用这个时刻提醒自己，不存在什么"只访问一次或看一眼"这回事。为你打破了心灵奴役的链条而欢欣鼓舞。记住，用户羡慕你，你应该同情他们，因为他们需要它。

另一个原因是过了糟糕的一天。在开始之前就在脑海中明确，无论你是用户与否，你都会有好日子和坏日子。雨水既降在教皇身上，也降在杀手身上。生活是相对的，没有高潮就没有低谷。意志力方法的问题在于，一旦用户过了糟糕的一天，他们就开始渴望去"后宫"，这进一步加剧了问题。非用户在应对压力和挑战方面更有能力，不仅是身体上，也包括精神上。如果你在戒断期间过了糟糕的一天，就接受它；提醒自己，当你成瘾时也有糟糕的日子，否则你不会决定停止。与其为此消沉，不如认识到它：*"好吧，今天不太好，但色情不会治愈它。明天会更好，至少我有一个美妙的奖励，我已经摆脱了那种可怕的成瘾。"*

当你是一个色情用户时，你必须屏蔽色情的负面影响。用户从来不会感到脑雾，他们只是"有点低落"。当你经历生活中不可避免的麻烦时，如果你产生了想要色情的念头，你是快乐和开朗的吗？当然不是。一旦你停止，就会有把所有出错的事情归咎于你停止这一事实的倾向。

如果工作让你感到压力，你会想："*在这种时候，我本来会进行一次。*"这是真的，但被忘记的重要事情是，色情没有解决问题，你只是通过为虚幻的拐杖而消沉来惩罚自己。你创造了一个不可能的情况，因为不能手淫看色情而感到悲惨，但如果你这样做，你会更加悲惨。*你知道你通过停止做出了正确的决定，那么为什么要通过怀疑你的决定来惩罚自己呢？*

记住，积极的心态始终是至关重要的。
