# 给非用户的建议

## 帮助你使用色情的朋友阅读本书

首先，仔细研究本书的内容，并尝试站在用户的角度思考。不要通过告诉他们正在毁掉自己的健康或玩火来强迫他们读这本书。他们比你更清楚这些。用户并不是因为享受或出于意愿才继续观看色情，他们只是为了保留自尊而这样告诉自己和别人。他们这样做是因为他们依赖色情，认为它能让他们放松、给他们勇气或信心（快乐或拐杖），并且因为他们觉得没有"性"——至少是他们版本的性——生活将永远无法享受。如果你试图强迫用户停止，他们会感到像被困的动物，反而更想要他们的网上后宫。这可能会让他们变成秘密用户，色情在他们心中会变得更加珍贵。

相反，关注硬币的另一面。让他们与前用户（博客、论坛、YBOP、NoFap等，但要注意倡导意志力方法的内容）接触。让前用户告诉他们，自己曾经也以为一辈子都会被套牢，以及作为非用户生活有多美好。一旦你让他们相信自己可以停下来，他们的思维就会开始打开。然后开始解释戒断痛苦造成的幻觉。那些"多巴胺冲击"不仅没有给他们提振，反而在破坏他们的信心，让他们变得烦躁和疲倦。

他们现在应该准备好自己读这本书了，期待着读到一页又一页关于不稳定唤起、性能力下降、色情引起的勃起功能障碍、早泄等等的故事。解释这种方法是完全不同的，对疾病的提及只占极小一部分内容。

简而言之，不要让这件事在黑暗中消亡。告诉你的朋友，但不要让这件事变得奇怪。如果你试图"赢得"对话或进行辩论，你只会疏远他们，进一步加剧他们的恐惧。

## 我应该告诉我的另一半吗？

我应该告诉我的妻子、女友或伴侣关于我的习惯吗？（目的是帮助你戒除。）这里有多个因素在起作用。

如果你已经尝试过用意志力方法戒除并失败，并且已经告诉了伴侣，那就告诉他们你的新方法，并让他们通过阅读本书来了解情况。他们将能够在戒断期间协助和激励你，并在小怪物试图绊倒你时成为你的坚强后盾。

如果你刚刚意识到色情陷阱的存在，过去没有尝试过戒除，那就先自己使用轻松戒色法。如前所述，这应该是一次愉快的体验。然而，如果你觉得困难，可以请求伴侣的帮助。对伴侣坦诚和脆弱，会强化你们的关系。

如果你享受逃离并没有因为犹豫不决而感到困难，就没有太多理由让伴侣知道。如果过去这不是个问题，就让它过去吧。不过，要有心理准备，你的伴侣可能会想知道为什么你的外貌、感觉和表现都变得更好了！

## 我的伴侣正在戒除色情

色情是关系的变态破坏者，虽然戒除可以立即完成，但愈合需要时间。许多用户由于上瘾滋生的非理性信念，会将愤怒发泄在伴侣和爱人身上。这些行为表现为煤气灯效应、撒谎和操纵行为。这不是所有用户的情况，但在疾病的后期阶段越来越常见。虽然这些行为可能源于潜在的色情成瘾，但了解这些行为很重要，如果认识到了，请考虑寻求专门从事性成瘾治疗的治疗师。

如果你的伴侣正处于戒断期，无论他们是否真的在受苦，都假设他们在受苦。不要试图通过告诉他们戒除很容易来淡化它，他们自己会发现的。相反，继续告诉他们你有多自豪，他们看起来好多了，和他们在一起有多甜蜜，他们总体上变得多么轻松。特别重要的是要持续这样做，因为当用户尝试戒除时，尝试的喜悦和同伴的赞扬可以帮助他们前进。然而，他们往往很快就会忘记，所以要持续给予赞扬。

因为他们没有谈论色情，你可能认为他们忘了，不想让你提醒他们。在使用意志力方法的情况下，通常情况恰恰相反，前用户往往对此念念不忘。所以不要害怕提起这个话题，继续赞扬他们（如果他们不想被提醒，他们会告诉你的）。

在戒断期间，尽力减轻他们的压力，想方设法让他们的生活变得有趣和愉快。对于从未有过这种成瘾的非用户来说，这也可能是一段艰难时期。如果群体中有一个成员烦躁不安，可能会造成普遍的痛苦。所以如果前用户感到烦躁，要预料到这一点，他们很可能会把它发泄在你身上，但不要还击，正是在这个时候他们最需要你的赞扬和同情。如果你自己感到烦躁，这是可以理解的，尽量不要表现出来。

成瘾者在尝试借助意志力方法戒除时会玩的一个把戏是发脾气，希望他们的伴侣或朋友会说："*我受不了看你这么痛苦。看在老天的份上，就服你的毒药吧。*"用户因此不必丢面子，因为他们不是在"放弃"，而是被指示这样做。如果前用户玩这个把戏，绝对不要鼓励他们复发。相反，说："*如果色情对你有这样的影响，感谢老天你很快就会自由了。你有勇气戒除，这多么了不起啊。*"

记住，康复旅程中有两个需要愈合的当事人。当你的伴侣戒除色情时，拥有自己的支持网络、自我照顾习惯和界限很重要。这个过程不会在一夜之间发生，需要信任、沟通和问责。写日记、发展自己的热情，最重要的是接受治疗，都有助于这个过程。

## 滑落（复发）

这一节的存在应该作为对那些离开陷阱的人的警告。就我个人而言，我从未复发过，但我将使用来自与社区成员访谈的经历和认知行为治疗的工具来说明。

首先，称之为复发是适得其反的。所发生的一切不过是你滑了一跤，喂养了小怪物，小怪物反过来启动了大洗脑怪物。滑落的用户（这，从定义上说，是向前倒下）通常会产生一系列非理性信念：

  - "*我永远不会自由*" - **灾难化思维**
  - "*我应该/必须每天锻炼、学习并硕果累累*"（又称 - **应该化**）
  - "*今天我PMO了，那读所有的书和论坛有什么用呢……我的目标是连M都不做，但我在这里——一个失败者——复发了。*" - **低挫折容忍度**
  - "*我的朋友/论坛读者/其他人已经坚持不做PMO（n）天了，但我做不到，所以我是没有希望的。昨天感觉很好，因为我学习好并且很有成效，但今天没有……我在走下坡路。*" - **与他人比较评价**
  - "我不应该有性方面的想法" - 他们自己、父母或整个社会在性方面植入了**僵化的信念**。问问自己，自我鞭打是否帮助你实现目标，如果是的话，你在享受这个过程吗？

导致每个用户洗脑的因素似乎是无限的。你比任何人都更了解自己，但这显然是不遵循指示的失败。你在色情中看到了价值，但是怎么看到的？

经常被忽视的是，逆转洗脑需要时间。这并不会让它变得更难，但几乎每个行业都在使用性，而主动对抗洗脑是一个有意识的过程（至少在开始时），所以可能需要一些时间来完全巩固所包含的教训。因此，建议多次阅读（可以跳到你有困难的章节），不应该花太长时间。

对于离开陷阱的宗教用户来说，一个令人惊讶的常见经历是希望它有点痛苦，作为一种赎罪形式。他们发现戒除如此容易，然后因为有这种感觉而感到内疚。但为什么要自我破坏，让它变得困难？小怪物在这方面非常狡猾。

将自己与小怪物分离——它是色情产业很久以前添加进来的。想象一个恶霸在学校操场上发脾气。你会对恶霸说什么？如果你屈服，你只会强化他们。一些戒除者最终喂养了恶霸，从而增加了他们的洗脑，但他们对陷阱的概念没有改变。振作起来，弄清楚哪里出了问题，享受自由！

你不是你的冲动。正念冥想是注意思想的练习，在心灵的本质中可以找到基本的教训。强烈建议你总体上进行冥想，它也与宗教实践完全兼容。你不能与自己或小怪物争斗。你必须无条件地爱自己和这个过程。

但要把失败从你的脑海中移除。以下是Gulliaco的《色情成瘾者的沉思》（链接在书末的资源部分）中的一段：

> 由于观看色情对你没有任何好处，它只会伤害你，想做这样的事情是极其荒谬的，我把它比作喝漂白剂。请看：
>
> **不喝漂白剂的艰难旅程。**
>
> 嗨！我们是NoBleach，我们举办重启挑战，参与者（"漂白宇航员"）在一段时间内戒除喝漂白剂。无论你的目标是随意参加每月挑战作为自我控制测试，还是过度喝漂白剂已经成为你生活中的问题，你想戒除更长时间，你都会在这里找到一个支持性社区和丰富的资源。
>
> - "*有时我允许自己喝一两杯漂白剂。我知道"一滴"是谎言，但我认为一杯不会有什么坏处。一个人不能摧毁我花时间不这样做的所有时间。*"
> - "*我停止喝漂白剂没有问题，但有时我走在街上，看到有人喝水，你知道，用玻璃杯，我想象那杯里有漂白剂。然后我有一种渴望，在和自己辩论是否应该这样做之后，我最终在晚上喝了一杯。*"
> - "*看，我的问题是，有时，当我独自在厨房里时，我开始看到那些玻璃杯，有时我通过打开存放漂白剂的容器来诱惑自己，有时我闻它……好吧，我最终又回到了原点。我非常渴望停止这件事，但我不确定自己是否能够停止。*"
> - "*停止喝漂白剂是不可能的，我是说，我总有嘴，你知道吗？如果我总有一个喉咙提醒我可以吞咽漂白剂，我怎么能停下来？*"
> - "*哦，天哪，进行得很顺利，整整19天没有做。重要的是从失败中学习！现在我知道要避免做什么：在超市看清洁产品。我会尽量坚持一个月！我将重置我的计数器。祝我好运！*"

> 如果你有冲动，冷静下来，伙计！记住黑客书说的：
>
> "*漂白剂很难放弃，因为我们害怕被剥夺乐趣或支撑。害怕某些愉快的情况将永远不会再是同样的。害怕无法应对压力情况。换句话说，洗脑的效果欺骗我们相信购买漂白剂，并因此喝它，是所有人类的必须。更进一步，这是相信廉价漂白剂中有我们需要的东西，当我们停止使用时，我们会拒绝自己并造成空虚。在你的脑海中明确这一点：漂白剂不是填补空虚，而是创造空虚！*"
> 
> 我说：
> "*假设你被迫观看一杯满满的漂白剂五分钟。试着记住你那么喜欢的那些品牌或气味之一。也许它伴随着某种声音，或者你只记得选定的细节。漂白剂就在那里，你无法闭上眼睛或转过头，因为这种漂白剂在你的脑海中，是记录在你身上的记忆。*
>
> *你感到任何渴望吗？你感到舌头有任何感觉或呼吸有任何变化吗？你对你所记住的东西有什么感受？让它们被识别出来，漂白剂想要模糊它们，使它们变得混乱，让你只注意那想要抓住你的东西。*"
>
> 通过以上内容，我并不是要否定你的感受，更不是要说"哈哈我聪明你笨"，而是给你一个视角，让你意识到克服这种成瘾有多么荒谬地容易（并且将永远如此）。
> 观看色情不像一个开关，你说"*哦，好吧，我处于X情况，那我就看色情*"。幻想！谎言！你多久允许自己喝一杯漂白剂？从不？为什么？因为这是一件可怕的事，就是这样！如果你不意识到PMO是一件对自己做的可怕的事，你怎么能摆脱你的成瘾？

## 关于MO（手淫、性高潮）呢？

人们几千年来一直在手淫，没有什么问题。明确一点，色情才是问题所在。

话虽如此，你仍然可能因为同样的原因对MO上瘾，例如"必须性高潮"的心态、精神升级、强迫身体发生性关系，以及单纯的享乐主义追求快乐。

色情和手淫极有可能在你的脑海中已经深度交织在一起。许多用户发现，他们因为手淫到色情诱发的幻想而最终复发。随着你的大脑重新连接，你会发现这种洗脑最终会消退，但最好暂时休息一下MO。你还应该寻求真实的性来加速这一过程。

这不是一个指令，但请评估一下：关于保精（semen retention）报告的好处是多方面的——专注力和精力的增加、"脑雾"的消除和信心的增加，以及一系列其他好处。从个人经验来看，有明显的区别，这一切都取决于你如何升华这种增加的能量。

推测一下，没有严格的科学知识，这些好处可能归结为几个不同的因素。

- 性高潮后，大脑会释放催乳素，抑制多巴胺的释放。

- 剥夺大脑的多巴胺冲刷，使其能够从简单地生活中获得更多吸收。

- 精液在约78天后被血液重新吸收，是你身体所能获得的最好营养之一。

- 将性能量升华为富有成效的习惯，带来额外的生产力。

你也可能希望在没有性高潮的情况下发生性关系，如前所述，这是一种美妙的性体验（通常称为Karezza）。你可以通过练习凯格尔运动来增强这方面的能力。从个人经验来看，针对这块肌肉最简单有效的方法是在排尿中途停止和开始（但要注意不要过度，这可能会引起自身的问题）。性爱中坦陀罗部分和传播部分的分离是逃离PMO陷阱的众多好处之一（我的伴侣也非常喜欢！）。

## 偏离标准建议

这一节是新的，写得有些谨慎；即便如此，也必须提及。

一些使用轻松戒色法的人发现，他们观看色情的欲望变得如此之低，以至于他们无法进行最后一次。**这没关系**，但不要低估进行一次的力量。有意识地浏览并巩固你有多么不喜欢PMO可能非常有力。就我个人而言，我发现这非常有用，很高兴洗手不干，真正如释重负地永远不必再做这件事了。然而，效果可能因人而异。

如果你已经从陷阱中解脱了一段时间，刚刚消除了洗脑，就没有必要喂养小怪物，因为它只会唠叨你。享受自由吧！

## 帮助终结这场丑闻

互联网色情是自由社会中的危险之一，它借助个人自由倡导者的善意努力。文明的基础——人类物种进步如此之远的原因——无疑是因为我们能够传达我们的知识和经验，不仅彼此之间，而且对未来世代。即使是动物也认为有必要保护其后代免受生活陷阱的伤害。

色情制作者并非出于真诚，真心相信他们在帮助人类，尤其是现在互联网色情成瘾已被广泛研究。也许在最初阶段，人们真的相信色情能教育人们亲密关系，但当局知道这是个谬论。没有任何视频网站对教育提出真实主张。唯一的主张是关于他们商品的冲击性、新颖性和升级性。

彻底的虚伪令人难以置信：作为一个社会，我们在其他方面对学校欺凌和人体物化感到紧张。与互联网色情相比，这些问题不过是小疙瘩。每年成瘾人数攀升到新高，花费宝贵时间与想象中的幻想像素人在一起，以牺牲他们的健康、活力、精力和时间为代价。它是迄今为止关系中最大的杀手，每年数十万人的生活因为上瘾而被毁掉。互联网色情制作者不在主流出版物上做广告——他们不需要，我们的生物冲动将我们引领到他们库存丰富的网上后宫门槛，像当地毒贩一样分发免费样品。如今，视频网站与其说是存储商品，不如说是鼓励访客发布内容。

多么聪明，色情公司将*18+*警告作为对未成年用户的威慑，尽管有些甚至懒得这样做。互联网色情影响所有年龄段的每个人。"*我们已经警告了你危险，所以这是你的选择*"，是他们的态度。他们采取了任何步骤来验证年龄吗？没有，那会吓跑他们的客户。当然，如果年龄验证立法，他们就会找到另一个国家来运营。或者，他们会付一些"精英"来写关于禁酒令如何导致走私和黑手党的建立的文章吗？方便地被遗忘的问题是，为什么废除禁酒令没有导致与酒精相关的伤亡减少，以及执法部门未能控制黑手党的增长。

我们可以通过教育年轻一代来以不同的方式解决这个问题。如果他们在购物时能绕过香烟和酒精，他们也可以对互联网色情这样做。我们已经看到了社会转变，例如"No Nut November"和"Coomer"表情包成为主流。用户没有选择，就像海洛因成瘾者一样。用户不是决定上瘾的，他们是被引诱进入一个微妙的陷阱。如果他们有选择，明天早上唯一的用户将是刚刚开始的青少年，相信他们随时可以停下来。

为什么有这种虚伪的标准？为什么海洛因成瘾者被视为罪犯，却可以登记为成瘾者，获得美沙酮和适当的医疗治疗以帮助戒除？试着登记为色情成瘾者——如果你去看医生寻求帮助，他们要么告诉你："*少看一点，试试节制*"，你已经知道这行不通，要么开药来解决你的"抑郁"。更糟糕的是，建议去找真实的伴侣——认真的？他们从来没有听说过发现色情更好并在伴侣背后做这件事的用户吗？有些人就是不理解。

恐吓活动不能帮助用户停止，反而让它变得更难。它们所做的只是吓到用户，让他们更想看。它们也不能阻止青少年上瘾。青少年知道色情会扼杀他们的性欲，但他们也知道看一眼不会有问题。因为成瘾如此普遍，青少年迟早——无论是通过社会压力还是好奇心——都会尝试一次访问。由于免费色情有糟糕的片段，他们很可能会上瘾。

我们为什么允许这场丑闻继续下去？为什么政府不出来进行适当的宣传活动？为什么没有人告诉我们互联网色情是一种毒品和致命毒素，它不会让你放松或给你信心，而是会摧毁你的神经，只需偷看一眼就会上瘾？为什么他们不能通过要求注册信用卡（也许通过第三方）来强制执行年龄验证？许多主要色情网站的所有者MindGeek，正试图欺骗各国政府使用他们自己的专有年龄验证解决方案——不要让他们这样做！H·G·威尔斯的《时间机器》描述了在遥远未来一个人落入河中的事件。他的同伴们只是像牛一样坐在岸边，对绝望的呼声漠然不理。不人道且令人不安，就像社会对色情危机的普遍冷漠一样。

社会正在发生变革之风。一个雪球已经开始从山上滚下来，希望这本书能帮助把它变成雪崩。你也可以通过传播信息来提供帮助。

因此，请问——如果你看到任何人在使用意志力挣扎，或者试图戒除色情，请亲切地将他们指向这个方法。然而，真正的任务是改变关于色情的叙事。请考虑养成一个习惯：如果你在网上看到或甚至亲身经历色情的正常化，你的目标是*尊重地*教育和解放他们。

偶尔，你可能会得到负面反应，但有时一条评论就足够了。正如许多在你之前做过的人一样，你可以期待收到感谢你给予他们自由的感激信息。

## 最终警告

你现在可以作为一个快乐的非用户享受余生了。为了确保你做到这一点，你需要遵循以下简单指示。

1.  将以下页面收藏在书签中，并根据需要参考它。

2.  如果你开始羡慕另一个用户，意识到他们会羡慕你。你没有被剥夺。他们才是。

3.  记住，你并不喜欢作为一个用户。这就是你停下来的原因。你享受成为非用户。

4.  记住，没有"只偷看一眼"这回事。

5.  永远不要怀疑你永不再看色情的决定。你知道这是正确的决定。

6.  如果你有任何困难，找到并联系一位熟悉互联网色情问题的治疗师。你可以在网上找到这些人的列表。
