# Será que eu posso compartimentar?

Esse mito é espalhado primariamente pelos usuários que tentam largar esse vício através do método da força de vontade, que ficam fazendo ginástica mental e começam uma espécie de rotina à la Jekyll e Hyde: "*O pornô é pro meu alter ego e a parte bonita da vida real é pro meu lado dos relacionamentos.*" Nada é mais distante da verdade: os tobogãs do pornô, o DeltaFosB e as mudanças neurológicas passarão a influenciar os relacionamentos da vida real, tornando-os menos desejáveis. O Sr. Hyde certamente desobedecerá às instruções do Sr. Jekyll.

Se você usa o pornô disponível na internet, você está treinando a si mesmo para o papel de voyeur, ou de precisar da opção de clicar em algo mais excitante diante do menor sinal de queda na dopamina. Ou para a busca contínua por aquela *cena perfeita* para ter o maior retorno possível. Além disso, você pode estar se masturbando numa posição encurvada, ou assistindo pelo seu smartfone na cama, à noite, eventualmente desejando essas pistas e situações mais do que os próprios estímulos naturais que a vida real tem a oferecer. O sexo de verdade se opõe a praticamente todos os aspectos do seu harém virtual, então não tem nenhuma chance contra ele quando comparado. As memórias criadas quando você é jovem são fortes e duradouras, e substituir esses tobogãs que o pornô criou para criar novas conexões, consequentemente, leva tempo. Entretanto, isso não quer dizer que é nem um pouco mais difícil.

Sempre que você se permite "escorregar no tobogã do pornô" é como se você o estivesse lubrificando. Você está mantendo suas células nervosas sempre preparadas para percorrer aquele caminho específico. Quando você estaciona perto de um restaurante fast-food, o cheiro da fritadeira preenche suas narinas. A venda já está feita. Da mesma forma, os tobogãs que a pornografia cria no seu cérebro já estão prontos para que você seja sugado e estão abertos vinte e quatro horas por dia. Cada pista ou gatilho ativa seu circuito de recompensas com a promessa de sexo -- no entanto, isso não é sexo. De qualquer forma, suas células nervosas solidificam essas associações com excitação sexual por meio da criação de novas conexões entre neurônios que fortalecem o hábito. Quanto mais você usa pornografia, mais forte ficam as conexões nervosas associadas com o uso da pornografia. O resultado final é que você pode de fato acabar *precisando* ser um voyeur, *precisando* clicar para ver vídeos cada vez mais chocantes e estimulantes, *precisando* usar pornô para poder dormir, ou *precisando* buscar pelo final perfeito para poder terminar a sessão.

Como acontece com qualquer outra substância ou droga comportamental, o corpo cria uma certa imunidade e a droga para de aliviar completamente os anseios trazidos pela abstinência. Tão logo o usuário fecha uma sessão eles já querem outra, e rapidamente, a fome permanente se mantém insatisfeita. A inclinação natural é a de escalar para conseguir mais aquele "barato" que vem com a dopamina. Entretanto, a maioria dos usuários são impedidos de fazer isso por uma ou outra das razões seguintes:

**Dinheiro:** Eles não têm condição de pagar pelo acesso a sites pornô pagos.

**Saúde:** O corpo só aguenta até certo ponto, seja os orgasmos ou os picos de dopamina. Ademais, os orgasmos acionam processos químicos no corpo que impedem que dopamina continue sendo liberada. É necessário que ocorra desta forma: é assim que o corpo funciona.

Uma vez que o pequeno monstro tenha saído do seu corpo, o sentimento horrível de insegurança vai embora. Sua autoconfiança retorna, junto com um maravilhoso sentimento de respeito por si próprio, que proporciona a confiança que te possibilita tomar controle da sua vida e usá-la como um trampolim que para enfrentar outros problemas. Essa é uma das muitas grandes vantagens de se libertar de qualquer vício.

O mito da compartimentação é uma das muitas estratégias que o pequeno monstro vai usar para tentar confundir sua mente. Esses truques fazem com que seja mais difícil parar -- devido à impossível satisfação da fome permanente, causando muitos usuários a se voltarem até mesmo para cigarros, bebida em excesso e até mesmo drogas mais pesadas na busca de satisfazer o vazio.

Humanos são animais que avaliam: nós avaliamos tanto nós mesmos como os outros. Assistir vídeos pornô com seu parceiro é insatisfatório, já que ambos avaliam um ao outro em comparação com a narrativa do vídeo. Você quer o Brad Pitt no seu quarto, mesmo se ele estiver em um pôster? Nenhuma pessoa de verdade pode competir com um harém em que todas as "experiências" são executadas por atores que estão obedecendo um script, sendo dirigidas por um profissional e disponíveis imediatamente vinte e quatro horas por dia.