# Substitutos

Alguns exemplos de substitutos incluem restringir-se a revistas pornô, imagens estáticas online, "dietas pornográficas", etc. **Não use nenhuma dessas coisas.** Elas tornam o processo mais difícil, não mais fácil. Se você sente a fissura e usa um substituto, ele só vai prolongar a fissura, tornando-a mais dolorosa. O que você está afirmando para si mesmo ao fazer esse tipo de coisa é que você precisa de pornografia pra preencher o vazio. Seria como dobrar-se diante da pirraça de uma criança. Isso só faz com que as fissuras continuem vindo e prolongando a tortura. Em qualquer caso, usar substitutos não aliviará as fissuras. Seu anseio é por compostos químicos no cérebro. Tudo o que isso fará é manter você pensando em pornografia. Lembre-se destes pontos:

1.   Não há nenhum substituto para o pornô.

2.   Você não precisa de pornô. Não é como um alimento. É veneno. Quando as fissuras vierem, lembre-se de que são os usuários que sofrem de sintomas de abstinência, e não os não-usuários. Enxergue-as como elas são: mais um dos males da droga. Enxergue-as como algo que enuncia a morte de um monstro.

3.   É o pornô que cria o vazio. Ele não o preenche. Quanto mais rápido você ensinar ao seu cérebro de que você não precisa assistir, mais cedo você estará livre. Evite, particularmente, tudo o que se assemelha a pornografia, tal como revistas eróticas, filmes, histórias românticas e comerciais. Isso não é ter a mente fechada: tudo bem falar sobre romance e sexo, mas não é o caso com a pornografia. Sempre há um jeito de encontrar quando e onde discriminar. É verdade que uma pequena proporção dos usuários que tentam largar o vício usando pornô softcore ou dietas de pornografia de fato têm sucesso (a partir de suas próprias perspectivas) e atribuem seus sucessos a esse tipo de uso. Entretanto, eles largam o vício *a despeito* desse uso e não por causa dele. É um fato infeliz que ainda se recomende tais medidas.

Isso não é surpreendente porque, se você não compreende completamente a armadilha que subjaz na pornografia, uma dieta ou substitutos mais leves soam como algo bastante lógico. Isso se baseia na crença de que quando você tenta se desvencilhar do pornô, você tem dois inimigos a vencer:

-    Romper o mau hábito.

-    Sobreviver as terríveis fissuras de abstinência.

Se você tem dois inimigos terríveis para vencer, faz sentido não combatê-los ao mesmo tempo, mas sim um de cada vez. Essa teoria implica que quando você para de usar pornografia, você deve diminuir a frequência do uso para uma vez por semana ou usar só "pornografia segura". Uma vez que o hábito tiver sido desfeito, gradualmente se reduz a oferta, e ,dessa forma, combater esses inimigos separadamente.

Isso faz sentido lógico mas é baseado em informação incorreta. A pornografia não é um hábito, mas um vício em dopamina, e a dor física que vem com a abstinência é quase imperceptível. O que você está tentando alcançar ao parar de usar, é matar ambos os monstros no seu corpo e no seu cérebro o mais rápido o possível. Tudo o que essas técnicas de substituição fazem é prolongar a vida do pequeno monstro, o que por sua vez prolonga a lavagem cerebral. O Método Fácil torna fácil o processo de parar imediatamente, eliminando a lavagem cerebral antes da sua última sessão. O pequeno monstro logo estará morto, e até mesmo quando estiver morrendo, não será um problema maior do que era quando você era um usuário.

Apenas pense: como é que se pode recomendar que se cure um vício prescrevendo o uso da mesma droga em que se está viciado? Há muitas histórias na Internet sobre aqueles que largaram o "pornô hardcore", mas que continuam viciados em alternativas “seguras”, tendo caído na lábia das justificativas criadas pelo pequeno monstro. Não se deixe enganar pela ideia de que pornô "leve" não é horrível: o primeiro vídeo que você viu rapidamente também era. Todos os substitutos têm exatamente o mesmo efeito que qualquer outra espécie de pornografia. Alguns até tentam compensar o desejo por pornografia com comida, mas apesar da sensação de vazio associada com querer assistir pornô ser indistinguível do desejo de comer, saciar um não irá satisfazer o outro. Na verdade, se tem algo que é provável de fazer uma pessoa querer assistir pornografia, essa coisa é se empanturrar de comida. Como foi previamente exposto, dietas pornográficas e pornô "leve" só vão te colocar no meio de um cabo de guerra, com a resistência à tentação se mostrando tão irritante que você sentirá alívio ao visitar seu harém online favorito. 

O maior vilão de todos os substitutos é prolongar o problema real, a lavagem cerebral. Você precisa de um substituto para a gripe quando ela passa? É claro que não. Ao dizer que você precisa de um substituto para a pornografia, o que você está realmente dizendo é que você está fazendo um sacrifício. A depressão associada com o método da força de vontade é causada pelo fato do usuário acreditar que está fazendo um sacrifício. Tudo o que você está fazendo é substituir um problema por outro. Não há prazer em se encher de comida, cigarros ou álcool. Você só ficará gordo, miserável e em pouquíssimo tempo estará de volta na droga.

Usuários casuais acham difícil destituir a crença se que estão sendo privados de sua pequena recompensa, como aqueles que ficam sem internet durante um período de tempo em uma viagem, evento de família, etc. Alguns dizem, *” Eu não saberia como relaxar se não fosse pela pornografia.”* Isso prova o ponto — frequentemente a trégua no uso é feita não porque o usuário precisa ou sequer a deseja, mas porque o viciado — que é o que eles são — precisa desesperadamente coçar a coceira.

Lembre-se, as sessões de pornografia nunca foram recompensas genuínas. Elas eram equivalentes a vestir sapatos apertados só para sentir o prazer de tirá-los. Então se você sente que deve obter uma recompensa, deixe ela ser o seu substituto; enquanto estiver trabalhando calce sapatos ou vista roupa íntima de um tamanho muito pequeno, e não se permita removê-los até que você tenha sua pausa, então experiencie o momento maravilhoso de relaxamento e satisfação quando eles forem removidos. Talvez você ache que isso seria estúpido na verdade. Você está absolutamente certo. Pode ser difícil visualizar enquanto ainda está na armadilha, mas é isso que os usuários fazem. Também é difícil visualizar que em breve você não precisará daquela pequena “recompensa” e que você em breve você vai sentir uma pena genuína dos amidos que ainda estiverem na armadilha e se perguntar o porquê deles não conseguirem ver o problema.

Contudo, se você continuar a se enganar que o a visita ao seu harém online era uma recompensa genuína, ou que você precisa de um substituto, você vai se sentir privado e miserável. É provável que você acabe caindo na mesma armadilha nojenta novamente. Se você precisa de uma trégua real como donas de casa, professores, médicos e outros trabalhadores precisam, logo estará desfrutando dessa trégua ainda mais porque você não precisará se viciar. Lembre-se que você não precisa de um substituto. As dores de abstinência são uma fissura por dopamina e logo não existirão mais. Deixe isso ser o seu suporte pelos próximos poucos dias e aproveite o momento de livrar seu corpo e mente da escravidão e dependência.
