# Wat geef ik op?

**Helemaal niets!** Porn is moeilijk op te geven vanwege de angst dat we beroofd worden van ons plezier of onze steun. De angst dat bepaalde aangename situaties nooit meer helemaal hetzelfde zullen zijn. De angst dat je niet in staat zult zijn om met stressvolle situaties om te gaan. Met andere woorden, het zijn de effecten van hersenspoeling die ons doen geloven dat seks — en bij uitbreiding orgasme — een must is voor alle mensen. Nog verder, het is het geloof dat er iets vanzelfsprekend is aan internetporno dat we nodig hebben, en dat wanneer we stoppen met gebruiken, we onszelf tekort doen en een leegte creëren.

Keep this firmly in mind: **Porn vult geen leegte**, ***het creëert er een!***

Onze lichamen zijn de meest geavanceerde objecten op de planeet. Of je nu gelooft in intelligent ontwerp, natuurlijke selectie, of een combinatie van beide, onze lichamen zijn duizenden keren effectiever dan die van de mens! We zijn niet in staat om de kleinste levende cel te creëren of de wonderen van het gezichtsvermogen, voortplanting en diverse onderling verbonden systemen die aanwezig zijn in onze lichamen of hersenen. Als deze schepper of proces had bedoeld dat we bovennatuurlijke prikkels zouden kunnen verwerken, zouden we zijn voorzien van verschillende beloningssystemen. Onze lichamen zijn uitgerust met fail-safe waarschuwingsmechanismen en we negeren deze op eigen risico.

## Er is niets om op te geven

Als je het "kleine monster" uit je lichaam en de hersenspoeling (het "grote monster") uit je geest verwijdert, zul je niet vaak willen masturberen, en geen internetporno ervoor willen gebruiken. Er zijn veel bekende en onbekende factoren als het gaat om porno verslaving, waarbij velen in de medische gemeenschap geen concept hebben van het bevragen of identificeren van iemand als een porno verslaafde. Veel gerapporteerde symptomen worden onterecht onder andere oorzaken geplaatst. Het is niet zo dat gebruikers over het algemeen domme mensen zijn, het is gewoon dat ze ongelukkig zijn zonder porno. Gevangen tussen twee vuren, zich onthouden en ongelukkig zijn omdat ze geen porno kunnen gebruiken, of ongelukkig zijn omdat ze zich schuldig voelen en zichzelf beginnen te haten vanwege het gebruik ervan. Wanneer ze symptomen krijgen zoals lage rugpijn of seksuele disfunctie, zijn hun gedachten verdeeld tussen het aanvaarden van verantwoordelijkheid en wegkijken.

Een andere vergelijking met rokers: we hebben allemaal rokers gezien die excuses bedenken om stiekem een trekje te nemen en we zien de ware verslaving in actie. Verslaafden doen dit niet voor plezier, maar omdat ze ongelukkig zijn zonder het.

Voor velen eindigde hun eerste seksuele ervaring in een orgasme, dus ze kregen het geloof dat ze niet van seks kunnen genieten zonder een orgasme. Voor mannen wordt porno gepromoot als een hulpmiddel bij seks, soms zelfs als een educatie in zelfvertrouwen tijdens de daad. Dit is onzin, de conditionering van bovennormale prikkels slaagt er alleen maar in om het naar beneden te halen.

Niet alleen is er niets op te geven, maar er zijn ook enorme positieve resultaten te behalen. Wanneer gebruikers overwegen te stoppen, richten ze zich meestal op gezondheid en viriliteit. Dit zijn geldige en belangrijke redenen, maar persoonlijk geloof ik dat de grootste winst psychologisch is:

- De terugkeer van je zelfvertrouwen en moed.

- Vrijheid van slavernij.

- Niet langer afschuwelijke zwarte schaduwen achter in je hoofd hebben en jezelf verachten.


## Leegte, de leegte, de prachtige leegte!

Stel je voor dat je een koortslip op je gezicht hebt, dus je gaat naar de apotheek en de apotheker geeft je gratis een zalf om te proberen. Je smeert de zalf erop en het verdwijnt meteen. Een week later verschijnt het opnieuw, dus ga je terug naar de apotheker en vraagt of ze nog meer zalf hebben. De apotheker zegt: *"Natuurlijk, houd de tube maar, je hebt het misschien later nog nodig.”*

Je brengt de zalf aan en plotseling verdwijnt de zweer weer. Maar elke keer dat de zweer terugkomt, wordt deze groter en pijnlijker, en de tussenpozen worden steeds korter. Uiteindelijk bedekt de zweer je hele gezicht en is het ondraaglijk pijnlijk, en keert het elke half uur terug. Je weet dat de zalf het tijdelijk zal verwijderen, maar je bent erg bezorgd. Zal de zweer uiteindelijk je hele lichaam bedekken? Zal het interval volledig verdwijnen? Je gaat naar je dokter en zij kunnen het niet genezen, dus probeer je andere dingen maar niets helpt behalve de zalf.

Inmiddels ben je volledig afhankelijk van de zalf, en ga je nooit de deur uit zonder ervoor te zorgen dat je een tube bij je hebt. Als je naar het buitenland gaat, zorg je ervoor dat je meerdere tubes meeneemt. Naast je zorgen over je gezondheid, rekent de apotheker honderd euro per tube. Je hebt geen andere keuze dan te betalen.
Je stuit op een artikel dat dit bespreekt en ontdekt dat het niet alleen jou overkomt; veel mensen hebben last van hetzelfde probleem. In feite heeft de medische gemeenschap ontdekt dat de zalf de zweer niet daadwerkelijk geneest, maar alleen onder het oppervlak van de huid brengt. Het is de zalf die ervoor heeft gezorgd dat de zweer groeit, dus het enige wat je hoeft te doen om van de zweer af te komen is stoppen met het gebruik van de zalf, en het zal vanzelf verdwijnen.

Zou je doorgaan met het gebruik van de zalf? Zou het wilskracht kosten om de zalf niet te gebruiken? Als je het artikel niet geloofde, zou er misschien een paar dagen van bezorgdheid zijn, maar zodra je merkte dat de zweer begon te verbeteren, zou de behoefte of het verlangen om de zalf te gebruiken verdwijnen. Zou je ongelukkig zijn? Natuurlijk niet! Je had een vreselijk probleem waarvan je dacht dat het ongeneeslijk was, maar nu heb je de oplossing gevonden. Zelfs als het een jaar duurde voordat de zweer verdween, zou je elke dag als het beter werd, denken aan hoe geweldig je je voelde. Dit is de magie van stoppen met porno.

De zweer is niet de lichaamspijnen, het gebrek aan normale lust, verminderde opwinding, vervagende penetratie, de verspilde tijd aan tweedimensionale afbeeldingen, gevoelens van inbreuk op aanspraak, en het verachten van de mensen die je betrapt hebben of nog erger, jezelf verachten. Deze zijn allemaal naast de zweer.

De zweer zorgt ervoor dat we onze gedachten sluiten voor al deze dingen — het is dat paniekgevoel van een fix willen. Niet-gebruikers hebben geen last van dat gevoel. Het ergste wat we ooit ervaren is angst, en het grootste voordeel is van die angst af te zijn. Het wordt veroorzaakt door je eerste sessie, verder versterkt en veroorzaakt door elke volgende sessie.

Sommige gebruikers zijn 'gelukkig', verblind door hun sluwe kleine monsters, en gaan zo door dezelfde nachtmerrie, met valse argumenten om hun domheid te rechtvaardigen..

*Het is zo fijn om vrij te zijn!*
