# Tijd besparen

Meestal geven gebruikers bij het proberen te stoppen de belangrijkste redenen op als gezondheid, religie en stigma van de partner. Een deel van de hersenspoeling van deze vreselijke drug is de pure slavernij ervan; de mens heeft hard gevochten om slavernij in veel delen van de wereld af te schaffen — toch brengt de gebruiker zijn leven door met zelfopgelegde slavernij. Ze zijn zich niet bewust van het feit dat wanneer ze pornogebruik mogen gebruiken, ze wensen dat ze een niet-gebruiker waren. De enige keer dat porno kostbaar wordt, is wanneer we 'proberen' te minderen of te onthouden, of wanneer onthouding ons wordt opgelegd.

Het kan niet vaak genoeg herhaald worden dat hersenspoeling het moeilijk maakt om te stoppen met porno, dus hoe meer we verdrijven voordat we beginnen, hoe gemakkelijker je het zult vinden om je doel te bereiken. Bevestigde gebruikers, die niet geloven dat porno een negatieve invloed heeft op hun gezondheid (zoals porno-geïnduceerde erectiestoornissen, hypofrontaliteit, enz.) en geen innerlijke worsteling ervaren, zijn meestal jonger of vrijgezel met een af en toe een sekspartner. Daardoor gaat de interne feedback verloren vanwege de aard van hun jeugd, of is deze te zeldzaam om te worden waargenomen en geregistreerd.

Een beter argument voor een jongere gebruiker is de tijd die ze besteden, in plaats van te zeggen: "*Ik kan niet geloven dat je je geen zorgen maakt over de tijd die je besteedt.*" Over het algemeen lichten hun ogen op als ze zich benadeeld voelen als ze worden aangevallen op gezondheidsgronden of sociale stigma's, maar als het gaat over tijd...  
"*Oh, ik kan het me veroorloven. Het is maar* x *uur per week en ik vind het de moeite waard, het is mijn enige genoegen*”
"*Ik kan nog steeds niet geloven dat je je geen zorgen maakt. Laten we eens aannemen dat een half uur per dag gemiddeld, inclusief de fysieke uitputting van dopamine-onttrekking, je ongeveer een volledige werkdag per veertien dagen doorbrengt. Ik weet zeker dat je het ermee eens zou zijn dat een half uur per dag een zeer behoudende schatting is. Heb je erover nagedacht hoeveel tijd je in je leven zult doorbrengen? Wat doe je in die tijd? Ontwikkel je echte relaties? Nee, je favoriete pornoster heeft geen medelijden met je, alleen omdat je zoveel tijd aan hun video's hebt besteed — je verspilt tijd! Niet alleen dat, je gebruikt eigenlijk die tijd om je fysieke gezondheid kapot te maken, je zenuwen en zelfvertrouwen te vernietigen om een leven lang slavernij, pijn, droefheid en prikkelbaarheid te lijden. Dat moet je toch zorgen baren, toch?*"

Het wordt op dit punt duidelijk — vooral bij jongere gebruikers — dat ze het nooit hebben beschouwd als een levenslange verslaving. Af en toe berekenen ze de tijd die ze in een week verspillen en dat is alarmerend genoeg. Heel af en toe, en alleen wanneer ze overwegen te stoppen, schatten ze wat ze in een jaar uitgeven, wat angstaanjagend is — maar over een heel leven is ondenkbaar. Echter, omdat we in een discussie zitten, zal de bevestigde gebruiker impulsief zeggen: *"Ik kan het me veroorloven, het is maar zoveel per week,"* waarbij ze een verkooptechniek op zichzelf toepassen zoals een encyclopedieverkoper.

Zou je een baanaanbod weigeren dat je huidige jaarsalaris betaalt en je ook elk jaar een maand vrij geeft? Elke gebruiker zou zonder aarzeling instemmen en druk bezig worden met het vinden van vakantiedeals naar exotische locaties. Het uitvogelen hoe je een hele maand zonder werk doorbrengt, zou het grootste probleem zijn om op te lossen. In elke discussie met een bevestigde gebruiker (en houd alsjeblieft in gedachten dat dat niet iemand zoals jij bent die van plan is te stoppen), heeft nog nooit iemand mijn aanbod geaccepteerd. Waarom niet?

Vaak zal een bevestigde gebruiker op dit punt zeggen: "*Kijk, ik maak me eigenlijk niet echt zorgen over het geldaspect.*" Als je in die richting denkt, vraag jezelf dan af waarom je je geen zorgen maakt. Waarom zou je in andere aspecten van je leven veel moeite doen om hier en daar een paar dollar te besparen, maar duizenden uitgeven om je geluk te vernietigen en de kosten te dragen?

Elke andere beslissing die je in je leven neemt, zal het resultaat zijn van een analytisch proces waarbij voor- en nadelen worden afgewogen om tot een verstandige beslissing te komen. Het kan een verkeerde beslissing zijn, maar het zal het resultaat zijn van logische vermindering. Telkens wanneer een gebruiker de voor- en nadelen afweegt van het gebruik van internetporno, luidt het antwoord tientallen keren: **"STOP MET GEBRUIKEN! JE BENT EEN SUKKEL!"** Daarom gebruiken alle gebruikers niet omdat ze willen of beslissen om te gebruiken, maar omdat ze niet kunnen stoppen. Ze ***moeten*** porno gebruiken en hersenspoelen zichzelf zo, terwijl ze hun kop in het zand steken.

Bevestigde gebruikers moeten in gedachten houden dat de situatie alleen maar snelgroeiend erger zal worden, met meer studies die naar buiten komen en meer mensen die praten over de nadelige effecten van internetporno. Vandaag de dag zijn het niet-medische mensen die de effecten bespreken, morgen staat het op de lijst met diagnostische tests van je arts. Voorbij zijn de dagen waarop de gebruiker 'downtime' kon verbergen achter werkstress in hun seksleven; je partner zal zich afvragen waarom je 's avonds laat nog op je laptop zit. De arme gebruiker — die zich al ongelukkig voelt — wil nu dat de grond zich opent en hen inslikt.

Het vreemde is dat hoewel veel mensen graag veel geld zouden betalen voor sportschoolabonnementen en personal trainers om spieren op te bouwen en er gevormd uit te zien (en velen van hen in hun denkbeeldige (en echte) wanhoop hun toevlucht nemen tot behandelingen zoals het verhogen van testosteron, met twijfelachtige en gevaarlijke bijwerkingen), er veel mensen in deze groep zijn die zouden profiteren van het stoppen met een praktijk die systematisch hun hersenen natuurlijke ontspanningssystemen vernietigt.

Dit komt omdat ze nog steeds denken met de gehersenspoelde geest van de gebruiker. Veeg voor een moment het zand uit je ogen. Internetporno is een kettingreactie en een ketting voor het leven, en als je die ketting niet doorbreekt, blijf je de rest van je leven een gebruiker. Schat eens in hoeveel tijd je denkt dat je de rest van je leven aan porno zult besteden. Het bedrag zal natuurlijk van persoon tot persoon verschillen, maar laten we aannemen dat het anderhalf jaar aan werkuren is. Stel je voor dat er morgen een cheque van de loterij voor anderhalf jaar salaris op je tapijt ligt? Je zou van vreugde dansen, dus begin te dansen! Je staat op het punt om die voordelen te gaan ontvangen!

Als je denkt dat dit een sluwe manier is om ernaar te kijken, houd je jezelf nog steeds voor de gek. Bereken hoeveel tijd je zou hebben bespaard als je nooit je eerste glimp had opgevangen helemaal aan het begin.

Binnenkort zul je de beslissing nemen om je laatste sessie te gebruiken (nog niet, onthoud alsjeblieft de instructies!), een niet-gebruiker blijven door niet opnieuw voor de val te vallen. Het enige wat je hoeft te doen om een niet-gebruiker te blijven, is geen porno gebruiken en 'slechts één blik' vermijden. Onthoud dat als je dat wel doet, het je zal kosten wat je ook geschat hebt als je salariswinst.

Als je iemand begeleidt bij hun pornoverslaving, vertel ze dan dat ze iemand kennen die een baanaanbod heeft geweigerd dat hun huidige jaarsalaris betaalt en hen ook een volledige maand betaalde vrije tijd geeft. Als hen wordt gevraagd wie die idioot is, vertel ze dan: ***"Jij!"*** Het is onbeleefd, maar soms moet je het punt op een minder beleefde manier duidelijk maken.
