# De wilskracht methode

Het is een geaccepteerd feit in de samenleving dat het erg moeilijk is om te stoppen met porno. Boeken en forums die je adviseren hoe te stoppen beginnen meestal met te vertellen hoe moeilijk het is. De waarheid is dat het belachelijk eenvoudig is. Het is begrijpelijk om die uitspraak in twijfel te trekken, maar overweeg het eerst maar eens. Als je doel is om een mijl te rennen in vier minuten, dat is moeilijk en je zult jarenlang intensief moeten trainen, en zelfs dan ben je mogelijk fysiek niet in staat.

Echter, alles wat je hoeft te doen om te stoppen met porno is om er niet meer naar te kijken en/of te masturberen. Niemand dwingt je om te masturberen (behalve jijzelf) en in tegenstelling tot voedsel of water is het niet nodig voor overleving. Dus als je wilt stoppen, waarom zou het dan moeilijk moeten zijn? In feite is het dat niet. Het zijn gebruikers die het zichzelf moeilijk maken door gebruik te maken van wilskracht of enige methode die de gebruiker dwingt om het gevoel te hebben dat ze een soort opoffering doen. Laten we deze methoden eens bekijken.

We besluiten niet om gebruikers te worden, we experimenteren alleen met pornotijdschriften of -websites en omdat ze verschrikkelijk zijn (dat klopt, verschrikkelijk), afgezien van onze gewenste clip, zijn we ervan overtuigd dat we kunnen stoppen wanneer we willen. In eerste instantie bekijken we die eerste paar clips wanneer we willen en bij speciale gelegenheden. Voordat we het beseffen, bezoeken we die sites niet alleen regelmatig en masturberen we wanneer we willen - we masturberen dagelijks. Porno is een deel van ons leven geworden, ervoor zorgend dat we overal een internetverbinding nodig hebben. We geloven dan dat we recht hebben op liefde, seks, orgasme en de stressverlagende eigenschappen van porno. Het lijkt niet tot ons door te dringen dat dezelfde clip en acteurs ons niet dezelfde mate van opwinding geven en we beginnen te vechten tegen de rode lijn om 'slechte porno' te vermijden. In feite verbetert masturbatie en internetporno ons seksleven niet en vermindert het ook de stress niet, het is alleen dat gebruikers geloven dat ze niet van het leven kunnen genieten of met stress kunnen omgaan zonder het.

Het duurt meestal lang voordat we ons realiseren dat we verslaafd zijn, omdat we de illusie hebben dat gebruikers naar porno kijken omdat ze ervan genieten - en niet omdat ze ***moeten.*** Wanneer we geen 'plezier' beleven aan porno, wat we nooit kunnen tenzij er nieuwheid, schok of escalatie wordt toegevoegd, zijn we onder de illusie dat we kunnen stoppen wanneer we maar willen. Dit is een valstrik van zelfvertrouwen. "*Ik geniet niet van porno, dus ik kan stoppen wanneer ik wil*". Alleen lijkt je nooit te 'willen' stoppen.

Het is meestal pas wanneer we daadwerkelijk proberen te stoppen dat we ons realiseren dat er een probleem bestaat. De eerste pogingen zijn over het algemeen vroeg - getriggerd door het ontmoeten van een partner en opmerken dat ze niet 'helemaal genoeg' zijn na de eerste dates. Een andere veelvoorkomende reden is het opmerken van gezondheidseffecten in het dagelijks leven.

Ongeacht de reden, wacht de gebruiker altijd op een stressvolle situatie, of het nu gaat om gezondheid of seks. Zodra ze stoppen, begint het kleine monster hongerig te worden. De gebruiker wil dan iets om hun dopamine te stimuleren, zoals sigaretten, alcohol, of hun favoriet - internetporno - met hun harem slechts een muisklik verwijderd. De pornocache bevindt zich niet langer in de kelder, het is virtueel en overal toegankelijk. Als hun partner in de buurt is of ze zijn met vrienden, hebben ze geen toegang meer tot hun virtuele harem, wat hen nog meer van streek maakt.

Als de gebruiker wetenschappelijk materiaal of online gemeenschappen is tegengekomen, zal hij een innerlijke strijd voeren, verleidingen weerstaan en zich beroofd voelen. Hun manier om stress meestal te verlichten is nu niet beschikbaar, wat een drievoudige klap betekent. Het waarschijnlijke resultaat na deze periode van marteling is compromis - "*Ik zal minderen*" of "*Ik heb het verkeerde moment gekozen*" of misschien, "*Ik wacht tot de stress uit mijn leven is verdwenen.*" Echter, zodra de stress weg is, is er geen reden om te stoppen en besluit de gebruiker niet opnieuw te stoppen tot de volgende stressvolle periode.

Natuurlijk is er nooit een goed moment omdat het leven voor de meeste mensen stressvoller wordt. We verlaten de bescherming van onze ouders, betreden de wereld van het opzetten van een huishouden, het aangaan van hypotheken, het krijgen van kinderen en het hebben van meer verantwoordelijke banen. Wat er ook gebeurt — het leven van de gebruiker kan niet minder stressvol worden omdat porno eigenlijk stress veroorzaakt. Hoe sneller de gebruiker doorgaat naar de escalatiefase, hoe meer nood ze worden en hoe groter de illusie van afhankelijkheid groeit.

In feite is het een illusie dat het leven stressvoller wordt en porno - of een vergelijkbare kruk - creëert die illusie. Hier zal later uitgebreider op worden ingegaan, maar na deze eerste mislukkingen vertrouwt de gebruiker meestal op de mogelijkheid dat ze op een dag wakker worden en gewoon niet meer willen masturberen of porno willen gebruiken. Deze hoop wordt meestal aangewakkerd door verhalen van andere ex-gebruikers, "*Ik nam het niet serieus tot ik merkte dat mijn erectie afnam, toen wilde ik geen porno meer gebruiken en stopte met masturberen.*"

Laat je niet voor de gek houden; onderzoek deze geruchten en je zult ontdekken dat ze nooit zo eenvoudig zijn als ze lijken. Meestal heeft de gebruiker al voorbereidingen getroffen om te stoppen en heeft hij de gebeurtenis slechts gebruikt als een aanzet. Vaker nog, in het geval van mensen die "zomaar" stoppen, hebben ze een schok meegemaakt: misschien een ontdekking door hun partner, een gebeurtenis waarbij ze porno van een niet-normale seksuele richting hebben bekeken, of ze hebben zelf een angst voor seksuele disfunctie gehad. "*Dat is gewoon wie ik ben.*" Hou jezelf niet voor de gek. Het gebeurt niet tenzij je het laat gebeuren.

Laten we in meer detail bekijken waarom de wilskrachtmethode zo moeilijk is. Gedurende het grootste deel van ons leven hanteren we de kop-in-het-zandbenadering van "*Ik stop morgen wel*". Af en toe zal iets een poging tot stoppen in gang zetten. Het kunnen zorgen zijn over gezondheid, kracht of een periode van zelfanalyse waarin we ons realiseren dat we er eigenlijk niet van genieten. Wat de reden ook is, we beginnen de voor- en nadelen van porno af te wegen. Seks wordt verdeeld in tantrische (aanraking, geur, stem) en voortplantende (orgasme); dit is een van de belangrijkste sleutels om onze geest te openen, en zonder dit belangrijke onderscheid zal er verwarring ontstaan, wat tot mislukking leidt. Bij een verstandige beoordeling komen we erachter wat we ons hele leven al hebben geweten, de conclusie is duizend keer over “***STOP ERMEE!***"

Als je zou gaan zitten en punten zou geven aan de voordelen van stoppen en deze zou vergelijken met de voordelen van porno, zou het totale puntentotaal voor stoppen veruit elke 'nadelen' overtreffen. Als je Pascal's Wager toepast, verlies je bij het stoppen bijna niets, met een grote kans op winst en een nog grotere kans om *niet* te verliezen. Hoewel de gebruiker weet dat ze beter af zullen zijn als niet-gebruiker, zorgt het geloof dat ze een opoffering doen ervoor dat ze struikelen. Hoewel het een illusie is, is het krachtig. Ze weten niet waarom, maar de gebruiker heeft het geloof dat tijdens de goede en slechte tijden van het leven, de sessies lijken te helpen. Zelfs voordat ze aan hun poging beginnen, wordt de maatschappelijke hersenspoeling verder versterkt door de hersenspoeling van hun eigen verslaving, gecombineerd met de nog krachtigere hersenspoeling van hoe moeilijk het is om 'op te geven'.

Gebruikers horen verhalen van mensen die al vele maanden gestopt zijn en toch wanhopig naar porno verlangen, of van teleurgestelde stoppers, die, nadat ze gestopt zijn, de rest van hun leven betreuren dat ze graag een sessie zouden willen hebben. Er zijn verhalen van gebruikers die vele maanden of jaren gestopt zijn, gelukkige levens leiden, alleen om toch weer één 'blik' naar porno te hebben en plotseling weer verslaafd te zijn. Gebruikers kennen waarschijnlijk verschillende mensen in de gevorderde fase van de ziekte, die zichzelf zichtbaar vernietigen en duidelijk niet van het leven genieten - maar toch doorgaan met gebruiken. Bovendien hebben ze waarschijnlijk zelf een of meer van die ervaringen meegemaakt.

Dus in plaats van te beginnen met het gevoel, "*Geweldig! Heb je het nieuws gehoord? Ik hoef geen porno meer te kijken!*", beginnen ze in plaats daarvan met gevoelens van somberheid en negativiteit - alsof ze proberen de Mount Everest te beklimmen - en ze bepalen vals dat zodra het kleine monster zijn klauwen in je heeft, je voor het leven verslaafd bent. Veel gebruikers beginnen de poging door zich te verontschuldigen bij hun vriendinnen of vrouwen: "*Kijk, ik probeer te stoppen met porno. Ik zal waarschijnlijk de komende paar weken prikkelbaar zijn, dus probeer het me alsjeblieft te vergeven.*" De meeste pogingen zijn gedoemd te mislukken voordat ze beginnen.

!
Assumeer dat de gebruiker een paar dagen zonder een sessie overleeft. Ze krijgen hun opwinding terug en beginnen te herstellen. Ze hebben hun favoriete tubesites niet geopend en
worden daardoor opgewonden door normale stimulatie waar ze eerder aan voorbij gingen. De redenen waarom ze in de eerste plaats besloten te stoppen verdwijnen snel uit hun gedachten, zoals het zien van een ernstig verkeersongeval tijdens het rijden. Het zal je even vertragen, maar de volgende keer dat je laat bent voor een afspraak trap je weer op het gaspedaal.

Aan de andere kant van de strijd staat het kleine monster dat nog steeds zijn fix niet heeft gehad. Er is geen fysieke pijn - als je hetzelfde gevoel zou hebben door een verkoudheid, zou je niet stoppen met werken of depressief worden, je zou erom lachen. Het enige wat de gebruiker weet, is dat ze hun harem willen bezoeken. Het kleine monster weet dit en start het grote hersenspoelmonster op, waardoor dezelfde persoon die een paar uur of dagen eerder alle redenen om te stoppen opsomde, nu wanhopig op zoek gaat naar elk excuus om weer te beginnen. Ze beginnen dingen te zeggen als:

-   “*Het leven is te kort, er zou een bom kunnen afgaan, ik zou morgen onder een bus kunnen belanden. Ik ben te laat. Ze vertellen je tegenwoordig dat alles verslavend is.*"

-   “*Ik heb het verkeerde moment gekozen.*"

-   “*Ik had moeten wachten tot na Kerstmis, na mijn vakantie/toetsen, na dit stressvolle moment in mijn leven.*"

-   “*“Ik kan me niet concentreren, ik word prikkelbaar en slechtgehumeurd, ik kan mijn werk niet eens goed doen.*"

-   “*Mijn familie en vrienden zullen niet van me houden. Laten we eerlijk zijn, voor ieders bestwil moet ik opnieuw beginnen. Ik ben een bevestigde seksverslaafde en er is geen manier waarop ik ooit weer gelukkig zal zijn zonder een orgasme.*"

-   “*Niemand kan overleven zonder seks." (Gehersenspoeld door goedbedoelende mensen die geen onderscheid maken tussen de tantrische en voortplantingsdelen van seks)”*

-   “*Ik wist dat dit zou gebeuren, mijn brein is ‘gevoeliger gemaakt’ door DeltaFosB door veranderingen die zijn veroorzaakt door dopaminepieken als gevolg van mijn overmatig gebruik van porno in het verleden. Deze gevoeligheid kan 'nooit' uit de hersenen worden verwijderd.*"

Op dit punt geeft de gebruiker meestal toe. Bij het openen van de browser neemt de schizofrenie toe. Aan de ene kant is er de enorme opluchting om de drang te beëindigen nu het kleine monster eindelijk zijn fix krijgt; aan de andere kant is het orgasme verschrikkelijk en begrijpt de gebruiker niet waarom ze het doen. Daarom denkt de gebruiker dat het ontbreekt aan wilskracht. In feite is het geen gebrek aan wilskracht, alles wat ze hebben gedaan is hun mening veranderd en een volkomen logische beslissing genomen in het licht van de laatste informatie.

"*Wat heeft het voor zin om gezond of rijk te zijn als je ongelukkig bent?*"

Absoluut geen! Het is veel beter om een kort, plezierig leven te hebben dan een lang, ongelukkig leven. Gelukkig geldt dit niet voor de niet-gebruiker, omdat het leven oneindig veel plezieriger is. De ellende die de gebruiker doormaakt, komt niet door afkickverschijnselen - hoewel deze aanvankelijk worden getriggerd - de werkelijke pijn is de innerlijke strijd veroorzaakt door twijfel en onzekerheid. Omdat de gebruiker begint met het gevoel dat ze een opoffering doen, beginnen ze zich dan beroofd te voelen, wat een vorm van stress is.

Een van deze stressvolle momenten is wanneer de hersenen hen vertellen om 'een kijkje te nemen', en ze willen terugkrabbelen zodra ze stoppen. Maar omdat ze zijn gestopt, kunnen ze dat niet en dat maakt hen nog depressiever en zet de trigger opnieuw aan. Een andere factor die stoppen zo moeilijk maakt, is het wachten tot er iets gebeurt. Als je doel is om te slagen voor een rijexamen, zodra je het examen hebt gehaald, is het zeker of je je doel hebt bereikt. Onder de wilskrachtmethode is het interne verhaal - "*Als ik lang genoeg zonder internetporno kan, zal de drang om ernaar te kijken uiteindelijk verdwijnen.*" Je kunt dit in de praktijk zien in online forums waar verslaafden praten over hun reeksen of dagen van onthouding.

Zoals hierboven gezegd, is de kwelling die de gebruiker ondergaat mentaal en wordt veroorzaakt door onzekerheid. Hoewel er geen fysieke pijn is, heeft het toch krachtige effecten. Nu ellendig en onzeker, is de gebruiker verre van het vergeten, nu vol twijfels en angsten.

-   “*Hoe lang zal het verlangen duren?*"

-   “*Zal ik ooit weer gelukkig zijn?*"

-   “*Zal ik ooit weer zin hebben om 's ochtends op te staan?*"

-   “*Hoe zal ik ooit omgaan met stress in de toekomst?*"

De gebruiker wacht tot de dingen verbeteren, maar terwijl ze nog steeds treuren, wordt de 'harem' steeds kostbaarder. In feite gebeurt er *wel* iets, maar onbewust, als ze weken kunnen overleven zonder de browser te openen, verdwijnt het verlangen naar het kleine monster. Echter, zoals eerder vermeld, zijn de afkickverschijnselen van dopamine en opioïden zo mild dat de gebruiker zich er niet eens van bewust is. Op dit moment voelen veel gebruikers aan dat ze 'het hebben afgekickt' en dus kijken ze even om dat te bewijzen, waardoor ze weer terugvallen op de waterglijbaan. Nadat ze dopamine aan het lichaam hebben geleverd, is er nu een stemmetje achter in hun hoofd dat zegt: "*Je wilt er nog een.*" In feite waren ze ermee gestopt, maar hebben ze zichzelf opnieuw gehaakt.

Als kind keek je naar tekenfilms en volgens de neurowetenschap vormde je neurale paden (DeltaFosB) ervoor. Als je een kind wilt ontmoedigen om te kijken, zou je onderzoeken of die paden nog steeds bestaan en volwassenen bevragen waarom ze niet meer graag naar hun favoriete kindertekenfilms kijken. Ten eerste is er beter entertainment beschikbaar en ten tweede hebben de tekenfilms gewoon niet meer dezelfde magie. Met de wilskrachtmethode ontzeg je het kind gewoon de tekenfilm, maar met EasyPeasy zorg je er ook voor dat ze er geen waarde meer aan hechten. Wat is beter?

De gebruiker zal meestal niet meteen weer een sessie starten, denkend: "*Ik wil niet opnieuw verslaafd raken!*" en laat een veilige periode van uren, dagen of zelfs weken verstrijken. De ex-gebruiker kan dan zeggen: "*Nou, ik raakte niet verslaafd, dus ik kan veilig weer een sessie hebben.*" Ze zijn weer in dezelfde val getrapt als toen ze voor het eerst begonnen en zijn al op de glibberige helling.

Gebruikers die slagen met de wilskrachtmethode vinden het vaak lang en moeilijk omdat het primaire probleem de hersenspoeling is. Lang nadat de fysieke verslaving is verdwenen, hangen gebruikers nog steeds rond, ongelukkig. Uiteindelijk, nadat ze deze langdurige marteling hebben overleefd, begint het tot hen door te dringen dat ze niet toe zullen geven, stoppen met treuren en accepteren dat het leven doorgaat en plezierig is zonder porno. Er zijn aanzienlijk meer mislukkingen dan successen, omdat sommige mensen die slagen door hun leven gaan in een kwetsbare toestand, achtergelaten met een zekere mate van hersenspoeling die hen vertelt dat porno hen inderdaad een boost geeft. Dit verklaart waarom veel gebruikers die lange tijd gestopt zijn later weer opnieuw beginnen.

Veel ex-gebruikers zullen af en toe een sessie hebben als een 'speciale traktatie' of om zichzelf ervan te overtuigen hoe sterk hun zelfbeheersing is. Het doet precies dat - maar zodra hun sessie voorbij is, begint de dopamine te verdwijnen en begint een stemmetje achter in hun hoofd hen naar een andere te leiden. Als ze besluiten deel te nemen, lijkt het nog steeds onder controle te zijn, geen schokken, escalatie of het zoeken naar nieuwheid, dus zeggen ze: "*Geweldig! Terwijl ik er niet echt van geniet, zal ik niet verslaafd raken. Na Kerstmis / deze vakantie / dit trauma stop ik.*" Maar ze weten niet dat de waterglijbanen van hun brein nog meer zijn ingevet.

Te laat, ze zijn al verslaafd! De val waar ze zichzelf uit hebben weten te worstelen, heeft opnieuw zijn slachtoffer geëist.

Zoals eerder gezegd, komt plezier er niet in voor. Het deed het nooit! Als we keken vanwege plezier, zou niemand langer op de buissites blijven dan nodig is om de daad te volbrengen. Hoe dan ook, een betere manier om jezelf te plezieren is vanuit herinneringen. We gaan ervan uit dat we van internetporno genieten alleen omdat we niet kunnen geloven dat we zo dom zouden zijn om verslaafd te raken als we er niet van zouden genieten. De meeste gebruikers hebben geen idee van supernormale prikkels, nieuwheid of schokken zoeken en zelfs nadat ze erover hebben gelezen, geloven ze niet dat hun gebruik gemotiveerd wordt door evolutionaire beloningscircuit-bedrading. Daarom is zo veel van porno onbewust - als je op de hoogte was van de neurologische veranderingen en het moest rechtvaardigen dat het je in de toekomst geld zou kosten, zou zelfs de illusie van plezier verdwijnen.

Als we proberen onze geest af te sluiten voor de slechte kant, voelen we ons dom. Als we het onder ogen moesten zien, zou dat onaangenaam zijn! Als je een gebruiker in actie ziet, zul je zien dat ze alleen gelukkig zijn als ze zich er niet van bewust zijn dat ze het gebruiken. Eenmaal bewust, zijn ze meestal ongemakkelijk en verontschuldigend. Porno voedt het kleine monster dus door het uit je lichaam te reinigen samen met de hersenspoeling (grote monster), zul je niet de behoefte en ook niet het verlangen hebben om te kijken!
