# Slechts één glimp.

"Slechts één glimp." is een mythe die je uit je gedachten moet verbannen:

-   Het is *slechts één glimp* die ons in de eerste plaats op gang brengt.

-   Het is *slechts één glimp* om ons door een moeilijke periode heen te helpen of op een speciale gelegenheid die de meeste van onze pogingen om te stoppen tenietdoet.

-   Het is *slechts één glimp* die, nadat we erin geslaagd zijn de verslaving te doorbreken, ons weer in de val lokt. Soms is het alleen maar om te bevestigen dat ze geen porno meer nodig hebben, en één bezoek aan de harem bewijst dat precies.

De nasleep van porno zal vreselijk zijn en de gebruiker ervan overtuigen dat ze nooit meer verslaafd zullen raken - maar dat zijn ze al. De gebruiker voelt dat iets dat hen zo ellendig en schuldig maakt, hen niet had moeten laten doen wat ze hebben gedaan, maar toch deden ze het.

Het is de gedachte aan 'één speciale sessie' die gebruikers vaak weerhoudt om te stoppen, die na je lange conferentiereis komt, na een zware werkdag, na een ruzie met de kinderen, of na een incident waarbij je partner je afwijst voor seks. Zorg er ***vastberaden*** voor dat je in gedachten houdt dat er niet zoiets bestaat als 'slechts één glimp'. Het is een kettingreactie die de rest van je leven zal duren, tenzij je deze doorbreekt. De mythe over af en toe, een speciale gelegenheid houdt gebruikers in de put na het stoppen. Maak er een gewoonte van om nooit de 'geen big deal'-sessie te zien, het is fictie. Wanneer je aan porno denkt, zie dan een smerig leven lang spenderen achter een scherm voor het voorrecht om jezelf mentaal en fysiek te vernietigen - een leven van slavernij en hopeloosheid. Het is geen misdaad als je erecties onbetrouwbaar zijn, maar het is wel een misdaad als je op de lange termijn gelukkiger zou kunnen zijn maar in plaats daarvan kiest voor kortetermijn 'plezier'.


Het is oké dat we niet altijd met 'iets te doen' voor de leegte kunnen komen; dat is in elk geval niet realistisch mogelijk in elke situatie voor ons hele leven. We kunnen ons voor de meeste situaties voorbereiden, maar soms gebeurt het gewoon. Goede en slechte tijden gebeuren ook, ongeacht porno. Maar maak het duidelijk in je gedachten, de porno is het niet. Je zit vast aan een leven vol ellende of helemaal geen. Je zou er niet aan denken om cyanide in te nemen alleen omdat je van de smaak van amandelen houdt, dus stop met jezelf te straffen met af en toe een 'geen-big-deal'-sessie. Vraag een gebruiker met problemen, "*Als je de kans had om terug te gaan naar de tijd voordat je verslaafd raakte, zou je dan een gebruiker zijn geworden?*" Het antwoord is onvermijdelijk: "*Je moet een grapje maken!*". Toch heeft elke gebruiker elke dag van zijn leven die keuze, dus waarom kiezen ze er niet voor? Het antwoord is angst, de angst dat ze niet kunnen stoppen of dat het leven niet hetzelfde zal zijn zonder.

Houd op met jezelf voor de gek te houden! Je kunt het doen, iedereen kan het. Het is belachelijk eenvoudig, maar om het zo te maken, zijn er bepaalde fundamentele zaken die je duidelijk moet begrijpen.

1.  Er is niets op te geven, alleen maar prachtige positieve resultaten om te behalen.

2.  Overtuig jezelf nooit van het idee van een incidentele 'geen-big-deal' of 'slechts één glimp'-sessie. Het bestaat niet. Er is alleen een leven vol vuiligheid en slavernij.

3.  Er is niets anders aan jou; elke gebruiker kan het gemakkelijk vinden om te stoppen.

Veel gebruikers geloven dat ze bevestigde verslaafden zijn of een verslavende persoonlijkheid hebben. Dit gebeurt meestal als gevolg van het lezen van overmatige hoeveelheden schokkende neurowetenschappen. Er bestaat niet zoiets, niemand wordt geboren met de behoefte om naar videoclips te masturberen voordat ze verslaafd raakten. Het is de drug die je haakt, niet de aard van je karakter of persoonlijkheid. De aard van verslavende supernormale prikkels doet je geloven dat dit het geval is. Het is echter noodzakelijk om deze overtuiging te verwijderen, want als je gelooft dat je verslaafd bent, zul je dat zijn, zelfs nadat het kleine monster in je lichaam allang dood is. Het is belangrijk om al deze hersenspoeling te verwijderen.

