# Een sociale gewoonte?

De gezondheid van de geest en het lichaam zijn de belangrijkste redenen waarom we zouden moeten willen stoppen - maar dat zijn ze altijd al geweest. We hebben eigenlijk geen wetenschappelijk onderzoek en kennis in de neurowetenschappen nodig om ons te vertellen dat porno verslavend is en onze levens potentieel kan verwoesten. Onze lichamen zijn de meest geavanceerde objecten op de planeet, en elke gebruiker weet vanaf de eerste sessie dat de stimulus tot excessen kan leiden en giftig kan worden.

De enige reden waarom we ooit betrokken raken bij porno is de overlap van de cyclus met ons evolutionaire programmering. Internetporno is zeer beschikbaar, gratis en 24 uur per dag beschikbaar. Porno werd ooit als onschuldig beschouwd, maar dat was toen de afbeeldingen statisch waren en de video's een reis naar de plaatselijke winkel vereisten voor een VHS-bandje.

Vandaag de dag wordt over het algemeen — zelfs door de gebruikers zelf — erkend dat porno een supernormale stimulus is en verslavend kan zijn. In vroeger tijden gaf de sterke man niet toe dat hij masturbeerde, met 'loser' als een denigrerende term. In elke kroeg, club of bar wilde het merendeel van de mannen trots een vrouw mee naar huis nemen en echt seks hebben. Vandaag de dag is de situatie volledig omgekeerd voor de internetpornoverslaafde. De moderne man realiseert zich dat hij begint te voelen dat hij geen vrouw nodig heeft. Samenwerken online, bespreekt hij ervaringen, bedenkt strategieën en verkent opties. De moderne sterke man wil niet afhankelijk zijn van drugs. Door sociale revolutie overwegen alle gebruikers serieus om te stoppen met internetporno en masturbatie. De moderne gebruikers beschouwen porno als een nutteloze en schadelijke activiteit.

De meest opvallende trend die op forums wordt opgemerkt, is de toenemende nadruk op de antisociale aspecten van porno. De dagen waarin een man opschepte over het hebben van seks en orgasmes elke dag worden langzaam vervangen door het besef van slavernij aan het pornomonster.

De enige reden waarom mensen doorgaan nadat ze zijn geïnformeerd, is omdat ze er niet in geslaagd zijn te stoppen of te bang zijn om het te proberen. Er is een breed spectrum van interesse in het onderwerp, sommigen onthouden zich van porno, masturbatie en orgasme — met of zonder partners. Praktijken die de seksuele en voortplantingsdelen van seks scheiden, zoals semen retentie en Karezza, worden besproken en in groten getale aangenomen. Veel van de eerder genoemde mislukkingen zijn in werkelijkheid misstappen voorwaarts, enigszins ten goede komend aan mensen die ze beoefenen. Zodra je de no-PMO-route begint, zul je de beste aanpak vinden die van toepassing is op jouw leven; het wordt aangemoedigd om je eigen plan te bedenken over orgasmes na het begrijpen en beoefenen van seksuele scheiding. Wat je route ook is, je zult waarde zien in het beperken van het aantal keren dat je hersenen overspoelt met chemicaliën door middel van een orgasme, en nooit meer porno, seks en orgasme zien als een plezier of een steun voor je emotionele zelf.
Diverse populaire online gemeenschappen, opgericht door niet-gebruikers, zijn toegewijd aan het stoppen met niet alleen porno, maar ook masturbatie. Deze sites zijn uiteindelijk gunstig voor degenen die ontsnappen, maar de meeste notities wijzen hen naar wilskracht. Het gevolg van obsessie met abstinentie-reeksen en andere maatregelen is zelfmedelijden en gebrek aan vreugde. Veel van de hersenspoeling blijft levend en wel. Uiteindelijk breekt iemand en vindt er een domino-effect plaats, andere gebruikers ontdekken dat ze niet de enigen zijn. Echter, hun inspanningen zijn niet tevergeefs, ze vallen vooruit, zij het met veel zelfmarteling terwijl ze hun browsers sluiten maar niet de wens en de noodzaak. EasyPeasy werkt in de omgekeerde volgorde, door eerst de behoefte en het verlangen te verminderen, voordat de browser wordt gesloten. Elke dag verlaten steeds meer gebruikers het zinkende schip en degenen die er nog op zitten, worden doodsbang dat ze de laatste zullen zijn.

**WEES DIT NIET!**
