# Ga ik het plezier missen?

**Nee!** Nadat het kleine pornomonster dood is, nadat je lichaam geen dopamine meer verlangt, en de pornowaterglijbanen in je hersenen snel beginnen te vervagen door gebrek aan 'smering', zal elke overgebleven hersenspoeling verdwijnen. Niet alleen zul je merken dat je zowel fysiek als mentaal beter in staat bent om de stress en spanningen van het leven aan te kunnen, maar je zult ook ten volle kunnen genieten van de goede tijden.

Er is maar één gevaar, namelijk de invloed van degenen die nog steeds seks gebruiken als hun kruk en plezier. 'Het gras van de buren is altijd groener' is alomtegenwoordig in veel aspecten van ons leven en gemakkelijk te begrijpen. Waarom, in het geval van porno — met nadelen die zo enorm zijn in vergelijking met de illusoire 'voordelen' — heeft de voormalige gebruiker de neiging om te benijden degenen die seks en porno eisen als een kruk?

Met al de hersenspoeling vanaf de kindertijd is het heel begrijpelijk dat we in de val zijn gelopen. Waarom is het dan — nadat we hebben ingezien wat voor een dwaas spelletje porno is, en erin zijn geslaagd de gewoonte af te leren — dat we rechtstreeks teruglopen in dezelfde val? Het is de invloed van de maatschappelijke hersenspoeling die porno met seks vermengt en het als normaal presenteert. De ex-gebruiker heeft een moment van zwakte! De onzekere leegte die ze voelen doordat ze single zijn (wat trouwens geen misdaad is) veroorzaakt gevoelens van angst en drijft hen naar de waterglijbaan. Dit is inderdaad een merkwaardige anomalie, vooral als deze observatie wordt overwogen: niet alleen is elke niet-gebruiker ter wereld blij dat ze dat niet zijn, maar elke gebruiker ter wereld, zelfs met hun vervormde, verslaafde, gehersenspoelde geest die lijdt aan de waan van plezier of ontspanning, wenst dat ze nooit verslaafd waren geraakt in de eerste plaats. Dus waarom benijden sommige ex-gebruikers?

1. ‘Slechts één blik.' Onthoud, dat bestaat niet. Stop met het zien van het geïsoleerde geval en begin het te bekijken vanuit het perspectief van de pornogebruiker. Je zou jaloers kunnen zijn over hen, maar zij keuren zichzelf niet goed, en zij zijn jaloers om jou. Als je op de een of andere manier medisch naar een andere gebruiker kon kijken, zou dat de meest krachtige stimulans van allemaal kunnen zijn om je eruit te helpen. Let op hoe snel ze veel tabbladen en browservensters openen? Snel vooruitspoelen naar de belangrijke secties, snel verveeld raken van clips en door het hele scala van genres gaan, wat nieuwheid, schok, angst, enz. oplevert. Let vooral op dat de handeling automatisch lijkt te zijn. Onthoud — ze genieten er niet van, het is dat ze zichzelf niet kunnen vermaken zonder het. De volgende ochtend, wakker worden met een verzwakte wil, verloren energie en wazige ogen, zullen ze zichzelf moeten blijven verstikken bij de eerste verschijning van stress en spanning. Ze staan voor een leven van vuiligheid, slechte geestelijke gezondheid en aangetast zelfvertrouwen — een leven van zelfvernietiging met zwarte schaduwen achterin hun gedachten. Om welk doel te bereiken? De illusie dat je krijgt wat je ‘verdient' en verdoemd plezier?

2.  De tweede reden waarom sommige ex-gebruikers verlangens hebben, is omdat de pornogebruiker iets doet - zoals zelfgenoegzaamheid - en de niet-gebruiker niet, dus ze hebben de neiging zich beroofd te voelen. Maak het in je hoofd duidelijk, het is niet de niet-gebruiker die beroofd wordt, maar de arme verslaafde die beroofd wordt van:

-   Gezondheid

-   Energie

-   Zelfvertrouwen

-   Innerlijke rust

-   Moed

-   Gemoedsrust

-   Vrijheid

-   Zelfrespect

Breek uit de gewoonte om jaloers te zijn om pornogebruikers en begin hen te zien als de ellendige, zielige wezens die ze werkelijk zijn. Ik weet het, ik was ooit een van de ergste. Daarom lees je dit boek en niet degenen die het niet onder ogen kunnen zien en zichzelf blijven voorliegen.

Je zou niet jaloers zijn om een heroïneverslaafde, en net als bij alle drugsverslaving, zal de jouwe niet beter worden. Elk jaar zal het exponentieel erger worden — als je vandaag geen plezier hebt in het gebruiken, zul je het morgen nog minder leuk vinden. Wees niet jaloers om andere gebruikers, heb medelijden met hen. Geloof me: *Ze hebben je medelijden nodig!*
