# Kan ik afscheiden?

Deze mythe wordt voornamelijk verspreid door gebruikers die proberen te stoppen met de wilskrachtmethode, die mentale gymnastiek uitvoeren en beginnen aan een Jekyll-en-Hyde-routine: "*Porno is voor mijn alter ego en romantiek in het echte leven is voor mijn relatiekant.*" Niets is verder van de waarheid verwijderd — de pornowaterglijbanen, DeltaFosB en neurologische veranderingen zullen de romantiek in het echte leven overnemen en minder wenselijk maken. Mr. Hyde zal zeker de instructies van Dr. Jekyll overschrijven.

Als je internetporno gebruikt, train je jezelf voor de rol van toeschouwer, of heb je de optie om bij de geringste daling van de dopaminegehaltes naar iets opwindenders te klikken. Of, de voortdurende zoektocht naar precies de juiste scène voor maximaal effect. Bovendien kun je masturberen in een voorovergebogen positie of je smartphone in bed bekijken, waardoor je uiteindelijk die signalen meer verlangt dan echte stimuli. Seks staat haaks op bijna elk aspect van de online harem, dus het maakt geen schijn van kans in vergelijking. De herinneringen die worden gecreëerd als je jong bent, zijn krachtig en langdurig, dus het afbreken van die pornografische waterglijbanen en het herbedraden of creëren van nieuwe duurt langer. Dat wil echter niet zeggen dat het moeilijker is.

Elke keer dat je op de 'pornowaterglijbaan' stapt, smeer je hem, houd je de zenuwen fris en klaar om te vuren. Wanneer je naast een fastfoodrestaurant parkeert, zweeft de geur van de friteuse je neus binnen en is de verkoop al gemaakt. Op dezelfde manier staan de pornowaterglijbanen in je hersenen voor je klaar om je mee te slepen en zijn ze vierentwintig uur per dag open. Elke cue of trigger laat je beloningscircuit oplichten met de belofte van seks — alleen is het dat niet. Toch versterken zenuwcellen deze associaties met seksuele opwinding door nieuwe takken te laten groeien om de verbindingen te versterken. Hoe meer je porno gebruikt, hoe sterker de zenuwverbindingen worden. Het uiteindelijke resultaat is dat je misschien een toeschouwer moet zijn, steeds moeten klikken naar steeds escalerend en nieuw materiaal, porno nodig hebben om in slaap te vallen, of op zoek moeten gaan naar het perfecte einde om de klus te klaren.

Net als bij elk middel of gedragsmatige drug, ontwikkelt het lichaam tolerantie en houdt het middel op om de afkickverschijnselen volledig te verlichten. Zodra de pornogebruiker een sessie afsluit, willen ze er nog een, en snel, de permanente honger blijft onbevredigd. De natuurlijke neiging is escalatie, om de dopaminekick te krijgen. De meeste gebruikers worden echter om een of beide van de volgende redenen verhinderd dit te doen.

**Geld:** Ze kunnen zich niet veroorloven om zich te abonneren op betaalde pornosites.

**Gezondheid:** Er is slechts zoveel dat het lichaam aankan, ofwel de dopaminepieken of orgasmes. Bovendien veroorzaken orgasmes daadwerkelijk chemische reacties om de dopamine-uitstoot te verminderen. Het moet wel, zo werkt het lichaam nu eenmaal.

Zodra het kleine monster je lichaam verlaat, eindigt het vreselijke gevoel van onzekerheid. Je zelfvertrouwen keert terug, samen met een geweldig gevoel van zelfrespect, waarbij je de zekerheid verkrijgt om de controle over je leven te nemen en het te gebruiken als een springplank om andere problemen aan te pakken. Dit is een van de vele geweldige voordelen van het loskomen van elke verslaving.

De afscheidingsmythe is een van de vele trucjes die het kleine monster met je geest speelt. Deze trucs maken het moeilijker om te stoppen — vanwege de onmogelijke bevrediging van de permanente honger — waardoor veel gebruikers hun toevlucht nemen tot sigaretten, overmatig drinken, of zelfs hardere drugs om de leegte te vullen.

Mensen zijn beoordelende wezens, zowel naar onszelf als naar anderen toe. Samen met je partner naar porno kijken is onbevredigend, omdat je elkaars prestaties afzet tegen het verhaal. Wil je Brad Pitt in je slaapkamer, zelfs als hij op een poster staat? Geen enkel persoon kan op tegen een harem waarbij elke 'ervaring' wordt geacteerd, geschreven, geregisseerd door professionals en direct beschikbaar is vierentwintig uur per dag.
