# Vermijdt valse prikkels

Veel gebruikers die de wilskrachtmethode gebruiken, proberen hun motivatie te verhogen door valse prikkels te creëren. Er zijn veel voorbeelden hiervan, een typisch voorbeeld is zichzelf belonen met cadeaus na een maand geen porno te hebben gekeken. Dit lijkt een logische en verstandige aanpak, maar is in feite vals, omdat elke zelfrespecterende gebruiker liever doorgaat met het kijken naar porno dan zichzelf te belonen met een cadeau dat ze zelf hebben gegeven. Dit zorgt voor twijfel in de geest van de gebruiker, omdat ze niet alleen dertig dagen moeten onthouden, ze zijn ook niet zeker of ze zelfs zullen genieten van de dagen zonder porno. Hun enige plezier of steunpilaar is weggenomen! Dit vergroot alleen maar de omvang van het offer dat de gebruiker denkt te maken, nu nog kostbaarder in hun gedachten.

Andere voorbeelden zijn:

-	Ik stop zodat het me zal dwingen om een sociaal leven en meer echt seks te hebben.

-	Ik stop zodat een magische energie me zal helpen om boven de concurrenten uit te springen en de partner te krijgen die ik nastreef.

-	Ik stop zodat ik me kan inzetten om mijn energie en enthousiasme niet te verspillen met porno om honger in mezelf te laten groeien.

Deze zijn waar, kunnen effectief zijn, en je kunt uiteindelijk krijgen wat je wilt — maar denk er eens over na. Als je krijgt wat je wilt, zodra de nieuwigheid weg is, zul je je beroofd voelen; als je het niet kreeg, zul je je ellendig voelen. Hoe dan ook, vroeg of laat zul je weer in dezelfde val trappen.

Het koppelen van stoppen aan een valse prikkel vergroot alleen maar de twijfel, want als je je prikkel niet krijgt (en zelfs als je dat wel krijgt), begin je te twijfelen zoals "Zal stoppen mijn leven eigenlijk beter maken? Als ik stop en niet krijg wat ik wilde, heb ik de methode dan wel correct gebruikt?" Gedachten als deze vergroten gevoelens van opoffering en creëren dus verlangens.

Een ander typisch voorbeeld is online- of forumovereenkomsten. Deze hebben het voordeel dat ze verleiding gedurende bepaalde periodes elimineren. Echter, ze mislukken over het algemeen om de volgende redenen:


1. De prikkel is vals. Waarom zou je willen stoppen alleen omdat andere mensen dat doen? Dit creëert alleen maar extra druk en verhoogt het gevoel van opoffering. Het is prima als alle gebruikers oprecht op een bepaald moment willen stoppen, maar je kunt ze niet dwingen te stoppen, hoewel ze dat stiekem allemaal willen. Totdat ze er klaar voor zijn, creëert een pact extra druk, wat alleen maar hun verlangen om te kijken vergroot. Dit maakt van hen geheime kijkers, waardoor het gevoel van afhankelijkheid verder wordt vergroot.

2. Afhankelijkheid van elkaar met behulp van de wilskrachtmethode zorgt voor gevoelens van boetedoening, waarin ze wachten tot de drang verdwijnt. Als ze toegeven, is er een gevoel van mislukking. Bij het gebruik van de wilskrachtmethode zal minstens een van de deelnemers opgeven, wat de andere deelnemers de excuses geeft waar ze op hebben gewacht. Het is niet hun schuld, ze zouden hebben volgehouden maar 'Fred' heeft ze laten zitten. Het is de waarheid dat de meesten van hen al hebben valsgespeeld.

3. Het delen van de eer is het tegenovergestelde van afhankelijkheid. Er is een prachtig gevoel van prestatie bij het stoppen met porno en wanneer je het alleen doet, kan de lof die je ontvangt van je vrienden en online maatjes een enorme boost zijn gedurende de eerste paar dagen. Echter, wanneer iedereen het tegelijkertijd doet, moet de eer gedeeld worden en wordt de boost bijgevolg verminderd.

4. Een ander klassiek voorbeeld is de belofte van de goeroe. Stoppen zal je gelukkig maken omdat je niet langer betrokken bent bij de strijd, je brein begint opnieuw te bedraden en impulscontrole terug te krijgen. Echter, je moet in gedachten houden dat dit je niet zal veranderen in een seksgod of je de loterij zal laten winnen. Niemand anders dan jijzelf maakt het ook maar iets uit als je stopt met porno. Je bent geen zwak persoon als je drie keer per dag porno kijkt en PIED hebt, of een sterk persoon als je verslaafd bent en het niet doet.

Stop met jezelf voor de gek te houden. Als het aanbod voor tien maanden werk voor een jaarsalaris van twaalf maanden, of de risico's van het verminderen van het vermogen van je brein om dagelijkse stress en spanningen aan te kunnen, of het in gevaar brengen van een betrouwbare erectie, of een leven lang mentale en fysieke marteling en slavernij hen niet heeft gestopt, zullen de bovengenoemde valse prikkels geen enkel verschil maken en alleen maar de opoffering erger doen lijken. Richt je in plaats daarvan op de andere kant:

\"Wat krijg ik ervoor terug? Waarom moet ik porno kijken?\"

Blijf kijken naar de andere kant van het touwtrekken en vraag jezelf af wat porno voor je doet. *ABSOLUUT NIETS*. Waarom moet ik het doen? *DAT HOEF JE NIET! JE STRAFT JEZELF ALLEEN MAAR*. Het is de Weddenschap van Pascal: je hebt bijna niets te verliezen (afnemende opwinding), kansen op grote winst (volledige en betrouwbare opwinding, mentaal welzijn en geluk) en geen kans om groot te verliezen.

Waarom zou je dan je stoppen met porno kijken aankondigen aan vrienden en familie? Nou, het zal van je een trotse ex-verslaafde of ex-gebruiker maken, geen blije en gelukkige niet-gebruiker. Het kan je partner een beetje afschrikken omdat ze dit misschien zien als een plan om meer seks te hebben, op een soort New Age-manier. Ze kunnen ook bang zijn dat je verandert in een seksmachine. Het is moeilijk uit te leggen tenzij ze ruimdenkend zijn.

Elke poging om anderen te betrekken bij het stoppen geeft meer macht aan het kleine monster. Door het uit je gedachten te duwen en het volledig te negeren, heeft het effect van proberen er niet aan te denken. Wees in plaats daarvan opmerkzaam, zodra je de gedachten, signalen (alleen thuis) of afwezige gedachten opmerkt, zeg gewoon tegen jezelf "Geweldig, ik ben niet langer een slaaf van porno. Ik ben vrij en blij om verschillen in seks te ervaren!" Dit zal de zuurstof naar de gedachte afsnijden en voorkomen dat deze zich naar drang en verlangens ontwikkelt. In dit opzicht kan het beoefenen van mindfulness-meditatie nuttig zijn om te helpen bij het depersonaliseren van gedachten.
