# De Makkelijke Manier Om Te Stoppen

Dit hoofdstuk bevat instructies over de gemakkelijke manier om te stoppen met porno. Als je de instructies volgt, zul je merken dat stoppen variëert van relatief gemakkelijk tot plezierig! Als je de onderstaande instructies volgt, is het belachelijk eenvoudig om te stoppen met porno. Je hoeft slechts twee dingen te doen:

1.  Neem de beslissing dat je nooit meer naar porno zult kijken.

2.  Blijf er niet treurig over. Verheug je.

Je vraagt je waarschijnlijk af: *"Waarom de rest van het boek? Waarom kon je dat niet meteen zeggen?"* Nou, het antwoord is dat je uiteindelijk toch somber zou worden en dus uiteindelijk je beslissing zou veranderen. Waarschijnlijk heb je dat al vele malen eerder gedaan.

Zoals al gezegd, is porno een subtiele, duistere valstrik. Het grootste probleem bij stoppen is niet de dopamineverslaving - wat zeker een probleem is, maar niet het belangrijkste - het is de hersenspoeling. Daarom is het nodig om eerst alle mythen en illusies te vernietigen. Begrijp je vijand, ken hun tactieken, en je zult ze gemakkelijk verslaan. Na grote delen van mijn leven te hebben geleden aan diepe depressies terwijl ik probeerde te stoppen, ging ik uiteindelijk in één keer naar nul zonder een slecht moment. Het was zelfs plezierig, zelfs tijdens de afkicksperiode, en ik heb sindsdien nooit meer de kleinste neiging gehad. Integendeel, het was een van de meest prachtige dingen die in mijn leven zijn gebeurd.

Mijn laatste poging was anders. Net als alle gebruikers tegenwoordig, had ik serieus nagedacht over het probleem in mijn hoofd. Tot dan toe, na het falen, was het gebruikelijk om mezelf te troosten met de gedachte dat het de volgende keer makkelijker zou zijn. Het was nooit bij me opgekomen dat ik zo de rest van mijn leven door zou moeten gaan. Die gedachte vervulde me met afschuw en ik begon heel diep na te denken over het onderwerp.

In plaats van automatisch de browser op te starten, analyseerde ik mijn gevoelens en bevestigde wat ik al wist. Ik genoot niet van porno en vond het vies en walgelijk. Ik begon te kijken naar mensen die geen porno gebruikten in andere delen van de wereld, of oudere mensen die nooit de tube-sites hadden leren kennen. Tot dan toe had ik non-gebruikers altijd beschouwd als zweverige, onsociale, kieskeurige mensen. Echter, toen ik hen bekeek wanneer ze verschenen, leken ze - als er al iets was - sterker en meer ontspannen. Ze leken in staat om de stress en spanningen van het leven aan te kunnen en leken meer te genieten van sociale activiteiten dan porno-gebruikers. Ze hadden zeker meer sprankeling en levenslust dan zij.


Ik begon met ex-gebruikers te praten. Tot dat moment had ik hen altijd beschouwd als mensen die gedwongen werden om te stoppen om gezondheids- of religieuze redenen en altijd stiekem verlangden naar een bezoek aan een harem. Een paar zeiden wel, "Je hebt af en toe wat verlangens, maar die zijn zo zeldzaam dat ze niet de moeite waard zijn om je druk over te maken." De meesten zeiden echter, "Missen? Maak je een grap? Het leven heeft nog nooit beter gevoeld!"

Zelfs degenen die faalden, zagen het als een stap vooruit - ze veroordeelden zichzelf niet en accepteerden zichzelf onvoorwaardelijk. Als een coach die een fout van een echt gouden speler accepteert. Het praten met ex-gebruikers vernietigde nog een mythe die ik altijd in mijn hoofd had, namelijk dat er een natuurlijke zwakte in mij was, tot het tot me doordrong dat iedereen door deze privénachtmerrie gaat.

Eigenlijk zei ik tegen mezelf, *"Talloze mensen stoppen nu en leiden perfect gelukkige levens, ik hoefde het niet te doen voordat ik begon en ik kan me herinneren dat ik hard moest werken om aan deze viezigheid te wennen. Dus waarom zou ik het nu moeten doen?"* Hoe dan ook, ik genoot niet van porno, haatte het hele smerige ritueel en wilde de rest van mijn leven niet doorbrengen als slaaf van deze walgelijke verslaving. Ik zei toen tegen mezelf:

*“Of je het nu leuk vindt of niet, je hebt je laatste sessie voltooid."*

Ik wist vanaf dat moment dat ik nooit meer een sessie zou hebben. Ik verwachtte niet dat het gemakkelijk zou zijn, precies het tegenovergestelde. Ik geloofde volledig dat ik me had ingeschreven voor maanden van diepe depressie en de rest van mijn leven af en toe een verlangen zou hebben. In plaats daarvan is het vanaf het begin absolute zaligheid geweest.

Het kostte me lang om uit te zoeken waarom het zo gemakkelijk was geweest en waarom ik die angstaanjagende afkickverschijnselen niet had geleden. De reden is dat ze niet bestaan, het is de twijfel en onzekerheid die afkickverschijnselen veroorzaken. De prachtige waarheid is dat het ***gemakkelijk is om te stoppen met porno.*** Het is alleen twijfel en gepieker dat het moeilijk maakt. Zelfs als verslaafden kunnen gebruikers relatief lange periodes zonder doen op bepaalde momenten. Het is pas wanneer je het wilt, maar het niet kunt hebben, dat je lijdt.

Daarom is de sleutel om het gemakkelijk te maken ervoor te zorgen dat stoppen zeker en definitief is. Niet hopen, maar *weten* dat je er klaar mee bent, nadat je de beslissing hebt genomen. Nooit twijfelen of erover twijfelen, in feite juist het tegenovergestelde - altijd vreugdevol zijn! Als je vanaf het begin zeker kunt zijn, zal het gemakkelijk zijn. Maar hoe kun je er vanaf het begin zeker van zijn? Daarom is de rest van het boek noodzakelijk. Er zijn bepaalde essentiële punten die nodig zijn om duidelijk in je hoofd te krijgen voordat je begint:

1. Realiseer dat je het kunt bereiken. Er is niets anders aan jou en de enige persoon die je kunt laten kijken, ben jij zelf. Niet die ster, die zichzelf nooit in hun wildste dromen had voorgesteld dat ze zouden worden gebruikt om kracht te verminderen.

2. Er is absoluut niets om op te geven. Integendeel, er zijn enorme positieve winsten te behalen. Niet alleen zul je gezonder en rijker zijn, maar je zult meer genieten van de goede tijden en minder ellendig zijn tijdens de slechte.

3. Er bestaat niet zoiets als even kijken of een enkel bezoek. Pornografie is drugsverslaving en een kettingreactie; door te klagen over het af en toe bezoeken, straf je alleen maar onnodig jezelf.

4.  Bekijk porno niet als een 'jongens zullen jongens zijn' gewoonte die je misschien schaadt, maar als drugsverslaving. Onder ogen zien dat of je het nu leuk vindt of niet, *je hebt de ziekte.* Het zal niet verdwijnen omdat je je kop in het zand steekt. Onthoud dat het, net als alle verlammende ziektes, niet alleen voor het leven duurt maar veel erger wordt. De makkelijkste tijd om het te genezen is nu.

5.  Scheid de ziekte - de neurologische verslaving - van de mentaliteit om een gebruiker te zijn of niet. Alle gebruikers zouden, als ze de kans zouden krijgen om terug te gaan naar de tijd voordat ze verslaafd raakten, die kans met beide handen aangrijpen. Jij hebt die kans vandaag! Denk er niet eens aan als 'opgeven'.

Na het nemen van de definitieve beslissing dat je je laatste bezoek hebt gehad, ben je al een niet-gebruiker. Een gebruiker is een van die arme zielen die door het leven gaan en zichzelf vernietigen met porno. Een niet-gebruiker is iemand die dat niet doet. Zodra je die definitieve beslissing hebt genomen, heb je je doel al bereikt. Verheug je daarover, zit niet te mokken en te wachten tot de chemische verslaving verdwijnt. Ga er meteen op uit en geniet van het leven. Het leven is prachtig, zelfs als je verslaafd bent, en elke dag zal zoveel beter worden als je dat niet bent.

De sleutel om het gemakkelijk te maken om te stoppen, is er zeker van te zijn dat je zult slagen in volledige onthouding tijdens de terugtrekkingsperiode, een maximum van drie weken. Als je in de juiste gemoedstoestand bent, zul je dit belachelijk gemakkelijk vinden.

Op dit punt, als je je geest zoals gevraagd aan het begin hebt geopend, heb je al besloten te ontsnappen. Je zou nu gevoelens van opwinding moeten hebben, als een hond die aan de leiband trekt, niet kunnen wachten om de DeltaFosB-porno-waterglijbanen af te breken. Als je een gevoel van doem en somberheid hebt, is dat om een van de volgende redenen:

1.  Iets is niet goed geland in je hoofd. Lees de bovenstaande vijf punten opnieuw en vraag jezelf af of je ze als waar beschouwt. Als je aan een punt twijfelt, lees dan de betreffende secties van het boek opnieuw.

2.  Je bent bang voor falen op zich. Maak je geen zorgen, lees gewoon verder en je zult slagen. Het hele gedoe rond internetporno is een vertrouwensstreek van enorme omvang. Slimme mensen vallen voor vertrouwensstreken, maar alleen een dwaas blijft zichzelf voor de gek houden nadat hij de truc heeft ontdekt.

3.  Je bent het eens met alles maar bent nog steeds ongelukkig. Wees dat niet! Open je ogen, er gebeurt iets wonderbaarlijks. Je staat op het punt te ontsnappen uit de gevangenis, het is essentieel om met de juiste gemoedstoestand te beginnen: *"Het is geweldig dat ik een niet-gebruiker ben!"*

Allemaal wat nu moet gebeuren is dat je in die gemoedstoestand blijft tijdens de terugtrekkingsperiode, en de volgende hoofdstukken behandelen specifieke punten om je daartoe in staat te stellen. Na de terugtrekkingsperiode hoef je niet meer zo te denken, het zal automatisch gaan. Het enige mysterie in je leven zal zijn waarom je het niet eerder hebt gezien. Maar twee belangrijke waarschuwingen.

-   Stel je plan om je laatste bezoek te maken uit totdat je het boek hebt uitgelezen.

-   Een terugtrekkingsperiode van maximaal drie weken is al vaak genoemd, wat tot misverstanden kan leiden. Ten eerste kun je onbewust het gevoel hebben dat je drie weken lang moet lijden. Dat hoeft niet. Ten tweede moet je vermijden te denken: *"Op de een of andere manier moet ik drie weken lang onthouden en dan zal het wel goedkomen."* Er zal eigenlijk niets magisch gebeuren na drie weken; je zult je niet plotseling voelen als een niet-gebruiker, aangezien zij zich eigenlijk niet anders voelen dan gebruikers. Als je treurt over het stoppen tijdens de drie weken, is de kans groot dat je na die drie weken nog steeds over hetzelfde zult treuren. Samengevat, als je nu kunt beginnen door te zeggen: *"Ik ga nooit meer gebruiken, is het niet geweldig?"*, dan zal na drie weken alle verleiding verdwijnen. Maar als je zegt: *"Als ik deze drie weken zonder porno maar overleef..."*, dan zul je na die drie weken snakken naar een bezoek aan een harem.

Dit is belangrijk: je brein wil de status quo handhaven, dus als je gelooft dat je iets goeds verliest bij het stoppen, zul je je natuurlijk vreselijk voelen. Het is onmogelijk om jezelf te dwingen om een bepaalde manier te voelen als je brein dat niet gelooft. Daarom is het belangrijk om de illusie weg te nemen dat porno je überhaupt iets geeft. Op die manier weet je dat je niets opoffert.

Seksuele disfunctie heeft veel te maken met je brein en mindset. Internetporno herschikt het beloningscircuit van je brein en geeft je geest een 'twijfelachtige' mindset. Deze zelftwijfel zal ongetwijfeld seksuele disfunctie veroorzaken. Alle verlangen hebben in je bovenste deel, maar geen opwinding ervaren in je onderste deel is het ergste wat je mindset kan overkomen. Libido die hand in hand gaat met romantiek is het elixer van jeugd dat je kunt hebben tot aan je dood. Door te stoppen blijven de kansen hoog, maar dat is niet de enige of belangrijkste winst. Het is je vrijheid van slavernij!
