# Slechts één klein kijkje

Dit is de ondergang van velen die de wilskracht methode gebruiken. Ze zullen drie of vier dagen doorgaan en dan het af en toe een kijkje nemen om ze bezig te houden. Ze realiseren zich niet welk verwoestend effect dit heeft op hun moraal.

Voor de meeste gebruikers was hun eerste blik op de tube site harem niet zo goed als seks met een echt persoon. De schone clips zijn zeldzaam, waardoor hun bewuste geest een boost krijgt en denkt: "*Goed, dat was niet helemaal zo plezierig. Ik verlies de drang en ben niet van de schokkende dingen.*" In feite is het tegenovergestelde het geval. Maak het in je hoofd duidelijk, genot van een orgasme was niet de reden dat je stopte met porno. Als gebruikers er alleen waren voor het orgasme, zouden ze nooit meer dan één clip bekijken. De enige reden waarom je porno nodig had, was om dat kleine monster te voeden. Bedenk eens, na vier dagen te zijn uitgehongerd, hoe kostbaar dat ene kijkje voor het was. Je bewuste geest is zich er niet van bewust, maar de fix die je lichaam kreeg wordt gecommuniceerd naar je onderbewustzijn, en al je degelijke voorbereiding zal worden ondermijnd. Er zal een stemmetje achterin je hoofd zijn dat zegt dat, ondanks alle logica, de sessies kostbaar zijn en dat je er nog een wilt.

Dat kleine kijkje heeft twee schadelijke effecten:

1.  Het houdt het kleine monster in je lichaam in leven.

2.  Erger nog, het houdt het grote monster in je gedachten levend. Als je de 'laatste blik' had, zal het gemakkelijker zijn om de volgende te hebben.

Porno is een muizenval zonder kaas, alleen vergif. Met wilskracht moet je jezelf ervan overtuigen om de kaas niet te pakken, maar EasyPeasy stelt je in staat om te zien dat het vergif is. Je hoeft het niet te vermijden, je gaat er gewoon niet in.

Bovenal, onthoud:

*'Gewoon even kijken' is hoe mensen in de eerste plaats verslaafd raken.*
