#Is het moelijker voor mij?

Er zijn oneindig veel combinaties van factoren die bepalen hoe gemakkelijk elke individuele gebruiker zal stoppen. Om te beginnen heeft elk van ons ons eigen karakter, carrière, persoonlijke omstandigheden, timing, metabolisme, enz. Bepaalde beroepen kunnen het moeilijker maken dan andere, maar als de hersenspoeling wordt verwijderd, hoeft dit niet zo te zijn. Neem de volgende paar voorbeelden.

Soms is het moeilijk voor leden van het medisch beroep. We denken dat het voor artsen gemakkelijker zou moeten zijn omdat ze zich meer bewust zijn van de effecten, maar hoewel dit krachtigere redenen biedt om te stoppen, maakt het het niet gemakkelijker om te bereiken. De redenen hiervoor zijn als volgt:

1.  De voortdurende besef van de gezondheidsrisico's veroorzaakt angst, een van de omstandigheden waarin we de behoefte voelen om afkickverschijnselen te verlichten.

2.  Het werk van een arts is buitengewoon stressvol en ze zijn meestal niet in staat om de extra stress van afkickverschijnselen te verlichten tijdens het werk.

3.  Ze hebben ook de extra stress van schuldgevoelens, waarbij ze het gevoel hebben dat ze een voorbeeld moeten stellen voor de rest van de bevolking. Dit legt meer druk op hen en vergroot het gevoel van gemis.

Na een zware dag op het werk, wanneer hun stress even wordt verlicht door porno, wordt die sessie verkeerd gekoppeld aan de ervaren opluchting. Door deze verkeerde verband krijgt porno de eer voor de hele situatie en wordt het plotseling heel waardevol wanneer men stopt en door afkickverschijnselen gaat. Dit is een vorm van een af-en-toe gebruiker en geldt voor elke situatie waarin de gebruiker gedwongen wordt om langdurig te onthouden. Onder de wilskrachtmethode is de gebruiker ongelukkig omdat hij wordt beroofd en niet geniet van de vermoeidheid en slaap die volgt op een sessie. Hun gevoel van verlies wordt daardoor enorm vergroot. Echter, als je eerst de hersenspoeling en het geklaag over porno kunt verwijderen, kunnen de rustpauze en slaap nog steeds worden genoten, zelfs terwijl het lichaam verlangt naar de amine-transmitters - serotonine, norepinefrine en dopamine.

Een andere moeilijke situatie is verveling, vooral wanneer dit gepaard gaat met periodes van stress. Typische voorbeelden zijn studenten en alleenstaande ouders, waarbij het werk stressvol maar eentonig is. Tijdens een poging om te stoppen met de wilskrachtmethode heeft de alleenstaande persoon lange periodes om te klagen over hun 'verlies', wat op zijn beurt gevoelens van depressie versterkt. Ook dit kan gemakkelijk worden overwonnen als je gemoedstoestand juist is. Maak je geen zorgen dat je voortdurend wordt herinnerd aan het feit dat je bent gestopt met porno. Gebruik zulke momenten om te juichen in het feit dat je jezelf bevrijdt van het kwaadaardige monster.

Als je een positieve gemoedstoestand hebt, zullen deze pijnen momenten van plezier worden. Onthoud dat elke gebruiker, ongeacht leeftijd, geslacht, intelligentie of beroep, het gemakkelijk en plezierig kan vinden om te stoppen, **als je alle instructies volgt.**

## Primaire redenen voor falen.

Er zijn twee primaire redenen voor mislukking. De eerste is de invloed van externe stimulatie - een reclame, een online nieuwsartikel, internet browsen, enzovoort. Ze bevinden zich in een zwak moment, of worden zelfs jaloers bij het zien van intimiteit in sociale situaties. Dit onderwerp is al uitvoerig besproken. Gebruik het moment om jezelf eraan te herinneren dat er niet zoiets bestaat als één bezoek of één blik. Verheug je in het feit dat je de keten van mentale slavernij hebt doorbroken. Onthoud dat de gebruiker jaloers op je is en dat je medelijden met hen moet hebben, want zij hebben het nodig.

De andere reden is een slechte dag hebben. Maak het voor jezelf duidelijk voordat je begint, dat of je nu een gebruiker bent of niet, je goede en slechte dagen zult hebben. Het regent voor zowel de paus als de moordenaar. Het leven is relatief en je kunt geen hoogtepunten hebben zonder dieptepunten. Het probleem met de wilskrachtmethode is dat zodra de gebruiker een slechte dag heeft, ze beginnen te klagen om een bezoek aan de 'harem', wat het probleem verder bemoeilijkt. De niet-gebruiker is beter in staat om met stress en druk om te gaan, niet alleen fysiek maar ook mentaal. Als je een slechte dag hebt tijdens de terugtrekkingsperiode, neem het dan zoals het komt; herinner jezelf eraan dat er slechte dagen waren toen je verslaafd was, anders zou je niet hebben besloten te stoppen. In plaats van erover te klagen, erken het liever: *"Oké, vandaag is niet zo goed maar porno zal het niet genezen. Morgen zal beter zijn en in ieder geval heb ik een fantastische bonus, ik ben van die vreselijke verslaving af."*

Wanneer je een gebruiker van porno bent, moet je je geest afsluiten voor de negatieve aspecten van porno. Gebruikers ervaren nooit een 'wattenhoofd', ze voelen zich gewoon 'een beetje somber’. Als je te maken hebt met de onvermijdelijke problemen van het leven en je een gedachte hebt om porno te willen, ben je dan blij en opgewekt? Natuurlijk niet. Eenmaal gestopt, is de neiging om alles wat misgaat toe te schrijven aan het feit dat je gestopt bent.

Als werk je stresseert, denk je: *"In zulke situaties zou ik een sessie gehad hebben."* Dat klopt, maar wat belangrijk is om te onthouden is dat porno het probleem niet oploste, en je straft jezelf simpelweg door te treuren om denkbeeldige steunpilaren. Je creëert een onmogelijke situatie, ellendig omdat je niet naar porno kunt masturberen, terwijl je nog ellendiger zult zijn als je het wel doet. Je weet dat je de juiste beslissing hebt genomen door te stoppen, dus waarom jezelf straffen door aan je beslissing te twijfelen.

Onthoud, een positieve mentale benadering is altijd belangrijk.
