# Vervangers

Sommige voorbeelden van vervangers zijn het beperken tot pornotijdschriften, statische internetafbeeldingen, pornodieten, enz. **GEBRUIK ER GEEN VAN**. Ze maken het moeilijker, niet gemakkelijker. Als je een verlangen voelt en een vervanger gebruikt, zal het alleen het verlangen verlengen en het moeilijker maken. Eigenlijk zeg je dat je pornografie nodig hebt om de leegte te vullen. Het zal zijn alsof je toegeeft aan een kaper of een kinderlijke woede, waardoor de verlangens blijven komen en de marteling wordt verlengd. Hoe dan ook, de vervangers zullen de verlangens niet verlichten. Je behoefe is naar bepaalde neurotransmitters in de hersenen, en het enige wat het zal doen is ervoor zorgen dat je aan pornografie blijft denken. Onthoud deze punten:

1.  Er is geen vervangers voor pornografie.

2.  Je hebt geen pornografie nodig. Het is geen voedsel, het is vergif. Wanneer de verlangens komen, herinner jezelf eraan dat het de gebruikers zijn die afkickverschijnselen hebben, niet de niet-gebruikers. Zie ze voor wat ze zijn, nog een kwaad van de drug. Zie ze als de dood van een monster.

3.  Internetpornografie creëert de leegte; het vult deze niet. Hoe sneller je je brein leert dat je niet hoeft te kijken, hoe eerder je vrij zult zijn. Vermijd vooral alles wat op pornografie lijkt, zoals mannenbladen, films, romantische romans en reclames. Dit is geen gesloten houding, het is prima om over romantiek en seks te praten, maar niet over pornografie. Er is altijd een manier om te bepalen wanneer en waar je onderscheid moet maken. Het is waar dat een klein aantal gebruikers die proberen te stoppen met behulp van softcore pornografie of pornografiediëten wel slagen (vanuit hun eigen perspectief) en hun succes toeschrijven aan dergelijk gebruik. Echter, zij stoppen *ondanks* hun gebruik en niet dankzij. Het is jammer dat velen nog steeds deze maatregelen aanbevelen.

Dit is niet verrassend, want als je de valstrik van pornografie niet volledig begrijpt, klinkt een dieet of zachte vervanging heel logisch. Het is gebaseerd op de overtuiging dat wanneer je probeert te stoppen met pornografie, je twee krachtige vijanden moet verslaan:

-   De gewoonte doorbreken.

-   Verschrikkelijke lichamelijke afkickverschijnselen overleven.

Als je twee krachtige vijanden moet verslaan, is het verstandig om ze niet tegelijkertijd te bestrijden, maar één voor één. Dus de theorie gaat dat wanneer je eerst stopt met het gebruik van porno, je de frequentie vermindert tot eens per week of veilige porno gebruikt. Dan, als het gewoonte doorbroken is, verminder je geleidelijk de hoeveelheid, waardoor je elk probleem afzonderlijk aanpakt.

Dit klinkt logisch, maar is gebaseerd op onjuiste informatie. Porno is geen gewoonte, maar een dopamineverslaving, en de daadwerkelijke fysieke pijn van ontwenning is bijna onmerkbaar. Wat je probeert te bereiken bij het stoppen is het zo snel mogelijk doden van zowel de monsters in je lichaam als je brein. Alle vervangingstechnieken verlengen alleen het leven van het kleine monster, en daardoor wordt de hersenspoeling ook verlengd. EasyPeasy maakt het gemakkelijk om onmiddellijk te stoppen, door de hersenspoeling te doden vóór je laatste sessie. Het kleine monster zal snel sterven, en zelfs terwijl het sterft, zal het niet meer een probleem zijn dan toen je een gebruiker was.

Denk er eens over na, hoe kun je verslaving aan een drug genezen door dezelfde drug aan te bevelen? Er zijn veel verhalen online over mensen die gestopt zijn met het gebruik van hardcore internetporno, maar verslaafd zijn geraakt aan 'veilige' alternatieven, omdat ze zijn gevallen voor de rechtvaardigingen van hun kleine monster. Laat je niet misleiden door het feit dat de veilige porno niet verschrikkelijk is - dat was die eerste high-speed clip ook niet. Alle vervangers hebben precies dezelfde effecten als elke andere vorm van porno. Sommigen beginnen zelfs te eten, maar hoewel het lege gevoel van verlangen naar een sessie niet te onderscheiden is van honger naar voedsel, zal het ene het andere niet bevredigen. Sterker nog, als er iets is dat is ontworpen om je naar porno te laten verlangen, is het jezelf volproppen met eten. Zoals eerder uitgelegd, zullen porno-diëten en veilige porno je alleen maar in het midden van het touwtrekken brengen, waarbij de weerstand tegen verleiding zo vervelend is dat je opgelucht bent om je favoriete online harem te bezoeken.

Het voornaamste kwaad van vervangers is het verlengen van het echte probleem, hersenspoeling. Heb je een vervanger nodig voor de griep als het voorbij is? Natuurlijk niet. Door te zeggen dat je een vervanger nodig hebt voor porno, zeg je eigenlijk dat je een opoffering doet. De depressie die gepaard gaat met de wilskrachtmethode wordt veroorzaakt doordat de gebruiker gelooft dat ze een opoffering doen. Het enige wat je doet is het ene probleem vervangen door een ander. Er is geen plezier in jezelf volproppen met eten, sigaretten of alcohol. Je wordt er alleen maar dik, ongelukkig van en binnen de kortste keren ben je weer aan de drugs.

Gebruikers die af en toe porno bekijken, vinden het moeilijk om het idee los te laten dat ze worden beroofd van hun kleine beloning, zoals degenen die niet online mogen tijdens een reis, een familiebijeenkomst, enzovoort. Sommigen zeggen: "*Ik zou niet weten hoe ik moet ontspannen als het niet voor porno was.*" Dat bewijst het punt - vaak wordt de pauze niet genomen omdat de gebruiker het nodig heeft of zelfs wil, maar omdat de verslaafde - dat is wat ze zijn - wanhopig de jeuk moet krabben.

Onthoud dat de pornosessies nooit echte beloningen waren. Ze waren gelijkwaardig  aan het dragen van te strakke schoenen om het genot van het uittrekken ervan te voelen. Dus als je het gevoel hebt dat je een kleine beloning nodig hebt, laat dat dan je vervanger zijn; draag tijdens het werk schoenen of ondergoed dat een maat te klein is, en sta jezelf niet toe om ze uit te doen tot je pauze hebt, en ervaar dan het heerlijke moment van ontspanning en tevredenheid wanneer ze worden uitgedaan. Misschien vind je dat nogal stom klinken. Daarin heb je helemaal gelijk. Het kan moeilijk zijn om je voor te stellen terwijl je nog in de val zit, maar dat is wat gebruikers doen. Het is ook moeilijk voor te stellen dat je binnenkort die kleine 'beloning' niet meer nodig zult hebben en dat je binnenkort vrienden die nog steeds in de val zitten met oprecht medelijden zult bekijken en je afvraagt waarom ze het punt niet kunnen zien.

Echter, als je jezelf blijft voorliegen dat het bezoek aan de online harem een echte beloning was, of dat je een vervanging nodig hebt, zul je je beroofd en ongelukkig voelen. De kans is groot dat je uiteindelijk weer in de weerzinwekkende val trapt. 
Als je, net als huisvrouwen, leraren, artsen en andere werknemers, een echte pauze nodig hebt, zul je er nog meer van genieten omdat je niet verslaafd bent. Onthoud dat je geen vervanging nodig hebt. De pijn is een verlangen naar dopamine en zal snel verdwijnen. Laat dat je steun zijn voor de komende dagen en geniet ervan om je lichaam en geest te bevrijden van slavernij en afhankelijkheid.
