# Moet ik situaties van verleiding vermijden?

Het advies tot nu toe is rechtstreeks geweest en heeft je gevraagd om het als instructie te behandelen in plaats van als suggestie. Er zijn geldige, praktische redenen voor dit advies en die redenen zijn ondersteund door duizenden casestudies. Wat betreft de vraag of je wel of niet moet proberen verleiding te vermijden, dit is niet duidelijk te beantwoorden. Elke gebruiker zal voor zichzelf moeten beslissen. Echter, twee nuttige suggesties kunnen worden gedaan om je door dit proces heen te helpen. Het is de angst voor toekomstige afkickverschijnselen die ons doet blijven terugvallen op porno voor de rest van ons leven, en deze angst bestaat uit twee verschillende fasen.

**Fase één - “*Hoe kan ik zonder porno overleven?*"**

Deze angst is het paniekerige gevoel dat de gebruiker krijgt wanneer ze single zijn of een aseksuele, ongeïnteresseerde of niet-beschikbare partner hebben. De angst wordt niet veroorzaakt door afkickverschijnselen, maar is de psychologische angst voor afhankelijkheid, van het niet kunnen overleven zonder seks en orgasme. Het bereikt een hoogtepunt wanneer je op het punt staat te stoppen, wanneer je afkickverschijnselen op hun laagst zijn. Het is de angst voor het onbekende, het soort angst dat mensen ervaren wanneer ze leren duiken.

De duikplank is één voet hoog maar lijkt zes voet hoog te zijn. Het water is zes voet diep maar lijkt één voet diep te zijn. Het vereist moed om jezelf te lanceren, ervan overtuigd dat je je hoofd gaat breken. Het lanceren is het moeilijkste deel, als je de moed hebt om het te doen — de rest is makkelijk! Dit verklaart waarom veel sterke gebruikers nooit hebben geprobeerd te stoppen, of slechts enkele dagen kunnen volhouden wanneer ze dat wel doen. In feite zijn er enkele gebruikers op een pornodieet die, nadat ze hebben besloten te stoppen, eigenlijk snel overgaan tot hardere clips dan wanneer ze niet hadden besloten te stoppen. De beslissing veroorzaakt paniek, wat stressvol is en een signaal activeert om naar het harem te gaan. Maar nu kun je er geen meer hebben, wat leidt tot gevoelens van gemis en verergerde stress.

De trigger activeert snel wanneer de vonk overslaat en je de browser opent. Maak je geen zorgen, de paniek is slechts psychologisch. Het is de angst dat je afhankelijk bent. De prachtige waarheid is dat je dat niet bent, zelfs als je nog verslaafd bent. Raak niet in paniek en lanceer jezelf.

**Fase Twee - Langdurige Angst **

De tweede fase is langetermijn, waarbij je bang bent dat bepaalde situaties in de toekomst niet plezierig zullen zijn of dat je geen trauma aankan zonder porno. Maak je geen zorgen, als je jezelf kunt lanceren, zul je merken dat het tegenovergestelde het geval is. Het vermijden van verleiding valt zelf in twee categorieën.

1.  “*Ik zal me abonneren op een pornodieet van eens in de vier dagen. Ik zal me zelfverzekerder voelen wetende dat ik online kan gaan als het moeilijk wordt. Als ik faal, is dat prima, dan voeg ik gewoon extra dagen toe aan mijn volgende cyclus.*"

Het falingspercentage bij mensen die dit doen, is veel hoger dan bij degenen die helemaal stoppen. Dit komt voornamelijk doordat als je een moeilijk moment hebt tijdens de afkickperiode, het makkelijk is om op de browser te springen en het bovenstaande excuus te gebruiken om het harem te bezoeken. Als je de vernedering hebt van het duidelijk breken van je eigen regels als een gebroken glazen raam, ben je eerder geneigd om de verleiding te weerstaan. Hoe dan ook, de drang zou waarschijnlijk al voorbij zijn als je deze had uitgesteld. De belangrijkste reden voor het hoge falingspercentage in deze gevallen is echter dat de gebruiker zich in de eerste plaats niet helemaal toegewijd voelde om te stoppen. Onthoud de twee belangrijke aspecten om te slagen:

    -   Zekerheid.

    -   “*Is het niet fantastisch dat ik geen porno meer nodig heb?*"

In beide gevallen, waarom in hemelsnaam heb je een sessie nodig? Als je nog steeds naar je harem moet gaan, lees het boek dan opnieuw. Er klopt iets niet helemaal. Neem de tijd om het grote hersenspoelingsmonster in je hoofd volledig te doden.

2.  “*Moet ik stressvolle of sociale gelegenheden vermijden tijdens de terugtrekkingsperiode??*"

In het geval van stressvolle situaties, ja. Het heeft geen zin om onnodige druk op jezelf te leggen. In het geval van sociale evenementen, zoals bars of clubs, is het advies het tegenovergestelde. Ga meteen uit en geniet! Je hebt geen seks nodig of de voortplantingskant van seks, zelfs niet terwijl je verslaafd bent aan porno. Ga uit en verheug je erover dat je geen seks of voortplantingsseks hoeft te hebben, het zal al snel bewijzen dat het leven zoveel beter is zonder deze druk. Denk maar eens aan hoeveel beter het zal zijn als het kleine monster je heeft verlaten, samen met die behoeftige gedachten.
