# Het moment van onthulling

Meestal ervaren ex-gebruikers binnen drie weken na hun ontsnapping het moment van onthulling. De lucht lijkt helderder te worden en het is het moment waarop de hersenspoeling volledig eindigt. In plaats van tegen jezelf te zeggen dat je geen porno hoeft te kijken, besef je plotseling dat de laatste band verbroken is en dat je de rest van je leven kunt genieten zonder het ooit nog nodig te hebben. Vanaf dit punt begin je meestal ook naar gebruikers te kijken als objecten van medelijden.

Ex-gebruikers die de wilskrachtmethode gebruiken, ervaren dit moment normaal gesproken niet omdat hoewel ze blij zijn om ex-gebruikers te zijn, ze blijven geloven dat ze een opoffering doen. Hoe meer je verslaafd was, hoe fantastischer dit moment is, en het duurt een leven lang. Hoewel er veel vreugde in het leven is, is het onmogelijk om de daadwerkelijke sensatie van het ervaren ervan opnieuw te beleven. De vreugde van het niet meer hoeven kijken naar porno is anders; als je je slecht voelt en een oppepper nodig hebt, herinner jezelf eraan hoe heerlijk het is om niet meer verslaafd te zijn aan die vreselijke verslaving. Velen noemen het een van de grootste gebeurtenissen in hun leven. In de meeste gevallen vindt het moment van onthulling niet plaats na drie weken, maar na een paar dagen.

In mijn geval gebeurde het zelfs vóórdat ik mijn laatste bezoek aan het harem had afgerond. Ik weet zeker dat veel van de lezers hier, nog voordat ze het einde van de hoofdstukken hadden bereikt, iets zouden zeggen als: "*Je hoeft geen woord meer te zeggen. Ik zie alles zo duidelijk, ik weet dat ik nooit meer porn nodig zal hebben.*" Op basis van ontvangen feedback gebeurt dit vaak. Bij voorkeur, als je alle instructies volgt en de psychologie volledig begrijpt, zou het onmiddellijk met jou moeten gebeuren.

Hoewel wordt gezegd dat het ongeveer vijf dagen duurt voordat merkbare lichamelijke afkickverschijnselen verdwijnen, en ongeveer drie weken voor een ex-gebruiker om volledig vrij te zijn, kunnen dergelijke richtlijnen twee problemen veroorzaken. Het eerste probleem is dat de suggestie wordt geïmplanteerd in de gedachten van mensen dat ze tussen de vijf dagen en drie weken moeten lijden. Het tweede probleem is dat de ex-gebruiker geneigd is te denken: "*Als ik vijf dagen of drie weken kan overleven, kan ik aan het einde van die periode een echte oppepper verwachten.*"

Echter, ze kunnen vijf prettige dagen of drie prettige weken hebben, gevolgd door rampzalige dagen die iedereen treffen, die niets te maken hebben met verslaving maar worden veroorzaakt door andere factoren in ons leven. Dan ervaart onze ex-gebruiker die wacht op het moment van onthulling in plaats daarvan depressie. Het zou hun zelfvertrouwen kunnen vernietigen. Op dezelfde manier, als er geen richtlijnen waren, zou de ex-gebruiker de rest van zijn leven kunnen wachten tot er niets gebeurt. Dit is wat er gebeurt met het overgrote deel van degenen die stoppen met de wilskracht methode.

Mensen vragen vaak naar de betekenis van de vijf dagen en drie weken. Zijn het zomaar willekeurige periodes? Nee, hoewel ze geen exacte data zijn, weerspiegelen ze een verzameling van feedback uit de loop der jaren. Ongeveer vijf dagen na het stoppen is wanneer de ex-gebruiker ophoudt met het hebben van verslaving als de belangrijkste bezigheid van hun geest. De meeste ex-gebruikers ervaren een onthulling rond deze periode, meestal in stressvolle of sociale situaties waar ze eerder niet mee konden omgaan of die niet prettig waren zonder een bezoek aan het harem. Plotseling realiseer je je dat je er niet alleen van geniet of mee omgaat, maar dat de gedachte aan porno zelfs nooit bij je is opgekomen. Vanaf dat moment is het meestal een gladde zeiltocht. Dat is wanneer je weet dat je vrij bent.

Het is zowel mijn eigen ervaring als die van vele anderen die hebben geprobeerd te stoppen met behulp van de *wilskracht-methode* dat rond de periode van drie weken de meeste serieuze pogingen om te stoppen mislukken. Wat meestal gebeurt, is dat na ongeveer drie weken je het gevoel hebt dat je de drang om naar porno te kijken hebt verloren. Je moet dit aan jezelf bewijzen, dus je springt op de browser om je harem te bezoeken. Het voelt vreemd om te bevestigen dat je het overwonnen hebt. Maar in het proces heb je de DeltaFosB-waterglijbaan gesmeerd dankzij de verse dopamine-rush waar je lichaam de afgelopen drie weken naar heeft gesnakt. Zodra je klaar bent, begint de dopamine je lichaam te verlaten. Een stemmetje komt terug en zegt: "*Je hebt het niet overwonnen, je wilt er nog een.*"

Je haast je niet meteen terug omdat je niet weer verslaafd wilt raken, dus je laat een veilige periode voorbijgaan. Wanneer je de volgende keer in de verleiding komt, kun je tegen jezelf zeggen: "*Nou, ik ben niet weer verslaafd geraakt, dus er is geen kwaad in nog een keer.*" Je bent al op weg naar de glijdende helling. Het sleutelwoord is niet wachten op het moment van onthulling, maar beseffen dat zodra je de browser sluit, het voorbij is. Je hebt de zuurstoftoevoer naar je kleine monster afgesneden. Geen enkele kracht op aarde kan je ervan weerhouden om vrij te zijn, tenzij je erover blijft piekeren of wacht op onthulling. Ga genieten van het leven; pak het meteen aan. Het moment zal snel komen.
