# Het Laatste Bezoek

Na besloten te hebben over timing, ben je nu klaar om je harem voor een laatste keer te bezoeken. Voordat je dat doet, controleer de twee belangrijkste punten.

1.  Voel je je zeker van succes?

2.  Heb je een gevoel van verdoemenis en somberheid, of een gevoel van opwinding dat je iets prachtigs gaat bereiken?

Als je twijfels hebt, lees dan eerst het boek opnieuw. Onthoud dat je nooit hebt besloten om in de val van porno te stappen, maar dat de val is ontworpen om je voor het leven te onderwerpen. Om te ontsnappen, moet je de positieve beslissing nemen dat je gaat stoppen en je laatste bezoek brengt.

Onthoud, de enige reden waarom je tot nu toe dit boek hebt gelezen, is omdat je heel graag wilt ontsnappen. Maak nu die positieve beslissing, doe een plechtige belofte dat wanneer je je privé-browser sluit, of het nu gemakkelijk of moeilijk is, je nooit meer je harem zult bezoeken. Misschien ben je bezorgd dat je deze belofte al meerdere keren in het verleden hebt gedaan en toch hebt gefaald, of dat je verschrikkelijke trauma's zult moeten doorstaan. Heb geen angst, het ergste wat er kan gebeuren is dat je faalt, dus daarom heb je absoluut niets te verliezen en zoveel te winnen.

Maar stop zelfs met denken aan falen — de prachtige waarheid is dat het niet alleen belachelijk makkelijk is om te stoppen, je kunt er zelfs van genieten. Deze keer ga je EasyPeasy gebruiken! Het enige wat je hoeft te doen is de eenvoudige instructies op te volgen die zo meteen worden gegeven.

1.  Doe nu de plechtige belofte en meen het.

2.  Bekijk bewust de afbeeldingen en filmpjes op je favoriete website, let op de wanhopige pogingen van de sitebeheerders, acteurs en zelfs amateurs om de schok, nieuwigheid en bovennatuurlijke aard van hun waren te versterken, en vraag jezelf af waar het plezier is.

3.  Wanneer je uiteindelijk de browser sluit, doe dat dan niet met het gevoel van "*Ik mag nooit meer een andere online harem bezoeken*" of "*Ik mag geen andere meer bezoeken*", maar eerder met een gevoel van vrijheid, zoals "*Is het niet geweldig? Ik ben vrij! Ik ben niet langer een slaaf van porno! Ik hoef deze vieze sites nooit meer in mijn leven te bezoeken.*"

4.  Wees je ervan bewust dat er enkele dagen lang een kleine pornosaboteur in je buik zal zijn. Je merkt misschien alleen het gevoel van verlangen naar een sessie. De kleine pornomonster wordt vaak omschreven als een lichte fysieke drang naar dopamine. Strikt genomen is dit incorrect, en het is belangrijk om te begrijpen waarom. Omdat het tot drie weken duurt voordat dat kleine monster sterft, geloven ex-gebruikers dat het kleine monster blijft hunkeren na het laatste bezoek aan de online harem, en daarom moeten ze wilskracht gebruiken om de verleiding tijdens deze periode te weerstaan. Dit is niet het geval; het lichaam verlangt niet naar dopamine die door porno wordt veroorzaakt; alleen de hersenen verlangen.

Als je de komende dagen dat gevoel hebt dat je even wilt spieken, heeft je brein een eenvoudige keuze. Het kan dat gevoel begrijpen voor wat het werkelijk is — een leeg, onzeker gevoel dat begon bij het eerste bezoek aan een online pornosite en verder werd versterkt door elk volgend bezoek — en tegen jezelf zeggen: **"JOEPIE! IK BEN EEN NIET-GEBRUIKER!"**

Of je kunt gaan verlangen naar porno en voor de rest van je leven lijden. Denk er eens over na, zou dat niet ontzettend dom zijn om te doen? Om te zeggen: “*Ik wil nooit meer porno kijken*" en dan de rest van je leven te zeggen: “*Ik zou graag even willen kijken*"? Dat is wat degenen die de wilskrachtmethode gebruiken doen, en het is geen wonder dat ze zich zo ongelukkig voelen. De rest van hun leven doorbrengen in wanhoop om iets waar ze wanhopig op hopen nooit meer te hebben. Geen wonder dat zo weinig mensen slagen en de weinigen die dat wel doen zich nooit helemaal vrij voelen.

> *‘Vorm deze mentale afbeelding duidelijk in je hoofd, want het kan heel behulpzaam zijn om de kracht van externe stimulatie te overwinnen om je te verstoren. Zie jezelf rustig zitten, laat de telefoon overgaan, negeer het signaal, onbewogen door zijn opdracht. Hoewel je ervan bewust bent, maakt het je niet meer uit of gehoorzaam je het niet meer. Ook moet je in gedachten houden dat het externe signaal op zichzelf geen macht over je heeft, geen macht om je te bewegen. In het verleden heb je er gehoor aan gegeven, erop gereageerd, puur uit gewoonte. Je kunt, als je wilt, een nieuwe gewoonte vormen om niet te reageren.*’
>
> *‘ Merk ook op dat je falen om te reageren niet bestaat uit iets doen, of een inspanning leveren, of weerstaan of vechten, maar uit niets doen — ontspannen van het doen. Je ontspant gewoon, negeert het signaal, en laat de oproep onbeantwoord. Het rinkelen van de telefoon is een symbolische vergelijking voor elke andere externe stimulus waaraan je gewoonlijk controle geeft en die je nu heel bewust wilt veranderen.*'
>
> ---  Maxwell Maltz, *The New Psycho Cybernetics* hoofdstuk 12. 

Het is alleen het twijfelen en wachten dat het moeilijk maakt om te stoppen, ***dus twijfel nooit aan je beslissing*** omdat je weet dat het de juiste is. Als je begint te twijfelen, zet je jezelf in een onmogelijke situatie. Ongelukkig terwijl je verlangt naar een bezoek, maar niet in staat om er een te hebben. Wat probeer je te bereiken als je stopt met porno, ongeacht welk systeem je gebruikt? Nooit meer kijken? Nee! Veel ex-gebruikers doen dat, maar gaan de rest van hun leven door met een gevoel van gemis.

Wat is het verschil tussen gebruikers en niet-gebruikers? Niet-gebruikers hebben geen behoefte, noch verlangen om porno te kijken, ze hebben geen verlangen en hoeven geen wilskracht uit te oefenen om het niet te kijken. Dat is wat je probeert te bereiken en het is volledig binnen jouw macht om dat te doen. Je hoeft niet te wachten om te stoppen met verlangen naar porno of om een niet-gebruiker te worden, het is voltooid op het moment dat je dat laatste browservenster sluit en de dopamine-aanvoer afsluit. **JE BENT AL EEN GELUKKIGE NIET-GEBRUIKER!**

Je zult een gelukkige niet-gebruiker blijven, op voorwaarde dat:


1.  Je nooit twijfelt aan je beslissing.

2.  Je niet wacht om een niet-gebruiker te worden. Als je dat doet, zul je gewoon wachten op niets en een fobie creëren.

3.  Je probeert *niet* om niet aan porno te denken of wacht op het 'moment van onthulling’, waardoor je angst creëert.

4.  Je geen vervangers gebruikt.

5.  Je ziet alle andere gebruikers zoals ze echt zijn en hebt medelijden met hen in plaats van jaloers op hen te zijn.

Of het nu goede of slechte dagen zijn, verander je leven niet alleen omdat je gestopt bent. Als je dat doet, maak je een echte opoffering terwijl dat niet nodig is. Onthoud, je hebt het leven niet opgegeven. Je hebt niets opgegeven. Integendeel, je hebt jezelf genezen van een vreselijke ziekte en bent ontsnapt uit een verraderlijke gevangenis. Naarmate de dagen verstrijken en je gezondheid - zowel fysiek als mentaal - verbetert, zullen de hoogtepunten hoger lijken en de dieptepunten minder laag dan toen je nog een gebruiker was. Telkens wanneer je de komende dagen of de rest van je leven aan porno denkt, denk dan:

***“ JOEPIE! IK BEN EEN NIET-GEBRUIKER!"***

## Een laatste waarschuwing

Geen enkele gebruiker, als ze de kans zouden krijgen om terug te gaan naar de tijd voordat ze verslaafd raakten, met de kennis die ze nu hebben, zou ervoor kiezen om te beginnen. Tienduizenden mensen die de gewoonte met succes hebben afgezworen en vele jaren een perfect gelukkig leven leiden, raken toch weer verstrikt. Ik vertrouw erop dat dit boek je zal helpen om relatief gemakkelijk te stoppen. Maar wees gewaarschuwd, gebruikers die het gemakkelijk vinden om te stoppen, vinden het net zo gemakkelijk om weer te beginnen. **Val niet voor deze valstrik.**

Het maakt niet uit hoelang je gestopt bent of hoe zeker je bent dat je nooit meer verslaafd zult raken, maak het tot een levensregel om nooit meer naar porno te kijken om welke reden dan ook. Weersta de illusies en suggesties in de media, en onthoud hoe ze hun beeld van 'openheid' pushen door porno in de mainstream te brengen, zich er niet van bewust dat porno en dwangmatige masturbatie relaties vernietigen en het persoonlijke gevoel van welzijn voor een groot aantal mannen en steeds meer vrouwen ondermijnen.

Onthoud dat die eerste blik of bezoek niets voor je zal doen. Je zult geen afkickverschijnselen hebben om te verlichten en het zal je een rotgevoel geven. Wat het wel zal doen, is het genot van de dopamine-rush in je geest en brein brengen, en een stemmetje achter in je hoofd zal je vertellen dat je er nog een wilt. Dan heb je de keuze om een tijdje ongelukkig te zijn, of de hele smerige keten opnieuw te beginnen.





