# Help Degenen op het Zinkende Schip

Pornogebruikers raken tegenwoordig in paniek, omdat ze veranderingen voelen in de manier waarop internetporno wordt waargenomen door mannen en vrouwen. De verslavende aard van internetporno wordt steeds vaker bestudeerd en wordt nu terecht beschouwd als verschillend van traditionele porno. De moeiteloosheid en beschikbaarheid zorgen zelfs bij voorstanders van porno voor alarm. Ze voelen ook dat hun strijd voor vrije meningsuiting en gedachten wordt gekaapt door verschillende elementen. Het wilde westen van het ongecontroleerde internet maakt het vrijwel onmogelijk om leeftijdsbeperkingen op te leggen aan supernormale prikkels. Het is jammer dat dit voorlopig niet snel zal eindigen, maar honderdduizenden gebruikers stoppen, waarbij de meeste verslaafden zich bewust zijn van onderzoeken die overeenkomsten aantonen tussen porno en verslaving aan stoffen. Elke keer dat een gebruiker het zinkende schip verlaat, voelen degenen die er nog op zitten zich steeds ellendiger.

Elke gebruiker weet instinctief dat het belachelijk is om zichzelf te saboteren en tijd door te brengen voor tweedimensionale pixels, hun brein te overspoelen en zo neurale paden te ontwikkelen die een slechte seksuele prestatie garanderen. Als je nog steeds niet denkt dat het dom is, probeer dan met een pornomagazine te praten dat in het centrum van je stad staat en vraag jezelf af wat het verschil is. Slechts één. Op die manier kun je niet genieten van de warmte en intimiteit. Als je kunt stoppen met het kopen van alcohol en sigaretten elke keer dat je boodschappen doet, kun je zeker stoppen met het bezoeken van je online harem. Gebruikers kunnen geen rationele redenen vinden om naar porno te kijken, maar ze voelen zich niet zo belachelijk als andere mensen het ook doen.

Gebruikers liegen schaamteloos over hun gewoonte, niet alleen tegen onderzoekers en de mensen om hen heen, maar ook tegen zichzelf. Ze moeten wel - de hersenspoeling is essentieel als ze nog enig zelfrespect willen behouden. Ze voelen de behoefte om hun 'gewoonte' niet alleen aan *zichzelf*, maar ook aan niet-gebruikers te rechtvaardigen. Ze adverteren voortdurend de illusoire voordelen van porno op subtielere manieren.

Als een gebruiker stopt met de wilskrachtmethode, voelen ze zich nog steeds beroofd en worden ze al snel klagers. Dit bevestigt alleen maar aan andere gebruikers hoe juist ze zijn om door te blijven gaan met gebruiken. Als de ex-gebruiker erin slaagt om de gewoonte af te schoppen, zijn ze vervolgens dankbaar dat ze niet langer door het leven hoeven te gaan met zelfsabotage of energieverspilling en hebben ze geen behoefte meer om zichzelf te rechtvaardigen. Onthoud, het is angst die ervoor zorgt dat het hoofd van de gebruiker in het zand blijft steken, enkel het gedrag in twijfel trekkend bij het stoppen. Help de gebruiker door die angsten weg te nemen. Vertel hen hoe geweldig het is om niet door het leven te hoeven gaan in een gevangenis, hoe heerlijk het is om 's ochtends fit en gezond wakker te worden in plaats van energieloos en zelfhatend te zijn, hoe prachtig het is om vrij te zijn van slavernij, om ten volle van het leven te kunnen genieten en verlost te zijn van die zwarte schaduwen. Of nog beter, laat ze dit boek lezen.

Het is essentieel om een getrouwde gebruiker niet te kleineren door te suggereren dat ze opzettelijk hun relatie ruïneren of op de een of andere manier vals spelen of vies zijn. Er bestaat een veelvoorkomend misverstand dat de ex-gebruiker op dit gebied erger is. Deze opvatting heeft enige basis, maar is over het algemeen te wijten aan de wilskrachtmethode om te stoppen. Omdat de ex-gebruiker - hoewel ze de gewoonte hebben afgeleerd - nog steeds een deel van de hersenspoeling behoudt en nog steeds gelooft dat ze een opoffering hebben gebracht. Ze voelen zich kwetsbaar en hun natuurlijke verdedigingsmechanisme is om de pornogebruiker aan te vallen.

Dit zou het ego van de ex-gebruiker kunnen opkrikken, maar het helpt de gebruiker helemaal niet. Het zet hen alleen maar met de rug tegen de muur, waardoor ze zich nog ellendiger voelen en bijgevolg hun behoefte aan porno nog groter wordt. Hoewel de verandering in de houding van de medische wereld ten opzichte van internetporno de belangrijkste reden is waarom veel gebruikers stoppen, maakt dit het niet gemakkelijker om te doen. In feite maakt het stoppen veel moeilijker. De meeste gebruikers geloven tegenwoordig dat ze in de eerste plaats stoppen om gezondheidsredenen. Dit is niet helemaal waar.

Hoewel het enorme gezondheidsrisico uiteraard de belangrijkste reden is om te stoppen, hebben gebruikers jarenlang hun kracht gesaboteerd en heeft dit geen enkel verschil gemaakt. De belangrijkste reden waarom gebruikers stoppen is omdat de maatschappij langzaam maar zeker porno begint te zien zoals het is: een drugsverslaving. De houding van de samenleving verandert langzaam: veel partners zouden nu vragen stellen als je midden in de nacht op je laptop zit.

Volledige verboden op porno in sommige landen of het ontbreken van internet zijn klassieke voorbeelden van het dilemma van de reizende gebruiker. Over het algemeen zijn ze van mening dat dit hen zal helpen hun consumptie te verminderen. Het resultaat is dat ze in plaats van één of twee keer per dag, waar ze geen van beiden van zouden hebben genoten, een hele week onthouden. Tijdens deze gedwongen periode van onthouding zullen ze echter niet alleen mentaal beroofd zijn terwijl ze wachten op hun beloning, hun lichaam verlangt er ook naar. Oh, hoe kostbaar dat bezoek aan hun online harem is wanneer ze uiteindelijk worden toegelaten.

Opgelegde onthouding vermindert eigenlijk niet het gebruik, omdat de gebruiker zichzelf alleen maar meer verwent wanneer hij eindelijk alleen gelaten wordt. Het enige wat het doet is onthouden in het hoofd van de gebruiker hoe kostbaar internetporno is en hoe afhankelijk ze ervan zijn. Het meest verraderlijke aspect van deze opgelegde onthouding is het effect ervan op adolescenten. We laten de kapers van 'vrijheid van meningsuiting', de porno producenten, toe om ongelukkige tieners als doelwit te stellen om ze in de eerste plaats verslaafd te maken. Dan, in wat waarschijnlijk de meest stressvolle periode in hun leven is, wanneer ze in hun verwarde geesten het meest behoefte hebben aan porno, persen we hen af om ermee te stoppen vanwege de pijn die ze zichzelf aandoen.

Velen zijn hiertoe niet in staat en worden, zonder eigen schuld, gedwongen om voor de rest van hun leven te lijden onder een schuldcomplex. Velen slagen en zijn blij dat ze dat doen, denkend, *\"Prima. Ik zal dit nu doen en nadat het voorbij is, ben ik hoe dan ook genezen. \"* Dan komt de pijn en angst van het vinden van werk en andere volwassen worstelingen, gevolgd door de grootste 'high' van hun leven — het vinden van een baan. De pijn en angst zijn voorbij, nu ze zich veilig voelen, komt het oude triggermechanisme weer in werking. Een deel van de hersenspoeling is nog steeds aanwezig en voordat de geur van de nieuwe werklaptop verdwenen is, staat de gebruiker op de drempel van zijn favoriete online harem. De opwinding van de gelegenheid blokkeert de vieze gevoelens uit hun gedachten, ze hebben geen intentie om opnieuw verslaafd te raken, maar slechts één blik zou geen kwaad kunnen... Te laat! Ze zijn alweer verslaafd.

Het oude verlangen van het kleine monster zal opnieuw beginnen en zelfs als ze niet meteen opnieuw verslaafd raken, zal de post-high depressie hen waarschijnlijk te pakken krijgen. Het is vreemd dat hoewel heroïneverslaafden in de wet criminelen zijn, de reactie van de samenleving is om deze individuen te helpen. Laten we dezelfde houding aannemen ten opzichte van de arme pornogebruiker. Ze doen het niet omdat ze dat willen, maar omdat ze denken dat ze moeten. In tegenstelling tot de heroïneverslaafde, lijden ze meestal jarenlang onder mentale en fysieke marteling. We zeggen altijd dat een snelle dood beter is dan een langzame, dus benijd de arme pornogebruiker niet. ***Ze verdienen jouw medelijden.***
