# 简易方法

本书的目标是引导你进入一种新的思维方式。与通常的戒断方法不同——在那种方法中，你一开始就感觉像在攀登珠穆朗玛峰，接下来几周都在渴望和感到被剥夺——使用这种方法，你从一开始就会有一种欣喜的感觉，就像被治愈了一种可怕的疾病。从那以后，你在人生中走得越远，就越会回顾这段时间，惊讶自己当初为什么会使用任何色情。你会以怜悯而非羡慕的眼光看待其他色情用户。

如果你不是从未上瘾的人（为你的另一半阅读）或已经戒掉的人（或者正处于"色情节食"的禁食期），那么在你完全读完这本书之前继续使用是很重要的。这似乎是一个矛盾，这条继续对着色情自慰的指示比其他任何指示都引起更多的反对，但随着你继续阅读，你使用色情的欲望会逐渐减少。**请认真对待这条指示：过早尝试戒掉对你没有好处。**

许多人没有读完这本书，因为他们觉得自己必须放弃一些东西，有些人甚至故意每天只读一行，以推迟那个"可怕的时刻"。换个角度想想，你有什么可失去的呢？如果你读完本书后没有停止，你的状况也不会比现在更糟。这从定义上讲是帕斯卡的赌注，一个你没有什么可失去且有很大机会获得巨大收益的赌注。

顺便说一句，如果你已经几天或几周没看色情了，但不确定自己是色情用户、前用户还是非用户；或者你发现随着你吸收这些材料，你看色情的欲望已经减弱了，那么在阅读时不要用色情来自慰。事实上，你已经是一个非用户了，但我们必须让你的大脑跟上你的身体。读完这本书，你将成为一个快乐的非用户。轻松戒色与正常方法完全相反，在正常方法中，人们列出色情的诸多缺点并说：
*"如果我能坚持足够长的时间不看色情，最终欲望就会消失，我就能再次享受生活，摆脱奴役。"*
这是一种符合逻辑的做法，每天有成千上万的人用这种方法戒掉。然而，成功是非常困难的，原因如下：

**停止PMO不是真正的问题。**
每次你结束一次色情使用，你就已经停止了。在你每四天一次的色情节食的第一天，你可能有强有力的理由说*"我不想再使用色情，甚至不想再自慰了。"*所有用户都是这样的，他们的理由比你能想象的更强有力。真正的问题是第二天、第十天或第一万天，在一个软弱的时刻你会"只看一眼"，然后想要更多，突然你又上瘾了。

**对健康风险的认识会产生更多恐惧，使戒断更加困难。**
告诉一个用户色情正在摧毁他们的性能力，他们做的第一件事就是去寻找能让多巴胺飙升的东西：一支香烟、酒精，甚至打开浏览器搜索色情。

**所有戒断的理由实际上使戒断更难。**
这是由两个原因造成的。首先，我们不断被迫放弃我们的"小朋友"或某种支柱、恶习或快乐（无论用户如何看待它）。其次，它们造成了一种"盲点"。我们不是因为应该停止的理由而自慰。真正的问题是，我们为什么想要或需要这样做？

使用轻松戒色方法，我们（最初）忘记我们想停止的理由，面对色情问题，问自己以下问题：

1.  色情对我有什么作用？

2.  我真的在享受吗？

3.  我真的需要在一生中不断破坏我的思想和身体吗？

美丽的真相是*所有色情*对你完全没有任何作用。让我说得很清楚，这不是说作为用户的缺点超过了优点，而是观看色情根本***没有***任何优点。

大多数用户发现有必要为他们使用色情找理由，但他们提出的理由都是谬论和幻觉。

首先，我们将消除这些谬论和幻觉。事实上，你很快就会意识到根本没有什么可放弃的。不仅如此，成为非PMO者还有奇妙的、积极的收获，幸福感和快乐只是这些收获中的两个。一旦消除了没有色情生活就永远不会那么愉快的幻觉——意识到没有色情生活不仅同样愉快，而且无限美好——一旦消除了被剥夺或错过什么的感觉，我们将回过头来重新考虑增强的幸福感和快乐——以及戒掉色情的数十个其他理由。这些认识将成为积极的额外助力，帮助你实现你真正渴望的：享受你摆脱色情成瘾奴役的自由生活！
