# 警惕减量

许多用户诉诸减少用量，将其作为迈向停止的跳板，或者作为控制小怪物的尝试。许多人建议减量或"色情节食"作为一种振作方式。将减量作为停止的跳板是***致命的***。正是这些减量的尝试让我们被困住余生。通常，减量发生在停止尝试失败之后。在禁欲几个小时或几天之后，用户会说这样的话：

"*我无法想象在不访问我的网上后宫的情况下入睡，所以从现在起我每四天只使用一次色情，或者清除我收藏的'糟糕色情'。如果我能遵循这个色情节食，我可以保持在这个水平或进一步减少。*"

现在，某些可怕的事情发生了：

1.  他们陷入了最糟糕的处境，仍然对网络色情上瘾，不仅在身体上，而且在心理上让怪物保持活跃。

2.  生活在等待下一次使用的煎熬中。

3.  在减量之前，每当他们想访问后宫时，就会打开浏览器，至少部分地缓解戒断痛苦。现在除了正常的生活压力外，他们让自己在大部分生活时间里承受着戒断痛苦，这让他们更加痛苦和易怒。

4.  在沉溺其中时，他们既没有享受大多数使用，也没有意识到自己在使用一种超常刺激。这是自动的，唯一真正被"享受"的后宫访问是在禁欲一段时间之后。现在他们为每次后宫访问多等待一个小时，他们"享受"每一次。等待的时间越长，每次使用似乎变得越"愉快"，因为使用中的"享受"不是使用本身——而是结束由渴望引起的焦虑——无论是轻微的身体渴望还是心理上的郁闷。受苦越久，每次使用就显得越"愉快"。

停止的主要困难不是神经学成瘾，那很容易。用户在各种场合都会毫无困难地停止——亲人去世、家庭或工作事务等。他们可能会去，比如说，十天没有访问，而这并不困扰他们。但如果他们在同样的十天里本可以访问色情，他们会抓狂的。

许多用户会在工作日获得机会但选择克制，或者他们会经过维多利亚的秘密或游泳池等地方而没有太多不便。许多人在不得不暂时睡在沙发上为访客腾地方，或者自己去拜访时会克制。即使在脱衣舞酒吧或天体海滩也没有发生骚乱。用户几乎很乐意由某人或某事说他们不能观看色情。事实上，想要戒掉的用户会从长时间不访问后宫中得到一种秘密的快乐，给了他们也许某天永远不再需要它的希望。

停止时真正的问题是洗脑——一种认为网络色情是某种支撑或奖励、没有它生活将永远不同的幻觉。减量非但不会让你对网络色情失去兴趣，反而只会让你感到不安和痛苦，让你相信这个地球上最珍贵的东西是你错过的新片段，没有看到它你永远不会快乐。

没有什么比那个一直试图减量的用户更可悲的了，他们受到一种错觉的折磨，认为色情看得越少，就越不想访问自己的网上后宫。事实恰恰相反——看的色情越少，他们就越长时间承受戒断痛苦，也越"享受"缓解它的宽慰。然而，他们会注意到自己最喜欢的类型不再那么令人满足了。但这不会阻止他们：如果视频网站只专注于一个明星或一种类型，没有任何用户会访问超过一次。

难以置信？自制力最糟糕的时刻是什么？等待四天然后达到高潮。那么，对于大多数采取四天色情节食的用户来说，最珍贵的时刻是什么？没错，正是等待四天后的同一次高潮！你真的相信你是为了享受性高潮而自慰，还是更理性的解释是，你需要在一种被授权的幻觉下缓解戒断痛苦？

在你熄灭最后一次使用之前，消除洗脑对于消除关于色情的幻觉是必不可少的。除非你在关闭那个窗口之前已经消除了你享受它的幻觉，否则之后你无法在不再次上钩的情况下证明这一点。当你徘徊在书签和保存的图片上时，问问自己这个动作有什么光荣之处。也许你认为只有某些片段是有品味的，比如习惯性或喜爱主题的片段。如果是这样，为什么还要看其他视频或主题？因为你养成了习惯？为什么有人会习惯性地损害自己的大脑并自我浪费？一个月后什么都不会不同，那么为什么一个色情片段会有所不同？

你可以自己测试这一点。找出上个月那个热门片段，证明它是不同的。然后，设置一个提醒，在一个月没有色情之后观看同一个片段。它会像上个月几乎一样令人满足。同一个片段在你在社交活动中被拒绝或被潜在伴侣考验之后会有所不同。原因是，如果小怪物仍然不满足，成瘾者就永远无法完全快乐。

满足从何而来？只不过是如果他们不能缓解戒断症状就会感到痛苦。观看色情和不观看之间的差异就是快乐和痛苦之间的差异。这就是为什么网络色情似乎更好的原因。那些早上第一件事就上网找色情的用户，无论看不看都是痛苦的。

减量不仅不起作用，而且是最糟糕的折磨形式。它不起作用，因为最初用户希望通过越来越少地养成这个习惯，能减少观看色情的欲望。这不是习惯，而是成瘾。任何成瘾的本质都是渴望越来越多，而不是越来越少。因此，为了减量，用户必须在余生中运用意志力和自律。所以，减量意味着永远需要意志力和自律。停止要容易得多，也不那么痛苦；字面上有数以万计的减量失败案例。

停止的问题不是多巴胺成瘾，那很容易应对。而是错误地相信色情给你带来快乐，这种信念最初是由我们开始使用前收到的洗脑带来的，并被实际的成瘾进一步强化。减量所做的只是进一步强化这种谬误，以至于色情完全主导了他们的生活，并让他们相信地球上最珍贵的东西是他们的成瘾。

少数成功案例是通过相对较短的减量期，然后"一刀切"实现的。这些用户是尽管减量还是停止了，而不是因为减量才停止的。减量所做的只是延长了痛苦，失败的尝试让用户变成了神经质，并更加相信自己终身上钩了。这通常足以让他们退缩回到网上后宫寻求快乐和拐杖，或者至少在下次尝试之前再坚持一段时间。

然而，减量确实有助于说明色情的无意义，清楚地表明在禁欲一段时间后访问后宫并不令人愉快。你必须把头撞向砖墙（承受戒断痛苦），才能在停止时让它变得舒服。因此，选择是：

1.  终身减量，承受自我施加的折磨，而这无论如何你都无法做到。

2.  终身越来越折磨自己，这是毫无意义的。

3.  善待自己，完全切断色情。

减量所展示的另一个方面是，偶尔或临时的后宫访问根本不存在。网络色情是一种连锁反应，将持续你的余生，除非你做出积极的努力来打破它。

**记住：减量只会把你拖垮。**
