# 轻松停止的方法

本章包含关于轻松停止色情的说明。只要你遵循说明，你会发现停止的过程从相对容易到令人愉快！只要遵循以下说明，停止色情就变得极其容易。你只需要做两件事：

1.  下定决心，永远不再看色情。

2.  不要为此消沉。要为此欢欣鼓舞。

你可能会问：*"为什么还需要这本书的其余部分？为什么你不一开始就这么说？"* 答案是，你最终会为此消沉，进而改变自己的决定。你之前可能已经这样做过很多次了。

如前所述，色情是一个微妙而险恶的陷阱。停止的主要问题不是多巴胺成瘾——那当然是个问题，但不是主要问题——而是洗脑。因此，有必要首先打破所有的神话和错觉。了解你的敌人，知道他们的战术，你就能轻松打败他们。在我终于逃脱之前，我曾花了大量时间在试图戒除时遭受严重的抑郁折磨，而逃脱之后，我直接归零，没有经历任何痛苦时刻。即使在戒断期间也是一种享受，此后我再也没有感受到丝毫渴望。恰恰相反，这是我生命中发生过的最美好的事情之一。

我最后一次尝试与以往不同。像现在所有的用户一样，这个问题在我脑海中已经经过了认真的思考。在此之前，每次失败后，我习惯于用"下次会更容易"来安慰自己。我从未想到过我必须这样度过余生。这个念头让我充满恐惧，我开始对这个问题进行深入思考。

我没有下意识地打开浏览器，而是分析了自己的感受，并确认了我已知的事情。我并不享受色情，觉得它肮脏恶心。我开始观察生活在世界其他地方的非用户，或者那些从未接触过视频网站的老年人。直到那时，我一直认为非用户是软弱、不善交际、挑剔的人。然而，仔细观察他们时，他们看起来——如果有什么区别的话——更强壮、更从容。他们似乎能够应对生活的压力，并且似乎比色情用户更享受社交活动。他们确实比色情用户更有活力和热情。

我开始与前用户交谈。在此之前，我一直认为他们是因为健康或宗教原因被迫放弃的，并且总是秘密地渴望着去网上后宫。有几个人确实说：*"偶尔会有渴望，但它们太少太偶然，不值得担心。"* 大多数人却说：*"想念它？你一定是在开玩笑！生活从未如此美好！"* 即使是失败，对他们来说也是向前的跌倒——他们不谴责自己，而是无条件地接受。就像一位教练会接受一位真正优秀球员的失误一样。与前用户交谈打破了我脑海中一直存在的另一个神话，即我内心存在某种天生的软弱，直到我意识到所有人都经历过这种私密的噩梦。

基本上，我对自己说：*"无数的人现在正在停止，并过着完全幸福的生活，我在开始之前并不需要它，而且我记得当时还需要努力适应这种污秽。所以我现在为什么需要它？"* 无论如何，我并不享受色情，厌恶整个肮脏的仪式，不想将余生奴役于这种令人厌恶的成瘾。然后我对自己说：

*"不管你喜不喜欢，你已经完成了最后一次。"*

从那一刻起，我就知道我再也不会有另一次了。我没有期望这会容易，恰恰相反。我完全相信我已经签约进行数月的严重抑郁，并将在余生中偶尔感受渴望。然而，从一开始就是绝对的幸福。

我花了很长时间才弄清楚为什么这么容易，以及为什么我没有遭受那些可怕的戒断痛苦。原因是它们根本不存在，是怀疑和不确定性制造了痛苦。美好的真相是***停止色情很容易。*** 只有优柔寡断和消沉才会让它变得困难。即使在成瘾的情况下，用户在某些时候也可以在相对较长的时间内不看色情。只有当你想要但得不到时，你才会受苦。

因此，让停止变得容易的关键是使停止确定且最终。不是希望，而是*知道*你已经摆脱了它，做出了决定。永远不要怀疑或质疑它，事实上，恰恰相反——始终欢欣鼓舞！如果你从一开始就能确定，这将会很容易。但你怎么能从一开始就确定呢？这就是为什么这本书的其余部分是必要的。在开始之前，有几个关键点需要在你的脑海中明确：

1.  认识到你能做到。你与众不同的地方什么都没有，唯一能让你看色情的人是你自己。不是那些明星，他们在最疯狂的梦中也从未想过自己被用来降低他人的男子气概。

2.  根本没有什么可以放弃的。恰恰相反，有巨大的积极收益。不仅是你会更健康、更富裕，还有在好时光你会更享受，在坏时光你会不那么悲惨。

3.  根本没有"只是看一眼"或"只访问一次"这回事。色情是药物成瘾，是一个连锁反应，通过抱怨偶尔的访问，你只会不必要地惩罚自己。

4.  将色情视为药物成瘾，而不是可能伤害你的"男孩本性"习惯。面对现实：不管你喜不喜欢，**你已经患上了这种病。** 因为你把头埋在沙子里，它不会消失。记住，像所有使人衰弱的疾病一样，它不仅持续终生，而且呈指数级恶化。现在是治愈它最容易的时候。

5.  将疾病——神经学上的成瘾——与作为用户或非用户的心态分开。所有的用户，如果有机会回到他们成瘾之前的时刻，都会抓住这个机会。今天你就有这个机会！甚至不要把它想成"放弃"。

一旦你做出了最终决定，认为你已经完成了最后一次访问，你就已经是一个非用户了。用户是那些可怜的人，一生中用色情摧毁自己。非用户是不这样做的人。一旦你做出了最终决定，你就已经实现了目标。为这个事实欢欣鼓舞，不要坐着消沉等待化学成瘾消失。立即走出去，享受生活。即使在成瘾时生活也是美好的，当你不再成瘾时，每一天都会变得更加美好。

让戒除变得容易的关键是确定你能在戒断期——最多三周——内完全成功地戒断。如果你的心态正确，你会发现这极其容易。

到了这个阶段，如果你在开头时按照要求敞开了心扉，你就已经决定要逃脱了。你现在应该有一种兴奋的感觉，就像一只在皮带上挣扎的狗，迫不及待地要打破DeltaFosB色情水滑梯。如果你有一种末日和阴郁的感觉，那将是出于以下原因之一：

1.  某些东西在你脑海中没有凝结。重新阅读上面的五点，问自己是否相信它们是真的。如果你对任何一点有疑问，重新阅读本书的相关章节。

2.  你害怕失败本身。不用担心，继续阅读，你会成功的。整个网络色情的生意是一个巨大规模的骗局。聪明的人会上当受骗，但只有傻瓜，一旦发现骗局后，还继续自欺欺人。

3.  你同意一切，但仍然感到悲惨。不要这样！睁开眼睛，有美好的事情正在发生。你即将逃离监狱，以正确的心态开始是至关重要的：*"我是一个非用户，这太美妙了！"*

现在所需要做的就是在戒断期内保持你的这种心态，接下来的几章将处理具体的要点，使你能够做到这一点。戒断期之后，你不必再那样思考，你会自动地这样思考。你生命中唯一的谜将是你为什么之前没有看到这一点。然而，有两个重要的警告。

-   推迟你的最后一次访问计划，直到你读完整本书。

-   前面已经多次提到了最多三周的戒断期，这可能会造成误解。首先，你可能下意识地认为你必须忍受三周。你不必。其次，避免陷入"不知为何我必须坚持三周，然后我就会没事"的陷阱。三周后实际上不会发生任何神奇的事情，你不会突然感觉像一个非用户，因为非用户实际上和用户的感受并没有什么不同。如果你在三周内为停止而消沉，那么很可能你在三周后仍然会为此消沉。总结一下，如果你现在就能对自己说*"我永远不会再使用了，这不是太美妙了吗？"*，三周后所有的诱惑都会消失。而如果你说*"如果我能在没有色情的情况下熬过这三周……"*，你会在三周结束后迫切地想要去网上后宫。

这样想——你的大脑想要维持现状，所以如果你相信戒除时你正在失去某些好的东西，你显然会感觉很糟糕。如果你的大脑不相信，你就不可能强迫自己以某种方式感受。这就是为什么要费心消除色情给你任何东西的幻觉是重要的。这就是你知道你没有牺牲任何东西的方式。

性功能障碍与你的大脑和心态有很大关系。网络色情重新连接你大脑的奖励回路，给你的心灵一种"怀疑"的心态。这种自我怀疑无疑会导致性功能障碍。上半身充满渴望，但下半身毫无反应，这是对你心态最糟糕的事情。性欲与浪漫齐头并进是你可以拥有到死的青春活力。通过戒除，你会保持高概率，但这不是唯一或主要的收获。这是你从奴役中获得的自由！
