# 反馈

这场战争不是针对用户，而是针对色情行业的陷阱，发动这场战争的简单原因是我享受这样做。每次听到有用户从监狱中逃脱，我都会感到无比的喜悦。但这种喜悦并非没有相当大的挫败感，主要是由两类色情用户造成的。尽管在前一章有警告，我仍不断对那些觉得容易戒除、后来却再次上瘾，发现下次无法成功的人的数量感到惊讶。

这就像看到有人淹没在沼泽里，快要沉下去了。你帮助他们脱身，他们心存感激，但六个月后却一头扎回沼泽里。那些容易戒除又重新开始的用户构成了一个特殊的问题，但当你获得自由时***请、请、不要犯同样的错误。*** 人们认为这些人重新开始是因为他们仍然上瘾，思念多巴胺。事实上，他们发现戒除太容易了，以至于失去了对色情的恐惧。他们认为："*我可以偶尔来一次，即使我再次上瘾，我也会发现容易戒除。*"

恐怕这行不通，因为戒除色情容易，但控制成瘾却是不可能的。停止色情的唯一必要条件就是不使用它。

人们通常回归色情是因为误解了轻松戒除法中"轻松"的含义。

想象一个人坐在一个冰冷房间的冰冷混凝土地板上。在他们对面的墙上，有一扇窗户展示着外面完美的春天——树木轻轻摇曳，鸟儿在啁啾——旁边就是一扇未锁的门。

从那个冰冷的房间里走出去需要任何意志力吗？不需要！逃离比留下来更难吗？当然不！（事实上，因为身体在移动，逃离稍微容易一点）。如果不是被欺骗的话，有谁会神志清醒地把自己置于那种处境，造成自己数月或数年的挫败感？

轻松戒除法拉开窗帘，让用户清楚地看到外面，消除关于外面有多可怕以及用户在房间里有多舒适的**幻觉**。

另一类令人沮丧的用户是那些太害怕而不敢尝试停止的人，或者当他们尝试时，发现这是一场巨大的挣扎。主要的困难似乎如下。

**失败的恐惧。**

:   失败并不丢人，但不尝试纯粹是愚蠢。这样想，你没有什么可躲避的。可能发生的最坏情况是失败，那样你并不比现在更糟糕。想想成功会是多么美好。如果你不做尝试，你已经保证了失败。

**痛苦和悲惨的恐惧。**

:   不用担心，只要想想：如果你再也不看色情，会发生什么可怕的事情？绝对没有。如果你继续看，可怕的事情*会*发生；重读关于帕斯卡赌注的笔记。无论如何，恐慌是由多巴胺引起的，很快就会消散。最大的收获是摆脱那种恐惧。你真的相信用户愿意忍受勃起功能衰退、性表现不可靠，或他们从色情中获得的虚幻乐趣吗？如果你感到恐慌，深呼吸会有帮助。如果你和其他人在一起，他们让你感到不舒服，就逃离他们，去车库、空办公室或其他地方。

    如果你想哭，不要感到羞耻。哭泣是自然缓解紧张的方式。从来没有人哭过之后不感觉好些的。我们对年轻男性做的一件可怕的事情是让他们被训练成不哭。你可以看到他们试图忍住眼泪，但看着那紧咬的下巴。我们教会自己不显示情感，但我们本不该把情感藏在心里。可以喊叫、大喊或发脾气。踢什么东西。把你的挣扎看作一场你不可能输的拳击赛。没有人能阻止时间，每过一刻，你体内的那个小怪物就在死去。享受你必然到来的胜利。

**不遵循说明。**

:   令人难以置信的是，一些用户说这个方法对他们不起作用。然后他们描述了他们如何不仅忽略了一个说明，而且几乎所有的说明都被忽略了。为了清晰起见，这些说明在本章末尾被汇总为一份清单。

**误解说明。**

:   主要问题似乎是这些：

    "*我无法停止想色情。*"

    :   当然不能，如果你试图这样做，你会创造一种恐惧症，变得痛苦。这就像晚上试图入睡：你越努力，就越难。如果你有90%的时间都在想色情，这没关系，重要的是你在想什么。如果你在想"*哦，我喜欢看色情*"或"*我什么时候才能自由？*"，你会很痛苦。如果你反而在想"*耶！我自由了！*"，你会很快乐。

    "*小色情怪物什么时候会死？*"

    :   多巴胺潮水很快离开你的身体，但无法判断你的身体何时停止遭受多巴胺戒断的轻微身体感觉。那种空虚、不安全的感觉与正常的饥饿、沮丧或压力完全相同。色情所做的只是提高这种感觉的程度。这就是为什么用意志力方法戒除的用户永远不能确定自己是否已经戒掉了，即使在身体停止遭受多巴胺戒断之后。如果遭受正常的饥饿或压力，他们的大脑仍然告诉他们这是要求他们享有权利的访问的正当理由。关键是你不必等待渴望消失，因为它如此轻微，我们甚至不知道它的存在，只知道它是一种想要的感觉。当你离开牙医时，你会等着颌骨停止疼痛吗？当然不会，你继续生活。即使你的颌骨还在疼痛，你也会感到高兴。

        不要等待戒断离开，因为你会通过不断问自己"*这要多久？如果我感觉没有任何不同，我真的自由了吗？*"来产生怀疑。恐惧本身就是痛苦，因此等待戒除后生活变得更好会产生怀疑。除非你害怕戒断，否则戒断是察觉不到的，而神经学的指数级改善是缓慢的，所以如果你等待感受到不同，会感觉什么都没有发生，产生怀疑。

    *"'顿悟时刻'还没有到来。"*

    :   如果你在等待它，你只是在制造另一种恐惧症。我曾经用意志力方法停止了三周。和一位老朋友聊天时，他问我进展如何。
        "*我已经撑了三周了*"，我回答。
        他问道："*你是什么意思，你撑了三周？*"
        我解释道："*我已经三周没有看色情了。*"
        他说："*你打算怎么做？撑完你的余生？你在等什么，你已经做到了。你是非用户了。*"

        我想："*他完全正确，我在等什么？*" 不幸的是，由于对陷阱缺乏理解，我很快又回去了，但这一点被记住了。当你关闭浏览器时，你就成为了非用户。重要的是从一开始就成为一个快乐的非用户。

    "*我仍然渴望色情。*"

    :   那你就是非常愚蠢了。你怎么能声称想要成为非用户，然后又说你想要色情呢？这是矛盾的。如果你说你想要色情，你就是在说你想成为用户。非用户不想访问那些令人厌恶的视频网站。你已经知道自己想成为什么，所以不要折磨自己了。

    "*我已经退出生活了。*"

    :   为什么？你所要做的就是停止摧残自己，开始充满活力。你根本不必停止生活。就是这么简单，在接下来的几天里，你的生活会有轻微的创伤。你的身体将遭受几乎察觉不到的来自对多巴胺冲击的需求和索取的轻微烦扰。现在，记住这一点：你并不比原来更糟糕。这是你一生中一直在遭受的，每次你睡觉、在教堂、超市或图书馆时。当你是用户时，这似乎并没有困扰你，如果你不停止，你将在余生中继续遭受这种痛苦。

        色情和性高潮不会创造场合，而是剥夺你的场合。即使当你的身体仍在渴望多巴胺时，餐饮和社交场合也是美妙的。生活是美妙的——去参加社交活动，即使那里有裸体舞者。记住你不是在被剥夺，他们才是。他们每一个人都希望自己能处于你的位置，如果他们知道的话。享受成为女主角和关注中心的感觉。戒除色情是一个精彩的谈资，享受一个他们无法分享的秘密喜悦。你的朋友和同龄人会惊讶地看到曾经内向疲惫的你，现在变得快乐开朗。你从一开始就会享受生活；没有必要羡慕派对上的把妹达人，他们会羡慕你——如果他们知道的话。

    "*我很悲惨和烦躁。*"

    :   这是没有遵循说明的表现。找出是哪一条说明。有些人理解并相信所写的一切，但仍然从一种末日和阴郁的感觉开始，好像有什么可怕的事情正在发生。你不仅在做你想做的事，而且是地球上每个用户都想做的事。无论使用哪种停止方法，前用户都在试图达到某种心态，因此每一个与色情相关的想法都被"*耶！我自由了！*"所打断。如果这是你的目标，为什么要等待？就以那种心态开始，永远不要失去它。没有其他选择。

    "*我有过一周/一个月/六个月的好时光，但我又回到了陷阱里。*"

    :   记住，恐惧本身就是痛苦。屈服于痛苦会产生更多的恐惧，滋养已经减弱的小怪物，并成功地让非用户认为自己终身上瘾。在现实中，他们对洗脑的概念并没有改变，但他们给了多巴胺思考过程。这在定义上是向前跌倒，但也是没有遵循说明的表现。了解下面是哪一条，并为此感到高兴。

## 清单

如果你遵循这些说明，你不可能失败：

1.  郑重发誓，你永远不会再上网访问你的后宫，*也不会*满足于静态图片，*也不会*与色情图像和解，*也不会*接触任何包含超常刺激的内容，并坚守你的誓言。

2.  把这一点弄清楚：没有任何东西需要放弃。这不是说你作为一个非色情、手淫、性高潮（PMO）者会过得更好（你一直都知道这一点）；也不是说虽然没有理性理由让你进行PMO，但你从中得到一些乐趣或依靠，否则你就不会这样做。所要说的是，***PMO中没有真正的乐趣或依靠。*** 这只是一种幻觉，就像撞头来获得停止时的乐趣一样。

3.  不存在根深蒂固的PMO者。你只是数亿落入这个微妙陷阱的人之一。就像曾经认为自己无法逃脱的数百万其他前PMO者一样，你已经逃脱了。

4.  如果在你生命中的任何时候，你要权衡PMO的利弊，压倒性的结论将始终是"*停止做。你是个傻瓜！*"没有任何东西会改变这一点。一直如此，永远如此。做出你知道是正确的决定后，不要通过怀疑来折磨自己。帕斯卡赌注完美地适用于PMO，没有损失的可能，有很高的获得机会，以及避免损失的高可能性。

5.  不要试图不去想色情，也不要担心你一直在想它。每当你想到它时，无论是今天、明天还是余生，都想**"耶！我是非PMO者了！"**

6.  **不要**使用任何形式的替代品。**不要**把笔记本电脑放在睡觉旁边来挑战自己。**不要**避开戏剧、电影或杂志。**不要**仅仅因为你停止了就以任何方式改变你的生活方式。如果你遵循上述说明，你很快就会经历"顿悟时刻"，但是：

7.  不要等待"顿悟时刻"的到来。只需继续你的生活，享受高潮，应对低谷。你会发现很快这一时刻就会到来。
