# Maxaan ka tanaasulayaa?

**Gabi ahaan, waxba!** Porn waxay u adagtahay in la iska daayo waayo cabsida in nalaga qaadaayo raaxadeena ama taageerteena. Cabsida laga qabo in gaar xaaladaha wanaagsan aysan weligooda dib isku ahaan doonin. Cabsida in lagaaga tagaayo adigoosan la qabsan karin xaaladaha walbaarka leh. Si kale haddii loo dhigo, waa saameynta maskax-xadashada oo nagu khiyaanaysa inaan aamino in galmada - oo orgasm-ka la socoto  - ay tahay wax oo looga baahan yahay bini’aadamaha dhamaantood. Xataa inta ka sii dheer, waa aaminsanaanta inay jiraan wax oo dabeecadda porn ku jira oo aan u baahanahay, iyo in markaan joojino isticmaalka aan nafteena diido doonno oo aan maran abuurayno. 

Tan maskaxdaada ku caddey: **Porn maranka ma buuxiso,** ***mid ayay abuurtaa!***

Jirkeena waxay yihiin waxyaabaha oo meeraha ugu casrisan. Haddii aad aaminsan tahay naqshada caqli leh, xulashada dabiiciga ah, ama labadaba isku-darkood, jirirkeena kumanaan jeer ay ka waxtar badan yihiin bini'aadamka naftigiisa! Ma awoodno inaan abuurno unugga nool ugu yar ama mucjisooyinka aragtiga, taranka iyo nidaamyada kala duwan oo isku xiran oo ka jira jirkeena ama maskaxdeena. Haddii Abuuraha ama Habsocotkaan uu noogu talo galay inaan u xamilno kicinta xaf-dhaafsan oo aan caadiga ahayn, waxa nala siin lahaayay nidaamya abaal-marineed oo kala duwan. Jirkeena waxa la siiyay aalado digniin ah kuwaana waan iska indhatirnaa annaga oo khatar nagu ah.

## Wax oo la tanaasulo ma jiro

Mar haddii aad shaydaanka yar jirkaaga ka saartid oo aad maskax-xadashada (shaydaanka weyn) maskaxdaada ka saartid, ma rabayso inaad midba marar badan siigaysato ama aad porn u isticmaasho. Waxaa jira wax badan oo la yaqaano iyo waxyaalo oo la aqoonin markii loo fiiriyo balwadda porn, iygoo qaar badan oo bulshada caafimaadka ka mid ah ay fikrad ka qabin su'aasha ama go'aaminta qof inuu porn ula qabatimay. Calaamado badan oo la warbixiyo oo porn keento ayaa si khaldan loogu calaamadeeyaa sababo kale. Ma aha in isticmaalayaasha ay guud ahaan u yihiin dad oo doqon ah, waa kaliya inay darxumeysan yihiin porn la'aanteed. Waxay ku xayiran yihiin inta u dhaxaysa shaydaanka iyo badda oo aada u buluugsan, iyagoo ka-foogaadaan iyo darxumeysan waayo inaysan porn isticmaali karin, ama darxumeysan waayo ay yihiin dembileyaal waxayna sidaas darteed u bilaabayaan inay naftooda quudhsadaan. Markay helaan calaamado sida xanuunka dhabarka hoose ama cillada galmada, maskaxdooda ayaa ku xayiran inta ka dhaxaysa inay aqbalaan mas'uuliyadda joojinta porn ama inay dhinaca kale u jeestaan.

Halkaan waa tusaale kale oo sigaar cabbayaasha: Dhammaanteena waxaan aragnay sigaar cabayaal kuwaas oo soo saara marmarsiyo si ay ugu dhuuntaan si ay u cabaan, waxaanan aragnaa qabatin dhab ah ee ficil ahaan. balwadlayaasha tan ma sameyaan si ay u baashaalaan, laakin waxay u sameyaan waayo ay darxumeysan yihiin la'aanteed.

Qaar badan, khibradda galmada ugu horeysay orgasm bay ku dhammaatay, marka sidaas ay u heleen aminsanaanta inaysan galmada ku raaxaysan karin mid la'aantiis. Nimankuna, porn waxaa loo suuq-geeyaa inay gargaar xagga galmada ay tahay, mararka qaarkooduna sida waxbarashada kalsoonida inta falka lagu jira. Tan waa wax aan jirin, saameynta kicinta xad-dhaafsan oo aan caadiga ahayn waxay kaliya ku guulaysataa inay hoos u dejiso.

Ma aha kaliya inaysan jirin wax oo la tanaasuli doono, laakin waxaa sidoo kale jira faa’iidooyin waaweyn oo la haysan karo. Markay isticmaalayaashu ka milicsadaan joojinta, waxay u janjeeraan inay diirad saaraan caafimaadka iyo ragnimadda. Kuwaan waa sababo sax ah oo muhiim ah, laakiin aniga shaqsi ahaan waxaan aaminsanahay in guulaha ugu weyn ay nafsiyeed yihiin:

-   So laabashada kalsoonidaada iyo gesinimadaa.

-   Xornimada addoonsiga.

-   Mar dambe aan lahaan doonin hadhad madow xun oo maskaxdaada ku jirta oo aad naftaada quudhsato.

## Maran, maran, maranka quruxda badan!

Ka fikir adigoo wajigaaga nabar ku soo baxay, oo aad markaas farmashiistaha u tagtay, oo uu lacag la'aan kugu soo siiyay boomaato oo la mariyo si aad u tijaabiso. Boomaatada ayaad ismarisay iyo nabarkuna isla markiiba uu baaba'ay. Toddobaad ka dib nabarka wuu soo laabtaa. Marka farmashiistaha ayaad dib ugu noqotaa iyo waxaad weydisaa inay boomaato ka badan ay hayaan. Farmashiistaha wuxuu dhahaa: *“Hubaal; tubbada iska hayso, waxaa laga yaabaa inaad hadhow u baahato."*

Boomaatada ayaad marsataa, iyo nabarka mar kale ay baaba'daa. Laakiin mar kasta oo uu nabarka soo noqdo, wuu sii weynaadaa iyo wuu sii xanuunayaa, iyadoo muddada u dhaxaysaa marmarinta ay sii yaryaraanayso. Ugu dambeyntii, nabarka wuxuu daboolaa wajigaaga oo dhan wuxuuna leeyahay xanuun oo aad u cadaabsan, wuxuuna soo noqonayaa nus saac kasta. Waa ogtahay in boomaatada ay si ku meel gaar ah uga saari doonto, laakiin hadda aad ayaad u walwalsan tahay. Nabarka, ugu dambeyntii, jirkaaga oo dhan muu ku faafi doona? Muddada u dhaxaysuna gabi ahaanba may u baabi'i doontaa? Markaas, waxaad u tagtaa dhakhtarkaaga mana daaweyn karaan, markaas waxaad isku daydaa waxyaabo kale, laakiin wax ma jiraan oo kaa caawinaysa markii boomaatada laga reebo.

Halkaan markay marayso, waxaad si buuxda ugu tiirsan tahay boomaatada, adigoo waligaaga guriga ka bixin adigoon hubinin inaad tubbo haysato. Haddii aad dibadda u baxdo, waxaad hubisaa inaad qaadato dhowr tubboyin. Ka sokow walwalkaaga oo ku saabsan caafimaadkaaga, farmashiistaha wuxuu bilaabay inuu boqol doolar kaaga qaato tubbo walbo. Mana haysatid wax kale oo aan ahayn inaad lacagta bixiso.

Markaas waxaad la kulantaa maqaal oo ka hadlaya arrintaan, iyo waxaad ogaataa in aanay adiga kaliya ay kugu dhacaynin, oo ay dad badan dhibaato isku mid ah qabaan. Mideeda kale waxaad heshay inay bulshada caafimaadka ay ogaatay in boomaatadaas aysan si dhab ah u daaweynin nabarka, oo taas beddelkeeda ay kaliya nabarka maqaarka hoostiis ku hayso. Waa boomaatada naftigeeda sababta oo keentay inuu nabarka sii weynaado, marka waxa kaliya ee ay tahay inaad sameyso si aad nabarka meesha ka saarto waa inaad joojisa isticmaalka boomaatada si ay nabarka kaligeeda isku baabi'iso.

Adigoo halahaas og: Ma sii wadi lahayd isticmaalka boomaatada? Awooda rabitaanka may qaadan lahayd si aan boomaatada u isticmaalin? Waxaa laga yaabaa, haddii aadan kowdi maqaalka aaminin, inay jiri lahaayeen dhowr maalmood oo walwalsan, laakin mar haddii aad garwaaqsatid in nabarka ay bilaabatay inay baaba'do, baahida ama rabitaanka in boomaatada la isticmaalo toos bay u bixi lahayd. Ma murugoon lahayd? Dabcan sidaas ma ahaan lahayn! Waxaad haysatay dhibaato aad u xun oo aad u malayneysay inaan la daaweyn karin, laakiin hadda waxaad heshay xalka. Xataa haddii ay sannad ku qaadato inuu nabarka kaa tago, maalin walba uu soo roonaado waxaad ka fikiri lahayd sida aad wanaag u dareentay. Tan waa awooda ee joojinta porn.

Nabarka porn ma aha xanuunka jirka, la'aanta damaca caadiga ah, kacsi-galmada daciifka, dhexgelinta sii yaraanaya, waqtiga lagu khasaariyay sawirada laba-geesoodka ah, dareen xaq-u-lahaanshaha, iyo quudhsiga dadka oo ku qabteen adigoo daawatay, ama wax oo taas ka sii daran: isquudhsada naftaada. Kuwaas oo dhan waa waxyaalaha oo nabarka ku darsan.

Laakin nabarka naftigeeda waxay naga dhigtaa inaan maskaxdeena ka xirno waxyaalahaas oo dhan. Nabarka waa dareenka argagaxa rabitaanka inaan helno hagaajinta dopamine. Kuwa oo porn isticmaalaynin kuma dhibaatoodaan dareenkaas. Arrinta ugu xun aan ku dhibaatoono waa cabsida, oo faa'iidada ugu weyn ay tahay takhalusidda cabsidaas. Cabsidaasuna waxaa sababa u ahaayay fadhigaaga ugu horeyay, iyadoo la sii xoojiyay oo uu sababay mid kasta oo ku xigta.

Isticmaalayaasha qaarkood way 'faraxsan yihiin', iyagoo ku indha-tirmeen shaydaanka ee khiyaanada leh, waxayna sidaas darteed u dhex maraan qarow oo isku mid ah, iyagoo soo bandhigaya doodo been ah si ay isugu dayaan inay qiil u yeelaan doqonimadooda.

*Aad bay u fiican tahay in la xoroobo!*
